### ISSUE TITLE
`HolyTile` からボトルが出た瞬間に無敵が解除されない

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1000]
### 概要
- タイトルまま

### 再現方法
- `HolyTIle` からボトルが出た瞬間にギミックを衝突させる

### 期待される挙動
- [ ] `HolyTile` からボトルが出た瞬間でもギミックが衝突する

### スクリーンショットなど

https://user-images.githubusercontent.com/26104258/123545371-9a5e4b00-d792-11eb-9ec4-7d96ee263673.mov

### 備考
- 現状は移動先に `OnEnter` したときに `HolyTile` の判定をしている？もしそうなら、移動元の `OnExit` でやればよさそう

**Comment by xiii111** [comment]
スクリーンショットを更新した。動画の前半で衝突判定にならないのは、`TornadoGimmick` が既にボトルに重なっていて、衝突判定が起こり得ないからである。これは今回のスコープ対象外とする。一方で動画の後半はボトル移動中にもかかわらず、衝突判定が起きて失敗している。これはイシューの内容と反する

**Comment by xiii111** [comment]
@takasusuke ↑ 起きていた問題って

> `TornadoGimmick` が既にボトルに重なっていて、衝突判定が起こり得ないからである

の部分の話かな？これは無敵時間を付与するタスクでも許容されていた話だと思うが、今回でこの修正をしますか？

**Comment by takasusuke** [comment]
> > `TornadoGimmick` が既にボトルに重なっていて、衝突判定が起こり得ないからである
> 
> の部分の話かな？これは無敵時間を付与するタスクでも許容されていた話だと思うが、今回でこの修正をしますか？

なるほどそういうことなのか。
無敵時間の付与のタスクで許容されていた、という話がちょっとよくわかっていません。別の問題に考えています。

この修正をする、認識です。

**Comment by xiii111** [comment]
@takasusuke 

> 無敵時間の付与のタスクで許容されていた

無敵時間を考える時に、無敵時間が解除された瞬間、ギミックと衝突中だった場合失敗とするか？みたいな話がなかったですか？

**Comment by takasusuke** [comment]
> > 無敵時間の付与のタスクで許容されていた
> 
> 無敵時間を考える時に、無敵時間が解除された瞬間、ギミックと衝突中だった場合失敗とするか？みたいな話がなかったですか？

Lifeの無敵時間が解除された瞬間、ギミックと衝突中だったら失敗とする、のがLifeによる無敵の挙動で、
Holyの無敵時間が解除された(フリックした)瞬間、ギミックと衝突中でも失敗にならない、のが今のHolyの挙動です。

Lifeで失敗になるので、Holyも失敗にしたいと思っています。
"許容する"が何を許容する、と言っているのか目的語？がわかってないです。

Lifeの無敵明けに失敗になることを許容する、からHolyでも失敗になることを許容する？なら
現状は失敗になってないから失敗にしたい。

**Comment by takasusuke** [comment]
`GimmickControllerBase.cs`の
```
// 衝突イベントを処理する
this.OnTriggerEnter2DAsObservable()
  .Select(other => other.GetComponent<BottleControllerBase>())
  .Where(bottle => bottle && bottle.IsInvincibleAfterDamaged)
  .Subscribe(bottle => {
      var disposable = bottle.OnInvincibleAfterDamagedExpired.Subscribe(bottleObject => {
          HandleCollision(bottleObject);
          bottleObject.GetComponent<BottleControllerBase>().HandleCollision(GetComponent<Collider2D>());
      }).AddTo(this);
      _invincibleAfterDamagedExpiredDisposables.Add(bottle, disposable);
  }).AddTo(this);
```
の`bottle && bottle.IsInvincibleAfterDamaged`をうまいことやればできそう

**Comment by xiii111** [comment]
> Lifeの無敵時間が解除された瞬間、ギミックと衝突中だったら失敗とする、のがLifeによる無敵の挙動で、

あ、これ失敗になるんだっけ。失礼しました🙏🙏

**Comment by xiii111** [comment]
@takasusuke ちなみに ↓ のようにコード片を表示できます 🙆‍♂️🙆‍♂️

https://github.com/LITO-apps/Treevel-client/blob/1266c6340d81494fd9f5ee4cb54994c57c99b60d/Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickControllerBase.cs#L32-L41
