### ISSUE TITLE
TornadoとDynamicBottleの当たり判定が起きることがある

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1020]
### 概要
TornadoとDynamicBottleの当たり判定が起きることがある。

### 再現方法
Tile3番にDynamicBottleを配置。isGhostにチェックを入れる。
Tornadoを1行目右から0秒開始5秒間隔で発射。
ステージをプレイ。

### 期待される挙動
DynamicBottleとTornadoの当たり判定は起きない。

### スクリーンショットなど
https://user-images.githubusercontent.com/26213141/125179660-455b1400-e22b-11eb-962c-1686bbd583bd.mov

### 備考
- １回目のみ？
- １回目でも当たり判定が起きないことがある？
- Tornado以外のGImmickとDynamicBottleでは？
- StaticBottleやErasableBottleは大丈夫？

**Comment by xiii111** [comment]
📝 確定再現ではないですが、稀に再現することを確認しました。その過程で #1042 の問題を見つけたので、起票しました

**Comment by xiii111** [comment]
📝 以下から `HandleCollision` が呼ばれていた。そっちかい！という感じ

https://github.com/LITO-apps/Treevel-client/blob/962d5fd1378d183cd8473b4a755fc28a103f7668/Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickControllerBase.cs#L31-L41
