### ISSUE TITLE
[#813] 秋の木のデザイン草案

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1022]
## 終了条件
- 草案を作成する

## 考慮事項
- レベル選択画面の木のアイコン
- ステージ選択画面の背景
- ステージ選択のボタン

秋の木：**もみじ**

**Comment by takesi0627** [comment]
@LITO-apps/engineer 
https://docs.google.com/presentation/d/1NB1PzHa7hA0_JZ389TC_253Z_mxNQPEMe5YGz5yKsJk/edit#slide=id.gb8217f59cf_0_8

**Comment by xiii111** [comment]
📝 一旦作業中に戻す

**Comment by takesi0627** [comment]
@takasusuke @xiii111 
まとめスライド追加しました。
レビューよろしくお願いします。

**Comment by takasusuke** [comment]
- 各スライドのタイトルの大きさを変更しました
- [前提]のスライドは草案の方に移動しました
- いくつか画像と文字の関連がわかりやすくなるように図形を追加しました
- ステージ選択画面のイメージ図(15枚目のスライド)は個人的にとてもわかりやすいと思っていたので、スライドに追加しました
- 少し説明を追加しました(アングルの指定など)

自分はこんな感じかなと思います。
あとはよろしくお願いいたします。

**Comment by takesi0627** [comment]
[依頼完了](https://lito-apps.slack.com/archives/CJ30Q29HQ/p1627021962000700)のためクローズします
