### ISSUE TITLE
冬の木（クリスマスツリー）のデザインの草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1023]
## 終了条件
- [ ] 草案を作成する

## 考慮事項
- レベル選択画面の木のアイコン
- ステージ選択画面の背景
- ステージ選択のボタン

冬の木：**クリスマスツリー**

**Comment by xiii111** [comment]
@takasusuke @takesi0627 全然完成じゃないんだけど、StageSelect の案が煮詰まってきたので、こんなイメージ！みたいな画像貼ってもらえませんか？かなり助かります

- https://docs.google.com/presentation/d/1YPUNxBIP7x9cZwSElzScDYK9_wAeuJOhOWS5mDIYknM/edit#slide=id.ge6583a4490_0_2

**Comment by takasusuke** [comment]
スライド追加しました。
StageSelectは背景が明るいパターン、暗いパターンで考えるのもありだと思いました。

**Comment by takasusuke** [comment]
良いと思います。
若干言葉を修正しました。

**Comment by takesi0627** [comment]
🙆‍♂️

**Comment by xiii111** [comment]
Thanks! 依頼します！

**Comment by xiii111** [comment]
#1087 を作成し、Slack で [依頼](https://lito-apps.slack.com/archives/CJ30Q29HQ/p1628856382001100) しました！
