### ISSUE TITLE
[設定画面] トグル UI のデザイン作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1024]
### 完了条件
- [ ] 設定画面で利用するトグル UI を確定する

### 備考
- チェックボックスとトグルが候補になっている
- チェックボックスはラベルテキストに対して、左側に置かれるケースが多いが、左側では他の設定画面の UI と統一性がなくなる可能性が高い（他の UI は右側にコントロールがある）
- チェックボックスを右に置くこともできる

#### チェックボックス
<img width="672" alt="スクリーンショット 2021-07-16 21 33 01" src="https://user-images.githubusercontent.com/26104258/125948209-4d7e39a0-52b3-4309-8259-58e0ef56fcd8.png">

#### トグル
<img width="605" alt="スクリーンショット 2021-07-16 21 33 05" src="https://user-images.githubusercontent.com/26104258/125948220-d61d3747-778e-4733-b110-fd6750e7efe6.png">

**Comment by takasusuke** [comment]
#1163 の経緯を参照
