### ISSUE TITLE
[設定画面] セクション UI のデザイン作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1026]
### 完了条件
- [ ] 設定画面で利用するセクション UI を確定する

### 備考
- シンプルなままでも良いかもしれない
- セクションごとに背景単位で括った方が良いかもしれない

### 参考画像
<img width="1639" alt="スクリーンショット 2021-07-16 21 44 06" src="https://user-images.githubusercontent.com/26104258/125951105-55562730-a93b-4f98-b130-2a990e3b6785.png">

**Comment by takasusuke** [comment]
#1163 の経緯を参照
