### ISSUE TITLE
秋の木（もみじ）デザイン

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1033]
草案 #1022

**Comment by takasusuke** [comment]
MenuSelect
https://drive.google.com/drive/u/0/folders/1RP4VaMNlEic4LJyLoEAcSylbgGD6mj82

StageSelectScene
https://drive.google.com/drive/u/0/folders/1-MXFHuhti_z8JRlGL3T1kXvKmQW0dZTL

**Comment by takasusuke** [comment]
@LITO-apps/engineer
確認よろしくです。

何か修正依頼等あればまとめてコメントします。

ない場合、適当にreactionつけといてください。

**Comment by takasusuke** [comment]
夕方の方のStageSelectSceneを使います
