### ISSUE TITLE
LevelSelectの木のボタンがSafeArea外で描画されていない

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1066]
### 概要
タイトルまま

### 再現方法
SafeAreaの範囲を可視化した状態にする。
LevelSelectで木のボタンがSafeArea外になるようにスクロールする。

### 期待される挙動
SafeArea外でも描画される

### 備考
TreeをおいているCanvasにSafeArea内に収めるようにするComponentをつけているけれど、それを外したら直るはず

**Comment by xiii111** [comment]
In Review に移動して~（危うく見逃すところだった）
