### ISSUE TITLE
`GustWind` アイコンの草案作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1070]
### 完了条件
- [ ] 草案を決める（こんなイメージだよね、が決まれば良い）

**Comment by xiii111** [comment]
@takasusuke @takesi0627 https://docs.google.com/presentation/d/1Va17DqD1Ysm5k6hjG77TzH1bd4VjLn4uEhA7SzWwiLY/edit#slide=id.p で草案を作成しました！レビューお願いします！コメントをいただいて、木曜日のタスク通話で議論する方向でいきたいです！

**Comment by takasusuke** [comment]
7P目を追加しました

**Comment by xiii111** [comment]
https://docs.google.com/presentation/d/1Va17DqD1Ysm5k6hjG77TzH1bd4VjLn4uEhA7SzWwiLY/edit#slide=id.geaa1a6a2f5_0_6 に決定。

**Comment by xiii111** [comment]
#1096 を作成したので閉じます！
