### ISSUE TITLE
`Spring-1` の枝の草案作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1076]
### 終了条件
- [ ] 草案資料を作成する

### 考慮事項
- 枝にそもそもデザイン素材が必要かどうか決める(単色の色さえ調整すれば良い気もする)
- ステージと枝の構図、配置をここで決めても良いかも

**Comment by takasusuke** [comment]
左: 非解放時
右: 解放時
の感じとなりました。
(ステージの配置は仮)

太さは図の通り。
色は半透明、非解放時はグレー、解放時は白(もしくは木ごとのColorの薄い色。実装してみて調整)
形は直線。

<img width="675" alt="スクリーンショット 2021-09-02 21 29 16" src="https://user-images.githubusercontent.com/26213141/131843581-b892da4a-e925-4d7c-abd8-43f889550c4f.png">
