### ISSUE TITLE
`Summer-1` の枝の草案作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1077]
#1035 待ち

## 終了条件
- [ ] 枝の色を決める
- [ ] 配置をなんとなく決める

**Comment by takasusuke** [comment]
作業可能状態になりました

素材
https://drive.google.com/drive/u/0/folders/1l-poZBbl6mvEwCHGy3DqG2TWfuYqTGOV

**Comment by xiii111** [comment]
@takesi0627 こちらお願いします🙏

**Comment by takesi0627** [comment]
<img src="https://user-images.githubusercontent.com/17778395/166394396-b0997b75-1a77-409a-9105-7b58055c0308.png" width="400">

**Comment by takasusuke** [comment]
案１
Springのように、枝の色を淡く(明るく?)する
案２
黄緑にする（スポイトで背景の黄色や緑色のどこかを取得するとどうか）

**Comment by takesi0627** [comment]
* 色味調整
* 太さSpringと合わせる

**Comment by takesi0627** [comment]
| before | 案１(1f, 0.98f, 0.7f) | 案２ (0.82f, 0.99f, 0.59f)
| -- | -- | -- |
| <img src="https://user-images.githubusercontent.com/17778395/169330199-6f2dcd56-026c-40f7-809b-85a6746f1251.png" width="400"> | <img src="https://user-images.githubusercontent.com/17778395/169329685-245d39ed-a64b-40d8-978d-7239d6bee333.png" width="400"> | <img src="https://user-images.githubusercontent.com/17778395/169331597-7a5bc457-ff76-4ddb-837a-15941417fb59.png" width="400">|

* 本来の彩度：`44`
* 案１：彩度を`30`に下げる
* 案２：右上あたりの葉っぱの色をピックして彩度を下げたバージョン

**Comment by takesi0627** [comment]
@takasusuke @xiii111 
案１と案２どれがいいかコメントください。
もしくは別の案見たいなら教えてください。

個人的に案１でいいと思います。
ちなみに太さは春と合わせておいた。

**Comment by xiii111** [comment]
@takesi0627 

> ちなみに太さは春と合わせておいた。

`before` の時点で太さが春と合わせてあるかな？

> 案１と案２どれがいいかコメントください。

どちらかと言われれば、案 1 が無難なのかなと思いました。強いこだわりはありません

**Comment by takesi0627** [comment]
> > ちなみに太さは春と合わせておいた。
> 
> `before` の時点で太さが春と合わせてあるかな？

あ、そうでした。
色の比較だけしたいので太さはそのままにしてた。

**Comment by xiii111** [comment]
LGTM！

**Comment by takasusuke** [comment]
元の案よりはどちらも馴染んでて良い気がする。
でも、そんなにしっくりくるわけではない。あんまり決め手がない。
枝のShaderとか、枝自体の表現とかもっと別の問題なんだろうなあ。。。

どちらでも良いので案１で良いかと思います。

**Comment by takesi0627** [comment]
では案１で実装進みます
