### ISSUE TITLE
失敗原因となるボトルとギミックの演出のデザイン草案作成

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1078]
## 終了条件
- [ ] 草案資料を作成する

### 考慮事項
- 失敗原因のBottleの演出は基本共通にする
- 失敗原因のGimmickの演出は色など、共通化できそうなものは共通化して、Gimmickごとに異なることも許容する。

**Comment by takasusuke** [comment]
草案資料置き場
https://docs.google.com/presentation/d/1pFyB4Uh0zq-Yu3DxQmO6Cqs4ayvvE7bLRpKzb8gjzGU/edit#slide=id.p

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
https://docs.google.com/presentation/d/1pFyB4Uh0zq-Yu3DxQmO6Cqs4ayvvE7bLRpKzb8gjzGU/edit#slide=id.gf27270e237_0_926

2, 3ページの説明でOK??

**Comment by xiii111** [comment]
@takasusuke 

> 割れたパーツが正位置(次ページ、ゲーム画面右下)だと他のBottleと違いが伝わりにくい気がしています。
動きがある感じを見せたい。

この説明が最高です! 依頼に関してはこれで良いと思います。
前のタスク通話では `LifeAttribute` がダメージを受けたとき（割れてはいない）の演出もこのイシューに含めるかも、という話がありましたが、そちらはどのように進めていきますか？

**Comment by takasusuke** [comment]
> 前のタスク通話では `LifeAttribute` がダメージを受けたとき（割れてはいない）の演出もこのイシューに含めるかも、という話がありましたが、そちらはどのように進めていきますか？

確かに言ってたような。。。
現状の実装(一瞬赤くなる)のように、何かしら見た目を変化させる対応は行うとして、現状に対するみんなの満足度次第かな。

ダメージを受けたら`DarkAttribute`が一瞬晴れるなら、今のままでも良いと思っている。

**Comment by takesi0627** [comment]
需要度はわかりませんが、
個人的に割れた後（もしくは割れながら）中の液体が減っていくような演出も入れたいですがどうでしょうか

**Comment by takasusuke** [comment]
依頼しました
https://lito-apps.slack.com/archives/CJ30Q29HQ/p1632743040000300

**Comment by takasusuke** [comment]
対応issueを作成しました
#1164
