### ISSUE TITLE
`Spring-1` の成功・失敗時用のステージボタンの縁を消す

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1080]
### 終了条件
- [ ] 縁を消したverの素材をもらえるように依頼する → 自分で縁消す画像作る
- [x] 今後、全てのステージボタンは縁あり・縁なしの２パターンほしいことを説明する

### 考慮条件

**Comment by takasusuke** [comment]
https://drive.google.com/drive/u/0/folders/1fkiF5M9Y5gop8ANRYu9ris3Ohzd4H-Ja

いただきました

**Comment by takasusuke** [comment]
#1293 で実装。
