### ISSUE TITLE
ワープアニメーション中に `GustWind` を受けると想定外の挙動が起こる

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1084]
### 完了条件
- [ ] ワープ元のアニメーション中に `GustWind` を受けても、何も起きない

＊上にフリックすると、右上に移動するのは、データ上はワープ先にいることになっているからと思われる

https://user-images.githubusercontent.com/26104258/132858966-2e5b64d8-1f33-4fd8-89db-83c759522637.mov

- [ ] ワープ先のアニメーション中に `GustWind` を受けても、何も起きない

https://user-images.githubusercontent.com/26104258/132859872-beb01823-11df-4e26-9d90-2e1caca35f43.mov

**Comment by xiii111** [comment]
直した場合には、 https://github.com/LITO-apps/Treevel-client/issues/710#issuecomment-898978426 も治っているか確認する。治せそうなら直す
