### ISSUE TITLE
冬の木（クリスマスツリー）デザイン

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1087]
ref: #1023

草案資料 11 ~ 18
- https://docs.google.com/presentation/d/1YPUNxBIP7x9cZwSElzScDYK9_wAeuJOhOWS5mDIYknM/

**Comment by takasusuke** [comment]
LevelSelect
https://drive.google.com/drive/u/0/folders/1JMl6JasRbiMrSa7A7pRBMEA7HJnRez5Z

StageSelectScene
https://drive.google.com/drive/u/0/folders/1RH5IIwZ6kVawLa3Y96sNd9PuIb1Jg6Uh

**Comment by takasusuke** [comment]
@LITO-apps/engineer
確認よろしくです。

何か修正依頼等あればまとめてコメントします。

ない場合、適当にreactionつけといてください。

**Comment by takasusuke** [comment]
閉じます
