### ISSUE TITLE
警告ポップアップの実装

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1089]
### 終了条件
#985 に基づいて実装

* メッセージは二つ：
    * 黒字の説明文字
    * 赤字の警告文字   

### 草案資料
https://docs.google.com/presentation/d/10Vh5hkDJVqCuAyPtfU6cAITBtfL6OtS5GUd03uNW-2U/edit#slide=id.ge623e28ce7_0_38

<img width="255" alt="スクリーンショット 2021-08-28 1 30 46" src="https://user-images.githubusercontent.com/26213141/131159542-5471ee79-2bf8-40ce-8b82-17b85efcf265.png">

**Comment by xiii111** [comment]
📝 α 版では対応する必要がなくなった
