### ISSUE TITLE
木の開放演出中に、木をタップできてしまう

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1090]
## 終了条件
- [ ] 木を解放演出が始まったらInput受け付けないようにする。（Timelineに実装）

**Comment by takesi0627** [comment]
`TouchScript`を利用する限り、現在有効のインプットを`disabled`にする方法がありません。

`TouchManager`をdisablesにしても、インプットは遮断されないし、`Standard Input`をDisabled にして再度enabledにするとインプットシステムがぶっ壊れる（[イシューとして上がっている](https://github.com/TouchScript/TouchScript/issues/302)）。

対策案としては下記2点を考えている。
* **透明なマスクでインプットを遮断**
画面全体に覆うような透明なマスクを配置し、演出開始の時に表示。演出終了時非表示。
    * メリット：早い。工数おおよそ2時間。
    * デメリット：汎用性がない。

* `TouchScript` をdisabled/enabled可能にするように自前で実装
`TouchManager`にdisabledみたいなプロパティを用意し、インプット処理が走るであろうところに `if` 文を挟んで無効化させる
`TouchManagerInstance.cs`の`INTERNAL_XXXPointer`系関数にて実装できそう。
    * メリット：汎用性がある。
    * デメリット：未知の領域のため工数見積もれない。早ければ2時間、躓いたら8以上かかってもおかしくない。


@xiii111 @takasusuke 
上記目を通していただいて、MTGでどうするか議論しましょう

**Comment by xiii111** [comment]
@takesi0627 調査ありがとうございます。一通り読んだ感じ、`透明なマスクでインプットを遮断` かなーと思ってます

**Comment by takasusuke** [comment]
`透明なマスクでインプットを遮断`
が良いと思いました。

UIManagerの子オブジェクトとして透明なマスクを置く感じを想像してるけど、一緒？？
透明なマスクを有効化させる時に、誰が有効化させたかの情報を配列で所持する感じかなあ
```
clientA, clientB, clientCがマスクを有効化。
clientAがアニメーションの終了時にマスクを無効化しても、まだclientB, clientCがマスクを有効化していて欲しいので、マスクは有効のまま。
```
みたいな。

TouchScriptにプロパティを追加することと、UIManagerにマスクオブジェクトを配置することは、どっちも汎用性は同じ感じがしました。
なので、ある程度工数が見積もれて、事故も起きなさそうな方にしたいと考えています。

**Comment by takesi0627** [comment]
> `透明なマスクでインプットを遮断`
> が良いと思いました。
> 
> UIManagerの子オブジェクトとして透明なマスクを置く感じを想像してるけど、一緒？？
> 透明なマスクを有効化させる時に、誰が有効化させたか(もしくは何人が有効かさせたか)の情報を配列で所持する感じかなあ
> 
> ```
> clientA, clientB, clientCがマスクを有効化。
> clientAがアニメーションの終了時にマスクを無効化しても、まだclientB, clientCがマスクを有効化していて欲しいので、マスクは有効のまま。
> ```
> 
> みたいな。
> 
> TouchScriptにプロパティを追加することと、UIManagerにマスクオブジェクトを配置することは、どっちも汎用性は同じ感じがしました。
> なので、ある程度工数が見積もれて、事故も起きなさそうな方にしたいと考えています。

UIManagerを利用すること自体は考えてなかった。いいアイデアだと思います。

ただ
> clientA, clientB, clientCがマスクを有効化。
> clientAがアニメーションの終了時にマスクを無効化しても、まだclientB, clientCがマスクを有効化していて欲しいので、マスクは有効

については工数かかりそうだし、今の所需要がなさそうなので、一旦このタスクでは対応しなくてもいいかなと思っています。
