### ISSUE TITLE
エラーポップアップの実装

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1094]
### 終了条件
#985 に基づいて実装

### 草案資料
https://docs.google.com/presentation/d/10Vh5hkDJVqCuAyPtfU6cAITBtfL6OtS5GUd03uNW-2U/edit#slide=id.ge923dc81e9_0_540

<img width="236" alt="スクリーンショット 2021-08-28 1 31 52" src="https://user-images.githubusercontent.com/26213141/131159658-c5641ce7-5bc8-46fb-86d4-fab8abb29c0e.png">

### 終了条件
- [x] デザイン通りのレイアウト作成
- [x] ビックリマーク：白い丸画像＋赤色＋！（Text Mesh Pro）
- [x] エラーの理由、アクションを表示コンテンツに追加

**Comment by takesi0627** [comment]
エラー情報の設定方法について一度仕様固めたいかも

**Comment by takesi0627** [comment]
ステージデータ風に作ってみたがコードが多くなるとイマイチかな

![image](https://user-images.githubusercontent.com/17778395/133905397-201bcbf2-8ee2-4a55-9f7d-1ca115de102c.png)

**Comment by takesi0627** [comment]
結論： `static`変数としてどこかで定義する。追加したいときはソースコードの編集になります
