### ISSUE TITLE
ステージ概要画面の実装

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1097]
### 終了条件
#985 に基づいて実装

- [x] 星画像作成or見つける(黄色・灰色)(0.5)
- [x] プレハブの作成 (2)
- [x] 難易度をStageDataに追加(0.5)
- [x] スクリプト組み込み(1.5)

※NEWはやらない

### 対象外：（別イシュー作成）
* ステージプレビュー機能
* 難易度で星を埋める機能

### 草案資料
https://docs.google.com/presentation/d/10Vh5hkDJVqCuAyPtfU6cAITBtfL6OtS5GUd03uNW-2U/edit#slide=id.ge9a8bf75b6_1_329

<img width="236" alt="スクリーンショット 2021-08-28 1 32 49" src="https://user-images.githubusercontent.com/26213141/131159764-7da56058-be74-4ea2-ab7a-e7153ce8ec72.png">

**Comment by takesi0627** [comment]
> ### 対象外：（別イシュー作成）
> * ステージプレビュー機能

#1206 
> * 難易度で星を埋める機能

#1207 

対象外の機能のイシューを作成しました。
対応時期についてはMTGで相談します
