### ISSUE TITLE
[iOS] 領域外が微妙に線状に見える

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1112]
### 完了条件
- [ ] `LevelSelectScene` において、スクロール領域外に謎の線が見える場合がある問題が解消されていること

#### iPhone 12 Pro（iOS 14）
＊拡大中のみピンクの細い線が見える
|縮小中|拡大中: 左側|拡大中: 右側|
|---|---|---|
|![IMG_1226](https://user-images.githubusercontent.com/26104258/132965773-dbd7d8c5-41ed-4bb3-a813-5a775be1f00d.PNG)|![IMG_1227](https://user-images.githubusercontent.com/26104258/132965775-e2e48f6a-3e8e-4397-9da1-9941880fc452.PNG)|![IMG_1228](https://user-images.githubusercontent.com/26104258/132966019-512b24b8-5a9d-459c-af8c-cb07388d5291.PNG)|

#### iPhone 11（たけしデバイス）
＊問題なし

<img width="300" alt="image" src="https://user-images.githubusercontent.com/17778395/132967313-28915434-a276-4679-a7a8-ececafe884ad.png">

#### iPhone 6sPlus（iOS 14.8）
＊黒の太い線が見える

<img src="https://user-images.githubusercontent.com/26213141/132219601-ea892d34-33ee-4d5a-8eb7-4f245ff50861.PNG" width="300">

**Comment by takasusuke** [comment]
![IMG_6672](https://user-images.githubusercontent.com/26213141/132219601-ea892d34-33ee-4d5a-8eb7-4f245ff50861.PNG)

**Comment by xiii111** [comment]
|縮小中|拡大中|
|---|---|
|![IMG_1226](https://user-images.githubusercontent.com/26104258/132965773-dbd7d8c5-41ed-4bb3-a813-5a775be1f00d.PNG)|![IMG_1227](https://user-images.githubusercontent.com/26104258/132965775-e2e48f6a-3e8e-4397-9da1-9941880fc452.PNG)|

**Comment by xiii111** [comment]
Simulator では再現せず。https://github.com/LITO-apps/Treevel-client/issues/1112#issuecomment-913621596 を見る感じも、デバイスや環境によって現象は異なるのかもしれない

<img src="https://user-images.githubusercontent.com/26104258/132966451-5e19d101-380c-47ca-871b-585e0ea6ac6a.png" width="300">

**Comment by takesi0627** [comment]
たけしデバイス(iPhone 11)
<img width="414" alt="image" src="https://user-images.githubusercontent.com/17778395/132967313-28915434-a276-4679-a7a8-ececafe884ad.png">

**Comment by takasusuke** [comment]
実行中のデバイスサイズを取得できたら、取得してログに出すと良いかもしれない

**Comment by xiii111** [comment]
@takasusuke https://github.com/LITO-apps/Treevel-client/issues/1112#issuecomment-913621596 の端末を教えてもらえませんか？

**Comment by xiii111** [comment]
#### #1146 マージ直後（9/22 8:20 時点 `develop` 最新）
- 環境: `Unity 2020.3.18f1` / `Xcode 13` / `iOS 15` / `iPhone 12 Pro 実機` / `develop` / 95e408f9 → **発生せず**

#### Unity ダウングレード直後
- 環境: `Unity 2020.3.18f1` / `Xcode 13` / `iOS 15` / `iPhone 12 Pro 実機` / `develop` / 8729dc23 → **発生せず**

#### Unity ダウングレード直前
-  環境: `Unity 2021.1.2f1` / `Xcode 13` / `iOS 15` / `iPhone 12 Pro 実機` / `develop` / 4d31cff1 → エラーがたくさん出て `iOS` へのビルドができなかった（この調査に労力をかけたくなかったので、この結果無しに考察する）

#### 約 1 ヶ月前
- 環境: `Unity 2021.1.2f1` / `Xcode 12` / `iOS 15` / `iPhone 12 Pro 実機` / `TestFlight 0.1 (2)` → **発生する**

---

治った理由は、以下の場合が考えられる
- `Unity` のダウングレードで治った → 調査せずともダウングレードした `Unity` でリリースすれば良いので ok
- `Xcode 13` で治った → 調査せずとも `Xcode 13` ビルドでリリースすれば良いので ok
- `iOS 15` で治った → `iOS 14` 以下で再現するなら直す必要あり
- `iPhone 12 Pro 実機` は以前と変化がないので、理由から外せる

とまぁ、網羅的に調べたが ... とりあえず手元で再現しないなら良しとしたい

よって @takasusuke `develop` の最新で再現するかを確認してもらえませんか？（ @takesi0627 はそもそも再現していないので、確認できない）

**Comment by takasusuke** [comment]
> @takasusuke [#1112 (comment)](https://github.com/LITO-apps/Treevel-client/issues/1112#issuecomment-913621596) の端末名を教えてもらえませんか？

iPhone 6sPlus 
iOS 14.8

実機で調査ってことよね。
実機Build、デバイス登録とかなんちゃら今度ヨロピコ。

**Comment by xiii111** [comment]
@takasusuke あーー実機でビルドできないやつか。あれ、パッと直せない（調べないといけなさそう）だから、イシュー作っておくわ

**Comment by xiii111** [comment]
#1152 を作った

**Comment by xiii111** [comment]
とりあえず、iPhone 6sPlus の Simulator で再現するかだけ確認する

**Comment by xiii111** [comment]
環境: `Unity 2020.3.18f1` / `Xcode 13` / `iOS 14.5` / `iPhone 6s Plus Simulator` / `develop` / 4cc826e9 → 再現せず

**Comment by xiii111** [comment]
@takasusuke @takesi0627 私の実機環境で再現しなくなったこと、Simulator ではありますが @takasusuke と同じデバイス環境で再現しなくなったことから問題ないと判断して、閉じます

@takasusuke #1152 が解消されたり、新しい TestFlight を配布したりで再度実機で触るタイミングがあると思います。その時に、同現象が再現していたら起票お願いします（iPhone 6s Plus の線は太くて見やすいので、すぐわかると思いますので）
