### ISSUE TITLE
[iOS] 長時間放置してると画面が真っ黒になる

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1113]
## 終了条件
- 長時間放置しても画面が真っ黒にならないようにする

### 考慮事項
- 何秒くらいでこの問題が起きるか確認する
- Shaderのランダム値が原因かもしれないので、Shaderを外した状態で試して、問題が起きるか確認する

### キャプチャ
<img src="https://user-images.githubusercontent.com/26104258/132966415-9554cf0f-705d-4ab0-a315-c4d646f123e7.png" width="300">

### 備考
- Simulator、実機共に

**Comment by takasusuke** [comment]
Simulator build で1:20から黒くなり始め、1:30で完全に黒くなった

**Comment by takasusuke** [comment]
Shaderのランダム値を生成している部分をコメントアウトした。
3:00LevelSelectSceneで待機していたけれど、黒くならなかった。
原因調べる。

**Comment by takasusuke** [comment]
## 原因
多分の原因。ランダムなノイズ生成で以下のような計算が入っている。
```
fixed2 q = st;

// 略
q = q*2.01;
// 略
q = q*2.02;
// 略
q = q*2.03;
// 略
q = q*2.01;  
```

qの初期値stは時間に応じて、1 + 0.20t という値が入る。
qの初期値15.6を超えた時、(73秒程度経過時)に、qの値が256を超える。
```
fixed は低精度で、固定小数点数です。一般的に 11 ビットで、–2.0 から +2.0 の範囲で、1/256 精度です。
```
ということから、何らか関係がある？(11bit使えるなら、2048くらいまで行けそうだけど、ここら辺の処理について詳しくないのでもうちょい調べないとわからない)
https://docs.unity3d.com/ja/2019.4/Manual/SL-DataTypesAndPrecision.html

----

## 残り調査
- qの値がオーバーフローしている？？ならさらに78秒程度待てばまた正しく描画される？
- fixed の精度についてもう少し調べる
- なぜEditorでは起きないのか？(こっちの調査は難しそう。。。）(オーバーフローせず、上限を超えたら単にそれ以上増えないだけかもしれない。[参考](https://techblog.kayac.com/unity-shader-parameters-precision)）

----

## 今後
Timeを使うときなどは、値域が想定の範囲に収まっているかどうか確認する(レビュー時に、そこを確認するように説明する)
Shaderの自作メソッドには、値域など充実したドキュメンテーションコメントで書くようにする。(これはShaderを書いているときに、値域を毎回考える時間が手間に感じるので、シンプルに欲しい)

**Comment by takasusuke** [comment]
単純に無理矢理オーバーフローさせて再現しようとしたけど出来なかった。
（Editorで再現しないからBuildしてテストするのコスト高すぎ。。。萎える。。。）

とりあえず値域に気をつけて他の実装にすれば大丈夫なはず。。。

**Comment by xiii111** [comment]
📝 まだ draft みたいなので `作業中` に戻しておきます
