### ISSUE TITLE
[iOS] LevelSelectの木のボタンがSafeArea外で描画されていない

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1132]
ref: #1066

### 概要
- Unity Editor 上の Simulator では問題ないが、iOS SImulator or 実機上だと #1066 が治っていない

### 再現方法
- iOS Simulator or 実機上で #1066 を確認する

### 期待される挙動
- iOS Simulator or 実機上でも #1066 が治っている

### スクリーンショットなど
<img src="https://user-images.githubusercontent.com/26104258/132966546-46f7b6cb-7f48-4b1d-ab00-01fe8285e6a1.png" width="300">

### 備考
- ナニコレ

**Comment by takasusuke** [comment]
これ、自分は再現しません。

`Unity`の`Window > Asset Management > Addressables > Groups で Build > New Build > Default Build Script`
して改めて行ったら大丈夫かも。

**Comment by xiii111** [comment]
ありうるわ。夜確認します

**Comment by xiii111** [comment]
@takasusuke 再現しませんでした、クローズしますね！
