### ISSUE TITLE
未実装のLevelSelectの木をシルエット表示する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1135]
## 終了条件

- [ ] 未実装の木用のプレハブ作成（桜木の画像＋黒色＋？のText Mesh Pro）
- [ ] 未実装の木用のLevelTreeContorllerを用意（RoadControllerが参照するため）
- [ ] LevelSelectに適用

**Comment by xiii111** [comment]
📝 `レビュー中` に移動します！
