### ISSUE TITLE
実機が熱くなることがある

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1136]
## 完了条件
- [ ] `WARNING -> applicationDidReceiveMemoryWarning()` について調べる
- [ ] アプリにおいて、電池消費が激しくなる要素について調べる
- [ ] 上記の要素を持ってしまっているかを調べる
- [ ] 問題がある箇所があれば、イシューにする

**Comment by takasusuke** [comment]
GamePlaySceneのPlaying State以外はFPSの設定下げた方が良いかも
https://ekulabo.com/frame-rate-battery

**Comment by xiii111** [comment]
実機が自由に操作できない状態なので、一旦取り組まない

**Comment by xiii111** [comment]
📝 まず起動時のログを見ていく

**Comment by xiii111** [comment]
`applicationDidReceiveMemoryWarning` が出ない時もある

**Comment by xiii111** [comment]
@takasusuke @takesi0627 上記のようにメトリクスごとにイシューを分け、本イシューでは Energy Impact に集中する方針で行きたいですが、レビューもらえますか？（そんなにちゃんとやらなくて良い、など）

**Comment by takasusuke** [comment]
調査感謝。
方針賛同。

**Comment by xiii111** [comment]
総合的な別イシューを作って、ベータ版とする。本イシューは作った後閉じる

**Comment by xiii111** [comment]
#1287 を作成したので、閉じます
