### ISSUE TITLE
[OnBoarding-0] コーチマークのデザイン草案作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1139]
草案資料
https://docs.google.com/presentation/d/1mC-cW7qsqoU9y45STU--wilfLOb1edGr6SGpFYyb9wE/edit#slide=id.p

ref: [原案スライド](https://docs.google.com/presentation/d/15e2wcvIBoLabvvKjIMYdpzn_vbQFIBNDrU2XSP7qLP4/edit#slide=id.gea6227538a_0_0)

### 完了条件
- [ ] 各種コーチマーク（#1140, #1141）のデザインを適用するだけの状態にすること
- [ ] #1140, #1141 の共通部分を実装するイシューを作成すること

### 備考
- 注目させたい箇所以外をマスクで暗転
- マスクの透明度は Popup の外側と同じ
- マスクをタップしたら、消える
- 表示したタイミングで完了扱いになる
- コーチマークのそばに表示する文言も考える

#### コーチマークのイメージ
＊どのような暗転をして、明るくしたい箇所をどのように囲うのかが本イシューのやること
<img width="364" alt="スクリーンショット 2021-09-13 19 09 18" src="https://user-images.githubusercontent.com/26104258/133065857-d0ac8ec7-3a7c-4601-b825-afcbc1a1c1ff.png">

**Comment by takasusuke** [comment]
#1140 で実装します
