### ISSUE TITLE
[OnBoarding-2] 木への誘導コーチマークのデザイン適用

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1140]
## 終了条件
- デザイン草案に基づいて実装

### 考慮事項
- デザイン草案資料 https://docs.google.com/presentation/d/1mC-cW7qsqoU9y45STU--wilfLOb1edGr6SGpFYyb9wE/edit#slide=id.p

コーチマークの形(丸)
<img width="517" alt="スクリーンショット 2021-10-18 1 10 40" src="https://user-images.githubusercontent.com/26213141/137635620-4c32c24b-2b53-4b05-a9f3-b39742770326.png">

テキストの表現(吹き出し、下地透明、縁あり(Treevelのメインカラーがあればそれ。なければ桜の色。))
吹き出しの実装は頑張る。
吹き出しの出っ張ってる部分は吹き出しの中央から出るようにする。(下図はGoogle Slideで作ったので中央からずれているけれど、これは無視)
<img width="544" alt="スクリーンショット 2021-10-18 1 11 10" src="https://user-images.githubusercontent.com/26213141/137635630-e96b4dc9-82df-4271-af75-d9f670bc7270.png">

文体(タップしたら何ができるか書く, 細かい文言は別途それを決めるissueがあるので一旦以下の画像でOK)

<img width="531" alt="スクリーンショット 2021-10-18 1 11 32" src="https://user-images.githubusercontent.com/26213141/137635641-8d8d9266-0cbe-48ab-aba4-8639acbfd586.png">

**Comment by xiii111** [comment]
#1139 を待つ

**Comment by takesi0627** [comment]
# 吹き出し候補

[by @takasusuke ](https://lito-apps.slack.com/archives/C01E5GTPRV3/p1638284491002700?thread_ts=1638283928.001500&cid=C01E5GTPRV3)

| [1️⃣](https://fukidesign.com/e0735/) | [2️⃣](https://fukidesign.com/e0874/) | [3️⃣](https://fukidesign.com/e0196/) |
| --- | --- | --- |
| <img width="300" src="https://user-images.githubusercontent.com/17778395/144450486-ac535b0c-7d20-4310-a09f-945df5c65fe7.png"> | <img width="300" src="https://user-images.githubusercontent.com/17778395/144450991-33d23704-944c-425c-9777-059d53b5b9ea.png"> | <img width="300" src="https://user-images.githubusercontent.com/17778395/144451311-f32ce962-3cfc-412b-a428-0aecea4d9bfe.png"> |


| [4️⃣](https://fukidesign.com/e0150/) | [5️⃣](https://fukidesign.com/e0862/) | [6️⃣](https://fukidesign.com/e0132/) |
| --- |  --- | --- |
| <img width="300" src="https://user-images.githubusercontent.com/17778395/144451749-329db592-3971-43bc-a648-f198821ab799.png"> | <img width="300" src="https://user-images.githubusercontent.com/17778395/144451824-139822d1-e802-44f0-b455-0a8cdedcc591.png"> | <img width="300" src="https://user-images.githubusercontent.com/17778395/144452016-e3a4f812-a2f7-414e-92cc-8b7df00fc221.png"> |


個人的**尖ってるところが真ん中にあるのが分かりやすい**から1️⃣と5️⃣がいいと思っている。
ポップ感が出したいなら5️⃣、そんなにいらないと言うなら1️⃣といった感じかな


@takasusuke @xiii111 
吹き出しいつでも差し替えられるのでとりあえず 5️⃣で実装進めようと思いますが、
他に何か意見あればコメントお願いします。
吹き出し全部[このサイト](https://fukidesign.com)からダウンロードしたものです、
他に試したいのあれば教えてください

**Comment by xiii111** [comment]
@takesi0627 とりあえず実装するなら、一番シンプルな 1 が良いと思いました！

**Comment by xiii111** [comment]
全体的には良さそうです！！

**Comment by takesi0627** [comment]
1️⃣にします
