### ISSUE TITLE
[OnBoarding-3] ステージの開放を伝えるポップアップのデザイン草案作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1142]
草案資料
https://docs.google.com/presentation/d/1eM58f1D1CMAOAwrYe0RPs4eNwOTwm7hGZdY5wAm3W1g/edit#slide=id.p

ref: [原案スライド](https://docs.google.com/presentation/d/15e2wcvIBoLabvvKjIMYdpzn_vbQFIBNDrU2XSP7qLP4/edit#slide=id.ge8e64a933a_0_38)

### 完了条件
- [ ] デザインを適用するだけの状態にすること

### 何を伝えるのか
- あなたは何をすべきなのか

ex) 荒廃した木を復活させるために、各ステージをクリアし、木を浄化していく必要がある

- 何をしたら完了なのか

ex) 8割のステージをクリアしたら、木は正常化する。全てのステージをクリアしたら、木は大繁栄を迎える（仕様が決まっていないが）

### 備考
- ポップアップの配置の方向性は OnBoarding 間で揃える
- ポップアップの外枠の大きさは内容に依らない
- ポップアップは表示したタイミングで完了扱いになる
- 表示する条件は、StageSelectScene を表示した時

#### ポップアップのイメージ
<img width="297" alt="スクリーンショット 2021-09-13 19 03 22" src="https://user-images.githubusercontent.com/26104258/133065061-bac21ea1-678b-4840-a12d-50e67d1a7904.png">

#### 表示のイメージ
<img width="364" alt="スクリーンショット 2021-09-13 19 27 18" src="https://user-images.githubusercontent.com/26104258/133068275-cfbc8c93-1f24-4acd-86ad-0b8229bfef2e.png">

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
OnBoarding-3のデザインを作成しました。
説明することが主に「薬(ボトル)」・「結晶(タイル)」・「天候(ギミック)」あると思っています。
この画面で説明できることは多くて2つ程度だと思っていて、説明できなかったことは、次のゲーム画面で補うことを想定しています。

MTGで決めますが、先に見て、画像別案等あればお願いします。

**Comment by xiii111** [comment]
@takasusuke コメントしました〜！

**Comment by takasusuke** [comment]
15p, 16pに案を追加しました

https://docs.google.com/presentation/d/1eM58f1D1CMAOAwrYe0RPs4eNwOTwm7hGZdY5wAm3W1g/edit#slide=id.gf8716d27f6_0_0

**Comment by takasusuke** [comment]
#1243 でお願いしました。
