### ISSUE TITLE
[OnBoarding-5] ステージの説明のためのデザイン草案作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1143]
草案資料
https://docs.google.com/presentation/d/1KehaVUkwpoz_VFrpUR2glL-X0I-iE7vNLIX16CixBtM/edit#slide=id.p

ref: [原案スライド](https://docs.google.com/presentation/d/15e2wcvIBoLabvvKjIMYdpzn_vbQFIBNDrU2XSP7qLP4/edit#slide=id.gea55eaec46_0_39)

### 完了条件
- [ ] デザインを適用するだけの状態にすること

### 何を伝えるのか
・ステージのクリアの仕方(同じ色の結晶に同じ色のBottleを全て置く)
・なぜそれでクリアできるのか
・クリアすると何が嬉しいのか

### 備考
- ポップアップを使うかどうかすら決まっていない
- 表示する条件は、初めて “ステージ” に入った時（Spring-1-1 などに絞らない）
- ギミックの説明は、ギミックの OnBoarding で
- ギミックがあることはテキスト程度で伝える
- このOnBoarding画面がある時は、チュートリアルを設定しない想定。(GoalBottleとGoalTileの説明は実質ここの可能性がある)

**Comment by takasusuke** [comment]
[「そんなものあったっけ？」が理想となるチュートリアルを，どのようにデザインすべきか](https://www.4gamer.net/games/999/G999905/20160826146/)

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
草案資料を作成しました。MTGで主に話しますが、先に見て何かコメントあればお願いします。
(なんか他の人が1回見てわかるスライドになってるのかわからんくなってきた)

https://github.com/LITO-apps/Treevel-client/issues/1143#issuecomment-966396497　を見て、出来るだけテキストで説明することは避ける考えを持ちました。
プレイ体験(+ギミックごとのポップアップで世界観の補足説明)でギミック等は説明すれば良いと思ったので、ギミックに関しては何も説明していません。

遊び方を説明する、かつ、世界観を補足する、本当に最低限の説明だけを選びました。
基準が共有できれば幸いです。(各ギミックのポップアップの言葉選びとつながる部分が多いかもしれない)


また、ステージの説明でポップアップは使いませんでした。
結晶とボトル、という盤面の説明しないといけないのに、ポップアップで画面の連続性が失われるのはマイナスになると考えました。
あと単純にポップアップにのせる画像とかが良いの思いつかなかった。

**Comment by xiii111** [comment]
@takasusuke スライドにコメントしました！また、

> 出来るだけテキストで説明することは避ける考えを持ちました。

良いと思います

> プレイ体験(+ギミックごとのポップアップで世界観の補足説明)でギミック等は説明すれば良いと思ったので、ギミックに関しては何も説明していません。

現時点では、良いと考えています

> 遊び方を説明する、かつ、世界観を補足する、本当に最低限の説明だけを選びました。
基準が共有できれば幸いです。(各ギミックのポップアップの言葉選びとつながる部分が多いかもしれない)

最低限にすること、私も同意です

> また、ステージの説明でポップアップは使いませんでした。
結晶とボトル、という盤面の説明しないといけないのに、ポップアップで画面の連続性が失われるのはマイナスになると考えました。

良いと思います

**Comment by xiii111** [comment]
@takesi0627 見といた方がいいかも

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
https://docs.google.com/presentation/d/1KehaVUkwpoz_VFrpUR2glL-X0I-iE7vNLIX16CixBtM/edit#slide=id.g101d91bee2a_0_0
11p~13Pに修正版を作成しました。
レビューお願いします。

**Comment by takasusuke** [comment]
#1187 で実装します
