### ISSUE TITLE
`Xcode` で実機ビルドができない

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1152]
### 概要
- @takasusuke @takesi0627 が `Xcode` で実機ビルドができない

### 再現方法
- @takasusuke @takesi0627 が実機でビルドしようとする

### 期待される挙動
- - @takasusuke @takesi0627 が実機でビルドできる

### スクリーンショットなど

![image](https://user-images.githubusercontent.com/17778395/134790128-795a119c-e527-46b3-8404-1217af0ae0be.png)

### 備考
- おそらくデバイス登録周りだと思うが、エラーを見てないから確信はない

**Comment by xiii111** [comment]
@takasusuke @takesi0627 スクリーンショットの部分、補完お願いします

**Comment by takesi0627** [comment]
https://teratail.com/questions/121771
https://help.apple.com/developer-account/?lang=ja#/dev40df0d9fa

**Comment by xiii111** [comment]
Slack より
> んーーー 信頼のもと aoi.t0517.dev@icloud.com ( private では使っていない開発用の apple id ) にログインできるようにするか、毎回個人の apple id を xcode で登録してもらうか
> ちなみに number bullet の時は前者だったかな。 @takasu から apple id と password を教えてもらった気がする 

2 時間調査したけど、これかなぁ。マイルストーン MTG で残りはやろうかな

**Comment by xiii111** [comment]
@takasusuke @takesi0627 これから実機でビルドしたい場合には、以下のようにお願いします！

1. いつも通り iOS 向けにビルドする
2. ルートの `Unity-iPhone` を選択し、`TARGETS > Unity-iPhone > Signing & Capabilities > All` の `Build Identifier` を任意の文字列に変更し、`Team` を自身の Apple Id に設定する
3. Xcode でビルドする
