### ISSUE TITLE
失敗時にリトライするとBGMが再生されない

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1153]
### 概要
失敗時にリトライするとBGMが再生されない
ポーズからのリトライでは問題ない

### 再現方法
任意のステージで失敗、リトライする
失敗してすぐリトライするのが鍵かもしれない

### 期待される挙動
ゲーム中のBGMが再生される

### スクリーンショットなど
https://lito-apps.slack.com/archives/C01E5GTPRV3/p1632837817007300

**Comment by takesi0627** [comment]
失敗した後すぐにリトライする時のみ発生

**Comment by xiii111** [comment]
@takesi0627 in review に移動して！
