### ISSUE TITLE
`Floating Button` によって、島の下部が常に隠れてしまっている

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1155]
### 問題意識
以下の画像のように、春と夏の島の下部は基本的には常に見えない。拡大やスクロールを駆使して、隙間などから見たりはできるが、折角の島なので見える状態にしたい

<img src="https://user-images.githubusercontent.com/26104258/134444116-a6dfd614-3361-4ba7-a555-2a5ee52476b8.PNG" width="300">

### 対応策
- 島の配置は `Floating Button` のy座標上で上から配置する
- ...

**Comment by xiii111** [comment]
やるということになったので、タイトルとラベルを変えて、以下に完了条件を示す

### 完了条件
- [ ] 島と海の間のスペースを縮める
- [ ] 島の大きさを少し小さくする
- [ ] `Floating Button` に被らないように、島を配置すること

**Comment by takesi0627** [comment]
> 📝iPhoneはセーフエリア下部分大きく取るため、フローティングボタンが上に来てしまうのでこの結果になっている。島の配置もセーフリア込みで組むべきかもしれない

背景の配置は6画面前提で組んでるのでセーフエリアを考慮することはできないので却下です。
大人しく上にずらすしかない。
しかし一体どれくらいに上にずらせばいいのかはわからない。
上げたところで、別の端末でセーフエリアが何ピクセル多く取ることがあればまた被ることになるだろう。
現状の実装では絶対に被らない保証はできない
