### ISSUE TITLE
`GamePlayScene` の前景が見づらい

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1162]
## 経緯

ゲーム中はなるべく前景（パネル）の方に集中してもらいたいので、
背景をぼかしたりして、フォーカスを背景に奪われないように対応。

## 終了条件

- [ ] 背景をぼかす方法について調査 (1)
- [ ] 調査した情報に基づいて実装 (2)

## 備考
背景のみ映っているカメラが必要かも

**Comment by takesi0627** [comment]
* PostProcessing の `Depth of Field` を利用する
  * https://gametukurikata.com/effect/postprocessingv2
  * パッとやっとみたがUIに効かないか反映されない。
* ガウシアンブラーのシェーダー
  * [Unityで手軽に2D擦りガラスシェーダー](https://qiita.com/ruccho_vector/items/651f760b3240a253bd1d)
  * [【Unity】【シェーダ】モバイルにおける軽量なブラーを考える](https://light11.hatenadiary.com/entry/2019/12/05/224855)
  * [【Unity】uGUI の Image を利用して背景をぼかす](https://hacchi-man.hatenablog.com/entry/2021/08/09/220000)
  * [【Unity】【シェーダ】ガウス関数を使ってブラーを掛ける](https://light11.hatenadiary.com/entry/2018/05/20/010105)
  * Imageを置いて、後ろに映ったものをキャプチャしてガウシアンフィルターをかけるという考え方。
* サードパーティ（BluredUGI）
  * https://github.com/edom18/BluredUGUI
  * 見た目微妙なのとサードパーティ入れたくないので、最終手段として取っておく。


多分シェーダーで実装すると思います。
色々参考コードあるので、どれが良いか検証して見極めていこうと思います。
