### ISSUE TITLE
`Spring-1` のステージ設計・実装

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1170]
## 完了条件
- [x] `Spring-1` のステージ配置（枝を含む）を決める
- [x] `Spring-1` の各ステージにおける、以下の内容を決める
  - [x] `Tree Id`（＊`Spring-1`）
  - [x] `Stage Number`（＊ステージ配置から決定）
  - [x] `Difficulty`（★ ~ ★★★★★）
  - [x] `Has Crystal`（＊ステージ配置から決定）
  - [x] `Constraint Stages`（＊ステージ配置から決定）
  - [x] `Tutorial Types`（＊登場するゲーム要素から決定）
  - [x] `Overview Gimmicks`（＊登場する `Gimmick` から決定）
  - [x] `Tile`
  - [x] `Bottle`（+ `Attribute`）
  - [x] `Gimmick`
- [ ] 決めた内容を適用する

## 方針
`Spring-1` は最初の木なので
- ステージを簡単にし、サクサクとクリアしてもらうことで、成功体験を提供する
- ステージの総数を少なめにし、短いスパンで木をクリアするという体験をしてもらう
- ゲームの失敗に関わるもの（≒ ギミック）の存在を伝えることで、ゲーム性を伝える
- 登場させる追加要素を少なくし、ユーザーの考える量を減らすことで、ゲーム性に慣れてもらう

## 設計
- https://docs.google.com/presentation/d/1KmfZvbYF4zkAP1-SerBJJbK-_-1WtRnVj2ba8ggHm84/edit#slide=id.gaaa75cf2d6_0_0

## 備考
- `1` は #1187 で利用するので、考える必要はない
- ユーザテストにより、大きく設計や難易度が変わりうるので、100 % のクオリティを目指さず、80 % を目指す。

**Comment by xiii111** [comment]
📝 一旦定例会でレビューをもらう

**Comment by xiii111** [comment]
@takasusuke @takesi0627 #1288 と #1289 を作成しました。一旦こちらが終わるまで、待ち状態にしようと思います

**Comment by takesi0627** [comment]
#1289 が完了したため、待ち状態を外し、プロジェクトに入れます

**Comment by xiii111** [comment]
> ## 懸念点
> ### 開放先を柔軟に設定したいが、やりづらい
> 出来るだけ `10` をクリアするのに必要ないステージは作りたくない（やる意味がなくなるから）。そもそもクリア条件が 10 をクリアしたら、ではない（というか決まってない）のでなんとも言えないが。とりあえず、`10` をクリアしたらクリア、ということにしたとしたら、全てのステージとは言わなくても、多くのステージが `10` に挑むために必要なステージであってほしい。しかしながら、木をモチーフにしている都合上、ありえない枝を引くことはしたくない。30 分くらいは困っている。議論したいところ
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/26104258/144564533-3a4f81b9-2429-4999-8e51-840c4a838432.jpg">
> 
> ### `Tutorial Types` の設定方法
> `開放先を柔軟に設定したいが、やりづらい` と関連するが、必ずしもナンバリング通りにユーザがプレイするとは限らないので、静的に `Tutorial Types` を設定するには工夫が必要である。例えば、3 にも 4 にもトルネードが登場し、3 にトルネードのチュートリアルを設定した場合、3 より 4 が先に挑戦されてはいけない。よって、3 より 4 が先に挑戦されないステージ設計にする必要があるが、全てのチュートリアルに対して、それを意識して設計するのはかなり難しいことを認識する必要がある。
> 
> では、動的にチュートリアルを出すとする。初めてのギミックかどうかを判別するロジックを持つのである。このやり方なら上記の問題は解消されるかもしれないが、新たな問題が発生しうる。それは、特定のステージに複数のチュートリアルが流れうることである。もちろん実装的には問題ないが、ユーザ的には、一気に二つ以上の新要素が加わると、大変である

こんな懸念点を概要に書いていたが、皆さんのご尽力により、解消された🎉🎉

**Comment by xiii111** [comment]
@takasusuke @takesi0627 お時間ないと思いますが、https://docs.google.com/presentation/d/1KmfZvbYF4zkAP1-SerBJJbK-_-1WtRnVj2ba8ggHm84/edit#slide=id.gaaa75cf2d6_0_0 を作成しました。ステージ詳細を決める前に議論したいので、レビューお願いします！

**Comment by xiii111** [comment]
@takasusuke @takesi0627 https://docs.google.com/presentation/d/1KmfZvbYF4zkAP1-SerBJJbK-_-1WtRnVj2ba8ggHm84/edit#slide=id.g1167d7fc05c_0_581 8 ページ目に設計概要案を書きました。木曜日に議論したいので、レビューお願いします！

**Comment by takesi0627** [comment]
一通り目を通しました。
全体的に良かったと思います。
確認ですが、`*` って難易度を示してます？

**Comment by xiii111** [comment]
> 一通り目を通しました。
> 全体的に良かったと思います。
> 確認ですが、`*` って難易度を示してます？

@takesi0627 その通りです。分かりづらすぎたので、注釈つけておきます！

**Comment by xiii111** [comment]
@takasusuke @takesi0627 レビューありがとうございました！コメントへの返信と、スライドの若干の変更をしました！本日議論させてください！また、ここから先は実装に入るので、#1176 の待ち状態を外しておきます！また、#1176 の概要を簡単に更新しておきました！
