### ISSUE TITLE
`Spring_2` のステージ設計・実装

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1176]
## 完了条件
- [ ] `Summer-1` のステージ配置（枝を含む）を決める
- [ ] `Summer-1` の各ステージにおける、以下の内容を決める
  - [x] `Tree Id`（＊`Summer-1`）
  - [ ] `Stage Number`（＊ステージ配置から決定）
  - [ ] `Difficulty`（★ ~ ★★★★★）
  - [ ] `Has Crystal`（＊ステージ配置から決定）
  - [ ] `Constraint Stages`（＊ステージ配置から決定）
  - [ ] `Tutorial Types`（＊登場するゲーム要素から決定）
  - [ ] `Overview Gimmicks`（＊登場する `Gimmick` から決定）
  - [ ] `Tile`
  - [ ] `Bottle`（+ `Attribute`）
  - [ ] `Gimmick`
- [ ] 決めた内容を適用する

## 方針
`Summer-1` は二番目の木なので
- ○○ を伝えたい
- ○○ を提供したい
- ○○ を体験してもらいたい

## 設計
#1170 のように Google Slide で作成するのが良さそうです

## 資料
https://docs.google.com/presentation/d/17mLTyIMmKF2s-T8LkFdE0562QHBFtA3yJE3p_nbcId4/edit#slide=id.gaaa75cf2d6_0_0

## 備考
- ユーザテストにより、大きく設計や難易度が変わりうるので、100 % のクオリティを目指さず、80 % を目指す。

**Comment by xiii111** [comment]
@takasusuke 一通り見て、コメントしました！背景デザインがないとしんどいですね ...

**Comment by takasusuke** [comment]
コメント感謝。
コメント返信、追記コメント(5ページ)しました。
続きは議論でよろしくお願いいたします。

**Comment by takasusuke** [comment]
Spring_2とする。
序盤：Warp
中盤：Thunder
終盤：Life

ステージ数は12~13。

**Comment by xiii111** [comment]
📝  一旦作業中へ
