### ISSUE TITLE
AttackableDynamicの失敗時演出のデザイン

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1178]
ParticleSystemの素材や、失敗時の煙演出の画像など

**Comment by xiii111** [comment]
@takasusuke https://github.com/LITO-apps/Treevel-client/issues/1067#issuecomment-939210386 で確定したので着手可能です。#1181 とイシューをまとめるかどうかはお任せします！まとめる場合には、見積もりラベルの合算や完了条件の転記、本イシューから見積もりラベルを消し、α版マイルストーンから外すなどをお願いします！

**Comment by xiii111** [comment]
#1181 とイシューをまとめるので、クローズ。見積ポイントは #1181 に結合する
