### ISSUE TITLE
記録画面のデザイン適用

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1180]
## 終了条件
- [ ] #1075 に基づいて実装

### 考慮事項
- `1`:「旅の記録」の画像を用意
- (木の状態は、解放状態に依存する)
- (日本語フォント使う)
- `1.5`:  記録画面に遷移したときに、グラフのアニメーションを行う
- `1.5`: フリック + プレイ回数
- `1`: 旅の記録
- SafeArea内にする(背景以外)
- [実装時のデザイン詳細](https://docs.google.com/presentation/d/1DDHLYk7kMF41DZCMPd-9Xtvf4_N7H6OQFyUtrCcNddY/edit#slide=id.gfb22d58c36_0_0)

<img width="249" alt="スクリーンショット 2021-10-24 11 07 27" src="https://user-images.githubusercontent.com/26213141/138577204-6114a415-8ce4-4e2a-9c72-e660705ee9e4.png">

**Comment by takesi0627** [comment]
#1061 を考慮して実装すること
