### ISSUE TITLE
季節ごとのテーマカラーを決定し、適用する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1183]
### 終了条件
- [ ] 季節ごとに異なる色を設定する箇所の洗い出し
- [ ] 各季節の色を決める
- [ ] 適用

### 考慮事項
- カラーパレット
https://material.io/design/color/the-color-system.html#tools-for-picking-colors
- 季節ごとの配色
https://www.design-memo.com/webdesign/season-color

**Comment by takasusuke** [comment]
季節の色を使う部分の洗い出し
## StartupScene
なし

## MenuSelectScene/LevelSelect
- (それぞれの島の道の色)

## MenuSelectScene/Record
- それぞれの木のクリア状況のゲージの色(#1230 で考えるのでこのissueでは考えない)

## MenuSelectScene/Others
なし

## StageSelectScene
なし

## GamePlayScene.Playing
なし

## GamePlayScene.Pausing
- 帯画像(背景、文字)
- 再開ボタン(背景、文字)

## GamePlayScene.Success
- CLEARの文字

## GamePlayScene.Failure
- リトライボタン

## その他
- コーチマークの吹き出しの色(桜の木に誘導するので、使うのは春の色のみ)
