### ISSUE TITLE
プログレスバーを消す

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1184]
## 完了条件
- [x] 現状表示されているプログレスバーを消す（ゲーム画面への遷移時のやつも含む）
- [x] 消した状態で、ユーザ体験がどれくらい悪いかを調査する
- [x] 調査結果を加味して、今後のアクションを決める

## 備考
- #394

**Comment by xiii111** [comment]
📝 画面遷移が遅かったり、画像ロードが遅かったりする場合に、簡単なロードインジケーターくらいは出せるようにしたほうが、今後便利な可能性が高い。消す際には、少し検討して別イシューを作成したい

**Comment by xiii111** [comment]
https://github.com/LITO-apps/Treevel-client/issues/1184#issuecomment-933932388 を少し検討するので、見積もりを 1 増やす

**Comment by xiii111** [comment]
> 調査結果を加味して、今後のアクションを決める 

若干ラグがあって気になるような気がするが、そこまで大きな問題にも見えなかったので、今後スマートフォンでいじるときなどに気になったらイシューを作ることにする
