### ISSUE TITLE
[OnBoarding-5] ステージの説明のためのデザイン適用

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1187]
### 終了条件
草案資料13p~17pの流れに沿って実装
https://docs.google.com/presentation/d/1KehaVUkwpoz_VFrpUR2glL-X0I-iE7vNLIX16CixBtM/edit#slide=id.g1037172d367_1_0

### 流れ
<img width="583" alt="スクリーンショット 2021-11-23 11 33 45" src="https://user-images.githubusercontent.com/26213141/142963245-3f1df569-ff38-4b63-a80c-d2c531c450b0.png">
<img width="1129" alt="スクリーンショット 2021-11-23 11 34 13" src="https://user-images.githubusercontent.com/26213141/142963277-3dfa3166-1ca5-40df-848e-07767dd85524.png">
<img width="1105" alt="スクリーンショット 2021-11-23 11 34 36" src="https://user-images.githubusercontent.com/26213141/142963297-e4c72454-dc60-4ffb-956b-5a895481ee7d.png">
<img width="1106" alt="スクリーンショット 2021-11-23 11 34 53" src="https://user-images.githubusercontent.com/26213141/142963308-62b19fcc-92c7-40f6-a72a-deed7326d051.png">
<img width="1101" alt="スクリーンショット 2021-11-23 11 35 12" src="https://user-images.githubusercontent.com/26213141/142963331-2b6ee3b4-ac21-400b-8b31-c3a1f74907be.png">

**Comment by takesi0627** [comment]
@LITO-apps/engineer 
今更気づいたけど、
テキストのところ吹き出しいらないんですか？
それとも議論するときにただ吹き出しまだ決定していなかっただけですか？

場合によっては今まで作った`CoachMark`が使えない可能性があるので確認しておきたいです

**Comment by takasusuke** [comment]
吹き出し無し想定で考えてたけど、特にこだわりはない。

他のOnBoardingと揃えられるし、楽な実装の方で良いと思います

**Comment by takesi0627** [comment]
了解、ありがとう！

さきちょっと対応策思いついたので、一旦なしの方向で実装してみる

**Comment by takesi0627** [comment]
残タスク
- [ ] コーチマークのテキストカスタマイズ可能に
- [ ] やじるしの実装
- [ ] タップOr長時間（x秒固定）
- [ ] 入力されたかの判定（ `BottleControllerBase.EnterTile` を利用）
- [ ] 成功イベントの上書き（コーチマークが閉じるまで成功ポップアップ出さない）
