### ISSUE TITLE
ゲーム内フォントの適用

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1189]
## 終了条件
#1013 で決めたMplusフォントを適用する 
- [ ] 不要なフォントを削除する
- [ ] Mplusの2種類のフォントを追加する
- [ ] 全てのTextのフォントをMplusに変更する(prefabならprefab, prefabになっていないものはSceneで直接)
- [ ] 太字のTextはMplus Boldフォントに設定する
- [ ] 権利表記

## 考慮事項
- Mplusに8種類フォントあるけど、8種類必要？2種類にして、必要に応じて追加する。
- 文章の長さは考慮しない
- 文字の大きさは考慮しない
- どの文字はどのフォントを利用するのかのガイドラインを作成する
- 日本語と英語でフォントはいったん変わらない

**Comment by xiii111** [comment]
📝 待ち状態を外す

**Comment by xiii111** [comment]
@takasusuke 

> - [ ] 不要なフォントを削除する

ですが、現状は以下のフォントが存在しているようです。どれも重たいファイルなので、不要なフォントはきっちりと消すようにお願いします！

- `4.5 mb`：`Assets/Project/Fonts/07やさしさゴシック.ttf`
- `3.9 mb`：`Assets/Project/Fonts/07LogoTypeGothic-Condense.ttf`
- `2.2 mb`：`Assets/Project/Fonts/07やさしさゴシックボールド.ttf`
- `1.7 mb`：`Assets/Project/Fonts/Mplus1-Regular.ttf`
- `1.6 mb`：`Assets/Project/Fonts/Mplus1-Bold.ttf`
- `403.3 kb`：`Assets/Project/Fonts/OtomanopeeOne-Regular.ttf`
- `344.5 kb`：`Assets/TextMesh Pro/Fonts/LiberationSans.ttf`
- `229.7 kb`：`Assets/Project/Fonts/GL-Otomanopee.ttf`
