### ISSUE TITLE
`DarkAttribute` のデザイン適用

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1192]
## 完了条件
- [ ] [素材画像](https://drive.google.com/drive/u/0/folders/1c7Q9gxb-O_WVooME9RvieGwujq8oobhr) をアニメーションに適用する
- [ ] Particle を実装する

## 手順
1. [素材画像](https://drive.google.com/drive/u/0/folders/1c7Q9gxb-O_WVooME9RvieGwujq8oobhr) の内、片方を既存の画像の代わりに利用する
  - #1303
2. [素材画像](https://drive.google.com/drive/u/0/folders/1c7Q9gxb-O_WVooME9RvieGwujq8oobhr) の内、もう片方を利用し、ユーザがボトルをホールドした時と、ボトルがゴールに移動した時のアニメーションを分ける（遷移上は、開く1 と閉じる2 になる可能性がある）
  - #1379 
3. dark 時に particle を出すようにする

## [デザイン草案](https://docs.google.com/presentation/d/1ED6jg7QrMTD40uJVKf8dCU34Pu06tLjXS2UO8cvoyas/edit#slide=id.gb4dad404de_0_4)

<img width="500" alt="スクリーンショット 2021-12-16 13 36 46" src="https://user-images.githubusercontent.com/26104258/146309080-3ccf7537-77b4-422f-89d0-3f1708d683d3.png">

<img width="500" alt="スクリーンショット 2021-12-16 13 36 53" src="https://user-images.githubusercontent.com/26104258/146309085-ba7f0d8d-e4ef-47e0-8854-1bc56b5af86a.png">

## Particle の備考
- https://github.com/LITO-apps/Treevel-client/pull/595
- GhostAttribute の実装

**Comment by xiii111** [comment]
@takasusuke [素材画像](https://drive.google.com/drive/u/0/folders/10jRljh2qHyqgFDu-zcjEAHeZcJwxNQ9G) を見ると、`タイムライン1_0001.png` と `タイムライン1_0002.png` のように、一見ほぼ同じ見た目のものが二つあるケースがいくつかあります。これは定例会でも話したように、20 フレームのアニメーションを作るにあたって、2 フレーム分、同じ画像を使うから、ということであっていますか？

**Comment by takasusuke** [comment]
1と2, 3と4, ...13と14枚目までは同じでそこから1枚ずつ違うから多分意図としては、1, 3, 5, ..., 13枚目の画像は2フレーム使う、ということだと思う。
プロジェクトに含める画像としては、2, 4, 6, 8, 10, 12, 14は使わずにアニメーションの設定で持続時間を変更するので良いと思います。

多分、手元で連番画像から動画作って見た目の確認するために同じ見た目の画像を用意したんだと思う。

**Comment by xiii111** [comment]
@takasusuke 返答ありがとう！ちなみに https://docs.google.com/presentation/d/1ED6jg7QrMTD40uJVKf8dCU34Pu06tLjXS2UO8cvoyas/edit#slide=id.gb7ac52c2e9_0_133 の

> 上行のように、闇が中央から晴れていくアニメーションと、下行のように、闇が外側から晴れていくアニメーションのどちらもゲーム内で使いたいと考えております

って、めっちゃ経緯忘れたんだけど、どういう出し分けをするんだっけ？

**Comment by takasusuke** [comment]
内側から晴れるアニメーションはTapした時のアニメーションで、
外側から晴れるアニメーションはゴール状態に達した時のアニメーションだった気がする

Tap終わりは、Tapした時の逆再生
ゴールじゃなくなった場合は、ゴールの時の逆再生
な記憶

**Comment by xiii111** [comment]
@takasusuke Tap = Hold ??

**Comment by takasusuke** [comment]
ya

**Comment by xiii111** [comment]
@takasusuke つまり、既存の animator の state を増やしたりしないといけないってことか。とりあえず、1 パターンを実装して、その後に Tap かどうかで animation を分けるようにしようかな
