### ISSUE TITLE
音源の購入

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1193]
### 終了条件

- [x] 購入リストを整理 (1)
- [x] 適切の音かどうか議論し、確認する(2)
- [x] 購入する(1)
- [x] Scrapboxに記入

**Comment by takesi0627** [comment]
@LITO-apps/engineer 
時間あったらアンケートの記入をお願いします
今日の通話まで間に合わないと思うので議論は定例に行いたいと思います。

アンケートの記入基準は今改めて聞いみて素直の気持ちでお願いします。

### `ASK`
アルファー版に向けて、秋と冬はまだ実装予定はないので 
* 05-StageSelectScene-Autumn 
* 06-StageSelectScene-Winter
* 10-GamePlayScene-Autumn
* 11-GamePlayScene-Winter

はまだ用意しなくてもいいんじゃないかと思いますが、いかがでしょうか

**Comment by takasusuke** [comment]
# アンケート
**※ 編集中**
◎：めっちゃ合うから買わなきゃ
△：ちょっと微妙だから保留（alpha版に入れても良いけど、時間あったらもっと良いの探したいくらいの感覚）
×：変えた方がいい（マジで新しいやつ探さないとやばいやつ）

## BGM
| ClipName | ◎ | △ | × |
| -- | -- | -- | -- | 
| 01-StartUpScene | - | v | - |
| 02-MenuSelectScene | - | - | - |
| 03-StageSelectScene-Spring |  - | - | - |
| 04-StageSelectScene-Summer |  - | - | - |
| 05-StageSelectScene-Autumn |  - | - | - |
| 06-StageSelectScene-Winter |  - | - | - |
| 07-GamePlayScene-Tutorial |  - | - | - |
| 08-GamePlayScene-Spring |  - | - | - |
| 09-GamePlayScene-Summer |  - | - | - |
| 10-GamePlayScene-Autumn |  - | - | - |
| 11-GamePlayScene-Winter |  - | - | - | 
| 12-GamePlayScene-Difficult |  - | - | - |

## SE
| ClipName | ◎ | △ | × |
| -- | -- | -- | -- | 
| Bottle_Break | - | - | - |
| Bottle_Destroy |  - | - | - |
| Bottle_Move |  - | - | - |
| ErasableBottle_In |  - | - | - |
| ErasableBottle_Out |  - | - | - |
| GamePlay_Failed_1 |  - | - | - |
| GamePlay_Failed_2 |  - | - | - |
| GamePlay_Succes |  - | - | - |
| Gimmick_Gust |  - | - | - |
| Gimmick_Meteorite_Collide |  - | - | - |
| Gimmick_Meteorite_Drop |  - | - | - |
| Gimmick_Powder |  - | - | - |
| Gimmick_Thunder_1 |  - | - | - |
| Gimmick_Thunder_2 |  - | - | - |
| LevelSelect_River |  - | - | - |
| Tile_Warp |  - | - | - |
| UI_Button_Click1<br>(UI_Button_Click_Start_App,<br>UI_Button_Click_Start_Game) |  - | - | - |
| UI_Button_Click2<br>(UI_Button_Click_General) |  - | - | - |
| UI_Dropdown_Close |  - | - | - |

---------
## コメント
- `01-StartUpScene` : この曲ありきで考えている部分も多いだろうし、気に入っている。TitleSceneの画像が入ったら、もしかしたら曲を変えたくなるかも、という消極的な意見で△。ほぼ◎。

**Comment by takesi0627** [comment]
@LITO-apps/engineer 

こんな感じに選考基準用意しておくが、選考基準はMTG直前に公開します。
（まだできていないのもあるけど、公開しちゃったらアンケート記入に影響するかもしれないので

> ### 買う
> ◎◎◎
> ...
> ### 買うけどアルファー版後差し替えあり
> △△△
> …
> ### ボツ
> ×××
> …

ボツのやつはスケジュールの関係で、アルファー版までもう一度探すのは大変だと思うので、対応としてはAlpha版までに適当にフリー素材入れる。
本番まで本素材を探す、購入、編集イシューをやるという方針でいこうかなと思います

**Comment by xiii111** [comment]
@takesi0627 アンケート記入終わりました！

**Comment by takesi0627** [comment]
# 採用基準
### ①買う
◎◎◎ 
◎◎△
◎◎×

### ②買うけどアルファー版後差し替えあり
△△△ 
△△◎
△△×
××◎
◎△×
△△×

### ③ボツ
×××
××△


スケジュールを鑑みて、購入基準を少々緩めでいきたいと思います。
なお、アルファー版実装しないものは本タスクでは購入しませんが、選考結果は今後本番に向けて音源実装の参考にします。

**Comment by takesi0627** [comment]
# アンケート集計

## BGM
| ClipName | 集計結果 | 判定 | 備考 |
| -- | -- | -- | -- | 
| 01-StartUpScene | ◎◎△ | ① |  |
| 02-MenuSelectScene | ◎△× | ② |  ※|
| 03-StageSelectScene-Spring | ◎◎◎ | ① | |
| 04-StageSelectScene-Summer | ◎△△ | ② | |
| 05-StageSelectScene-Autumn |◎◎◎ | ①| |
| 06-StageSelectScene-Winter | ◎◎◎ | ①| |
| 07-GamePlayScene-Tutorial | △×× | ③ | そもそも不要かも |
| 08-GamePlayScene-Spring | ◎◎△ | ① |  |
| 09-GamePlayScene-Summer | ◎△× | ② |  ※|
| 10-GamePlayScene-Autumn |◎◎△ | ① |  |
| 11-GamePlayScene-Winter | ◎◎◎ | ①| |
| 12-GamePlayScene-Difficult | ◎△△ | ② | |

## SE
| ClipName | 集計結果 | 判定 | 備考 |
| -- | -- | -- | -- | 
| Bottle_Break | ◎◎× | ① |  |
| Bottle_Destroy | ◎◎△ | ① |  |
| Bottle_Move | △△△ | ② | |
| ErasableBottle_In (フリー) | ◎◎× | ① |  |
| ErasableBottle_Out (フリー) | ◎△× | ② |  |
| GamePlay_Failed_1 |  ◎×× | ② |  ※|
| GamePlay_Failed_2 | ××△  | ③ |  ※ |
| GamePlay_Succes |◎◎△ | ① |  |
| Gimmick_Gust |◎◎◎ | ①| |
| Gimmick_Meteorite_Collide | ◎△× | ② |  |
| Gimmick_Meteorite_Drop | ◎◎△ | ① |  |
| Gimmick_Powder | ◎◎◎ | ①| α実装しない|
| Gimmick_Thunder_1 | ◎△× | ② |  Thunder_1の方が良さそうなので<br>そっち採用する|
| Gimmick_Thunder_2 |  ◎◎△ | ① |  |
| LevelSelect_River (フリー) |  ◎×× | ② |  ※|
| Tile_Warp (フリー) |   ◎×× | ② |  ※|
| UI_Button_Click1<br>(UI_Button_Click_Start_App,<br>UI_Button_Click_Start_Game) |◎◎△ | ① |  |
| UI_Button_Click2<br>(UI_Button_Click_General) | ◎◎△ | ① |  |
| UI_Dropdown_Close |  ◎◎× | ① |  |

**Comment by takesi0627** [comment]
> * `UI_Dropdown_Close` はドロップダウンがリリースに入らないし、めっちゃいい！ってわけでもないから無しかな

名前がDropdown_closeになってるが、ポップアップを閉じる時の音に使っています

**Comment by takesi0627** [comment]
* 2️⃣をつけたものを #1215 でベータ版以降時間があったら探す
* `02-MenuSelectScene` -> #1216
* `09-GamePlayScene-Summer` -> #1217

その他の音源を購入次第こちらを閉じたいと思います。
@takasusuke 申し訳ありませんが、`09-GamePlayScene-Summer`についてのコメントなどは #1217 へ移行するようにお願いします

**Comment by takesi0627** [comment]
購入したものは改めて [ここ（Google Sheets）](https://docs.google.com/spreadsheets/d/1ECC6cy1gLUKIs8iZ-1W_afyFT1cc9VA2dB3Jtpb1vLI/edit#gid=0)にまとめました
