### ISSUE TITLE
TornadoGimmickのデザイン適用

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1194]
#764 待ち
- [x] 移動中アニメーションの作成
- [x] 出現するアニメーションの作成
- [x] 警告をなくし、代わりに端から出現するアニメーションを入れる実装
- [ ] SE を探し、適用する
- [x] 曲がる際に一時止まる実装

**Comment by xiii111** [comment]
📝 In Review に移動
