### ISSUE TITLE
`Tornado` アイコンのデザイン草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1196]
### 終了条件
- [ ] 既存のTornado画像の中からアイコンにする素材を選定する
- [ ] #1221 の待ち状態をはずす

### 考慮事項
Tornado素材による。
そのまま適用できそうなら、このissueはcloseする。

若干、依頼が必要ならそれの草案資料を作成する

**Comment by takasusuke** [comment]
## 第一候補
Torando@spin-000
<img width="250" alt="スクリーンショット 2022-01-29 13 44 50" src="https://user-images.githubusercontent.com/26213141/151647709-4db6603c-fa52-4e55-8269-7b0564597768.png"> <img width="250" alt="スクリーンショット 2022-01-29 13 44 42" src="https://user-images.githubusercontent.com/26213141/151647711-b8555d4a-4ded-468a-b12c-217013a4f721.png"> <img width="250" alt="スクリーンショット 2022-01-29 13 46 38" src="https://user-images.githubusercontent.com/26213141/151647703-87ed6763-b00e-4bec-a378-05800a5721a2.png">

## 第二候補
Tornado@appear-008
<img width="250" alt="スクリーンショット 2022-01-29 13 43 40" src="https://user-images.githubusercontent.com/26213141/151647716-0dbab9dc-5ddb-4719-bf5b-0a127a82daaf.png"> <img width="250" alt="スクリーンショット 2022-01-29 13 43 32" src="https://user-images.githubusercontent.com/26213141/151647717-ce3e2010-4a78-4caf-8646-f4dc02b110ca.png"> <img width="250" alt="スクリーンショット 2022-01-29 13 46 29" src="https://user-images.githubusercontent.com/26213141/151647707-5631b05b-30bc-402b-a8f1-5545c616cf30.png">

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
候補を二つ選びました。
自分としてはアニメーション中のアイコンで伝わる、かつ、実際にプレイ中に登場する見た目と違わない方がユーザを混乱させない、という理由からアニメーション中のアイコンで良いと考えています。

OverviewPopupで背景の白とTornadoが同化するのが気になるのなら、背景の色を全てグレーにする（ギミックがない場合のグレーはもっと暗くする）か、Gimmmickごとに見やすい背景色を決めると良いかと思います。

※ Tutorialのアイコンは仮に１枚絵にしましたが、コマ送りアニメーションの方が伝わるとは思います。

コメントお願いします。

**Comment by takesi0627** [comment]
> OverviewPopupで背景の白とTornadoが同化するのが気になるのなら、背景の色を全てグレーにする（ギミックがない場合のグレーはもっと暗くする）か、Gimmmickごとに見やすい背景色を決めると良いかと思います。

白でも全然気にならないので白のままがいいと思います。
Gimmickごとに決めるのは労力かかるし、色が多すぎて混乱するので良くないと思います。


個人的に候補１の方がアイコンに似合います。
理由はよくわかりませんが、線が少ないからかもしれません。

**Comment by takasusuke** [comment]
Torando@spin-000 で決まり。
OnBoardingPopupの背景は白のままで良い。
