### ISSUE TITLE
チュートリアルポップアップのテキスト作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1203]
資料: https://docs.google.com/presentation/d/1SuyXL8nL6PVuhw1BB1p-ky2R8LXQxeGqmJQxXOxYFt8/

### 経緯
#1201 を行うにあたって、リリース時に必要なチュートリアルポップアップに対して、表示名と説明が用意されている必要がある。アイコン画像については、#1203  で行うことにする。

### 備考
- 表示名は 1 行、説明は 3 行に収まるようにする
- 英語も必要

### 完了条件
以下の表示名と説明を決める
#### ギミック
- [x] Tornado
- [x] Meteorite
- [x] AimingMeteorite
- [x] Thunder
- [x] GustWind
- [x] Erasable

#### タイル
- [x] Goal（ #1143 により不要になった）
- [x] Warp
- [x] Holy
- [x] SpiderWeb
- [x] Ice

#### ボトル
- [x] Dynamic
- [x] Static
- [x] Goal（ #1143 により不要になった）
- [x] AttackableDummy

#### ボトルアトリビュート
- [x] Dark
- [x] Reverse
- [x] Ghost
- [x] Life

#### 適用
- [x] 上記をアプリに適用する

**Comment by xiii111** [comment]
#1242 でチュートリアルタイプが定義されているので、それに対しての表示名と説明を考える

**Comment by xiii111** [comment]
📝  #1143 が終わるまでは、どのチュートリアルが存在するか分からないので、完了できない。全く着手できないわけではないので、取り組めるところまでは取り組む

**Comment by xiii111** [comment]
@takasusuke @takesi0627 https://docs.google.com/presentation/d/1SuyXL8nL6PVuhw1BB1p-ky2R8LXQxeGqmJQxXOxYFt8/ で、各オブジェクトにおける日本語の表示名・説明と、英語の表示名を考えました。英語の説明は日本語の説明が決まってから考えます。木曜日のタスク通話で議論したいので、コメントお願いします。`⚠️ レビュー時の注意点 ⚠️` というスライドもあるので、一読お願いします！

**Comment by takasusuke** [comment]
思いついたとこはコメントしました。
代替案が思いついてないものはコメントしていない。

**Comment by takesi0627** [comment]
すみませんコメント書く時間なかったがとりあえず目を通しました

**Comment by xiii111** [comment]
@takasusuke @takesi0627 https://docs.google.com/presentation/d/1SuyXL8nL6PVuhw1BB1p-ky2R8LXQxeGqmJQxXOxYFt8/edit#slide=id.gf21fbffcd0_0_10 の `基本情報` から再度レビューお願いします！タスク通話で議論しようと思います！

**Comment by takesi0627** [comment]
とても良かったと思います！
一点だけコメントしました。

**Comment by xiii111** [comment]
脆い岩石、修正し損ねていました。今から考えます

**Comment by xiii111** [comment]
ついでに漢字とカタカナをより統一感あるように出来ないか再検討する

**Comment by xiii111** [comment]
微修正完了

**Comment by xiii111** [comment]
https://docs.google.com/presentation/d/1SuyXL8nL6PVuhw1BB1p-ky2R8LXQxeGqmJQxXOxYFt8/ の内容で適用を始める。注意点としては、フォントサイズ。静的にフォントサイズを決める場合には、小さいデバイスでデバッグをすること。また、そのせいで大きいデバイスではスカスカで実装されてしまう可能性があるが、これはこのイシューの範疇外なので、考慮しないことにする
