### ISSUE TITLE
`LevelSelect_River` の音源が背景に合っていない

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1215]
## 経緯
現状は川の SE になっているので、海の SE にする

## 概要
- [ ] SE を探す
- [ ] SE を適用する

## 備考
- ザーッ のイメージ

**Comment by xiii111** [comment]
@takasusuke @takesi0627 候補を出しました！レビューお願いします！

魔王魂や MusMus には良い感じの音源がありませんでした。探してみての所感ですが、画面に見える海の範囲が非常に広いので（島が見渡せるほどには）、イメージに合う音源があまりないのかなという感じです。通常では音が聞こえない距離感の海なんですよね。なので、SE 自体をなくしてしまうのもアリかなーとは思いました

## 候補1
小波・砂浜
https://taira-komori.jpn.org/nature01.html

## 候補2
海のビーチの波
https://audiostock.jp/audio/387995

## 候補3
ビーチの波は穏やかな海
https://audiostock.jp/audio/387993

## 候補4
遠い海-穏やかな風
https://audiostock.jp/audio/384875

## 候補5
音を無くす

**Comment by takesi0627** [comment]
候補１〜候補３は波打を想起されるような音ですが、そのようは演出になっていないので適切ではない気がする。
候補４は風の音も加わってちょっとうるさい。

なしで良さそうです。

**Comment by xiii111** [comment]
なしで良いとのことで、修正を進めます
