### ISSUE TITLE
いくつのステージをクリアすれば次のレベルが解放するかわからない

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1230]
### 終了条件
- [ ] 草案資料を作る
https://docs.google.com/presentation/d/1h3za7ZCkU_FSPoksMxPMHsTVlwFcB9Ii1wffykdBRbo/edit#slide=id.p

### 考慮事項
- [ ] StageSelectSceneで、何ステージクリアすれば木がクリアかわかるようにする
- [ ] 全クリアすると木の状態が変わることを示唆する表示にする
- [ ] 記録画面の木の表示を参考にする(それと連動させる)

**Comment by xiii111** [comment]
@takasusuke #1288 を作りました、重複であればクローズしてください！#1288 を作っていて思いましたが、何ステージ、にこだわる必要がないと思いました

**Comment by takasusuke** [comment]
#1288 に依存するので、一旦STAY

**Comment by takasusuke** [comment]
#1288 でクリア条件を決めた結果、クリア条件は、クリア数ではなくなったのでこのissueは必要なくなりました。

**Comment by takesi0627** [comment]
#1288 の議論でクリア条件が変わりましたので本件をクローズする
