### ISSUE TITLE
BGM / SE 周りの調整と整理

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1238]
ref: https://github.com/LITO-apps/Treevel-client/pull/1234#pullrequestreview-787944413 https://github.com/LITO-apps/Treevel-client/pull/1234#issuecomment-950871902

### 概要
- #1234 で指摘された、BGM / SE 周りの調整と整理を行う

### 完了条件
＊必ずしも全てやる必要はない

by @xiii111 
- [ ] BGM をイヤホンで聴くと、かすかに ジーーー というノイズが入っているように聞こえます
- [ ] #1255
- [x] ステージ選択から挑戦した時に、Ready Go が流れ終わるまで、ステージ選択の BGM が流れているのに違和感を持ちました
- [x] SE の音量を個別に調整すれば良い話ですが、どちらも同じ設定値の場合に、`LevelSelectScene` の `LevelSelect_River` が `02-MenuSelectScene` に対して若干大きいようです。`LevelSelect_River` は今後差し替えることを加味して、無視しても構いませんが、この傾向は SE 全体で感じましたので、感想として伝えます（雷や隕石なども過度に大きいと思う）
- [x] 一時停止ボタンをタップしても SE が鳴らず、再開した時に一時停止ボタンの SE が流れるようです（再開するボタンの SE とぶつかっている）
- [x] 一時停止中の音量の下げ具合をもう少し高めても良さそうです
- [x] 一時停止中のやりなおすとあきらめるのボタンの SE がなさそうです
- [x] 記録 / ホーム / その他のボタンに SE がなさそうです
- [x] 成功画面の TAP TO RETURN や Twitter ボタンに SE がなさそうです
- [x] 失敗画面の RETRY と BACK と Twitter ボタンに SE がなさそうです
- [x] 失敗画面の失敗閲覧への切り替えに SE がなさそうです
- [x] GustWind の音が若干遅れたタイミングで聞こえる気がします
- [ ] 夏と冬のゲーム内での BGM が若干メリハリなく聞こえ始めるのが気になります

by @takasusuke 
- [x] (議論) FooterボタンにもButton_Clickの音入れるのはどうでしょうか
- [x] (感想) StageSelectのBGMは`StageSeelctDirector.cs`の`Start()`で再生しているけれど、`MenuSelectScene`のBGMは`Startup`のボタンを押した時、`StageSelectScene`から戻るときに再生しているので、画面と音のタイミングが合ってない印象を受けました。
`MenuSelectScene`のBGMも`LevelSelectDirector`の`Start()`で再生した方が良いかもと思いました。
- [x] (感想) 失敗時のBottleの音の開始が遅い(出だしが小さい?)と感じました。trimしても良いかも
- [ ] (議論) 失敗時にBGMを止めなくても良い気がしてきた
- [x] (議論) Gimmickって失敗時、音止めてるんだっけ？Thunderで失敗した時を聞く感じ、少なくとも失敗原因になったギミックのSEは止めなくても良い気がしてきた
- [x] 海のSEがループされていない

### その他
by @xiii111 
### ask
`Assets/Project/SoundClips/SoundDataList.asset` の運用を忘れてしまったのですが、例えば `UI_Button_Close_Popup` と `UI_Button_Return` は同じ `UI_Popup_Close` を参照していますが、これは一つに統一しないんでしたっけ？（`UI_Button_Click1` も同様）

<img width="661" alt="スクリーンショット 2021-10-25 13 31 03" src="https://user-images.githubusercontent.com/26104258/138635135-774bc566-c7c8-44ab-928a-37ded70fc8ed.png">

**Comment by takesi0627** [comment]
> ### ask
> `Assets/Project/SoundClips/SoundDataList.asset` の運用を忘れてしまったのですが、例えば `UI_Button_Close_Popup` と `UI_Button_Return` は同じ `UI_Popup_Close` を参照していますが、これは一つに統一しないんでしたっけ？（`UI_Button_Click1` も同様）

回答になってるかわかりませんが、このコメントが元になってると思います。
https://github.com/LITO-apps/Treevel-client/pull/791#discussion_r606644060

機能としては別だけど、SEのバリエーションが現状少ないので同じ音源を使うだけで、
プログラム上の呼び出し全部同じにするのも違う気がするので今に至ったと言った感じです。
