### ISSUE TITLE
[OnBoarding-3] ステージの解放を伝えるポップアップのデザイン

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1243]
## 終了条件
- 画像を作る

### 考慮事項
<img width="1277" alt="スクリーンショット 2021-11-06 12 11 10" src="https://user-images.githubusercontent.com/26213141/140596077-d814eca4-6176-4d99-b2d1-8b966a3482bd.png">

**Comment by takesi0627** [comment]
#1190 と合併
