### ISSUE TITLE
パフォーマンスの改善を行う

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1287]
## 完了条件
- [ ] パフォーマンスに関わる様々な要素を全体的に見てみる
- [ ] どのような数値を改善するかを決める
- [ ] 改善する内容ごとにイシューを作成する

## 改善候補
- CPU
- Memory
- FPS
- 電池消費

## 備考
- 取り組むのは出来るだけ終盤にする
- 改善をするのは別イシュー

**Comment by takesi0627** [comment]
#1634 #1635
に分割した。
