### ISSUE TITLE
木がクリアになる条件を決め、コードに反映する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1288]
## 完了条件
- [ ] どのような条件で木がクリアになるのかを決める
- [ ] 決めた内容をコードに反映する

## 備考
解放条件、草案資料
https://docs.google.com/presentation/d/1oAaDsB6wnuXJbSZ-tjtb-z-pdFcXQc5S237gjiR1IJg/edit#slide=id.g10724e3d0e9_0_96
- 候補として `最後のステージをクリアしたら` や `N % のステージをクリアしたら` など
- 木のクリアと完全クリアという概念を用意するかどうかも、このイシューで決める

**Comment by takasusuke** [comment]
### 木のクリア条件
- N個のステージをクリアする
- N個の特定のステージをクリアする

### 枝の形状
## 1~10まで分岐なし、直線的な有向グラフ
メリット：ステージの解放条件が直感的でわかりやすい
デメリット：
- クリアできないステージがあると他のステージをプレイすることができない
- 背景(木)に配置するUIとして、枝(分岐がある)という特性を活かした配置にできない。(世界観を補強できない)

## 木構造(循環のない有向グラフ)。N個の終端がある。
メリット：木の背景に合う配置ができる。1度に複数のステージを解放できる。
デメリット：
- 10番のステージ以外の終点をクリアする必要があるかどうかユーザがわからない。クリアする必要がある場合、それをユーザに伝える必要がある。
- あるステージの解放に複数のステージのクリアが必要な場合、それを伝える工夫が必要。

## 有向非巡回グラフ。視覚的に閉路がある。
メリット：特定のステージをクリアできなくても、別ルートのステージをクリアできれば、10番のステージに辿り着けることもある。
デメリット：
- 木のクリア条件が、10番のステージをクリアすることの場合、クリアしなくても良いステージを作ることもできる。
- 自然界の枝は、視覚的な閉路が存在しないので、枝以外の表示方法が好ましい

**Comment by takasusuke** [comment]
クリア条件
10番(頂上)のステージをクリアする + 0個以上のKEYとなるステージをクリアする

完全クリア条件
全てのステージをクリアする

**Comment by takasusuke** [comment]
考えることメモ
- 行き先が分岐する時、1から順に数字を振る意味があるのか(数字を振るなら、ユーザに順番を意識させる必要がある。数字を振らないならExtraステージとわかる表現にする必要がある。ステージクリア数が解放条件であることをユーザにわからせるなら分岐を作る選択肢もある)
- はじめのステージはどの木でも「１」から。

**Comment by takasusuke** [comment]
編集中

ユーザに直線的にプレイしてもらうパターン
メリット
デメリット


### ステージ数について。
1エリア10ステージという制約はキリが良いから見たいな理由で適当に決めたはず。
#1170 を受けて、10ステージは少なく感じた。
ギミックの出現頻度や出現位置、ボトルの初期位置、AttirbuteやTileの組み合わせでもっと難易度はグラデーションで作れるのから。

木ごとのステージ数はとりあえず揃えた方が良い気がするので、１ステージ15とか20にしたほうがよく思いました。
(Spring_2とかのステージでは1ステージ16とかでも良いとは思う。)
(Extraステージみたいな扱いにするなら、ステージ数の総数が揃っていなくてもそこまで変ではないとは思う。1から順番にナンバリングするなら揃えるのが無難な気がするけど、揃えなくても良いような。)
(拡張の話なので一旦決めなくて良いです。)

**Comment by takasusuke** [comment]
## 全体
### クリア条件について。
- クリア数がクリア条件の場合、分岐は用いずに直線的な構成にする。
クリアに必要なステージは難しすぎない程度。簡単すぎるわけではない。
完全クリアに必要なステージはEXTRAステージであることをわかるようにする（★マークをつけるなど）
- 特定のステージのクリアがクリア条件の場合、ステージアイコンに傷画像を重ねた表現にする。分岐はあっても良い。
https://docs.google.com/presentation/d/1oAaDsB6wnuXJbSZ-tjtb-z-pdFcXQc5S237gjiR1IJg/edit#slide=id.g108999ad1df_1_127

### ステージ数について。
1エリア10ステージという制約はキリが良いから見たいな理由で適当に決めたはず。
#1170 を受けて、10ステージは少なく感じた。
ギミックの出現頻度や出現位置、ボトルの初期位置、AttirbuteやTileの組み合わせでもっと難易度はグラデーションで作れるのから。

木ごとのステージ数はとりあえず揃えた方が良い気がするので、１ステージ15とか20にしたほうがよく思いました。

ステージを小さくしたり密度を上げるなどして、20ステージまでは問題なく表示できる余地はあると思います。
https://docs.google.com/presentation/d/1oAaDsB6wnuXJbSZ-tjtb-z-pdFcXQc5S237gjiR1IJg/edit#slide=id.g10724e3d0e9_0_87

**Comment by takasusuke** [comment]
@LITO-apps/engineer 

木のクリア条件と枝の接続ルールを分離して考えるのは難しかったです。

- クリア条件をどうするか（クリア数か、特定のステージをクリアするか）
- 分岐があるか
- 通常のステージとEXTRAステージを区別して表示するか

などを踏まえて、どういうゲームデザインにしたいかコメントお願いします。

**Comment by takasusuke** [comment]
決まり
- クリア条件：木に設定されたN個の特定のステージをクリアする
- 完全クリア条件：全ステージクリア

必要なissue
- クリアに必要な特定のステージがどれかわかるようにする
-
