### ISSUE TITLE
IceTile 上をボトルが高速で移動してしまう

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1313]

**Comment by xiii111** [comment]
📝  再現確認から

**Comment by xiii111** [comment]
現状で Ice があるステージは以下ですが、それぞれ 5 分ずつくらい操作しても、発生しませんでした。確かこの現象が起きたのは、マイルストーン MTG 中で、誰かのローカル環境だったと思います。何かしらの原因で一時的に発生した可能性もあるので、一旦閉じようと思います。また発生したら教えてください
- Spring_1_1
- Spring_1_3
- Spring_1_7
