### ISSUE TITLE
サウンド全体の音量調整

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1316]
- [ ] BGM：音量１の時に1.2dB ~ 1.8dB に収まる
- [ ] SE：気持ちで調整

**Comment by takesi0627** [comment]
[「ラウンドネス」基準について](https://www.4gamer.net/games/032/G003263/20121103005/)

* テレビのラウンドネス基準：-24LKFS +- 1dB
* ラウンドネスは`CRI Profile`から観測できる
<video src="https://user-images.githubusercontent.com/17778395/168437939-dea602ce-19bd-41f3-8434-12042f00029a.mov">
* ゲーム業界における基準はまだない。が、`CRI Profile`の初期値の -24LKFS +- 2dB は良さそうなので一旦それを目標に。

**Comment by takesi0627** [comment]
仕様決めの時に音量１の時って言いましたが、よく考えたら、頑張って調整したものが初期値であるべきなので、初期値である `0.5` の時のラウドネスを基準にする。
