### ISSUE TITLE
Optionが見出しであることを強調する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1317]
## 終了条件
- [ ] 設定画面の「Option」の文字が見出しに見えないので、見出しに見えるようにする

## 考慮事項
- TextMeshProで工夫しそう
- デザインは良い感じに？
- 日本語と英語で同じ文言なのでSpriteでも良いかも(文字が違っても、Spriteでできる)

<img width="277" alt="スクリーンショット 2022-01-30 10 31 06" src="https://user-images.githubusercontent.com/26213141/151683250-0eb05d47-45c0-4ba8-ad14-6baeab5a074d.png">

**Comment by takasusuke** [comment]
資料
![image](https://user-images.githubusercontent.com/26213141/153002894-49df8f4a-550b-4e77-8d84-4ac80878da80.png)

![image](https://user-images.githubusercontent.com/26213141/153002942-b10f6586-3a95-4f0c-86eb-6aaa8f468da9.png)

![image](https://user-images.githubusercontent.com/26213141/153003156-a73ac291-5c3f-4e08-91eb-a743496a14d0.png)

**Comment by xiii111** [comment]
> * Optionのテキストカラーの変更
> * Optionの位置の変更

とても良い

> * Option下に区切り線を追加

https://github.com/LITO-apps/Treevel-client/pull/1373#issuecomment-1034789490 と似た意見なんだけど、区切り線が目立ちすぎる。今回の場合には、境界線を用意する理由が、タイトルであることを伝えることであれば、タイトルの下のみに下線をつけて目立たせたり、テキスト自体を装飾する方向の方が良いと思った。この境界線はポジティブな理由をたくさん貰えないと、納得できない

> * VolumeのText位置の調整
> * Volume Sliderのカラーの変更
> * Volume Mute Buttonの位置の調整

とても良い。Volume の Text Color も変えているかな？

> * Review/Twitter Buttonの位置の調整

とても良い
