### ISSUE TITLE
レビューを投稿する機能の実装

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1327]
### 終了条件
- [ ] レビューを投稿するために必要なURLの取得方法を調べる
- [ ] レビューを投稿するためのURLを取得する
- [ ] 取得したURLを実装する

### 考慮事項
β版のマイルストーンで、URLの取得方法を調査したい。

**Comment by xiii111** [comment]
現在書かれている終了条件では、`レビューを投稿` ボタンから AppStore に遷移させ、レビューを自主的に投稿してもらう機能のみを想定しているように見える

<img src="https://user-images.githubusercontent.com/26104258/160236447-10d3d05d-09a7-4ae2-a26b-34a8d7349ca0.jpeg" width="300">

この機能は実装するとして、iOS では以下のようにレビュー投稿を促すダイアログを出すことができる

<img src="https://user-images.githubusercontent.com/26104258/160236401-ba00c686-8ca5-4d1a-a0c6-203c7992d3a3.PNG" width="300">

本イシューの範疇でこちらまで実装するかを定例会の時に決めたい。こちらの実装をする場合には、レビュー投稿を促すダイアログを出すタイミングをきちんと考える必要がある。例えば、総起動回数（既に記録済み）が 3 の倍数回になったタイミングで定期的にダイアログを出すなど。補足として、このダイアログを利用して、過去にレビューしてくれたかの状態を取得することはできませんが、**未評価であればダイアログを表示、評価済みであればダイアログが表示されないという振る舞いになるようです**（当然、`レビューを投稿` ボタンからの自主的なレビューはできます）。

ちなみにですが、Apple のポリシーとしては

- アプリに習熟する十分な時間を与えた後でレビューを要求する
- ユーザーが大事なタスクを処理してるときにレビューを要求しない
- しつこくダイアログを出さない

のようです。原則としては、「アクションの終了」のようなので、ゲームをクリアした後に特定の頻度で出す、なども良さそうです。もう少し情報を集めたいので、細かい調査は後ほど ...
