### ISSUE TITLE
`ErasableBottle` の演出を改善する

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1329]
## 完了条件
- [ ] `ErasableBottle` 登場時の演出を改善する
- [ ] `ErasableBottle` 退出時の演出を改善する

## 検討事項
★ はやった方が良さそう。それ以外は、今回やらなくても良さそう

### 通常時
- ★ 岩の色
- 岩の形

### 登場時
- 登場アニメーション
- 登場 SE

### 退出時
- ★ 退出アニメーション
- 退出 SE

**Comment by takasusuke** [comment]
いわくだきアニメーション
https://www.youtube.com/watch?v=romtGyLCQC4

**Comment by xiii111** [comment]
https://user-images.githubusercontent.com/26104258/161406505-96e1c7e3-61bd-44d0-8efa-6546cffcaf1b.mov
