### ISSUE TITLE
タップエフェクトのブラッシュアップ

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1331]
## 経緯

質素な見た目だから。

## 詳細

他ゲームのタップエフェクトを若干調査する
画像自体を変える or Particleを発生させる実装に変更する

## 完了条件

- [ ] 素材を作る
- [ ] 適用する

## 備考
- 画面によってタップエフェクトを分ける？（StageSelectSceneでタップしたら花びらが出てくるみたいな）
- 水の波紋みたいな透明な感じにするか、花びらParticleにするか...

**Comment by takasusuke** [comment]
https://user-images.githubusercontent.com/26213141/163694259-68fea426-b893-415d-9135-a64b54d4ec90.mov

**Comment by takasusuke** [comment]
@LITO-apps/engineer 

参考にできるタップエフェクトがあればください。

**Comment by takasusuke** [comment]
タップ位置にParticleを出すことに成功

https://user-images.githubusercontent.com/26213141/165526161-501c6fbf-6716-4839-921c-8723eafeb148.mov

**Comment by takasusuke** [comment]
主張しなさすぎ？
特定の色にすると、場合によっては見えづらいかもしれない。
点滅も若干はやい気もする

1つのParticleではなく、いくつかの群にしてみるか。

https://user-images.githubusercontent.com/26213141/165529184-f2e482a7-0d1c-4ae3-a65d-bf44bf78a004.mov
