### ISSUE TITLE
【Autumn】枝のデザイン草案

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1332]
## 完了条件
- [ ] いくつかのパターンを出して、レビューをもらう

**Comment by xiii111** [comment]
@takasusuke @takesi0627 3 案出してみました！ご意見をいただけたらと思います！個人的には `普通` が良いと思っていますが、比較するためにも 3 つ用意しました

|薄め `Color(1f, 0.7f, 0.6f)` |普通 `Color(1f, 0.6f, 0.5f)` |濃いめ `Color(1f, 0.5f, 0.4f)` |
|---|---|---|
|<img width="300" alt="スクリーンショット 2022-06-01 21 51 04" src="https://user-images.githubusercontent.com/26104258/171408876-9f07d648-bffd-4acb-bf11-ccaf5a4c9bee.png">|<img width="300" alt="スクリーンショット 2022-06-01 21 50 09" src="https://user-images.githubusercontent.com/26104258/171408843-e71fd3bd-5e15-449d-94d0-40b44df22f92.png">|<img width="300" alt="スクリーンショット 2022-06-01 21 51 54" src="https://user-images.githubusercontent.com/26104258/171408891-f067d024-711f-4e95-9d80-110d20a7d38b.png">|

**Comment by takasusuke** [comment]
`普通`か`濃いめ`が好き。
個人的には`濃いめ`の方が好き。あまり好き度に大差はない。

背景の似た色をスポイトで抽出してその色のカラーコードを設定すると、より背景に馴染む気はする。

あと、比較として、背景の木じゃない黄色い部分（進捗バーのオレンジに近い）の色も見てみたい

**Comment by xiii111** [comment]
@takasusuke こんな感じの素材でどうでしょうか

|進捗バーの色|下領域の背景色|上領域の背景色|
|---|---|---|
|<img width="300" alt="スクリーンショット 2022-06-02 13 21 06" src="https://user-images.githubusercontent.com/26104258/171552402-1630fe51-b3f3-45c8-b23c-73d325c38c76.png">|<img width="300" alt="スクリーンショット 2022-06-02 13 25 20" src="https://user-images.githubusercontent.com/26104258/171553005-e8b102d5-88be-45e1-99dd-1b37b6fc4cb6.png">|<img width="300" alt="スクリーンショット 2022-06-02 13 27 14" src="https://user-images.githubusercontent.com/26104258/171553048-b2484a1e-6fc9-4aa4-8675-1ecaa18ca120.png">|

**Comment by xiii111** [comment]
https://github.com/LITO-apps/Treevel-client/issues/1332#issuecomment-1143576243 の `濃いめ` で実装する

**Comment by xiii111** [comment]
色が確定したので、クローズします
