### ISSUE TITLE
Bottleの移動速度の調整

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1333]
## 終了条件
- [ ] フリックと Bottle の移動にラグを感じる UX なので、それを改善する

### 1. ボトルの移動速度を上げてみる
`TestFlight 0.1 (15)` で

https://github.com/LITO-apps/Treevel-client/blob/72c0440a4dd4e170f513e0196e8eab11f26d906d/Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs#L58-L61

の `_SPEED` を `150f` にしたものをアップロードした。これで改善するのであれば、スピードの問題な気がする

#### 50f
https://user-images.githubusercontent.com/26104258/152982868-357cff58-6bda-4ddb-acab-cba11ad5fec5.MP4

#### 150f
https://user-images.githubusercontent.com/26104258/152982817-957c8fad-e121-4ae3-a589-328955c41449.MP4

### 2. FlickGesture の調査

`FlickGesture` の以下のようなプロパティ（`FlickTime`、`MinDistance`、`MovementThreshold`）が原因かもと思い、色々といじってみた

```csharp
/// <summary>
/// Gets or sets time interval in seconds in which pointers must move by <see cref="MinDistance"/> for gesture to succeed.
/// </summary>
/// <value> Interval in seconds in which pointers must move by <see cref="MinDistance"/> for gesture to succeed. </value>
public float FlickTime
{
    get {
        return flickTime;
    }
    set {
        flickTime = value;
    }
}

/// <summary>
/// Gets or sets minimum distance in cm to move in <see cref="FlickTime"/> before ending gesture for it to be recognized.
/// </summary>
/// <value> Minimum distance in cm to move in <see cref="FlickTime"/> before ending gesture for it to be recognized. </value>
public float MinDistance
{
    get {
        return minDistance;
    }
    set {
        minDistance = value;
    }
}

/// <summary>
/// Gets or sets minimum distance in cm pointers must move to start recognizing this gesture.
/// </summary>
/// <value> Minimum distance in cm pointers must move to start recognizing this gesture. </value>
/// <remarks> Prevents misinterpreting taps. </remarks>
public float MovementThreshold
{
    get {
        return movementThreshold;
    }
    set {
        movementThreshold = value;
    }
}
```

しかしながら、これらのプロパティの内、`FlickTime` と `MinDistance` は `FlickGesture` の [`pointersReleased`](https://github.com/TouchScript/TouchScript/blob/74f58155ddcd42c0a37428f2dd6814e05ec70215/Source/Assets/TouchScript/Scripts/Gestures/FlickGesture.cs#L228) で利用されているだけで、あくまでも判定に関わるものであった。また、`MovementThreshold` においても、フリックに遅延を与えるものではないことが、`TouchScript` のソースコードからわかった

`pointersReleased` は手を離したタイミングで発火するようなので、`pointersReleased` が呼ばれるタイミングが、標準の API より遅くないか、`pointersReleased` が呼ばれてから実際にフリック判定になるまでが遅くないか、を検証した。検証では、以下の位置にログを仕込んで、その際の `分:秒:ミリ秒` を表示した

- `TouchPhase.Ended` → https://docs.unity3d.com/ja/2019.4/ScriptReference/TouchPhase.Ended.html
- `pointersReleased` → `FlickGesture` の `pointersReleased` の先頭
- `Move` → 以下の `Subscribe` 内

https://github.com/LITO-apps/Treevel-client/blob/65b2167128dd55af44795aa6eefcd4b6957ce37d/Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs#L80-L88

実際にフリックをした場合のログが以下である

![スクリーンショット 2022-02-08 22 17 51](https://user-images.githubusercontent.com/26104258/152996780-c22eb91d-2db5-46aa-9328-b46315d0c558.png)

`pointersReleased` が呼ばれるタイミングは、標準の API より遅いわけでなく、`pointersReleased` が呼ばれてから実際にフリック判定になるまでも遅くなかった。困った

## 今後の調査方針

- 調査 2 の深掘り
- レームレートが影響を与えるか
  - `TouchScript` の `FlickGesture` は座標の取得を `Update()` で行なっているらしく、フレームレートが落ちると処理速度が落ちるらしい
- TouchScript を利用しなければ改善するか

## 備考
- 速度というか、遅延しているように見える
- いろいろと調査して、実機で問題ない状態にする

**Comment by xiii111** [comment]
📝 FlickGesture の以下のようなプロパティが原因かもと思い、色々といじっている

```csharp
/// <summary>
/// Gets or sets time interval in seconds in which pointers must move by <see cref="MinDistance"/> for gesture to succeed.
/// </summary>
/// <value> Interval in seconds in which pointers must move by <see cref="MinDistance"/> for gesture to succeed. </value>
public float FlickTime
{
    get {
        return flickTime;
    }
    set {
        flickTime = value;
    }
}

/// <summary>
/// Gets or sets minimum distance in cm to move in <see cref="FlickTime"/> before ending gesture for it to be recognized.
/// </summary>
/// <value> Minimum distance in cm to move in <see cref="FlickTime"/> before ending gesture for it to be recognized. </value>
public float MinDistance
{
    get {
        return minDistance;
    }
    set {
        minDistance = value;
    }
}

/// <summary>
/// Gets or sets minimum distance in cm pointers must move to start recognizing this gesture.
/// </summary>
/// <value> Minimum distance in cm pointers must move to start recognizing this gesture. </value>
/// <remarks> Prevents misinterpreting taps. </remarks>
public float MovementThreshold
{
    get {
        return movementThreshold;
    }
    set {
        movementThreshold = value;
    }
}
```

**Comment by xiii111** [comment]
📝 `TestFlight 0.1 (15)` で

https://github.com/LITO-apps/Treevel-client/blob/72c0440a4dd4e170f513e0196e8eab11f26d906d/Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs#L58-L61

の `_SPEED` を `150f` にしたものをアップロードしました。これで改善するのであれば、スピードの問題な気がします

**Comment by xiii111** [comment]
📝 `TouchScript` の `FlickGesture` は座標の取得を `Update()` で行なっているらしく、フレームレートが落ちると処理速度が落ちるよう。こちらも併せて調査する

**Comment by xiii111** [comment]
- `MovementThreshold` を深く読み込む
- ドラッグした時点で判定するようにすれば、改善するかを調査する

**Comment by xiii111** [comment]
📝 `MovementThreshold` は関係ありませんでした

**Comment by xiii111** [comment]
📝 

> ドラッグした時点で判定するようにすれば、改善するかを調査する

ですが、`pointersPressed`（指で押された）、`pointersUpdated`（指が移動した）、`pointersReleased`（指が離れた）を調査してみました。以下は、典型的なフリックをしてみた場合のログです。1 フレームが 60 fps 出ている前提で 16 ms です。そのため、数フレームに過ぎませんが、操作を早くできる可能性はあります。しかしながら、このイシューでやるには大変なので、別イシューとしたいです。また、効果が絶大ではないので、コスパで言うと、かなり悪いかもしれません

<img width="265" alt="スクリーンショット 2022-02-14 21 08 35" src="https://user-images.githubusercontent.com/26104258/153877652-165b4246-7816-4f04-8f8c-85e9bee9c623.png">
<img width="251" alt="スクリーンショット 2022-02-14 21 08 42" src="https://user-images.githubusercontent.com/26104258/153877658-798cc553-b070-43fd-8fcf-2de57fe20f1c.png">
<img width="244" alt="スクリーンショット 2022-02-14 21 08 51" src="https://user-images.githubusercontent.com/26104258/153877660-5718af37-0521-49d3-857e-032b8b66e713.png">
<img width="253" alt="スクリーンショット 2022-02-14 21 09 00" src="https://user-images.githubusercontent.com/26104258/153877665-e0d4e547-1dca-40ae-826c-b866527b7f4e.png">

**Comment by xiii111** [comment]
@takesi0627 @takasusuke 現時点で出来そうな調査はやってみました。これからのアクションとしては、
1. とりあえず、ボトルの速度を一定数早くしてみる
2. ドラッグした時点で判定するようにして、動作が改善するかを実装してみる

ですかね。とりあえず 1 をやってみて、2 は余裕があったら ... になりそうですが、皆さんの意見を聞きたいです

**Comment by takasusuke** [comment]
方針同意。

感知の部分なので5フレーム(0.10秒)感度が上がれば体感としては全然違うのではと推測してる。
なので、ドラッグ実装の重要性としては数フレーム「しか」というよりはその数フレームが実はとても大事かも、くらいの感覚。

(NumberBulletの実装軽く見たんだけど、フリックじゃなくてスワイプで動かしてた模様。(UISwipeGestureRecognizer)。
閾値の調整とかした覚えもないので、少しでもスワイプした瞬間に移動させてたぽい。ぬるぬる動かすなら、結局その実装になりそう。）

**Comment by takesi0627** [comment]
> (NumberBulletの実装軽く見たんだけど、フリックじゃなくてスワイプで動かしてた模様。(UISwipeGestureRecognizer)。
閾値の調整とかした覚えもないので、少しでもスワイプした瞬間に移動させてたぽい。あの感じのぬるぬるを求めるなら、その実装になりそう。）

これを見て、もしかしたらうちらが求めていたのは `TransformGesture` なんじゃないかと思いました。
ので、ちょっと`FlickGesture`周りを`TransformGesture`に置き換えて検証してみたら結構いい感じだった
```
_transformGesture = gameObject.AddComponent<TransformGesture>();
_transformGesture.OnTransform.AsObservable()
    .Where(_ => isMovable)
    .Subscribe(g => {
        var deltaVector2 = new Vector2(_transformGesture.LocalDeltaPosition.x, _transformGesture.LocalDeltaPosition.y);
        var directionInt = Vector2Int.RoundToInt(deltaVector2.NormalizeDirection());
        if (_isReverse) directionInt *= -1;

        // ボトルのフリック情報を伝える
        BoardManager.Instance.FlickBottle(this, directionInt);
        // ボトル移動させるSEを再生
        SoundManager.Instance.PlaySE(ESEKey.Bottle_Move);
    }).AddTo(compositeDisposableOnGameEnd, this);

_transformGesture.UseUnityEvents = true;
```

動画ファイルがデカすぎるからSlackに貼っておきます
https://lito-apps.slack.com/archives/C01E5GTPRV3/p1644854628267969

**Comment by xiii111** [comment]
@takasusuke @takesi0627 標準的なフリックをした際の、`FlickGesture` と `TransformGesture` の速度差を推定してみました

|FlickGesture（差の平均：259 ms）|TransformGesture（差の平均：115 ms）|
|---|---|
|![スクリーンショット 2022-02-17 8 29 41](https://user-images.githubusercontent.com/26104258/154375135-2eaf91c9-a56c-41ff-a77a-84087e9ce35f.png)|![スクリーンショット 2022-02-17 8 31 23](https://user-images.githubusercontent.com/26104258/154375137-962c83e1-3529-4ee2-9157-33dce1ed90ac.png)|

両者の差の平均（標本数：7）は 144 ms = 8.64 フレーム（＊60 fps の場合）なので、かなりの差が出ているように思います。体感でも明らかな差を感じます。`TransformGesture` での実装を進めてみようと思います！
