### ISSUE TITLE
【Winter】枝のデザイン草案

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1335]
## 完了条件
- [ ] いくつかのパターンを出して、レビューをもらう

**Comment by xiii111** [comment]
## 冬の現状
<img width="350" alt="スクリーンショット 2022-06-01 20 13 41" src="https://user-images.githubusercontent.com/26104258/171392129-a3806944-d6e5-451e-92bc-54267e26a4b2.png">


## 春と夏の現状
|春|夏|
|---|---|
|<img width="300" alt="スクリーンショット 2022-06-01 20 06 51" src="https://user-images.githubusercontent.com/26104258/171391745-046f0b61-36d4-4dcf-b088-33c5609fd3b9.png">|<img width="300" alt="スクリーンショット 2022-06-01 20 09 03" src="https://user-images.githubusercontent.com/26104258/171391763-7d0c21fb-8bf6-4299-9bf2-ac287f5c8dc2.png">|

**Comment by xiii111** [comment]
@takasusuke @takesi0627 3 案出してみました！ご意見をいただけたらと思います！個人的には `雪` か `飾り` が良いと思っていますが、比較するためにも 3 つ用意しました

|雪 `Color(1f, 1f, 1f)` |飾り `Color(0.78f, 0.64f, 0.1f)` |木 `Color(0f, 0.7f, 0.25f)` |
|---|---|---|
|<img width="300" alt="スクリーンショット 2022-06-01 22 05 24" src="https://user-images.githubusercontent.com/26104258/171411283-a2ba58ab-769a-4c4f-b405-fcdfccea5036.png">|<img width="300" alt="スクリーンショット 2022-06-01 22 10 09" src="https://user-images.githubusercontent.com/26104258/171412210-65adc54b-4627-40d8-962a-055e28ff49f0.png">|<img width="300" alt="スクリーンショット 2022-06-01 22 13 18" src="https://user-images.githubusercontent.com/26104258/171412775-b3920062-348a-49ed-8df0-df3df1c02b74.png">|

## 参考画像
そういえば、当初は以下のような想定でしたね。なので、金色をイメージしていたのかもしれません。とはいえ、背景自体に金色のティンセルガーランドはあるし ... 悩みどころですね

<img width="250" alt="スクリーンショット 2022-06-01 21 58 31" src="https://user-images.githubusercontent.com/26104258/171410971-f9964a26-dacf-4f0d-9f82-9d345483beb2.png">

<img width="250" alt="スクリーンショット 2022-06-01 21 58 43" src="https://user-images.githubusercontent.com/26104258/171410996-ca8adf48-1e94-415e-80cd-9f6377c1644e.png">

**Comment by xiii111** [comment]
@takasusuke 参考までに `飾り` に近い色を複数用意しました。実際に使われている色をスポイトしています。元々の `飾り` に比べて、淡い色になっていると思います

|鈴に近い色|ティンセル色|
|---|---|
|<img width="300" alt="スクリーンショット 2022-06-02 13 33 30" src="https://user-images.githubusercontent.com/26104258/171553556-21f42979-f509-4922-815b-9f78f01c7679.png">|<img width="300" alt="スクリーンショット 2022-06-02 13 36 12" src="https://user-images.githubusercontent.com/26104258/171553820-6d693bea-8472-49b6-bdd0-3263a055bdb3.png">|

**Comment by xiii111** [comment]
https://github.com/LITO-apps/Treevel-client/issues/1335#issuecomment-1144428419 の `鈴に近い色` にする

**Comment by xiii111** [comment]
色が確定したので、クローズします
