### ISSUE TITLE
各季節の未実装ツリーを同季節の実装ツリーのシルエットにする

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1336]
### 終了条件
- [ ] Summer, Winter, Autumnの未実装ツリーを同季節の実装ツリーのシルエットにする(`LevelTreeController.cs`にて実装)

**Comment by takesi0627** [comment]
#1463 にて現在の実装ではこちらの対応不要ということが判明したので閉じます
