### ISSUE TITLE
全てのゲーム内テキストの日本語文言を決定、適用する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1345]
### 終了条件
- [ ] 全てのゲーム内テキストの日本語文言を決定し、適用する

### 考慮事項
- 「てにをは」を意識する
- 同じ表現で少しでも短い表現ができないか考える
- 文体を統一する
- ゲーム内用語を統一して使う
- 「、」「。」から始まる行がないように意識する

**Comment by xiii111** [comment]
1. Localization テーブルが全てのテキストに反映されているかを調べる
2. Localization テーブルの内容をスプレッドシートに転記する
3. どのような文言にするかを決める

**Comment by xiii111** [comment]
## 調査結果（WIP）
<img width="323" alt="スクリーンショット 2022-05-23 22 13 18" src="https://user-images.githubusercontent.com/26104258/169827344-d73164ad-ea7b-43c3-9a28-8b29c1d0e13f.png">

- `不測のエラーが発生しました`
- `ゲームを再起動してください`
- `エラーコード`
- `タイトルに戻る`

<img width="247" alt="スクリーンショット 2022-05-23 22 11 19" src="https://user-images.githubusercontent.com/26104258/169826981-91ae1853-7aa4-45a4-bbbc-feb7ac2db6b3.png">

- `スタート！`

<img width="287" alt="スクリーンショット 2022-05-23 21 02 12" src="https://user-images.githubusercontent.com/26104258/169815028-373b6548-abf2-45ea-8384-86927256d36f.png">

- `ホーム`
- `記録`
- `ヒストリー`

<img width="375" alt="スクリーンショット 2022-05-23 21 03 04" src="https://user-images.githubusercontent.com/26104258/169815166-bee19213-1bd9-43d8-ad70-cbd76cad4369.png">

- `プレイ回数`
- `フリック回数`
- `旅の記録`
- `日目`
- `旅を始めた日`

<img width="227" alt="スクリーンショット 2022-05-23 21 05 06" src="https://user-images.githubusercontent.com/26104258/169815586-c0608109-eef0-4be9-ab80-93d1cec9ad7b.png">

- `レビューを投稿`
- `公式ツイッター`

<img width="306" alt="スクリーンショット 2022-05-23 21 26 07" src="https://user-images.githubusercontent.com/26104258/169824293-04dd227d-64e8-4f41-b708-800670c5651f.png">

- `Option`

<img width="329" alt="スクリーンショット 2022-05-23 21 58 06" src="https://user-images.githubusercontent.com/26104258/169824575-e05f1fc8-1e0e-45fe-b5eb-d7eecb5ea68a.png">

- `挑戦！`
- `とじる`

<img width="231" alt="スクリーンショット 2022-05-23 21 59 26" src="https://user-images.githubusercontent.com/26104258/169824832-30f15e7a-4598-48c1-b7a6-eac4b4019abb.png">

- `結果をツイートする！`

<img width="275" alt="スクリーンショット 2022-05-23 22 00 23" src="https://user-images.githubusercontent.com/26104258/169825016-ff8b8718-5595-4837-a2a0-40cff41dc724.png">

- `やりなおす`
- `BACK`

<img width="319" alt="スクリーンショット 2022-05-23 22 01 17" src="https://user-images.githubusercontent.com/26104258/169825250-fc207790-2f07-4fbb-a1d9-569b202560f5.png">

- `再開する`
- `やりなおす`
- `あきらめる`

- `トルネード`
- `縦横無尽に移動するトルネード。巻き込まれないように注意して避けよう！`

- `メテオ`
- `上空から落ちてくるメテオ。当たらないように注意して避けよう！`

- `しつこいメテオ`
- `ギリギリまでボトルを狙って落ちてくるメテオ。一度逃げても、油断できない！`

- `カミナリ`
- `雲から落ちるカミナリ。雲が黒くなったら、カミナリが落ちるサインだ！`

- `トップウ`
- `荒れ狂うトップウは、ボトルを勢いよく動かす。舞っている葉を見たら警戒だ！`

- `もろいガンセキ`
- `タップすると壊れるガンセキ。木から突き出てくるので、小まめに壊そう！`

- `ワープスポット`
- `ボトルが入ると、別のスポットに飛ばされる。不思議な力があるようだ。`

- `結晶を治癒しよう`

- `すべてクリアしよう`

- `コンプリート！`

- `結晶のあるステージを全て\nクリアして木の病気を治そう`
- `結晶のクリア数は\nここから確認しよう`

＊ `BGM` / `SE` は議論の余地がないとして、ふくめていません

- `聖域`
- `全ての攻撃から守ってくれる聖域。ボトルを守りたいときは、ここに逃げよう！`

- `蜘蛛の巣`
- `ボトルの動きを止める蜘蛛の巣。絡まると一時的にボトルを動かせなくなるぞ！`

- `氷面`
- `木の表面が凍り、滑りやすくなっている。ボトルを動かす時は要注意！`

- `鋼ボトル`
- `鋼で作られた硬いボトル。割れる心配はないが、残念ながら薬は入っていない。`

- `ガンセキ`
- `動かすことができないガンセキ。場所を取るだけのお邪魔者だ！`

- `爆薬ボトル`
- `爆薬が入っているボトル。刺激を与えると爆発するので、取り扱い注意だ！`

- `暗闇`
- `ボトルが暗闇に覆われている。暗闇をホールドして、中身を確認してみよう！`

- `混乱`
- `ボトルが混乱に陥っている。思い通りに動かせないので、注意しよう！`

- `タマシイ`
- `頻繁に暴れ出し、ボトルを移動させるタマシイ。ホールドで動きを抑えこめる！`

- `丈夫なボトル`
- `丈夫で割れづらいボトル。数字が０になると、ボトルは割れてしまうので注意！`

- `結晶`
- `木を蝕む結晶。木を治すために、結晶の活動を抑えこもう！`

- `薬ボトル`
- `木の結晶を癒す薬。ボトルからこぼさないように、同じ色の結晶まで届けよう！`

**Comment by takesi0627** [comment]
LGTM

**Comment by takasusuke** [comment]
こりゃあすげーや

**Comment by xiii111** [comment]
ありがとうございます！作業中に戻して、地獄のスプレッドシートを作成します

**Comment by xiii111** [comment]
📝 https://docs.google.com/spreadsheets/d/1x68F67vbgdzW_50WbiLwWfFD53pWxVqExKBkUuem9hg/edit#gid=0 に転記完了

**Comment by xiii111** [comment]
@takasusuke @takesi0627 https://docs.google.com/spreadsheets/d/1x68F67vbgdzW_50WbiLwWfFD53pWxVqExKBkUuem9hg/edit#gid=0 に現行の文言と修正候補と備考を書きました。皆さんの意見を書くセルも用意したので、意見をください。木曜日までに書いていただけると助かります。木曜日の打ち合わせで議論しましょう

**Comment by takasusuke** [comment]
@xiii111 
書きました！！！！！ちゃんと書きました！！！！！
病気の症状として「結晶化」している、という認識だったんだけど、病気の原因が「結晶」という認識？と受け取れる表現も提案の中にあったので、ここは最初に議論しておくと良いかもしれない。

**Comment by xiii111** [comment]
@takasusuke 感謝！！！定例会でみっちり議論しましょう

**Comment by xiii111** [comment]
@takesi0627 リマインドですが、今日の打ち合わせまでにレビューして欲しいです

**Comment by xiii111** [comment]
📝 タスク通話では全て終わらなかったので、次の打ち合わせに持ち越し
