### ISSUE TITLE
レベル選択画面の木の解放演出のブラッシュアップ

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1351]
ref #992 
#817

## 終了条件
- [ ] 道の解放中にParticleを出す
- [ ] 道の解放後に木の周りに出現させるParticleのブラッシュアップ
- [x] アニメーション中の入力ブロック
- [x] フッターを非表示にする
- [ ] (クリアした木にもクリア演出してから、道が解放されるべきでは？)

## 備考
- 拡大率が高すぎる？どこからどこへの道が解放されたか知りたいかも
- 現在の木のクリア演出は対象外
- 解放演出後、拡大率を戻す必要なし？

**Comment by takasusuke** [comment]
Trail追加
これに、TrailなしのキラキラしたParticle、木の真ん中に後光みたいなぼんやりした大きな光の球体のせる？

https://user-images.githubusercontent.com/26213141/168614164-29ca794e-2676-4c0c-b085-4998d42b7163.mov

**Comment by takasusuke** [comment]
- [ ] クリア時と解放時の演出変える
- [ ] クリア時と解放時の演出向上
- [ ] 道のParticle演出
- [ ] 複数解放時の対応
- [ ] カメラのスケールを元に戻す

https://user-images.githubusercontent.com/26213141/169672083-fa605657-8a33-4814-81e7-be246d5a6cf2.mov

**Comment by takasusuke** [comment]
Camera位置を誘導するやつ（拡大率がMAXの時だけなぜか移動量が0に判定されてしまい、一瞬で移動してしまう。。。）


https://user-images.githubusercontent.com/26213141/169686752-9ce3ea3e-2a2d-455f-a91f-f039115ce811.mov

**Comment by takasusuke** [comment]
無限に時間溶ける...
6割くらいの完成度でやめてまた背景がきてからやるなりするか？

https://user-images.githubusercontent.com/26213141/170040209-3ae4e363-c1d4-41c1-984a-449bcadc379b.mov
