### ISSUE TITLE
アプリロゴの草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1361]
### 終了条件
- [x] アプリロゴの草案を作成する

# 資料
https://docs.google.com/presentation/d/1s3cxc7vBdvdWKXJ4mUJ9RJfildLDVXhomCLIFsEj5m4/edit#slide=id.p

### 考慮事項
- 調査から始める
- Treevel ? TREEVEL ? どちらでも可？
- StartUpSceneで見た時に、アプリの印象として最も紐づけたいワードは？
  - 自然 : 0~1
  - 季節 : 2
  - 旅 : 1
  - 木 : 0~1
  - 治療
  - パズル : 0~1
  - アクション
- 配色は複数検討

**Comment by xiii111** [comment]
<img src="https://user-images.githubusercontent.com/26104258/161355824-3edbae13-6e25-4399-ba5b-a6e9684241fd.jpeg" width="300">

**Comment by takasusuke** [comment]
ロゴの作り方
https://antenna-gds.com/blog/titlelogodesign/

ゲームロゴのギャラリー
http://glaim.tkmweb.info/

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
アプリロゴ案を作成しました。
MTGで議論可能なら議論、難しそうならまた別途。

**Comment by xiii111** [comment]
@takasusuke 一通りコメントしました。現状の結論としては
- 案 9 のように、Treevel の e 以外を灰色にする
- 案 9 のように、木をやや薄暗くする
- 案 11、案 12 のように、木と Treevel に一体感を持たせる
- 案 11 のように、木に結晶が突き刺さっているようにする
- 案 12 のように、木のデザインにロゴ感を持たせる

を組み合わせた案かなー ... とても難しいなと思いました

**Comment by takasusuke** [comment]
#1362 でリソース作成を行います。
ありがとうございました。

<img width="271" alt="スクリーンショット 2022-04-18 2 15 39" src="https://user-images.githubusercontent.com/26213141/163725391-6fe10629-b7d8-4bbc-9145-42146806313b.png">
