### ISSUE TITLE
クリアしなければいけないステージをユーザにわかるようにするデザインの草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1364]
## 終了条件
- StageSelectSceneのステージアイコンで、クリアに必要なステージがわかるようにする

StageSelectSceneのステージアイコンは以下の状態。
非開放(通常)
非開放(必須ステージ)
未クリア(通常)
未クリア(必須ステージ)
クリア

https://docs.google.com/presentation/d/153JCIP7XTAldvFXZvoEV96CScm2xAX3Iu2z6pfLuf4E/edit#slide=id.p

## 備考

featureが別途`4`見積もりのissueがある。

#1288
↓右上の数値表現は必須ではないので一旦なし。

<img width="261" alt="スクリーンショット 2022-01-16 10 50 50" src="https://user-images.githubusercontent.com/26213141/149644207-88fc2a38-f9e7-43af-9352-c42e9bc1b2f8.png">

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
MTGで。
案とかコメントあれば。
https://docs.google.com/presentation/d/153JCIP7XTAldvFXZvoEV96CScm2xAX3Iu2z6pfLuf4E/edit#slide=id.p

**Comment by xiii111** [comment]
@takasusuke 各デザイン案へのコメントと、全体的に思ったことを書いたスライドを追加しました！

**Comment by takasusuke** [comment]
傷の案は①。

傷の総数と、ユーザがクリアした傷の個数がわかるUIを考える。

木と傷の色は、各木に対して恣意的に決める

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
https://docs.google.com/presentation/d/153JCIP7XTAldvFXZvoEV96CScm2xAX3Iu2z6pfLuf4E/edit#slide=id.g111082ff5d0_0_225
18p ~ 23p に、クリアした傷の個数がわかるUIの案を作成しました。
よろしくお願いします。

**Comment by takesi0627** [comment]
@takasusuke 
コメントしました（珍しく結構書いた）

**Comment by takasusuke** [comment]
決まり案
今何をすると良いかユーザに伝える。
傷を全てクリアしたら一旦、LevelSelectに遷移する
傷クリア後に戻ってきたら、傷の個数目標ではなく、前ステージクリア目標に変更して表示する
傷ステージをクリアした場合、そのステージには元々傷があったことがわかるような特別なエフェクトを付与する

<img width="1041" alt="スクリーンショット 2022-02-01 20 48 48" src="https://user-images.githubusercontent.com/26213141/151963294-f84ff860-7525-4cd4-8d81-a8f037e3090a.png">

**Comment by takasusuke** [comment]
#1400 で実装します。
issue分割は、こちらのissueで適宜。
