### ISSUE TITLE
GamePlayScene に入ると `RenderingCommandBuffer` が発生することがある

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1370]
### 概要
- GamePlayScene に入ると `RenderingCommandBuffer` が発生することがある

```
RenderingCommandBuffer: invalid pass index 4 in DrawMesh
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

### 再現方法
- GamePlayScene に入ると `RenderingCommandBuffer` が発生することがある

### 期待される挙動
- GamePlayScene に遷移しても、エラーが発生しないこと

### スクリーンショットなど

<img width="479" alt="スクリーンショット 2021-12-24 9 29 45" src="https://user-images.githubusercontent.com/26104258/147302064-b98c40cd-7788-4768-bd2f-231dc915975f.png">

### 備考
- Unity のアップグレード後に起きた

**Comment by takasusuke** [comment]
これが原因かわからないけど、これだとしたらなんかのタイミングで勝手に直ったのかも。
当分、出ないなら一旦閉じて大丈夫だと思います。

https://masakami.com/archives/2019/07/23/348/

**Comment by xiii111** [comment]
@takasusuke なるほど ... そうですね。二人の環境で全く発生してませんし、また発生したら Reopen しましょう
