### ISSUE TITLE
ステージ選択画面における行動目標をユーザに表示する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1400]
#1364 に基づいて実装する

<img width="1041" alt="スクリーンショット 2022-02-01 20 48 48" src="https://user-images.githubusercontent.com/26213141/151963969-6f44cb75-f3ca-42ba-bc85-4065c0bc438c.png">

# 完了条件
- [ ] #1364 仕様定義
- [ ] タスク洗い出しイシュー作成

* 傷ステージ全てクリアしたらレベル選択画面に一回戻る実装
* ステージデータに傷ステージかどうかのプロパティを追加
* プログレスバーの実装
* ステージボタンに傷かどうかのプロパティを反映
* オンボーディング
* 傷ステージのデザイン適用
* 傷ステージの解放演出

**Comment by takesi0627** [comment]
@xiii111 @takasusuke 

全イシュー作成完了しました。
各イシューの依存関係、実装順は主に図で示すようになっている。
<image src="https://user-images.githubusercontent.com/17778395/154824921-9da0c838-a0ce-4387-861e-acf6c3fbfec2.png" width="400">

### レビュー観点
* イシューは適切に分割しているか
* イシューの内容は適切か
* イシューの依存関係は適切か（各イシューの概要で`depend on`で書かれているもの）
* イシューの漏れはあるか


以上レビューよろしくお願いします。

**Comment by xiii111** [comment]
📝  定例会までにみます

**Comment by xiii111** [comment]
@takesi0627 LGTM!!! めっちゃちゃんと分割されてて、素晴らしいと思いました！ていうか、分割ちゃんとやってよかったですね、めっちゃ見通しが良くなりましたし、これをまとめてやってたら、病んでたと思います。笑
