### ISSUE TITLE
`GvhProjectSettings.xml` で自動的に差分が発生することがある

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1404]
## Why

#1397 のレビュー時に指摘されたように、 5ab3a8beede06c19bad78a16145f83120786d8aa のような差分が自動的に発生することがある。差分はウザいが、勝手に適用して良い差分かが分からないので、調査をし、修正して良いかを決める

## 完了条件
- [ ] 該当差分を適用してどういう影響があるかを調べ、適用するか、差分が出ないように修正する。

**Comment by takesi0627** [comment]
📝AdMobs のSDKを更新してみるといいかもしれません

**Comment by xiii111** [comment]
確認します

**Comment by xiii111** [comment]
@takesi0627 cc @takasusuke `GvhProjectSettings.xml` の差分が適用される前後で、同様にビルドができることが確認できました。ビルドする際には、

```
$ pod install --repo-update
```

を実行して、`Unity-iPhone.xcworkspace` を手動生成する必要はありました

> しかし、現状全員各自のPC環境にCocoapodsをインストールしているので、このツール(ExternalDependencyManager)自体は不要になる。

これに関してですが、各々の CocoaPods のバージョンなどに影響を受けるのは面倒なので、イシューは作って、`Unity` の `iOS` 向けビルドの際に、`Unity-iPhone.xcworkspace` の生成に失敗する問題は、別途イシューを作成してほしいです！

**Comment by takesi0627** [comment]
@xiii111 
そちらの環境でビルド最後に `pod install`に関連するエラーが出ましたか？
出たとしたらどんな内容でしょうか？
もし文字コード `en-US.UTF-8`を使ってくださいみたいのことを書いてたら、言う通りにすれば次からはおそらく手動生成する必要がなくなるかもしれません。

**Comment by takesi0627** [comment]
> これに関してですが、各々の CocoaPods のバージョンなどに影響を受けるのは面倒なので（手動生成も面倒）、`Unity` の `iOS` 向けビルドの際に、`Unity-iPhone.xcworkspace` の生成に失敗する問題は、別途イシューを作成してほしいです！

ごめんなさい。僕が間違っていました。
今自分のPCの`cocoapods`をアンインストールしてそのままビルドしてみたが以下のようなメッセージが出て、自動ではインストールしてくれない模様
```
Error running CocoaPods. Please ensure you have at least version 1.0.0.  You can install CocoaPods with the Ruby gem package manager:
 > sudo gem install -n /usr/local/bin cocoapods
 > pod setup
```

`Assets > External Dependency Manager > iOS Resolver Install Cocoapods`を実行しないとインストールされないので、結局どんな設定にせよ、自分で手動でインストールする必要がある。

**Comment by xiii111** [comment]
> > これに関してですが、各々の CocoaPods のバージョンなどに影響を受けるのは面倒なので（手動生成も面倒）、`Unity` の `iOS` 向けビルドの際に、`Unity-iPhone.xcworkspace` の生成に失敗する問題は、別途イシューを作成してほしいです！
> 
> ごめんなさい。僕が間違っていました。 今自分のPCの`cocoapods`をアンインストールしてそのままビルドしてみたが以下のようなメッセージが出て、自動ではインストールしてくれない模様
> 
> ```
> Error running CocoaPods. Please ensure you have at least version 1.0.0.  You can install CocoaPods with the Ruby gem package manager:
>  > sudo gem install -n /usr/local/bin cocoapods
>  > pod setup
> ```
> 
> `Assets > External Dependency Manager > iOS Resolver Install Cocoapods`を実行しないとインストールされないので、結局どんな設定にせよ、自分で手動でインストールする必要がある。

@takesi0627 こちらですが、以前は何もしなくても `Unity-iPhone.xcworkspace` が自動的に Unity によって作成されていました。これができなくなった理由は判明していますか？

**Comment by xiii111** [comment]
> @xiii111 そちらの環境でビルド最後に `pod install`に関連するエラーが出ましたか？ 出たとしたらどんな内容でしょうか？ もし以下のように文字コード `en-US.UTF-8`を使ってくださいみたいのことを書いてたら、言う通りにすれば次からはおそらく手動生成する必要がなくなるかもしれません。
> 
> ```
>     �[33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
>     Consider adding the following to ~/.profile:
> 
>     export LANG=en_US.UTF-8
> ```

こちら、聞かれていることが明確には分からないのですが、Unity で iOS 向けにビルドすると（`Cocoapods` はインストール済み）、以下のようなエラーが出ます。UTF-8 に関する内容は含まれていません

![スクリーンショット 2022-02-27 8 05 06](https://user-images.githubusercontent.com/26104258/155861801-31e1324d-6976-4690-aaf1-f5c3058f35d9.png)

**Comment by takesi0627** [comment]
> こちら、聞かれていることが明確には分からないのですが、Unity で iOS 向けにビルドすると（`Cocoapods` はインストール済み）、以下のようなエラーが出ます。UTF-8 に関する内容は含まれていません
> 


![image](https://user-images.githubusercontent.com/17778395/155863489-10e7f74e-efc7-49f4-9786-2dc55693eca3.png)
`pod install output:` から内容が違いますね・・・
やっぱり`pod`のバージョン問題ですかね。






> @takesi0627 こちらですが、以前は何もしなくても `Unity-iPhone.xcworkspace` が自動的に Unity によって作成されていました。これができなくなった理由は判明していますか？


![image](https://user-images.githubusercontent.com/17778395/155863638-92ac1b5b-9cf4-47fc-aae3-aa0c22691498.png)
`https://github.com/googlesamples/unity-jar-resolver/issues/441`
特定のバージョンでDLLが読み込めない問題が報告されているが、これはxcworkspaceとどう関連するのかははっきりいえない。
podのバージョン、Unityのバージョン色々可能性はあると思います
（ネット上も同じ症状の人が多いからUnityのバージョンの可能性大かも）

**Comment by xiii111** [comment]
@takesi0627 

ローカルの `Cocoapods` をアンインストールしてから、`Assets > External Dependency Manager > iOS Resolver Install Cocoapods` を試しましたが、Xcode 周りでエラーが出てインストールに失敗しました。gem 経由でインストールというだけなので、`Cocoapods` のインストールに関しては、`brew` で済ませることにしました。

また、`Unity-iPhone.xcworkspace` が生成されない問題も調査してみましたが、前言ってくれていたように `MacOS` のバージョン・`Unity` のバージョンなど、複数の原因が考えられそうですね。とりあえずはローカルの `Cocoapods` でなんとかなるので、`Unity` を最新のベータ版などに上げても、問題が発生し続けるかだけ確認して、このイシューは閉じて良いと思いました。

**Comment by xiii111** [comment]
@takesi0627 

> とりあえずはローカルの Cocoapods でなんとかなるので、Unity を最新のベータ版などに上げても、問題が発生し続けるかだけ確認して、このイシューは閉じて良いと思いました。

これは試した？

**Comment by takesi0627** [comment]
> @takesi0627
> 
> > Unity を最新のベータ版などに上げても、問題が発生し続けるかだけ確認して、このイシューは閉じて良いと思いました。
> 
> これは試した？

あ、これ僕に試してほしいってことか。
でも僕の環境では現状xcodeworkspace問題なく生成されていますから、おそらく問題は発生しないと思うけど、一応試してみる

**Comment by xiii111** [comment]
あ、そうだったっけ。なら良いや！すまない
