### ISSUE TITLE
記録画面がピンク色になる

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1405]
## 概要
- 記録画面がピンク色になる

## 再現手順
- 記録画面を開く

## 期待動作
- 記録画面がピンク色にならない

## キャプチャ
<img src="https://user-images.githubusercontent.com/26104258/152474261-7746c6cd-aff9-4f6d-96d8-63f54931182a.PNG" width="300">

## 発生環境
- 8396adb8b8f8e4f681bc287865cc203177e57b17

## 備考
- Shader の問題だと思う

**Comment by xiii111** [comment]
## 現状まとめ
### 発生状況
|||| @xiii111 | @takasusuke |
|---|---|---|---|---|
|`0.1 (12)`| 5e5cd5361ff53cd08bf36cf03e83beaa075252f2 | 古い記録画面 | 正常 | 正常 |
|`0.1 (13)`| cfb1b6fc6cb3079a87f0aa9ee0a43a8a1cf111ec | 新しい記録画面 | 正常 | 正常 |
|`0.1 (14)`| 8b8d0d452a170a2b39c7180fd6e7a8efbc1d25c1 | 新しい記録画面 | ピンク色 | 正常 |

### 備考
- `MenuSelectScene/Record/Canvas/Background` の `Image/Material` を `BackgroundMaterial` から `None (material)` にすると、実機でピンク色にならなくなる（当然、Shader の効果も消える）。よって、`Material` or `Shader` が原因。調べたところ、iOS と Mac OS での Graphic API が異なることが原因の可能性がある。他にも #1406 で解決するという記事もあったが、こちらは効果がない状態

**Comment by xiii111** [comment]
## 現状まとめ - 2/7 (月)

- Unity のバージョン変化があるため、コミットを二分探索していくのはしんどい
- 発生しているのは @xiii111 だけ

### 発生状況
| メンバー | TestFlight | ブランチ / コミット番号 | iOS | 端末 | 再現状況 |
|---|---|---|---|---|---|
| @xiii111 | `0.1 (17)` | - | `iOS 15.3` | `iPhone 12 Pro (実機)` | ピンク色 |
| @xiii111 | - | `develop` / 65b2167 | `iOS 15.0` | `iPhone 12 Pro (Simulator)` | 異常なし |

**Comment by xiii111** [comment]
@takesi0627 @takasusuke すみません、お手数ですが、もう一度 `0.1 (17)` で確認してもらえませんか？Simulator でも発生しなかったので、これで二人とも発生しなかったら、一旦 Close しようと思います。リリース間際にまだ起きていたら、再度イシューを立てます

**Comment by takesi0627** [comment]
15.3 でも問題ありませんでした

**Comment by xiii111** [comment]
@takesi0627 ありがとう！

@takasusuke も余裕があったらみてほしい

**Comment by takasusuke** [comment]
問題発生しません

**Comment by xiii111** [comment]
はい、閉じます😇
