### ISSUE TITLE
`GraphicsSettings.asset` の `Built-in shader` に追加すべき `Shader` を追加する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1409]
## 経緯

#1256 でも実施しているように、実機で `Shader` を利用するためには、`Built-in shader` に追加する必要があるよう。しかしながら、`GeneralRecordBackgroundShader.shader` は `Built-in shader` に追加していなくても正常に動いているように見える。`Built-in shader` に追加すべき `Shader` と、追加する必要がない `Shader` は何によって変わるのかは調べておくべきである。また、追加すべき `Shader` が追加されていない場合があれば、追加するべきである

## 完了条件

- [x] `Built-in shader` に追加すべき `Shader` は何かを調べる
- [x] 追加すべき `Shader` のうち、追加していない `Shader` を追加する
- [x] 追加すべきでない `Shader` のうち、追加してしまっている `Shader` を削除する

**Comment by takasusuke** [comment]
Shaderを参照する方法
1. Shaderを利用したオブジェクトをScene内に配置する
2. Shaderを利用したオブジェクトをResources下に置く(or Addressを付与する)
3. `Project Settings/Graphics/Always Included Shaders`に追加する

参考：https://docs.unity3d.com/jp/540/ScriptReference/Shader.Find.html

**Comment by takasusuke** [comment]
現在の`Always Included Shaders`のリスト
- `Legacy Shades/Diffuse`
- `Hidden/CubeBlur`
- `Hidden/CubeCopy`
-  `Hidden/CubeBlend`
- `Sprites/Default`
- `UI/Default`
- `Hidden/Compositing`
- `Hidden/VideoComposite`
- `Sprites/Outline` : SpriteGlowでScriptから参照
- `Hidden/Grayscale Post Effect` : GamePlaySceneで結果画面表示時に背景にグレースケールをかけるためのShader。Scriptプトから参照

**Comment by takasusuke** [comment]
特に不要な設定はありません。
特に追加しなければいけない設定はありません。

DefaultでAlways Included Shadersに入っているShaderは、各種オブジェクトにshader(material)が設定されていない時に利用されるshaderです。
消す理由は特に無いかと思います。

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
https://github.com/LITO-apps/Treevel-client/issues/1409#issuecomment-1065900762
のコメントの内容共有だけして閉じる予定です。

**Comment by takesi0627** [comment]
異論なし

**Comment by xiii111** [comment]
@takasusuke とても納得感のある調査ですね。閉じて良いと思います！

**Comment by takasusuke** [comment]
感謝〜
