### ISSUE TITLE
広告の表示位置・種類・タイミング検討

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1410]
## 経緯
現状広告の表示位置・種類・タイミングの全てが未確定なので、実装できるレベルまで仕様を練る

## 完了条件
- [x] AdMob 広告の種類や仕様についてまとめる → 1.5 h
- [x] 広告の表示位置・種類・タイミングを決める → 4 h
- [x] 適用するイシューを作成する → 0.5 h

**Comment by xiii111** [comment]
@takasusuke @takesi0627 Unity における AdMob の実装方法についても、前提知識をそこそこ入れました。このタスクと直接関係のない部分についても少し調査をしてしまいましたが、このタスクと関係ある部分でいうと、どの種類の広告を出すかですよね。以下の 6 種類があります。

<img width="1629" alt="スクリーンショット 2022-04-18 21 32 47" src="https://user-images.githubusercontent.com/26104258/163808891-af24fbb6-6d09-4acf-9163-1f1ede5bbe8e.png">

バナー以外は全面広告です。高い収益を望まないのであれば、UX をあまり低下させないバナーが良いと思います。一度簡単に決定はしたと思いますが、改めてどうでしょうか？もし、バナー広告以外の詳細を知りたい場合には言ってください。別途調査してまとめます

**Comment by xiii111** [comment]
バナーを利用する場合には、たけしくんも過去に書いてくれていた [アンカー アダプティブ バナー](https://developers.google.com/admob/unity/banner/anchored-adaptive?hl=ja) を利用するのが良さそうです。これは実装方法の話なので、本イシューとはあまり関係ない。

**Comment by takesi0627** [comment]
バナーで良いと思います

**Comment by takasusuke** [comment]
調査ありがとうございます。

バナー広告はUIとしては見た目の良さが損なわれるので、ある意味UXが低下すると思います。
インターステイシャルはバナーと相互互換的に捉えている(一時的に画面を覆うものの、表示しないタイミングではUIの見た目は損なわない)のでタイミングはいくつか考えてみたい、と思っています。
（現在、StageSelectSceneにバナーを出しているが、バナーがなければ、木の名前やちょっとした統計情報といった情報を表示できるかもしれない。バナー広告がある画面ではその可能性を消しているとも言える。また、背景の良さも消えてしまう。）


※ リワードは該当するものが思いつかない、ネイティブアドバンスは実装コストが高そう、アプリ起動で広告出るゲームは自分でもやりたくないので省きました

----------
例ですが、
- 木を解放後、初めてその木(StageSelectScene)に遷移したとき
- 同一のステージを連続5*N回失敗したとき

といった案があるとして、「UXを損ねてユーザが離れる恐れがあるのでターゲットを熱中してくれているユーザに絞る」という制約があると、
- 木を解放後、初めてその木(StageSelectScene)に遷移したとき(Autumn以降)
- 同一のステージを連続10回失敗したとき。以降、30回目...60回目...100回目の失敗した時。
- ゲーム内累計100*N回目以降で、かつ、同一のステージを連続3回以上失敗した時。

といった案が生まれそう。
（リリースまでに実装するかとかは一旦考えてない。表示ロジックが複雑なものについてはアイデアだけで終わるかもしれない。）

**Comment by xiii111** [comment]
良い意見をもらえました。少し考えます

**Comment by xiii111** [comment]
> * [x]  AdMob 広告の種類や仕様についてまとめる → 1.5 h

お二人から意見ももらえたので、こちらは完了にして

> * [ ]  広告の表示位置・種類・タイミングを決める → 4 h

に取り組もうと思います！

**Comment by xiii111** [comment]
# 現状の方針
まず、以下の 6 つの広告が候補として挙げられます
- バナー
- インタースティシャル
- リワードインタースティシャル
- リワード
- ネイティブアドバンス
- アプリ起動

バナーとインタースティシャル以外は、Treevel との相性・実装コスト・過度な UX 阻害の観点で、対象外とします。そのため、バナーとインタースティシャルについて深掘りしていこうと思います

**Comment by xiii111** [comment]
## バナー広告（WIP）

**Comment by xiii111** [comment]
## インタースティシャル広告（WIP）

**Comment by xiii111** [comment]
## 今後のアクション
### 前提
- リリース初期において、収益を最優先しているわけではない

### バナー広告
- UI の表示領域に適度な余裕があり、ゲームへの没入性を過度に奪わないような画面のみを選び表示する

### インタースティシャル広告
- ゲームへの没入性は適切なタイミングを検討することでカバーできるが、UX の低下はインタースティシャル広告が表示されるだけで発生してしまう。また、適切なタイミングの検討も含めた実装工数は大きいため、リリース初期には実装しない。リリース後に、ユーザー数が十分に増えるなどの理由で収益化の効果が見込めそうな場合に、時間を作って実装するのはどうだろうか

**Comment by xiii111** [comment]
@takasusuke @takesi0627 

https://github.com/LITO-apps/Treevel-client/issues/1410#issuecomment-1107418567 と https://github.com/LITO-apps/Treevel-client/issues/1410#issuecomment-1107418642 でバナー広告とインタースティシャル広告の詳細をまとめてみました。それを考慮した今後のアクションを https://github.com/LITO-apps/Treevel-client/issues/1410#issuecomment-1107686463 に書きました。レビューをいただけますか？

**Comment by takasusuke** [comment]
なるほど。ためになります。
今後のアクション同意。

**Comment by xiii111** [comment]
> これはつまり `AdMobs`のAPIを呼び出すだけではBGMなどを止めてくれないので、手動的に止める必要があるのか？
> なかなか面倒やね。

面倒だね

**Comment by xiii111** [comment]
今後のアクションに同意ということで、

> ### バナー広告
> * UI の表示領域に適度な余裕があり、ゲームへの没入性を過度に奪わないような画面のみを選び表示する

こちらの画面選びをします

**Comment by xiii111** [comment]
## 前提
1. [AdMob のドキュメント](https://developers.google.com/admob/unity/banner/anchored-adaptive?hl=ja) にもある通り、広告は画面の上部か下部に配置します
2. UI の表示領域に適度な余裕がある箇所に配置します
3. ゲームへの没入性を過度に奪わないような画面のみに配置します

## 全画面のスクショと広告配置の可能性
⚪︎・・・良い
△・・・微妙
▲・・・実装に不安がある
×・・・ダメ
|起動×|レベル選択×|ヒストリー▲|記録△|
|---|---|---|---|
|前提3|前提2+3|前提1：フロートボタンの存在|前提2|
|![IMG_3548](https://user-images.githubusercontent.com/26104258/167237847-bfa81c3f-8c46-4c5a-b18d-7b6e08b49e5e.PNG)|![IMG_3549](https://user-images.githubusercontent.com/26104258/167237834-abea124e-a034-454b-aea4-131b69390807.PNG)|![IMG_3550](https://user-images.githubusercontent.com/26104258/167237830-80348be4-f9b7-499b-930e-4a60d48e9027.PNG)|![IMG_3551](https://user-images.githubusercontent.com/26104258/167237824-e1b88336-8323-4dd9-9939-b76480d28ca2.PNG)|
|設定▲|ステージ選択×|ステージ概要⚪︎|ゲームプレイ×|
|前提1：フロートボタンの存在|前提2+3||前提3|
|<img src="https://user-images.githubusercontent.com/26104258/167237819-2a64ec41-960e-433d-a02f-058372f27568.PNG" width="300">|![IMG_3553](https://user-images.githubusercontent.com/26104258/167237811-9a0b370f-7c59-4f2e-9883-c53109baae1b.PNG)|![IMG_3554](https://user-images.githubusercontent.com/26104258/167237803-779c087c-8629-42fe-9eff-8c3f2b4fd628.PNG)|![IMG_3555](https://user-images.githubusercontent.com/26104258/167237798-d6324d39-b65f-4ba7-b1a3-652b261245af.PNG)|
|ポーズ⚪︎|成功△|失敗⚪︎|結果の見直し⚪︎|
||前提2|||
|<img src="https://user-images.githubusercontent.com/26104258/167237791-a9b7034b-172b-4b0e-a68e-4dac9e5ff5fa.PNG" width="300">|![IMG_3557](https://user-images.githubusercontent.com/26104258/167238187-d000e596-ff6e-4f51-a716-342146fc992a.PNG)|<img src="https://user-images.githubusercontent.com/26104258/167237778-639563ae-17ee-467e-aefd-94db52f0b351.PNG" width="300">|<img src="https://user-images.githubusercontent.com/26104258/167237766-43aa02fd-4336-4f19-8328-77f9a70a7b5b.PNG" width="300">|

**Comment by xiii111** [comment]
@takasusuke @takesi0627 以下の観点でレビューお願いします！

- 広告配置の可能性が ⚪︎ や × のものに関して、何か異論があるか
- 広告配置の可能性が △ のものに関して、⚪︎ か × かを決めるための生産的な意見があるか

## 備考
- ⚪︎ になったものも実装工数を鑑みて、実装しない可能性があります
- 最終的に △ のまま決め切れなかったものは、実装しません

**Comment by takasusuke** [comment]
> 広告配置の可能性が ⚪︎ や × のものに関して、何か異論があるか

「失敗」と「結果の見直し」は同じ広告オブジェクトを使う認識？別のオブジェクトの認識？
「結果の見直し」画面の下部にバナー広告が出て、「失敗」画面のグレーマスクはバナー広告部分には被らない（同じ広告オブジェクトがマスクの有無に関わらず表示されている）、みたいな認識で受け取りました。

> 広告配置の可能性が △ のものに関して、⚪︎ か × かを決めるための生産的な意見があるか

フッターボタンがある状態でバナー広告表示するのは、見た目が現時点で微妙なので一旦なしで良いかと思います。
フッターボタン自体もっと良い見せ方があると思うので、フッターのデザインを再考するタイミングにでもバナー広告も念頭に入れれば良さそう。

「成功」画面のツイートボタンと、バナー広告は形状も役割(アプリ外への遷移)も被っているのでバナー広告なしで良いのでは。
（少し話逸れるけどツイートボタンは「成功」画面ではなく「結果の見直し」画面が適切な気もしてきた。その場合は「成功」画面にバナー広告あっても不自然ではない。）

**Comment by xiii111** [comment]
> 「失敗」と「結果の見直し」は同じ広告オブジェクトを使う認識？別のオブジェクトの認識？
「結果の見直し」画面の下部にバナー広告が出て、「失敗」画面のグレーマスクはバナー広告部分には被らない（同じ広告オブジェクトがマスクの有無に関わらず表示されている）、みたいな認識で受け取りました。

確かにそれで良さそうですね

> フッターボタンがある状態でバナー広告表示するのは、見た目が現時点で微妙なので一旦なしで良いかと思います。
フッターボタン自体もっと良い見せ方があると思うので、フッターのデザインを再考するタイミングにでもバナー広告も念頭に入れれば良さそう。

それもそうですね ... フッターボタンが絡むやつは、とりあえず実装なしでも良さそう

> 「成功」画面のツイートボタンと、バナー広告は形状も役割(アプリ外への遷移)も被っているのでバナー広告なしで良いのでは。

そうねー成功する機会よりも失敗する機会の方が多いと思われるこのゲームで、成功した時も広告を出すのはかなりネガティブな気もしますね（とはいえ、捉え方によっては、失敗というストレスが溜まるときに広告が畳み掛けてくるのも微妙なのか？）

> （少し話逸れるけどツイートボタンは「成功」画面ではなく「結果の見直し」画面が適切な気もしてきた。その場合は「成功」画面にバナー広告あっても不自然ではない。）

個人的には、ツイートボタンを置くなら成功画面が良い気がしている。理由としては、「結果の見直し」は失敗したときに見るのが価値あるもので、成功した時に見ても、あるべき場所にボトルがあるだけで大して価値のある画面じゃなく、成功した時にツイートするというユースケースと合っていないから。また「結果の見直し」はわかりやすい導線ではないので、積極的にツイッターとかで宣伝してほしい身としては、成功画面自体にあった方が良いと感じる（ツイートするユースケースをもっと考えて、ツイート内容に何を含めるかとかはもっと考えた方が良いと思うけど）

**Comment by xiii111** [comment]
📝  定例会で議論する

**Comment by takesi0627** [comment]
> @takasusuke @takesi0627 以下の観点でレビューお願いします！
> 
> * 広告配置の可能性が ⚪︎ や × のものに関して、何か異論があるか

異議なし。

> * 広告配置の可能性が △ のものに関して、⚪︎ か × かを決めるための生産的な意見があるか

* 成功画面について、個人的に失敗とポーズの空いている空間と大差ないと見受けられていルので⚪︎にしてもいいかなと思いましたが、
やはりツイートボタンがちょっと下の方に占領しているから△にしていますでしょうか

* フロートボタンはとりあえず × で良さそう

**Comment by xiii111** [comment]
#1575 を起票しました
