### ISSUE TITLE
【ステージ選択画面改修】傷ステージであることをUI（ステージボタン）に反映する

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1437]
## 経緯

ref: #1400
#1436 にて実装されたプロパティをUIに反映する

### 改修前
ステージボタンの本来３種類の状態を持つ
| 状態 | 対応するUI |
| --- | --- |
| 未解放 | ![image](https://user-images.githubusercontent.com/17778395/154823583-ca66c06c-72fd-42f7-8a33-605d2292323c.png) |
| 未クリア | ![image](https://user-images.githubusercontent.com/17778395/154823579-d9a8989b-d0a9-4c66-97de-b5f4ae39d1b9.png) |
| クリア |  ![image](https://user-images.githubusercontent.com/17778395/154823563-cdd5ce04-ae35-4d94-97b6-1df9e9f04823.png) |

### 改修後
 傷ステージの状態を加えて、6つの状態になると考えられる
| 状態 | 対応するUI |
| --- | --- |
| 傷 + 未解放 | ![image](https://user-images.githubusercontent.com/17778395/154823654-410a3946-e027-4799-bddd-d8efa7bb4c13.png) |
| 傷 + 未クリア | ![image](https://user-images.githubusercontent.com/17778395/154823660-83789d62-a7dd-403d-b81f-67181db4debd.png) |
| 傷 + クリア | ![image](https://user-images.githubusercontent.com/17778395/154823563-cdd5ce04-ae35-4d94-97b6-1df9e9f04823.png) + パーティクル |
| 未解放 | ![image](https://user-images.githubusercontent.com/17778395/154823583-ca66c06c-72fd-42f7-8a33-605d2292323c.png) |
| 未クリア | ![image](https://user-images.githubusercontent.com/17778395/154823579-d9a8989b-d0a9-4c66-97de-b5f4ae39d1b9.png) |
| クリア |  ![image](https://user-images.githubusercontent.com/17778395/154823563-cdd5ce04-ae35-4d94-97b6-1df9e9f04823.png) |

### 注意事項
* 傷状態のステージは、文字の色、太さを変更する必要がある。
* パーティクルによる演出は決まっていないため、本イシューで実装する必要はない。

## 完了条件

- [x] 傷ステージが反映できるようにプレハブに変更を加える
- [ ] 傷ステージが反映できるように`StageIconView.cs`に適切な実装を行う
- [x] デバッグできるように適切なテストデータを作る

## 備考
* depend on: #1436 
* StageListItemとStageのロジック共通化が望ましいですが、リファクタリング無理のないように。
* 傷ステージのクリア状態（パーティクルによる演出等）は別途対応可

**Comment by xiii111** [comment]
@takesi0627 これなんで In Review だっけ ... ??（付属の PR が見つからず）

**Comment by takesi0627** [comment]
ただのミスであった
