### ISSUE TITLE
【ステージ選択画面改修】傷ステージクリア演出

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1438]
## 経緯

ref: #1400
傷ステージをクリアしたら傷が消える演出が必要

## 詳細

演出シーケンス（一般）
1. `GamePlayScene`にて成功ポップアップから戻るボタンをクリック
2. 傷ステージが消える演出

演出シーケンス（次のステージが解放される場合）
1. `GamePlayScene`にて成功ポップアップから戻るボタンをクリック
2. 傷ステージが消える演出
3. 枝解放＋鍵解錠演出

### 演出内容
最低限フェードアウトだけでも大丈夫、ブラッシュアップはベータ版にて行う。

## 完了条件

- [ ] 傷ステージが消えるアニメーションの作成
- [ ] 演出シーケンスの実装
- [ ] SEを考慮

## 備考
depend on: #1437 

* タイムラインに傷演出を追加し、条件でスキップする実装を検討

**Comment by xiii111** [comment]
@takesi0627 また pr 無い状態で in review に移動されてる気がする。戻すね
