### ISSUE TITLE
【ステージ選択画面改修】傷ステージ、進捗バーの見方を教えるOn Boardingデザイン

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1440]
## 経緯

ref: #1400
傷ステージとは？進捗バーってなんなの？をユーザに教える必要があるためのコーチマークを設計する

## 完了条件

- [ ] シーケンスを設計、テキスト内容を提案し、議論の上で決定する
→
https://docs.google.com/presentation/d/1Ekm6V0pyh3O35tDw2QrdMNuNmnDY9QW-NP9uXoN0G2c/edit#slide=id.p

## 備考
出るタイミングは、初めての傷ステージクリア後？

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
説明案を作成しました。MTGで議論できたらと思います。

https://docs.google.com/presentation/d/1Ekm6V0pyh3O35tDw2QrdMNuNmnDY9QW-NP9uXoN0G2c/edit#slide=id.g116f2b94744_0_148
の10p、11p。

**Comment by xiii111** [comment]
@takasusuke 一通り目を通しましたが、良さそうに感じました！文言だけもう少し洗練できるかなとは思いましたが、デザインとしては、素晴らしかったです

**Comment by xiii111** [comment]
文言に関して、少しだけコメントを追加しました

**Comment by takasusuke** [comment]
以下に決まり。
#1441 で実装。

<img width="537" alt="スクリーンショット 2022-02-28 21 08 36" src="https://user-images.githubusercontent.com/26213141/155981503-45218278-a919-4cba-945a-73e10690f921.png">
