### ISSUE TITLE
`App Store Connect` のベータテストについて調査する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1460]
## 完了条件
- [x] ベータテストの特徴を調査する

## 調査項目
- [x] 導入方法
- [x] 審査提出方法
- [x] 配布方法
- [x] 分析方法

## 基本情報
https://developer.apple.com/jp/testflight/

> TestFlightを使用すると、AppおよびApp ClipをApp Storeでリリースする前にユーザーをテストに招待し、有益なフィードバックを受けることができます。テスターのメールアドレスを使うか、パブリックリンクを共有することで、最大10,000人のテスターを招待することができます。

`パブリックリンクを共有する` は良さそう

> ## 内部テスター
> ベータ版のテスターとして、Account Holder（アカウントホルダー）、Admin（管理者）、App Manager（App管理者）、Developer（デベロッパ）、Marketing（マーケティング）の役割のチームメンバーを、最大100人指定することができます。複数のグループを作成し、それぞれのグループで重点的にテストすべき機能に応じて、異なるビルドを各グループに追加することも可能です。デベロッパがApp開発のイテレーションを行う間、メンバーは各自最大30台のデバイスでテスト用のベータ版ビルドをすばやくテストし、入手可能なすべてのベータ版ビルドにアクセスしてテストすることができます。

これが今やってるやつかな

> ## 外部テスターとグループ
> 外部テスターのメールアドレスを使って、または有効化したパブリックリンクを共有することで、あらゆるユーザーを最大10,000人までAppのテストに招待できます。方法はシンプルで、テスターのグループを作成し、テストしてほしいビルドを追加するだけです。複数のグループを作成し、それぞれのグループで重点的にテストすべき機能に応じて、異なるビルドを各グループに追加することも可能です。テストを開始するには、Appの最初のビルドがTestFlight App Reviewで承認される必要があります。このビルドをグループに追加すると、審査のために自動的に送信されます。

これをやりたい。`テストを開始するには、Appの最初のビルドがTestFlight App Reviewで承認される必要があります。` にあるように、審査を通す必要がありそう

> ### Eメールによるテスターの招待
> テスターのメールアドレスがわかる場合は、Appをインストールしてテストを開始するためのリンクが記載された招待Eメールを送信することができます。テストに招待する外部テスターや特定のユーザーのリストがすでにある場合は、EメールでAppのベータ版を共有する方法が効果的です。

ちゃんと人選するなら、審査 + 今まで通りのメール招待、でやるのが良さそう

> ### パブリックリンクによるテスターの招待
> 既存のテスターのグループがない場合は、パブリックリンクを使って、Appのテストに参加できるユーザーを募る方法が効果的です。連絡先情報は必要ありません。AppのTestFlightページにアクセスして既存のグループをクリックし、「パブリックリンクを有効にする」をクリックします。その後、リンクをコピーして、ソーシャルメディア、メッセージングプラットフォーム、Eメールキャンペーンなどで共有することができます。なお、TestFlightという名前をローカライズしたり、Appを宣伝するためのTestFlightバッジを作成したりすることは許可されていません。
> 
> パブリックリンクを使用してグループに参加するテスターの数を制限することもできます。グループが制限人数に達するか、デベロッパがパブリックリンクを無効にすると、テストに参加しようとするユーザーに、新しいテスターの受け入れが終了したことを伝えるメッセージが表示されます。ポジティブなユーザー体験となるよう、パブリックリンクを共有する場所や、パブリックリンクを削除する適切なタイミングについて、十分に検討するようにしてください。

Twitter や Instagram、グループ Line などで宣伝をする場合には、こちらが良さそう。とはいえ、`Eメールによるテスターの招待` の上位互換なので、こちらを実施するので良さそう

> ### テストに関する情報
> Appを外部テスターに共有する際は、テストの内容を伝え、テストに関して他に重要な情報があれば、それらも伝える必要があります。こうした情報は、App Store Connectの「テスト情報」ページに入力してください。また、テスターからのフィードバックを受信して返答できるよう、定期的にチェックできるメールアドレスをテスターに提供してください。内部テスターにAppを配信する場合、テストに関する情報の入力は任意です。

注意深くみてほしいところや、注意事項も書いたりできる

> ### フィードバックの収集
> iOS、iPadOS、およびmacOS向けのTestFlightの場合、テスターはスクリーンショットを撮るだけで、Appから直接フィードバックを送信することができます。また、Appでクラッシュが発生した直後に、その状況に関する追加情報を提供することもできます。このフィードバックを表示するには、App Store ConnectでAppのTestFlightページを開き、「フィードバック」セクションの「クラッシュ」または「スクリーンショット」をクリックします。iOS 12以前、tvOS、watchOSでテストに参加しているユーザーからのフィードバックは、デベロッパが「テスト情報」で入力したメールアドレスに送信されます。

`テスターはスクリーンショットを撮るだけで、Appから直接フィードバックを送信することができます。` という機能を利用して、バグ報告や機能改善を送ってもらえそう。`Appでクラッシュが発生した直後に、その状況に関する追加情報を提供することもできます。` に関しては、Unity は Exception が発生してもアプリをクラッシュさせてくれないので、あまり有効ではない。そのためにエラーポップアップを出したりしているので、こちらは PlayFab のエラー計測を洗練させ、そちらを見守る必要がありそう。Unity の Exception 以外の理由でアプリがクラッシュすることもあると思うので、そちらの場合にはこの機能が効果的だと思われる

**Comment by xiii111** [comment]
![スクリーンショット 2022-03-15 9 49 38](https://user-images.githubusercontent.com/26104258/158284894-63861fd5-a8ee-44d8-81d5-bab9405590fa.png)

外部テストに `オープンテスト` と `個別テスト` のグループを作りました

`オープンテスト` では、パブリックリンクを ON にし、不特定多数にテストをしてもらいます。その性質上、完成度が高いバイナリを置く想定です

`個別テスト` では、パブリックリンクを OFF にし、特定の人にテストをしてもらいます。その性質上、完成度が低いバイナリも置く想定です

![スクリーンショット 2022-03-15 9 57 34](https://user-images.githubusercontent.com/26104258/158285189-466604dd-4421-40e0-800e-a0f1f7efef5e.png)

いずれのグループにバイナリを置く場合でも、置きたいバイナリを審査に出す必要があります。一度でも審査が通ったバイナリは、どちらのグループにも適用することができます

**Comment by xiii111** [comment]
一旦 Apple の審査を待っている。審査が通り次第

> * [ ] 配布方法
> * [ ] 分析方法

に取り組みます

**Comment by xiii111** [comment]
📝 まだ審査通ってない

**Comment by xiii111** [comment]
📝 修正版のバイナリを再度審査に提出した。審査待ち状態

**Comment by xiii111** [comment]
📝 審査通っていたので、再開

**Comment by xiii111** [comment]
外部テストにある `オープンテスト` では、パブリックリンクを有効にしました

<img width="1404" alt="スクリーンショット 2022-03-19 19 40 09" src="https://user-images.githubusercontent.com/26104258/159117756-220252d7-f59c-4c07-97ef-6b51ef8e6be8.png">

外部テストにある `個別テスト` では、パブリックリンクを有効にせず、内部テストと同じメンバーを追加しました

<img width="1404" alt="スクリーンショット 2022-03-19 19 40 17" src="https://user-images.githubusercontent.com/26104258/159117757-a13e8021-6fce-4554-9cb5-e1c225400bbd.png">

**Comment by xiii111** [comment]
## ベータ版 App 情報
以下を編集します

<img width="1405" alt="スクリーンショット 2022-03-19 19 51 28" src="https://user-images.githubusercontent.com/26104258/159118072-3939ceb4-497c-498f-a958-9396f75460a2.png">

すると、以下が変わります

<img src="https://user-images.githubusercontent.com/26104258/159118097-78be7f13-4f8d-41d5-8830-e51d198d1a55.jpeg" width="300">

## テストの詳細

以下を編集します

<img width="1383" alt="スクリーンショット 2022-03-19 19 53 24" src="https://user-images.githubusercontent.com/26104258/159118136-7df8cc6a-2649-4676-b538-383966ff7ee7.png">

すると、以下が変わります

<img src="https://user-images.githubusercontent.com/26104258/159118144-74fa2ace-8771-4d0c-b42f-1ff91035e2fa.jpeg" width="300">

## パブリックリンクの開封

|開封|さらに表示|同意|開く|
|---|---|---|---|
|![IMG_AD4E20EF8942-1](https://user-images.githubusercontent.com/26104258/159118225-3ab40713-9bc5-4c56-aa96-d04135f16e41.jpeg)|![IMG_AD4E20EF8942-2](https://user-images.githubusercontent.com/26104258/159118227-a38b7e3e-8901-4449-9663-25ea6d752dd8.jpeg)|![IMG_AD4E20EF8942-3](https://user-images.githubusercontent.com/26104258/159118228-0437299b-e591-4653-8f6f-0a4e34c4104b.jpeg)|![IMG_AD4E20EF8942-4](https://user-images.githubusercontent.com/26104258/159118230-f57bf7b1-f776-41d6-b470-c05d3dbfd940.jpeg)|

**Comment by xiii111** [comment]
## 正式な外部テストをするために必要なこと
- [ ] `PlayFab` のエラー計測を洗練させる
- [ ] 外部テストをするための機能を全て開発し終える
- [ ] 上記バイナリを TestFlight にアップロードする
- [ ] 上記バイナリを審査に通す
- [ ] `オープンテスト` と `個別テスト` に変わる、正式な外部テストグループを作成する
- [ ] `ベータ版 App 情報` を記述する
- [ ] `テストの詳細` を記述する
- [ ] パブリックリンクを有効にする
- [ ] テストしてもらいたい人達に、パブリックリンクを共有する
(この際に、メールアドレスが我々に伝わってしまうことも補足する)

**Comment by xiii111** [comment]
@takasusuke @takesi0627 本イシューの概要を含め、全てのコメントに上から順に目を通してください！（以前から編集されています）その上で、調査したりない項目があったら、教えてください。本イシューの調査は全て終わったつもりです！

**Comment by takasusuke** [comment]
memo
- App Store Connectで「外部テスト」、の項目は自分には表示されなかった
- テスト終了はどのように？(もらったフィードバックは残したまま、これ以上フィードバックをもらわない、が可能？)

**Comment by xiii111** [comment]
@takasusuke 

> ## memo
> * App Store Connectで「外部テスト」、の項目は自分には表示されなかった

権限を付与しました。表示される気がするので、確認お願いします

> ## ask
> * テスト終了はどのように？(もらったフィードバックは残したまま、これ以上フィードバックをもらわない、が可能？)

- パブリックリンクを無効にすると、以降リンクにアクセスしたテスターに対して、「このベータ版は、現在新規テスターを受け付けていません。」と表示されるようになります
- テスターフィードバックを無効にすると、以降クラッシュフィードバックとスクリーンショットを送信できなくなります
- テスター数の制限を設定すると、パブリックリンクを利用するテスターの数を制限できます

<img width="600" alt="スクリーンショット 2022-03-20 9 14 48" src="https://user-images.githubusercontent.com/26104258/159142700-ab0ef769-110c-408c-b420-f9a02526da00.png">

**Comment by takesi0627** [comment]
> * テストしてもらいたい人達に、パブリックリンクを共有する（メールアドレスが我々に伝わることも補足する）

メールアドレスが伝わるについては「サービス利用条件」にはちゃんと書いているみたいなので、必要ではないかなと思いました。

**Comment by xiii111** [comment]
> > * テストしてもらいたい人達に、パブリックリンクを共有する（メールアドレスが我々に伝わることも補足する）
> 
> メールアドレスが伝わるについては「サービス利用条件」にはちゃんと書いているみたいなので、必要ではないかなと思いました。

取扱注意という言い方は良くなかったですね。友人などを招待することが多いと思うので、「サービス利用条件」に書いてあるからといって OK とすると、トラブルの元な気もしたので、一応共有しました！

**Comment by takesi0627** [comment]
友人直接送る時はいいけど、例えばSNSでパブリックリンクを投稿するとかの時はそういう説明はいらないかなーって思います

**Comment by takasusuke** [comment]
メールアドレスについては、テストが終わったら削除することをApp情報に記載したい。

**Comment by xiii111** [comment]
問題なさそうだったので、閉じます！
