### ISSUE TITLE
ステージのロックアイコンが描画されないことがある

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1471]
## 概要
- ステージのロックアイコンが SafeArea 外に描画されない

## 再現手順
- ステージを SafeArea 内ギリギリに配置する
- ロックアイコンが欠けて見える

## 期待動作
- ロックアイコンはボタンじゃないので、欠けないようにする

## キャプチャ
<img src="https://user-images.githubusercontent.com/26104258/157242740-10607a5a-7dff-4468-bf29-40e7028b5059.png" width="300">

## 発生環境
- develop 最新

**Comment by takasusuke** [comment]
SnapScroll直下のViewport外に出ていることが原因。
SnapScrollを廃止(1つのSceneにSpring_1, 2, 3を配置しているのを廃止)しないと根本解決できない。
