### ISSUE TITLE
音源の圧縮のQualityの設定

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1480]
## 終了条件
- [ ] 音源の圧縮設定を比較、適用する

## 考慮事項
圧縮設定のうち、現在は`Vorbis`(最も圧縮できる設定)を使用。圧縮のQualityを調整でき、現在は最もQualityが高い(Quality100の)設定。
inspectorに表示される値としては、圧縮後の容量は以下のようになる。
|     | BGM | SE |
|-----|-----|-----|
|Original|346.4MB|35.3MB|
|Quality100|87.8MB|6.4MB|
|Quality75|49.6MB|4.6MB|
|Quality50|35.9MB|3.0MB|
|Quality25|19.9MB|1.6MB|
|Quality1|16.0MB|1.3MB|

音質を損なわないできるだけ容量の小さな設定にする。

**Comment by takesi0627** [comment]
`CRIWARE`を導入したことで不要になりました
