### ISSUE TITLE
iOS 広告追跡ダイアログを出す必要あるかを調査する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1490]
## 経緯

広告使ってるのでもしかしたら広告追跡のOn／Offポップアップを出す必要があるので調査する

## 完了条件

- [ ]

**Comment by xiii111** [comment]
> アプリやアプリが導入しているサードパーティーのiOS 14 SDKが[IDFA](https://magazine.fluct.jp/word_list/advertisingid)を利用して広告配信や広告の効果測定を行う場合、アプリ内でユーザーに対して利用の同意を求める必要があり、同意しなかったユーザーのIDFAは取得できなくなります。

**Comment by xiii111** [comment]
## まとめ

参考記事:
- https://zenn.dev/tetr4lab/articles/0e1006dda8f4ba
- https://www.adjust.com/ja/glossary/idfa/

### Q0. iOS 広告追跡ダイアログって何？
これ

<img width="239" alt="スクリーンショット 2022-03-26 18 48 00" src="https://user-images.githubusercontent.com/26104258/160234123-1c24e389-bf89-4aad-9285-b9387a9ebee9.png">

### Q1. どういう時に iOS 広告追跡ダイアログを出す必要ある？
A. IDFA（Identifier for Advertisers）を利用したい時。尚、iOS 広告追跡ダイアログは、ATT（App Tracking Transparency）という IDFA を使用する際に、ユーザーに IDFA の取得許可を得る仕組みによって出すことができる。もちろん、ユーザーに許可されなかった場合には、IDFA を利用できない。また、ATT を利用してダイアログを出すためには、App のプライバシーで「トラッキング」を申告する必要がある

### Q2. IDFA って何？
A. Apple がユーザーの端末にランダムに割り当てるデバイス ID である。広告主（GoogleAdMob など）はこの ID を使ってユーザーの広告エンゲージメント 、アプリ内のユーザー行動を計測することで、カスタマイズ（最適化）した広告を配信することができる。要は、ユーザーに出す広告の精度が上がる

### Q3. IDFA が利用できなかったら、どうなる？
A. 自動的に SKAdNetwork という仕組みが利用される。SKAdNetwork は、IDFAを使用せずに、プライバシーに配慮しつつ広告の最適化を行うための仕組みで、IDFA を利用した場合に比較して広告の追跡性能が低い。繰り返しの情報だが、IDFA が利用できない場合は、以下の 2 通りがある
- そもそも iOS 広告追跡ダイアログをユーザーに出していない（IDFA の使用許可を求めていない）場合
- iOS 広告追跡ダイアログをユーザーに出したが、使用許可が得られなかった場合

### Q4. じゃあ、どうする？
A. 現段階では、広告の精度をそこまで気にしていないし、何もしなくて良いのではと思った。僅かな収益の変化も大切にするのであれば、実装するのが良い。詳細な実装は https://zenn.dev/tetr4lab/articles/0e1006dda8f4ba を参照

**Comment by xiii111** [comment]
@takasusuke @takesi0627 調査結果を上記に書きました。今後のアクションに同意かどうかをコメントください

**Comment by takasusuke** [comment]
IDFAを利用しない方針に同意です。

**Comment by takesi0627** [comment]
IDFAなしで良さそう。

**Comment by xiii111** [comment]
ありがとうございます！
