### ISSUE TITLE
【成功画面】`Twitter` への導線を作る

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1498]
## 経緯

~~成功画面にTwitterアイコンが置いているが、左側が空いてるため不自然に感じる~~

成功画面から Twitter アイコンが消されたが、ステージを成功した時が一番ツイート欲が高いタイミングなので、Twitter への導線を作りたい

## 完了条件

- [ ] 成功画面のどこに `Twitter` への導線を置くかを決める
- [ ] 上記を実装する

## 備考
以下を検討しても良さそう
* `Twitter` に投稿しようなどの文言を記載する
* ツイッターアイコンではなく、`CustomButton` で実装する

**Comment by xiii111** [comment]
とりあえず Prod 環境で現状確認（#1536 での確認は Dev 環境だったため、SafeArea 部分が黒くなっていて、実際の雰囲気が分からない）

|ホームボタン有り|ホームボタン無し|
|---|---|
|<img width="300" alt="スクリーンショット 2022-04-05 22 17 33" src="https://user-images.githubusercontent.com/26104258/161763153-8b653158-0a3c-4c92-acbe-8652fdd8abb7.png">|<img width="300" alt="スクリーンショット 2022-04-05 22 16 29" src="https://user-images.githubusercontent.com/26104258/161763150-f56fa2b6-8b27-4443-94da-d414ac39f068.png">|
