### ISSUE TITLE
木のリリース順番を変更するための仕様変更のタスク洗い出し

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1514]
## 経緯
`Spring-1` 、`Summer-1`、`Autumn-1`、`Winter-1`をリリース時に出す予定していたが、
ステージの難易度の調整を考慮する設計にするため、
`Spring-1`、`Spring-2`、`Spring-3`... の順番でリリースすることに決めました。

## 完了条件
- [ ] 上記の仕様変更に対して行うべきタスクの洗い出し

**Comment by takesi0627** [comment]
現状の懸念点
* ステージ選択シーン、ゲームシーンの背景同じなので、今どの木にいるかわからない
* 記録画面の木のアイコンはどの木かわからない

**Comment by xiii111** [comment]
@takesi0627 まとめありがとうございます！

機能については良さそうです。デザインについてですが、ステージアイコンと木のアイコン以外に、ステージ選択の背景も調整が必要な気がしましたが、合っていますか？

> * `Spring-1`、`Spring-2`、`Spring-3`のステージアイコンの色味調整

花びらのことかな？色味を調整するには、木のアイコン・ステージ選択の背景などと連携が必要だと思うので、単独でタスクをこなすのは難しいかなと思いました。また、色味だけの調整で違いを伝えるのも結構難しいと思いました。色味を変えすぎると桜感が無くなるし、色味を変えなさすぎると `Spring-N` 間の違いがわからないし ... 何かアイデアを出した方が良い気もします。また、このタスクでは `Spring` に絞る想定ですか？

> * 木アイコンに描く季節の何本目の木かがわかるようなデザインを設計

こちら表現が分かりづらかったですが、記録画面用に木のアイコンだけに置く想定ですかね？

**Comment by takasusuke** [comment]
特にコメントはありません。
StageSelectSceneの左上空いてるし、「Spring_1」とか表示することを検討するのは良いかもしれないね。

**Comment by takesi0627** [comment]
> @takesi0627 まとめありがとうございます！
> 
> 機能については良さそうです。デザインについてですが、ステージアイコンと木のアイコン以外に、ステージ選択の背景も調整が必要な気がしましたが、合っていますか？
> 

背景の色は変えないことは先週のMTGで決めたかと思いますので対象外としています。


> > * `Spring-1`、`Spring-2`、`Spring-3`のステージアイコンの色味調整
> 
> 花びらのことかな？色味を調整するには、木のアイコン・ステージ選択の背景などと連携が必要だと思うので、単独でタスクをこなすのは難しいかなと思いました。また、色味だけの調整で違いを伝えるのも結構難しいと思いました。色味を変えすぎると桜感が無くなるし、色味を変えなさすぎると `Spring-N` 間の違いがわからないし ... 何かアイデアを出した方が良い気もします。また、このタスクでは `Spring` に絞る想定ですか？

確かにステージアイコンと木アイコンの色味は一緒に調整した方がいいですね。
このタスクは季節毎にイシューを作る想定です。
 
> > * 木アイコンに描く季節の何本目の木かがわかるようなデザインを設計
> 
> こちら表現が分かりづらかったですが、記録画面用に木のアイコンだけに置く想定ですかね？

すみませんこれ誤字りましたね、正しくは「描く季節」→「各季節」でした。
要は木のアイコンに数字を追加したり新たな情報を追加するためのデザインを考えるタスクです

**Comment by takesi0627** [comment]
## 🎨`design` タスク
* `Spring-1~3`のステージアイコン・木アイコンの色味調整
* `Summer-1~3`のステージアイコン・木アイコンの色味調整
* `Autumn-1~3`のステージアイコン・木アイコンの色味調整
* `Winter-1~3`のステージアイコン・木アイコンの色味調整
* 記録画面の各レベル（木）の表示のレイアウト設計
* 木アイコンに描く季節の何本目の木かがわかるようなデザインを設計

## 🔧`feature` タスク
* 記録画面の各レベル（木）の表示の実装
* `LevelSelectScene`の道、木の再設定
* 木アイコンに描く季節の何本目の木かがわかるようなデザイン適用
* `Spring-1`、`Spring-2`、`Spring-3`の解放順になるようにデータを設定する

**Comment by xiii111** [comment]
@takesi0627 LGTM !!

**Comment by takesi0627** [comment]
イシュー作成完了したのでクローズします
