### ISSUE TITLE
表示したい称号を決め、必要な記録データを確定させる

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1519]
## 経緯

初回リリースには称号機能を入れない予定だが、記録データは予め取っておかないといけない。なので、表示したい称号をこの時点で決め、必要な記録データを確定させる必要がある

## 完了条件

- [ ] 表示したい称号を決める
- [ ] 必要な記録データを洗い出し、確定させる
- [ ] #1520 の完了条件を埋める

## 備考
現状とっている記録データは以下である

### UserRecord
- 総起動日数（`StartupDays`）
- 初回起動日（`FirstStartupDate`）
- 最終起動日（`LastStartupDate`）

### StageRecord
- 挑戦回数（`ChallengeNum`）
- 成功回数（`SuccessNum`）
- 失敗回数（`FailureNum`）
- 失敗原因（`FailureReasonNum`）
- フリック回数（`FlickNum`）

## 見積もり時間について
- 称号の提案（1 時間）
- 称号の議論（1 時間）
- 称号の修正（30 分）
- 称号の議論（30 分）
- 称号の確定 + 記録データの確定（1 時間）

**Comment by xiii111** [comment]
📝 PlayStation における [トロフィー](https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%AD%E3%83%95%E3%82%A3%E3%83%BC_(PlayStation)) を参考にしたい

> トロフィーとは、ソニーが全世界で提供しているゲームソフトにおけるやり込み具合を表す指標である。

> トロフィーは取得の難易度が高い方から順に「プラチナ」「ゴールド」「シルバー」「ブロンズ」の4種類ある。プラチナトロフィーは「（そのプラチナトロフィーを除き）ゴールド・シルバー・ブロンズの全トロフィーを取得すること」が取得条件となることが多い

> PS4からは「トロフィーのレア度」が追加された。プレーヤーの割合により、「ふつう」「レア」「とてもレア」「超レア」の4つのレア度となる。

**Comment by xiii111** [comment]
## WIP

### タイプ 1：普通にプレイすれば良い系
- 特定の季節における、全ての木をクリアした
- 特定の季節における、全ての木を完全クリアした
- 特定の木をクリアした
- 特定の木を完全クリアした
- 特定のステージをクリアした（最初のステージなど）
- 特定のゲーム要素が登場するステージをクリアした
- 難易度 1 のステージをクリアした
- 難易度 2 のステージをクリアした
- 難易度 3 のステージをクリアした
- 難易度 4 のステージをクリアした
- 難易度 5 のステージをクリアした
- 設定画面を見た
- 記録画面を見た
- ヒストリー画面を見た
 
### タイプ 2：数をこなせば良い系
- アプリを `n` 回起動した
- ボトルを `n` 回移動した
- `n` 個のステージをクリアした
- ステージに `n` 回挑戦した
- ステージに `n` 回失敗した
- 特定の BGM を、ループするまで聞いた

### タイプ 3-1：達成が難しい系（達成条件がシンプルに難しい）
- 特定のステージを `n` 秒以内にクリアした
- ライフボトルが登場するステージにおいて、ライフを一度も削られずにクリアした 

### タイプ 3-2：達成が難しい系（達成条件がただただ稀）
- 虹色のボトルを見た（乱数で現れる虹色のボトルを用意するなど）

## メモ
-

**Comment by xiii111** [comment]
📝 iOS ゲームセンターにも似た機能があるので、調べる

**Comment by xiii111** [comment]
## Apple Arcade
- Apple Arcade が結構良かったから、貼っておく（ @takesi0627 ゲームセンターってまた別？）

### アカウント情報を開く

![IMG_3137](https://user-images.githubusercontent.com/26104258/161356099-8746afed-adfb-478e-ac84-6c4fdf77bad2.PNG)

### 達成項目を開く
![IMG_3138](https://user-images.githubusercontent.com/26104258/161356095-89204f4c-0eed-4278-8342-cedae2bfa8be.PNG)
![IMG_3139](https://user-images.githubusercontent.com/26104258/161356090-40b27020-bed7-4b72-97ff-bcca8f007dfe.PNG)
![IMG_3141](https://user-images.githubusercontent.com/26104258/161356086-7d0d884b-a1a1-4dc3-8348-a81f5217b103.PNG)
![IMG_3140](https://user-images.githubusercontent.com/26104258/161356089-ad2b7276-ff8c-4a17-b889-f23a1d91120f.PNG)




### Leaderboard を開く
![IMG_3142](https://user-images.githubusercontent.com/26104258/161356083-e36bdd48-99ff-4a2a-921c-e09a33c8cfe2.PNG)

**Comment by xiii111** [comment]
@takasusuke @takesi0627 https://github.com/LITO-apps/Treevel-client/issues/1519#issuecomment-1084417144 を更新しました。以下の観点でレビューをお願いします！
- 表示したい称号を網羅できているか
- 表示したい称号ではない称号が混ざっていないか
- ★ が付いている称号に過不足がないか（★ がついていない称号に関わる計測は、今回のイシュー群の範疇では計測しないことになります）

**Comment by takesi0627** [comment]
Apple Arcadeやってないから、それどこからアクセスできるの？
今気づいたが、Game Centerは設定からアクセスできます。

| 1 | 2 | 3 |
|--|--|--|
| <img width="414" alt="image" src="https://user-images.githubusercontent.com/17778395/161387435-8aed1d15-53cc-4a09-82bf-9f046108c507.png"> | <img width="414" alt="image" src="https://user-images.githubusercontent.com/17778395/161387496-0c4dd053-e9f0-408b-9817-7a313baf365f.png"> | <img width="414" alt="image" src="https://user-images.githubusercontent.com/17778395/161387561-5240d22c-4817-4378-ab47-ce64ffd3e651.png"> |

ゲーム内から実装次第アクセスすることもできます。（当然ですが`Apple ID`との連携が必要です）
<img width="400" alt="image" src="https://user-images.githubusercontent.com/17778395/161387622-4df03640-7416-4a0c-b480-4ec7dd5e4a82.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/17778395/161387664-f6a249c6-e155-48de-90f2-27baa2e8f254.png">

**Comment by takesi0627** [comment]
### `ASK`
★付くかどうかの基準もうちょっと詳しく説明してほしい。

★付いていないものは称号機能を搭載する前に達成したとしても、称号機能搭載する時点で獲得しなくてもいいから計測しなくていいという認識で大丈夫でしょうか？
（例えば、称号機能実装する前に設定画面開いたことがあるけど、称号機能搭載後また開いたらいいから現時点考慮しなくてもいいから★付かない）

**Comment by takasusuke** [comment]
- ★ アプリを n 日起動した

----
- 「Warp でボトルが移動した」等のゲーム要素に関する称号は「★ Warp でボトルが`n`回移動した」に読み替えると計測必要？
- ★ 結晶タイルを`n`個癒した

**Comment by xiii111** [comment]
@takesi0627 

> Apple Arcadeやってないから、それどこからアクセスできるの？

アプリ内からアクセスできた！

|アプリをタップ|左下のアカウントをタップ|色々でる|
|---|---|---|
|![IMG_3151](https://user-images.githubusercontent.com/26104258/161405250-d07cd470-b70a-480c-a6bc-4851a0c29875.PNG)|![IMG_3153](https://user-images.githubusercontent.com/26104258/161405248-fdb0f929-7744-47ef-9ece-8040d2060a8e.PNG)|![IMG_3154](https://user-images.githubusercontent.com/26104258/161405245-4c98c6a1-56bf-41d5-a59f-d6dcfbfa3935.PNG)|

> 今気づいたが、Game Centerは設定からアクセスできます。

実際に手元でアクセスできた！

> ゲーム内から実装次第アクセスすることもできます。

これが、私が Apple Arcade と勘違いしていたやつだ

> 比べてみた感じ、「達成項目」機能は一緒みたいですね。
ただ、Game Centerには「Leader Board」がないっぽいですが、今回の議題とは関係ない気もするので気にしなくていいはず

一緒みたいだね！確かに Leader Board がないですが、確かに今回とは関係ない

**Comment by xiii111** [comment]
@takesi0627 

> ### `ASK`
> ★付くかどうかの基準もうちょっと詳しく説明してほしい。

確かに一言でしか説明していなかった。申し訳ない

> ★付いていないものは称号機能を搭載する前に達成したとしても、称号機能搭載する時点で獲得しなくてもいいから計測しなくていいという認識で大丈夫でしょうか？ （例えば、称号機能実装する前に設定画面開いたことがあるけど、称号機能搭載後初めて開く時にカウントすればいいから現時点考慮する必要ないから★付かない）

そういう認識ですね。★ がついているのは、称号機能を搭載した時に、今までの記録を元に称号の達成状況が反映されていないと、かなり困りそう、というものです。この棲み分けの傾向としては、その称号を達成するために必要な労力が大きいか、ですね。他には、直感的に称号に反映されていないと不快感や再び達成する気にはなれない、これは達成したはずだ、と強く思われてしまいそうなものかどうか、もあります

**Comment by xiii111** [comment]
@takasusuke 

> * ★ アプリを n 日起動した

間違えました。n 日が正しいです！

> * 「Warp でボトルが移動した」等のゲーム要素に関する称号は「★ Warp でボトルが`n`回移動した」に読み替えると計測必要？

うーーん、そうねぇ、直前のコメントにもあるように、その称号を達成するための労力が大きい場合、ユーザーが再び達成する意欲を削いでしまったり、再び達成する気にならなかったりするので、計測しないといけないような気はしますね ... 定例会で議論しましょう

> * ★ 結晶タイルを`n`個癒した

これは、結晶タイルの上を薬ボトルが入ったり出たりしても、計測されるイメージ？

**Comment by xiii111** [comment]
追加で計測することなしということで、このイシューは閉じます！
