### ISSUE TITLE
WarpTileに入るときに、BottleがTileの大きさを超えないようにする

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1525]
## 経緯

Bottleの当たり判定が隣のTileにまで及ぶと、意図しないTile上で失敗することがありストレスフルだから

## 詳細

Warp時のBottleの当たり判定(見た目はそのまま)の調整を行う

## 完了条件

- [ ] WarpAnimation時に、Bottleの当たり判定のParameterを編集する

## 備考

https://user-images.githubusercontent.com/26213141/160260482-78de3441-9f18-479c-ad0b-5805f1dcecf4.mov

**Comment by takesi0627** [comment]
`WarpTile@bottle_in`や`WarpTile@bottle_out`からコライダーを制御することができません。
そして、`PolygonCollider2D`の大きさをいじるにはアタッチしているオブジェクトそのものの大きさをいじらないといけないので、
大きさを変えずに当たり判定を調整することはできません。
なので以下二つの提案をどちらにするか議論を行いたいです。

## 案1：演出中当たり判定を切る
演出中は`PolygonCollider2D`を`disabled`にし、演出終わったら`enabled`にする処理をスクリプト側に記述する。
* メリット：演出は今まで通りに変わらない
* デメリット：ワープ中で失敗することはない

## 案2：演出の拡大率を最大1までにする
`WarpTile@bottle_in`や`WarpTile@bottle_out`の`Scale`を上限1までの設定に調整する
* メリット：当たり判定は今まで通り
* デメリット：演出はちょっと控えめになっちゃう


もともと今のこの大きくなるアニメーションは自分が実装したらか、個人的には案１推しています。
ワープ中当たり判定が起きないのも正直デメリットとして捉える必要もないかなって思います。
ワープに捕まって動けない状態でギミックに当たったりするとストレスにもなるので、
ワープ中一時無敵になるの全然ありだと思います。


@takasusuke @xiii111 
ということでお二人の考え方を教えてください。
よろしくお願いします

**Comment by takasusuke** [comment]
- ワープ演出中に失敗すると確かにストレスあるから当たり判定を切るのありな気がしてきた。
- （見た目がロジックに制限されるのも個人的にはあまり好きではない。）

なので案１に賛成です。

**Comment by xiii111** [comment]
@takesi0627 状況の整理ありがとうございます。とてもわかりやすいです。

個人的には `案 1` が良いかなと思いました。理由としては、
- 演出中に初めて衝突することは非常に稀（演出をするために WarpTile に移動するタイミングで大抵失敗するから）
- ワープ動作をしている際に、当たり判定しないことに大きな違和感はないし、ユーザーにとっては当たらないことは不快要素ではない
- 演出のダイナミックさを重視したい

**Comment by takesi0627** [comment]
コメントありがとうございます。
それでは `案１`で進めさせていただきます
