### ISSUE TITLE
木アイコンに各季節の何本目の木かがわかるようなデザインを設計

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1526]
## 経緯

ref: #1514 
季節の中の木の種類は分けないことにした（春は桜３本、夏はバナナ３本・・・）ため、
各木の見分けがつかなくなるので、デザインを考え直す必要がある。

## 詳細

案
1. 数字をつける
2. キャプションをつける（春の１、春の２....） 

## 完了条件

- [x] 上記デザインの資料作成
- [x] 議論＆結論のまとめ ( #1533 に記入する)

**Comment by takesi0627** [comment]
https://docs.google.com/presentation/d/17CXPEr6LFASsGYjAmOlDCIGc0lc_sNit4jcfQsisNKo/edit#slide=id.g11f22f5927a_0_107

**Comment by takesi0627** [comment]
数字のみに決定。
配置位置、大きさのバリエーションを作って議論する

**Comment by takesi0627** [comment]
| | Record | LevelSelect |
|--|--|--|
| 左上| <img src="https://user-images.githubusercontent.com/17778395/161575171-1acedf0a-6106-49f1-ae00-7297e884a66b.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161574935-c1d093f0-1b51-4816-bdf0-4119c0e737f3.png" width="300">|
| 右上 | <img src="https://user-images.githubusercontent.com/17778395/161575791-ee58de97-909d-4f90-8d83-0c1cc01e7afa.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161575899-ee6ad21a-168f-43d8-862f-16ab60a7a05b.png" width="300"> |
| 中央 | <img src="https://user-images.githubusercontent.com/17778395/161576257-32a14c81-f246-4a77-b3c5-84eda0d013f5.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161576339-957cf33a-8c38-4553-927a-aae5ffb27108.png" width="300"> |
| 左下 | <img src="https://user-images.githubusercontent.com/17778395/161577029-b65625de-e9b7-4583-8aa0-57490f25cac8.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161577125-0e70d435-29f9-4f18-b625-f9a16644055a.png" width="300"> |
| 右下 | <img src="https://user-images.githubusercontent.com/17778395/161577464-a4689c92-26e9-404a-a3a3-72ee38370b4d.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161577385-9b3c8633-ce7d-49a4-b4af-3a5bdc71ec62.png" width="300"> |

**Comment by takesi0627** [comment]
@takasusuke @xiii111 

配置箇所のパターンを作ってみました。
コメントお願いします。


個人的に `LevelSelect` では`中央`で、`Record`では`左下`か`右下`がいいと思っています。

**Comment by takasusuke** [comment]
記録画面では季節ごとにカテゴライズして表示するかもしれないけれど、ひとまず現状のUIで考えるならば、
LevelSelectと記録画面で同じアイコンを使う方がわかりやすいと思います。

右上に置く場合は、LifeAttributeの表示であったり、LINEなどの通知であったり、数字が変化しうる、という体験がユーザにあるのではないか、と思いました。なのでこの場合は不適に感じました。

左下は、理由はわからないが単純に見慣れていない、という印象を受けました。

左上と右下ですが、左上の場合は、「１- 春」、「２ - 春」という感じがしました（あくまで右下に比べて）。
「春 - １」、「春 - ２」という印象を与えるのは右下と感じました。

右下と中央ですが、特に伝わり方に関しては優劣はないと感じました。
StageSelectSceneではアイコンの中央に数字を配置しているので、中央に置くことで統一感が向上し、結果として数字が増えるほど難易度が上がるといったことが示唆されると思います。
（統一感という目的ならば、数字のフォントとかもStageSelectScene揃えるべき、という話になりそう）
右下に置くと、その効果は薄れるかと思います。木ごとの難易度はあくまで目安かと思うので（星の個数などでユーザに伝わる形にしていない）、わざと薄めるのも手だと思います。

中央に置く場合、背景の木が見えなくなるという懸念をMTGでも話しましたが、特に懸念しているのはSummerです。
Summerでの見え方を見せていただけないでしょうか。
https://drive.google.com/drive/u/0/folders/1Fp2BtTTUxVdVCpvNNJVO7b_rNawE26Qw

**Comment by takesi0627** [comment]
| | Record | LevelSelect |
|--|--|--|
| 左上| <img src="https://user-images.githubusercontent.com/17778395/161989160-9b907cd9-8feb-4488-a96c-9b8c4cc0819b.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161989887-f85832c8-4eb4-45ba-bd2c-614cdb3d23dc.png" width="300">|
| 右上 | <img src="https://user-images.githubusercontent.com/17778395/161989019-90a4684b-7fc8-42b8-90dc-4db7813a126d.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161990256-3a9094e9-34cc-4ec7-993b-0e27fb99bdbf.png" width="300"> |
| 中央 | <img src="https://user-images.githubusercontent.com/17778395/161988609-5d489589-8172-40e0-a05d-1133f374c0f8.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161989794-ae0856a1-e06f-42c5-bc96-215812741e84.png" width="300"> |
| 左下 | <img src="https://user-images.githubusercontent.com/17778395/161988745-dfbc194c-512a-4830-a353-5ac4e7f3e0ea.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161990023-57139476-d489-40ff-8793-23421f292ab0.png" width="300"> |
| 右下 | <img src="https://user-images.githubusercontent.com/17778395/161988926-e4bee2fc-65ce-4167-b46e-29ea01eef992.png" width="300"> | <img src="https://user-images.githubusercontent.com/17778395/161990091-ac771d73-7e7a-4d20-a89a-74bc70c89c84.png" width="300"> |

@takasusuke 
夏の場合を作ってみました。どうでしょうか

**Comment by takesi0627** [comment]
* 位置は左上に決定
* ステージ選択画面に関しては数字＋木のアイコンを左上に置く

`TODO`: 数字１、２、３をブラッシュアップして提出

**Comment by takesi0627** [comment]
このフォントを使ってイメージを作成した（権利表記不要）
http://modi.jpn.org/font_memoir.php

| 1 | 2 | 3 |
|--|--|--|
| ![LevelIcon_Number_1](https://user-images.githubusercontent.com/17778395/162583718-4d541da6-d86f-43d3-a4ac-e5b45b425db7.png) | ![LevelIcon_Number_2](https://user-images.githubusercontent.com/17778395/162583787-85cd774b-1fbe-4f37-bc41-2a029fc044a4.png) | ![LevelIcon_Number_3](https://user-images.githubusercontent.com/17778395/162583728-3de6783f-926e-4bed-8454-08a4b7391b55.png) |

| LevelSelect | Record |
|--|--|
|![image](https://user-images.githubusercontent.com/17778395/162583671-ed7a0727-6cdb-4e13-b80a-dd0b9955f982.png)|![image](https://user-images.githubusercontent.com/17778395/162583692-6058cdb8-5dd9-45c6-a60f-a566090a2c8a.png)|

**Comment by xiii111** [comment]
@takesi0627 良さそうです！

@takasusuke @takesi0627 今回のタスクでは勿論対応しないんだけど、Treevel の世界観がやや暗め、という設定になっていた気がするのですが、通常時のフォントや今回のフォントなど、ややポップ寄りになっている気がする。ロゴが完成した時にまた考えれば良い気がするが、皆的にどう思うかあったら教えてほしい

**Comment by takesi0627** [comment]
以上で決定します。

**Comment by takesi0627** [comment]
#1533 に要件を記入しましたのでクローズします
