### ISSUE TITLE
記録画面の各レベル（木）の表示のレイアウト設計

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1531]
## 経緯

ref: #1514 
記録画面各木の進捗は現状以下の問題がありますので改善するためデザインを再設計する
* 木の本数が４本固定になっている
* 木の見分けがつかない
 
## 詳細

記録画面の下記画像の赤い枠の部分のデザインを考え直す
![image](https://user-images.githubusercontent.com/17778395/160413255-bc33941b-296e-4d58-948c-459a3a60642e.png)

## 完了条件

- [ ] 対象部分のデザインの提案
- [ ] #1532 に詳細仕様を記入する

## 備考
挑戦回数はともかくフリック回数は6桁欲しい。

**Comment by takasusuke** [comment]
#1526 を多少待つ。
4本以上の木の見せ方は先に考える。

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
記録画面の再設計をしました。レビューお願い致します。

**Comment by xiii111** [comment]
@takasusuke コメントしました！！

**Comment by takasusuke** [comment]
#1532 で実装します。
ありがとうございました。

<img width="309" alt="スクリーンショット 2022-04-18 2 21 06" src="https://user-images.githubusercontent.com/26213141/163725735-09f3deee-6f6a-4375-a9e4-b5946a0d704c.png">
