### ISSUE TITLE
記録画面の各レベル（木）の表示の実装

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#1532]
## 経緯

ref: #1514

## 詳細

- 草案資料に基づいてMenuSelectScene/Recordのレイアウトを修正する
- #1533 の木の見た目を記録画面にも適用する

## 完了条件

- [ ] ヘッダー部分の色を変える
- [ ] ヘッダー部分の上部をヘッダー部分と同じ色で埋める
- [ ] ヘッダー部分の画像の解像度を小さくし過ぎているので、素材の大きさまで戻す
- [ ] 挑戦回数、フリック回数の要素の高さを調整(小さく)する
- [ ] 挑戦回数、フリック回数の桁数を1桁増やす
- [ ] 解放状態、実装状態に応じた木の見た目を実現する
- [ ] スクロールできるようにする

## 備考
[草案資料スライド](https://docs.google.com/presentation/d/1G8RCmslSrFWflZTCeR6NwjoUqvMgE6FNW3Rg-uqsMMI/edit#slide=id.g121e6487277_0_0)

以下のことはここでは実装しない
- [ ] 解放(未クリア)状態、クリア状態、完全クリア状態の違いがわかるような見た目を実現する

草案
<img width="309" alt="スクリーンショット 2022-04-18 2 21 06" src="https://user-images.githubusercontent.com/26213141/163725469-3179b89c-dd54-4429-8bb9-44df4eea203e.png">

未解放、未実装の木の見た目
<img width="211" alt="スクリーンショット 2022-04-18 2 22 00" src="https://user-images.githubusercontent.com/26213141/163725492-07721242-9305-453c-9d7c-b7b712c10de7.png">

**Comment by takasusuke** [comment]
ついでにやりたいこと
- フリック、挑戦回数の表示桁数を5から6桁に増やす
- 上部の「日数」とかの画像の解像度を小さくしすぎて、ギザギザしているので元画像の大きさに戻す
- 上部の「日数」とかの画像より上を全て同じ色（紺色）で埋める

**Comment by takasusuke** [comment]
クリア数のテキストの色も季節依存にする
