### ISSUE TITLE
アプリ内レビューを適切なタイミング・頻度で表示するようにする

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1538]
## 経緯

#1327 で `レビューを投稿` ボタンを押下した際に、アプリ内レビューを出そうとしていたが、[公式ドキュメント](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/3566727-requestreview) を読むと、以下のような記述があった。

> Although you normally call this method when it makes sense in the user experience flow of your app, App Store policy governs the actual display of a rating and review request view. Because this method may not present an alert, it isn’t appropriate to call [requestReview()](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview) or requestReview(in:) in response to a button tap or other user action.

つまり、アプリ内レビューが表示されるかは、確定的ではないので、ボタンタップなどに呼応してアプリ内レビューを表示させようするのは適切ではないということだった。では、どのようなポリシーで出すのが良いかというと、

- アプリに習熟する十分な時間を与えた後でレビューを要求する
- ユーザーが大事なタスクを処理してるときにレビューを要求しない
- しつこくダイアログを出さない

のようである。原則としては、「アクションの終了」のようなので、ゲームをクリアした後に特定の頻度で出す、なども良さそうである。アプリ内レビューは、ユーザーから簡単にレビューをもらえる貴重な機会なので、ぜひ出したい

## 完了条件

- [ ] アプリ内レビューを出すタイミング・頻度を決める
- [ ] 上記を実装する

**Comment by xiii111** [comment]
# タイミング・頻度を決める

## 公式の参考資料
https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/ratings-and-reviews/

> **Ask for a rating only after the user has demonstrated engagement with your app.** For example, prompt the user upon the completion of a game level or productivity task. Never ask for a rating on first launch or during onboarding. Allow ample time to form an opinion.

ユーザーが生産的なタスクを完了させたときに評価を求める。また、評価を求めるまでに十分な時間をあける

→ **何回か遊んだ後のゲームクリア時などを狙う**

> **Don’t interrupt the user, especially when they’re performing a time-sensitive or stressful task.** Look for logical pauses or stopping points, where a rating request makes the most sense.

時間に敏感なタスクやストレスの多いタスクの実行中には、評価を求めない

→ **当然、ゲーム中などには評価は求めない**

> **Don’t be a pest.** Repeated rating prompts can be irritating, and may even negatively influence the user’s opinion of your app. Allow at least a week or two between rating requests and only prompt again after the user has demonstrated additional engagement with your app.

繰り返しの評価依頼には十分な時間（少なくとも 1 ~ 2 週間）をあけ、追加のエンゲージメントがあったときに行う

→ **時間的な頻度も考えて設計し、単調な繰り返し依頼はやめる**

> If the user hasn't already given feedback, the system displays an in-app prompt that asks for a rating and an optional written review.

評価をしてくれたユーザーには表示されない

→ **ボタンなどをトリガーにすることはできない**

> (In Settings, the user can also opt out of receiving these rating prompts for all apps they have installed.) 

設定からアプリ内レビューを完全にオフにすることができる

→ **ボタンなどをトリガーにすることはできない**

> The system automatically limits the display of the prompt to three occurrences per app within a 365-day period.

年に 3 回までしか、アプリ内レビューが表示されることはない

→ **ボタンなどをトリガーにすることはできない。また、年に何回も評価依頼をするような設計にしても、意味がない**

## 要は
- ステージや木のクリア時など、エンゲージメントが高いと思われるタイミングを狙う
- 初回の表示は、何回か遊んだ後にする
- 初回以降の表示は、時間的には 1 ~ 2 週間くらい開ける頻度にする
- 初回以降の表示は、追加のエンゲージメントがありそうなタイミングを狙う
- 年に 3 回しか表示されないので、3 回表示されれば良いくらいの気持ちで丁寧に設計する

## 提案
1 回目: **5 ステージクリアしたら**
- ある程度の回数にしたいが、沢山ステージを遊んでくれるユーザーは少なさそうなので、5 ステージクリアの段階で依頼してしまう。友人などであれば、基本的に 5 をつけてくれると思うので、その辺を狙いに行く。

2 回目以降: **次の季節の木が解放されたら**
- 1 回目でレビューをしてくれなかった人達には、追加のエンゲージメントがありそうなタイミングを狙いたいので、次の季節の木の解放演出が終わった後にしたい。単純に木のクリア時にしない理由は、ユーザーが木をクリアしたと認識できないから。演出などがあった後では、解放されたということが伝わり、よりエンゲージメントが高い状態になると考えられる。また、次の季節に限らず木の解放演出が終わった後にしないのは、レビュー依頼が高頻度だと思われるから。この条件にすると、最大でも 3 回のレビュー依頼になってしまうが、年に 3 回しか提案されないので十分と考える

**Comment by xiii111** [comment]
@takasusuke @takesi0627 上記の内容を一通り読んでいただき、`提案` の内容が適切かをレビューください🙏

**Comment by takesi0627** [comment]
提案について基本的に同意しますが、もうちょっと具体的に決めてほしい。
例えば、1回目のステージクリア後は
* クリア直後（成功ポップアップが出た後）
* ステージクリア演出後（ステージ選択に戻って次のステージの解放演出が終わった後）

など、いくつかのタイミングがあるはずです。
その可能性もうちょっと絞ってから実装に移す時は楽だと思います。

ちなみに2回目以降については
個人的に解放演出が終わった後、
次の木のステージ選択画面に入る時に出すのがいいと思っています。

**Comment by takasusuke** [comment]
> 1 回目: 5 ステージクリアしたら
脈絡がないように感じました。
傷ステージを1つクリアしたタイミングの方が納得感あるのではないでしょうか。(BGMが変わるので、一息ついた感もありそう。)

> 2 回目以降: 次の季節の木が解放されたら
同意。

**Comment by xiii111** [comment]
@takesi0627 

> 提案について基本的に同意しますが、もうちょっと具体的に決めてほしい。

おけです！

> ちなみに2回目以降については
個人的に解放演出が終わった後、
次の木のステージ選択画面に入る時に出すのがいいと思っています。

解放が終わったタイミングが一番クリアをして満足している状態です。なので、解放後にすぐに行くかわからない次の木のステージ選択画面に入るときにするのは微妙だと思っています

**Comment by xiii111** [comment]
@takasusuke 

> 脈絡がないように感じました。
傷ステージを1つクリアしたタイミングの方が納得感あるのではないでしょうか。(BGMが変わるので、一息ついた感もありそう。)

完全に採用 ...！

**Comment by xiii111** [comment]
## 提案 2nd（WIP）
### 1 回目: 初めて傷ステージをクリアしたら

本当はある程度の期間を空けてから依頼したいが（例えば、最初の木をクリア、など）、沢山のステージを遊んでくれるユーザーばかりではないので、初めて傷ステージをクリアしたら（最短で 4 ステージ目をクリアしたら）依頼してします。友人などであれば、基本的に 5 をつけてくれると思うので、その辺を狙いにいきます

より具体的なタイミングですが、初めて傷ステージをクリアして、成功ポップアップが表示されたタイミングで、依頼するための関数を呼ぼうと思っています

<img width="325" alt="スクリーンショット 2022-04-14 14 53 15" src="https://user-images.githubusercontent.com/26104258/163322567-5fc7c0e6-ed21-4fd7-8c40-cd4020f19a23.png">


### 2 回目以降: 次の季節の木が解放されたら

1 回目でレビューをしてくれなかった人達には、追加のエンゲージメントがありそうなタイミングを狙いたいので、次の季節の木の解放演出が終わった後にしたい。単純に木のクリア時にしない理由は、ユーザーが木をクリアしたと認識できないから。演出などがあった後では、解放されたということが伝わり、よりエンゲージメントが高い状態になると考えられる。また、次の季節に限らず木の解放演出が終わった後にしないのは、レビュー依頼が高頻度だと思われるから。この条件にすると、最大でも 3 回のレビュー依頼になってしまうが、年に 3 回しか提案されないので十分と考える

**Comment by xiii111** [comment]
@takasusuke @takesi0627 https://github.com/LITO-apps/Treevel-client/issues/1538#issuecomment-1098736569 で案を洗練させました。レビューお願いします！

**Comment by takasusuke** [comment]
同意！

**Comment by xiii111** [comment]
@takesi0627 の返信も待とうと思います！

**Comment by takesi0627** [comment]
タイミングについては意義なし。

> 解放されている季節が n ( `n = {2, 3, 4}` ) 以上 && n 回目の `RequestStoreReview()` をまだ呼んでいない状態（PlayerPrefs でフラグを持ちます）で、`LevelSelectScene` において道を解放する演出が終わった後に `RequestStoreReview()` を呼ぼうと考えています。

`RequestStoreReview`は、レビューした人であれば、自動的にスルーする仕込みじゃなかったっけ？
その認識が合っていれば `PlayerPrefs`で別でデータを持つ必要はなさそうですが、どうでしょうか

**Comment by xiii111** [comment]
@takesi0627 

> `RequestStoreReview`は、レビューした人であれば、自動的にスルーする仕込みじゃなかったっけ？

はい

> その認識が合っていれば `PlayerPrefs`で別でデータを持つ必要はなさそうですが、どうでしょうか

ここで対応したいのは、レビュー依頼したかどうかの判定であって、レビューを実際にしたかどうかではないです！

**Comment by xiii111** [comment]
確かに解放演出が実際に行われたら、の後に実装すれば PlayerPrefs は不要ですが `CheckReleaseNewLevelAsync` が呼ばれた後に単純に呼ぶ方が実装が複雑にならなさそうなので、フラグを持ってしまった方が良いかなぁと考えていました

**Comment by xiii111** [comment]
こちら実装ベースで話すでもよければ、PR のレビュー時に意見をもらった方が、わかりやすいと思いますがどうでしょうか？実際に実装してみたら、PlayerPrefs は不要だった ... ということもありそうです

**Comment by takesi0627** [comment]
そうですね！
実際持っているかどうかもそんなクリティカルの問題ではないので閉じていいと思います

**Comment by xiii111** [comment]
あ、このタスクは feature なので、実装もこのタスクでやります！

**Comment by takesi0627** [comment]
なるほど、じゃあ実装よろしくです！
