### ISSUE TITLE
太陽光ギミックの実装

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#1547]
## 経緯
失敗要素となるギミックの追加を行い、ゲームの幅を広げるため

## 詳細
素材に基づくデザイン適用
アニメーション実装

## 完了条件

- [ ] Particle
- [ ] Animation

## 備考
https://drive.google.com/drive/u/0/folders/1Rxi9MExV-6BtHms6sm1nSuxqjO0u7QgN

**Comment by xiii111** [comment]
重複なのでクローズ
