### ISSUE TITLE
ステージ解放アニメーション中のプログレスバーの表記がおかしい

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1555]
## 概要
- ステージ解放アニメーション中のプログレスバーの表記がおかしい

## 再現手順
1. ステージの開放先があるステージをクリアする
2. ステージが開放される
3. 開放されている間のプログレスバーの表記がおかしい

## 期待動作
- 開放されている間のプログレスバーの表記が正常になっている

## キャプチャ
https://user-images.githubusercontent.com/26104258/164228980-a3e8635d-a6c0-47ca-be7f-8e890db934fc.mp4

## 発生環境
- develop ブランチ

## 備考
- #1556 の動作を変えてしまわないことに注意する（= 初めて結晶ステージをクリアし、StageSelectScene で諸々のアニメーションが全て終わった後に、アプリ内レビューが表示される）

**Comment by takasusuke** [comment]
アニメーション前のState反映とアニメーション後のState反映を行う。
