### ISSUE TITLE
隕石が落ちる場所でない位置にいるボトルに衝突することがある

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1570]
## 概要
- 隕石が落ちる場所でない位置にいるボトルに衝突することがある

## 再現手順
- 確定再現の手順が見つからなかったが、平面上では重なっているように見えるときに衝突していそう

## 期待動作
- 隕石が落ちる場所でない位置にいるボトルには衝突しない

## キャプチャ
<img width="330" alt="スクリーンショット 2022-05-05 10 19 29" src="https://user-images.githubusercontent.com/26104258/167229170-62fcbc6a-6a61-4a8d-a97a-6cb433954285.png">

## 発生環境
- develop

**Comment by takasusuke** [comment]
developにて報告通りの現象が起きることを確認。

https://user-images.githubusercontent.com/26213141/167431031-8d0a4274-1387-4b9b-a083-17a0cc9c1a54.mov
