### ISSUE TITLE
[実機] アプリが `Background` に行くと、固まることがある

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1595]
## 概要
- 実機でアプリが `Background` に行くと、固まることがある

## 再現手順
1. 実機でアプリを `Background` に移動させる
2. アプリに戻ってくる
3. アプリが固まることがある

## 期待動作
- アプリが固まらない

## 備考
- どこから発生しているかを調べる
- どのような環境で発生するかを調べる（Editor、Simulator、実機）

**Comment by xiii111** [comment]
📝 #1587 のついでに確認したが、問題が発生していなかった。プロファイラを見る設定にしていたからかもしれない

@takasusuke #1587 の確認をする際に、現象が再現しているかを確認していただけませんか？

**Comment by xiii111** [comment]
サウンドのレビューするよね？その時に実機にビルトするはず。その時のバージョン

**Comment by takasusuke** [comment]
了解

**Comment by takasusuke** [comment]
Xcodeでbuildできなかった...([Slack参照](https://lito-apps.slack.com/archives/CBVRTRRBK/p1653488155767019))
できるなら来週の火曜までXcode上げたくないので待ってもらえん...?

**Comment by xiii111** [comment]
まつ

**Comment by xiii111** [comment]
@takasusuke ping

**Comment by takasusuke** [comment]
macOS上げ中

**Comment by takasusuke** [comment]
現象再現していませんでした！！

**Comment by xiii111** [comment]
感謝です！
