### ISSUE TITLE
不定タイミングで CRI 周りのエラーが出る

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1655]
## 概要
- 前から起きていたが、不定タイミングで CRI 周りのエラーが出る

## 再現手順
- 起動したタイミングを含め、不定のタイミング。確定再現をさせることはできない

## 期待動作
- CRI 周りのエラーが出ない

## キャプチャ
<img width="803" alt="スクリーンショット 2022-06-23 9 17 23" src="https://user-images.githubusercontent.com/26104258/175181600-27afe78e-1a14-46e3-b41a-daf7f473d3ec.png">

<img width="798" alt="スクリーンショット 2022-06-23 9 17 33" src="https://user-images.githubusercontent.com/26104258/175181614-67242cdc-3e8e-423d-8306-6f47d1bfa39c.png">

<img width="830" alt="スクリーンショット 2022-06-23 9 17 41" src="https://user-images.githubusercontent.com/26104258/175181622-8de27763-a309-4bad-ab0b-4ccd2d289131.png">

<img width="723" alt="スクリーンショット 2022-06-23 9 22 17" src="https://user-images.githubusercontent.com/26104258/175181887-0e051e51-17d2-4edd-8656-c6b3ee295622.png">

## 発生環境
- develop

**Comment by takesi0627** [comment]
📝 CriWareLeStub.cs:62 の `CriFsPlugin.criFsUnity_Initialize();`を2回連続呼び出した場合のエラーメッセージ。これじゃなさそう

![image](https://user-images.githubusercontent.com/17778395/176321959-53a12d1f-8da8-4ed1-836a-76fa7172b428.png)

**Comment by takesi0627** [comment]
@xiii111 
調査したいですが、普段 `Atom Browser` 開いていますか？
（もしくはどこかにドッキングしているか）

**Comment by xiii111** [comment]
普段は全く開いていません

**Comment by takesi0627** [comment]
再現パターンを見つかりました。

1. なんらかのエラーでエラーポップアップを開く
2. `Return To Title`を押してタイトルに戻る
3. エラー発生
