### ISSUE TITLE
投稿ボタンの動作確認をする

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#203]
## 終了条件
- iOS で投稿ボタンを押すと，共有画面が出る
- Android で投稿ボタンを押すと，共有画面が出る
- 共有画面から無事ツイートできる

**Comment by xiii111** [comment]
アプリのエミュレータで実行可能にした後に，検証できる
https://github.com/LITO-apps/Treevel-client/issues/206
https://github.com/LITO-apps/Treevel-client/issues/204

**Comment by xiii111** [comment]
@takasusuke @takesi0627 
　いろいろ調べたところ，今使っているパッケージ（[SocialConnector](https://github.com/anchan828/social-connector)）は2年間更新されておらず，新しい OS（AndroidOS，iOS） への追従が甘く，問題が指摘されているので，使わない方が良いと思い始めた．となったときに現状，実装コストが高くなく，安定している，画像を添付してツイートできるサービスは見つけられない．Twitter API も検討したが，実装コストが高いように感じた．
なので，一旦画像を添付できるようにするタスクを後に回して（必須機能ではないし，今後便利なサービスが生まれるかもしれない）テキストとハッシュタグのみをツイートできる機能に戻そうと思うのだけど，良いかな？

**Comment by xiii111** [comment]
上記のようになった場合，このタスクを閉じて以下のようなタスクを今週やる

#### 投稿機能から画像添付を削除する
終了条件：
- SocialConnector の利用をやめ，テキストとハッシュタグのみを Twitter で投稿できるようにする
- iOS，Android のエミュレータ（iOS は実機にするかも）でも正常に動作することを確認する

結局実機で確認するコストがあるので，ラベルは `4` をつけると思う

**Comment by xiii111** [comment]
また，以下のタスクを追加する（すぐにやるつもりはない）
#### Twitter にスクリーンショットを添付して投稿できるようにする

**Comment by takesi0627** [comment]
了解、いいと思います。

**Comment by takasusuke** [comment]
まる

**Comment by xiii111** [comment]
上記参照．さよなら
