### ISSUE TITLE
アニメーションデータベースの導入

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#217]
起動時にすべてのアニメーションを読み込んで、
必要なときにデータベースから取ってくる仕組みを作る。

### いいと思ったところ：
* 同じアニメーション使うところが多いからAnimationClipの実体を一つだけになるのはメモリ節約できる
* いちいちプレハブにアニメーションをアタッチする作業がめんどくさい。

### 懸念：
* `Animation.Play` の実装がわからないから、もし同じ `AnimationClip` 実体を再生する実装になってるなら、同じクリップを参照しているオブジェクトが一斉再生される可能性あるかもしれないが、実際やってみないとわからん。

**Comment by xiii111** [comment]
Addressableでなんとかする（ @takesi0627 が）
