### ISSUE TITLE
Addressable Asset System の導入

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#254]
- https://blogs.unity3d.com/jp/2019/07/15/addressable-asset-system/
[Addressable Assets Systemを完全に理解する](https://qiita.com/k7a/items/b4fd298bcb64dc968ad1)
[試しにやってみた（Qita）](https://qiita.com/kamihiro/items/3e9876bd4e4462a57d1d)

AssetBundle以降を使うメリットとして、コンテンツの更新があるときに（ステージの追加など）、ユーザーはアプリの更新せず、動的にダウンロードすることができる（その場合、サーバーを用意することになるだろう）。議論してほしいでけで、別に現状に文句あるわけではない。ただこれから画像などのアセットが多くなると思うし、もし動的なコンテンツの読み込みをやりたいんだったら今からフレームワークを作っておいた方がいいもしれない。

**Comment by takesi0627** [comment]
終了条件：
#298 #331 閉じる
