### ISSUE TITLE
メインカラー、サブカラーを提案する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#258]

**Comment by takasusuke** [comment]
カラーカタログを表示する
ダミーのオブジェクトをその色で塗って表示する

**Comment by takasusuke** [comment]
2020/2/16　現時点での案を
https://drive.google.com/drive/folders/1LXntznB0tvtw2BDysKX3I4T3-jJiueZH
にあげました。
赤系、青系の色案も上げる予定です。

**Comment by takasusuke** [comment]
赤系、青系の色案を上げました。

**Comment by takesi0627** [comment]
個人的に2番目が一番このアプリに似合ってると感じた。

このタスクとは関係ないけど、ロゴについてですが、グラディエントがない案も作ってもらってもいいですか？なんかシンプルで色そんなに鮮やかじゃないやつが見たい

**Comment by xiii111** [comment]
ロゴ以外を除けば，Color2かな！
このタスクのゴール地点どうしようか

**Comment by takasusuke** [comment]
第一候補はcolor2のような配色。
色は緑系統。
差し色は黄色系統。
背景はもう少し明るくても良い(伴ってメインカラーはもう少し鮮やかにするかも)。
ウィンドウは割と良い色。

**Comment by takesi0627** [comment]
![#32a876ff](https://placehold.it/15/32a876ff/000000?text=+) `#32a876ff `
