### ISSUE TITLE
パネル画像を切り取り、使える形にする

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#260]

**Comment by takasusuke** [comment]
切り取って、適切な命名規則でgoogle driveにあげる。

**Comment by takasusuke** [comment]
https://drive.google.com/drive/folders/1B1_Wl6X2jHfHyoXR9Q5FFbif0YE9oXFq
(/Treevel/GamePlayScene/Panel/Test_NormalPanel66x66.png)
に画像を置きました。
画像外側は透明、画像内部はすべて不透明です。
66x66は横66pt, 縦66ptです。

画像へのpathと、命名規則(本番の画像だと`Test_`は付けません)の確認、画像の確認してもらって問題なければ閉じます。

**Comment by takesi0627** [comment]
画像の解像度はどうやって決めていますか？
66だとなんか足りない気がするんだけど大丈夫でしょうか？

**Comment by takasusuke** [comment]
理解が深まり上げなおしました。
https://drive.google.com/drive/folders/1B1_Wl6X2jHfHyoXR9Q5FFbif0YE9oXFq
(/Treevel/ios/GamePlayScene/Panel/Test_NormalPanel@2x.png, Test_NormalPanel@3xpng)

画像の解像度は、44(px)(androidの基準だと48(dpi)に対応)が１つの指標です。
人間が押しやすい最小のボタンの大きさが44(px)です。
これを基準に44の倍数、もしくは11の倍数でpxを決めることが多いです。

今は画面の解像度が大きくなっているので、同じ大きさで表示するために、88(px)必要なデバイスと132(px)必要なデバイスが多いです。（44(px)のデバイスはもう無い）
なので、ドライブに上げたように、`@2x`, `@3x`と名付けて別に用意する必要が有ります。
(この名前にしておけばデバイスの解像度に合わせて勝手に対応するリソースを読み込むとか書いてあった気がするけどまだわかっていない)

今回もらったデータは、サイズを指定したわけではなく、とりあえずもらったものをテスト用に切り取っただけで、元の絵があまり大きくありません。
なので、大きいサイズの絵をあらかじめ保存しようが、このサイズのものを実装で拡大しようが変わりないです。
とりあえず、元の絵をそんなに大きくしない程度で、かつ、ちょうどよいpx数で保存しました。

たぶん小さい。

**Comment by takesi0627** [comment]
素晴らしい！

**Comment by xiii111** [comment]
`@2x` = 88(px)
`@3x` = 132(px)
を示していて，この`@?x`にしておけば，なんか良いことが起こるらしいからこの名前にしているってことで良いですかね！よければオッケーです！

**Comment by takasusuke** [comment]
- `Test_NormalPanel@1x.png`も上げました。

**Comment by takasusuke** [comment]
`@2x = 88(px)`
`@3x = 132(px)` であってます。
ベクター画像だったら１サイズの画像用意すれば勝手に2倍、3倍の画像を用意してくれるxcodeの機能があって、それで自動で作られる名前がこれららしい、けどそれが命名として慣習になってるっぽい
（もしかしたら恩恵ないかもだけど、ビルドのときとかにきっと良いことがありそうな気がするのでこの名前にしています）
