### ISSUE TITLE
デザインスケジュールを決める

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#261]

**Comment by xiii111** [comment]
- お願いする画像などのスケジュールを決める

**Comment by xiii111** [comment]
必要になりそうな画像
- 各種アイコン
- 銃弾
- タイル
- パネル
- 警告
- ボタン など

**Comment by takasusuke** [comment]
必要な画像の洗い出しを行いました
2ヶ月毎のスケージュールを大雑把に立てました。

https://scrapbox.io/treevel/%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%B1%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB

なんか引くほど総量あったので、デザイン担当さんにコメントいただこうかと思います。

**Comment by takesi0627** [comment]
> 銃弾じゃなくするのは決まったけど、何にするか決めてなかった。（cartiridgeとhole１つずつ）

これは、竜巻など、どういう自然現象かは決めてなかったという意味ですか

**Comment by takasusuke** [comment]
> > 銃弾じゃなくするのは決まったけど、何にするか決めてなかった。（cartiridgeとhole１つずつ）
> 
> これは、竜巻など、どういう自然現象かは決めてなかったという意味ですか

そうです

**Comment by takasusuke** [comment]
リリース前の機能の洗い出しを受けて、デザインスケジュールを更新しました。

https://scrapbox.io/treevel/%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%B1%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB

足りない部分や、不明瞭な部分の指摘を受けて、
かつ、デザイン担当さんの感想いただいてそれを出来れば共有したら、このイシューは閉じる予定です。

**Comment by xiii111** [comment]
これはまだ無理そうかな？

**Comment by takasusuke** [comment]
- 素材をお願いするわけですが、全体のレイアウト等を考慮して統一感持ってデザインを行う必要があるので、課金画面などの新たな画面やポップアップ画面などあやふやにしていた画面の機能、レイアウトを先に決めたいと思います
(アイデアに記しました、イシューになればそのリンクをコメントに追記します)
(ゲーム画面までの動線のレイアウトはある程度決まっているので、とりあえずそこから素材はお願いしますが、2ヶ月後の次のマイルストーンまでこれらの画面のレイアウトが決まっていないのは良くない)

- ボトルの素材を実際の画面に配置してみて色合いとか変更したい部分があるかもしれない、ということなのでゲーム画面までのボトル配置のイシュー、#322 (あと#325 もかもしれない) を優先的にやってもらえませんか？(今週のタスクは決めちゃったので、せめて来週とか)

- 素材をお願いする流れ
1. こちら側で、絵(下書き)および言葉で素材をお願いする
2. モチーフの案をいただいて、それに対してやりとりを行う
3. 清書した素材をいただく
4. 実際に画面に配置して修正を行う
という流れになると思います。なので、各素材に対して、下書きを作って、やりとりして、配置する、というところまでで1つのイシューにしていくのが良いと思いました。
(この流れは2週間くらいかと思います。いくつかの素材を並行してお願いすると思います。)

**Comment by takasusuke** [comment]
@xiii111 , @takesi0627 
2人にも読んでもらい、アイデアに書いたものをイシューにするならして閉じます

多分このレイアウトとか自分がやるんで、バグ修正とかの優先度低そうなの今回のマイルストーンから外すかも

**Comment by takesi0627** [comment]
> * ボトルの素材を実際の画面に配置してみて色合いとか変更したい部分があるかもしれない、ということなのでゲーム画面までのボトル配置のイシュー、#322 (あと#325 もかもしれない) を優先的にやってもらえませんか？(今週のタスクは決めちゃったので、せめて来週とか)

僕も早めにやりたいので大丈夫です

**Comment by takesi0627** [comment]
> 素材をお願いする流れ
こちら側で、絵(下書き)および言葉で素材をお願いする
モチーフの案をいただいて、それに対してやりとりを行う
清書した素材をいただく
実際に画面に配置して修正を行う
という流れになると思います。なので、各素材に対して、下書きを作って、やりとりして、配置する、というところまでで1つのイシューにしていくのが良いと思いました。
(この流れは2週間くらいかと思います。いくつかの素材を並行してお願いすると思います。)

これはScrapboxに書いといた方がいいかも？

**Comment by takasusuke** [comment]
@takesi0627 コメントどうもです。
- #322, #325 のタスク優先的にやってくれる件どうもです
- 素材お願いの流れはScrapboxに記述しました

**Comment by xiii111** [comment]
読みました．
後，アイデアの note は今週のミーティングの時にきちんとイシューにしましょう．

ところで，スケジュールを決めるというタスクはどこかで作り直しますか？

**Comment by takasusuke** [comment]
次のミーティングまでに、直近の1ヶ月で頼みそうなもの毎に`[タイル画像を配置する]`みたいにアイデアに入れておくので、それをイシューに入れようかなと。
(マイルストーンと同じ2ヶ月ではなく、とりあえず1ヶ月のスケジュールでやってみて、時間感を修正する)

それ以降も、ミーティングのタイミングで頼むものをイシューにすれば良いかと。

**Comment by xiii111** [comment]
そこまで固まってるなら大丈夫ですね．ミーティングごとのTODOをきちんと定義して（毎回Slackにわざわざ投稿している），そこにデザインスケジュールの打ち合わせ（考慮？）を組み込みましょう

**Comment by takasusuke** [comment]
細かいデザインスケジュール
https://scrapbox.io/treevel/%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%B1%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB(%E7%B4%A0%E6%9D%90%E3%83%99%E3%83%BC%E3%82%B9)
