### ISSUE TITLE
記録画面のレイアウトを決める

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#262]
- 概要図を提出するまで

**Comment by xiii111** [comment]
レイアウトを決める際に，以下のイシューの選別もしてください
- https://github.com/LITO-apps/Treevel-client/issues/112
- https://github.com/LITO-apps/Treevel-client/issues/111

**Comment by takasusuke** [comment]
記録画面について、全てのステージの記録を一覧表示する難しさ、ユーザが得たい情報を見つける難しさから、一覧表示しない２つの画面を考えました。
１つは、ゲーム画面直前に記録を表示する画面です。
選択したステージに他ユーザがどれくらい挑戦していてどれくらいクリアしているのか、また、自分の記録がわかる画面です。
![record1](https://user-images.githubusercontent.com/26213141/76932280-e1be2080-692d-11ea-80b7-abf17b1ac396.png)

![record2](https://user-images.githubusercontent.com/26213141/76932289-e5ea3e00-692d-11ea-834c-d27253428c5c.png)

**Comment by takasusuke** [comment]
もう１つは、全ステージの情報をソートして並べる画面、そしてトロフィーのようなユーザのやり込み具合を表示する画面です。
挑戦回数でのソート、木のIDでのソートを考えています。
ステージ名だけでなくステージに出てくるギミックのアイコンや、他ユーザのクリア率も表示すれば、自分がどんなステージで苦戦しているのかなどわかるかな、と思います。
![record3](https://user-images.githubusercontent.com/26213141/76932522-7759b000-692e-11ea-95ca-8b855f973217.png)

こちらはやり込み具合のわかる画面です。
取得、未取得とかで表示分け等はあると良いかもしれません。
![record4](https://user-images.githubusercontent.com/26213141/76932535-7cb6fa80-692e-11ea-8558-54da1024bad0.png)

**Comment by takasusuke** [comment]
- 全体的にマリオメーカーのステージに表示されている、クリア率等を参考にしました。
- このゲームの難しいステージは、少ない回数でクリアするのではなく、何度も失敗してようやくクリアすることが多いと思うので、自分の挑戦回数が他ユーザの初クリアまでの挑戦回数を超えると途端にやる気がなくなると思います。そのため、他ユーザの初クリアまでの挑戦回数は表示していません。
- クリアタイムですが、極論を言えば、ギミックが登場するまでにパネルを全て並べれば良いので1秒かからずにクリアも可能だと思います。そうなるとクリアタイムで他ユーザと競うのは意味がないので、基本的なプレイでは他ユーザのクリアタイムは表示しなくても良いかな、と思います。例えばランダムに選択された10ステージのクリア時間を測るモードとかあるなら面白いとは思います。

**Comment by takasusuke** [comment]
議論のポイントは
- 表示する情報の選択(初クリアの挑戦回数やタイムなど)
- グラフのように全ステージを一覧表示する画面が無いこと
あたりです。

**Comment by takasusuke** [comment]
- 閉じるボタンをつける

**Comment by xiii111** [comment]
#111 #112 は閉じて，"グラフを用いた記録表示の検討" というイシューを立てておいて欲しいです．

**Comment by xiii111** [comment]
閉じないですか？これ

**Comment by takasusuke** [comment]
- 記録画面をSceneとして作るイシューを分割してたてました
- #111, #112 は閉じました
- グラフを用いた記録表示の検討、に関するイシューをたてました

閉じます
