### ISSUE TITLE
設定画面のレイアウトを決める

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#263]
- 概要図を提出するまで

**Comment by xiii111** [comment]
以下のイシューの内容を考慮，イシューの取捨選択も行ってください
- https://github.com/LITO-apps/Treevel-client/issues/102
- https://github.com/LITO-apps/Treevel-client/issues/103
- https://github.com/LITO-apps/Treevel-client/issues/105
- https://github.com/LITO-apps/Treevel-client/issues/106
- https://github.com/LITO-apps/Treevel-client/issues/107
- https://github.com/LITO-apps/Treevel-client/issues/109
- https://github.com/LITO-apps/Treevel-client/issues/181

**Comment by takasusuke** [comment]
- #103 #105 #107 のデザインを変更できるのはなくて良い気がしました。

**Comment by takasusuke** [comment]
レイアウト案1
縦スクロール

![Setting1](https://user-images.githubusercontent.com/26213141/76399089-61de0680-63c1-11ea-94a1-89b21a613d35.png)

**Comment by takasusuke** [comment]
レイアウト案2
#106 のアプリレビューのアイコンを入れ忘れましたが、Twitter、過去作と並置する。
スタッフのパネルは、ゲーム画面みたいに動かせる

![Setting2](https://user-images.githubusercontent.com/26213141/76399149-7de1a800-63c1-11ea-9a77-9ddcedcf8a25.png)

**Comment by takasusuke** [comment]
- 一旦レイアウト案2の方で画面を作る
- 戻る機能はボタンだけでなく、スワイプでも行えるようにする(今後の実装)

**Comment by takasusuke** [comment]
- 一旦、設定画面の機能実装のために配置するときは、アプリやTwitterへのリンクはなし、STAFF紹介もなしで良い。
