### ISSUE TITLE
データベーススキーマの定式化（提案）

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#264]

**Comment by takesi0627** [comment]
https://scrapbox.io/treevel/サーバサイド

ここで簡単に書いておきました。
疑問、アドバイスなどはこちらで議論しましょう。

**Comment by xiii111** [comment]
`playing_stage_id`はいるのかな．途中で落とした場合は失敗扱いで良いと思った．
`record`に挑戦した回数はあっても良いと思う

**Comment by takasusuke** [comment]
- アプリ落としたら失敗でいいと思うので、`playing_stage_id`は自分もまだ必要性が見えない。
- `record`にクリアしているかどうかの`bool`が必要と思います。

**Comment by takesi0627** [comment]
* アプリがクラッシュしたりするなど、思わぬ事情で落とした場合、失敗扱いだとユーザが不快に思えるのでそれを入れました。そこらへんの処理の必要性はやはりあると僕は思います。

* `record` について挑戦した回数のクリアしたかどうかのどっちかを記録するのは要検討

**Comment by xiii111** [comment]
アプリクラッシュの件は了解．
データベースに使う可能性があるものは全て用意して損はないからOK

挑戦した回数もクリアしたかどうかも両方必要ではあると思う

**Comment by takasusuke** [comment]
質問
- アプリクラッシュと、ユーザが自分でアプリ落とすのって区別できるの？
独り言(無視して良いです)
- 初クリアまでの挑戦回数って見たいという需要あるんかなあ（記録画面のレイアウトがあまり思いついてない）
- ステージ途中から再現って難しそう。。。（クラッシュしたらそれはノーカウント扱いにしたいなあ。。。笑）

**Comment by takesi0627** [comment]
> 質問
> 
> * アプリクラッシュと、ユーザが自分でアプリ落とすのって区別できるの？
> 
区別できないので、ちゃーでんみたいに、ホーム画面入るときに一回チェックしてもしプレイ中だったらポップアップ出して継続するかしないかをユーザに選んでもらう実装になると思う。

> 独り言(無視して良いです)
> 
> * 初クリアまでの挑戦回数って見たいという需要あるんかなあ（記録画面のレイアウトがあまり思いついてない）
採用


> * ステージ途中から再現って難しそう。。。（クラッシュしたらそれはノーカウント扱いにしたいなあ。。。笑）
むむ、確かに面倒そう、ノーカウント扱いはありだと思います。

**Comment by takasusuke** [comment]
理解しました

- クリアしたかどうか
- 初クリアまでの挑戦回数
- 挑戦回数
は全て記録して良いと思います

**Comment by xiii111** [comment]
議論を終えたので閉じます！
