### ISSUE TITLE
組織名・アプリ名の変更

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#266]

**Comment by xiii111** [comment]
## 変更内容
- 各種チーム名を LITO (or LITO-apps) に
- 各種アプリ名を Treevel に

## 変更箇所
- Github の Organization と Repository
- Scrapbox
- Slack
- Google Drive

@takasusuke @takesi0627 
他に変更できてないところがあったら教えてください．
なければ閉じます．

**Comment by takesi0627** [comment]
Appleの開発者アカウントは変えれる？

**Comment by xiii111** [comment]
@takasusuke が詳しく知ってるけど，確かちゃんと法人にしていないと，個人でしかアカウント作れないはず．だから法人でない今は， @takasusuke のアカウントをみんなで運用するしかない．

**Comment by takasusuke** [comment]
既に返答ありますが、Appleの開発者アカウントは個人アカウントを使っていて変えられないです。

他の部分の変更は全てされていると思います。

**Comment by takesi0627** [comment]
Appleアカウントについて了解です、閉じましょうか

**Comment by xiii111** [comment]
ありがたい！閉じましょう！
