### ISSUE TITLE
カンバン（Projects）をクライアントとサーバで分割

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#267]

**Comment by xiii111** [comment]
https://github.com/LITO-apps/Treevel-client/projects/2
の内容を
https://github.com/orgs/LITO-apps/projects/2
にコピーした．

**Comment by xiii111** [comment]
[元々のカンバン](https://github.com/LITO-apps/Treevel-client/projects/2)（従来）から，[Organizationのカンバン](https://github.com/orgs/LITO-apps/projects/2)（移行先）に移しました．（デザインも含め）

その際に，最近の運用で便利に利用できているかを考慮して，以下の点を変えたいなと思います．
- 従来の`予備軍`カラムを削除
- 2ヶ月ごとのマイルストーンを用意
- 優先順位のマイルストーンを削除
- 毎週のマイルストーンは残したまま（どっちがいいか，`作業中`カラムにあれば今週のタスクと見ることもできる）

了承が取れたら，[元々のカンバン](https://github.com/LITO-apps/Treevel-client/projects/2)（従来）は消しましょう．

これからの運用で思ったこととしては，`アイデア`カラムはしっかりイシューにしたいですね．

**Comment by xiii111** [comment]
@takasusuke @takesi0627 レビューなどなどコメントください

**Comment by takesi0627** [comment]
ごめんちょっと遅かったかもしれないけど、
サーバとクライアントのレポジトリを分けて本当に良いのかってまた考えちゃったんだけど、
もしクライアントとサーバ両方のソースコードいじるタスクがあったらその場合どうするのかな

**Comment by xiii111** [comment]
通例だけど，統合テストをしないといけない．
大抵両者を紐付けて，テストが通ったら両方閉じる

**Comment by xiii111** [comment]
リポジトリを一緒にするのは経験したことないから，多分不適なんだと思う

**Comment by takesi0627** [comment]
イシュー1つでプルリク2つという想定でいいのかな

**Comment by xiii111** [comment]
そういう場合には，そうなるね！

**Comment by takesi0627** [comment]
了解した、マイルストーンの運用について問題なし

**Comment by xiii111** [comment]
@takesi0627 あざす
@takasusuke からレビューもらってOKなら前のカンバン全て粉砕する
マイルストーンの運用については，次のミーティングから試す

**Comment by takasusuke** [comment]
確認しました
だいじょうぶです

**Comment by xiii111** [comment]
ありがとさん
