### ISSUE TITLE
`FPS` について調査する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#272]
## 完了条件
- [x] 現状 `FPS` がどの程度になっているのかを確認する（実機、iOS シミュレーター、Unity ビルド）
- [x] `Treevel` では、どの程度の `FPS` が必要なのかを調査する
- [ ] 上記の調査の中で、何か取るべきアクションがあれば、イシューを作成する

## 備考
- 現状確認では、複数のシーンで確認すること
- Profiler を使ったり、Print したりして、確認

**Comment by xiii111** [comment]
`Editor` の `Play Mode` も見てみた。こちらは `FPS` を固定されていないので `VSync` がない。一方で `Rendering` と `Others` に多くのリソースを食われていて、`FPS` が `15FPS` ~ `30FPS` に留まっていることがわかる

<img width="800" alt="スクリーンショット 2022-05-16 22 18 28" src="https://user-images.githubusercontent.com/26104258/168601639-8d03593d-e340-40f4-9c65-02f1f49a54d9.png">

**Comment by xiii111** [comment]
`iOS` 実機で `FPS` を変えることに成功した。`VSync` が `60 FPS` になっていることがわかる

<img width="800" alt="スクリーンショット 2022-05-19 19 43 06" src="https://user-images.githubusercontent.com/26104258/169275583-c59bd311-3e28-4c03-9fbe-e45f93f45e5f.png">

**Comment by xiii111** [comment]
## 今後のアクション
- 60 fps のバイナリを上げる
- FixedUpdate と Update の違いを調べ直し、対応する設定について理解する

**Comment by xiii111** [comment]
## FixedUpdate()
### 概要
- 一定時間ごとに呼ばれるメソッド（端末に依存せずに再現性がある）
- 以下の `Fixed Timestep` から変更可能。デフォルトでは 0.02 秒間隔（30fps）

<img width="1383" alt="スクリーンショット 2022-05-20 19 12 40" src="https://user-images.githubusercontent.com/26104258/169506881-987891a8-1b5a-47e4-9532-a2777c7c43cd.png">

### 用途
`FixedUpdate()` を使う代表的な例は物理演算を行うとき。`Update()` に物理演算を書いてしまうと、端末の描画速度により `Update()` が呼ばれるタイミングにムラができてしまうので、物体の移動がカクカクになったり物理演算の結果に再現性が保てなくなってしまう可能性がある。一方、`FixedUpdate()` は `Update()` がフレーム落ちしていても、独立して一定時間ごとに呼び出されるので、物理演算の結果に再現性が保てるようになる

## Update()
### 概要
- 1 フレームごとに呼ばれるメソッド（端末の描画速度によって呼び出される回数が異なる）

### 用途
UI の入力処理（ボタンを押す、キー入力をするなど）に用いる。一定間隔ごとに呼び出される `FixedUpdate()` では、呼び出しのタイミングによっては入力処理が検知できなくなってしまう可能性があるので、`Update()` の方が確実に入力処理を検知できて望ましい

**Comment by xiii111** [comment]
@takasusuke @takesi0627 `0.1 (31)` で fps 30、`0.1 (32)` で fps 60 のバイナリをアップロードしました！動作感の確認をお願いします！上記にまとめている通り、fps を変更したことによる違いは `Update()` を伴うところに影響を与えます。物理演算をしている `FixedUpdate()` には影響を与えない（はず）なので、ご注意を

## FYI
`0.1 (32)` の fps 60 にするための処理は https://github.com/LITO-apps/Treevel-client/pull/1591 に差分があります

**Comment by xiii111** [comment]
`0.1 (32)` がまだアップロードされないので、少々お待ちください

**Comment by xiii111** [comment]
アップロードされました！！

**Comment by takasusuke** [comment]
サクサクしてる気がする。。。なぜ。。。
fps上げたことで`TransformGesture`の感度が上がって、フリックの反応良くなったり、連続フリックをスムーズにできるようになった気がする。。。

fps60にしても良いのでは...

**Comment by xiii111** [comment]
やっぱサクサクしてる ... よね？

**Comment by takesi0627** [comment]
サクサクですな、
ユーザ体験的には良かった気がする。
でも明らかにボトルの速度が変わった気がします。
気になるポイントそれだけです。

**Comment by xiii111** [comment]
@takesi0627 

> でも明らかにボトルの速度が変わった気がします。
> 気になるポイントそれだけです。

この理由を知りたいってことかな？

**Comment by takesi0627** [comment]
知りたいけど、キリがなさそうなので、とりあえず今は操作感で判断すればいいと思う
