### ISSUE TITLE
ERROR 発生時の処理

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#296]
シーンのロードが失敗するなど次に進めない致命的なエラーが発生する場合は、デバッグできるようにエラーコードを定義し、ユーザに提示する。また、アプリを消さずに続けるようタイトル（ホーム画面など）に戻る処理が必要。

* ERROR Code の定義
* メッセージボックスの提示
* タイトルに戻る処理

**Comment by takesi0627** [comment]
終了条件：
1. UIManagerにエラーメッセージボックスのインスタンス生成、呼び出す処理を記述。
2. エラーメッセージボックスのプレハブを作成
3. エラーコードの定義 （DefinitionにEnum作成）
