### ISSUE TITLE
ゲームの成功時と失敗時で遷移先や表示する文章を変更する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#297]
成功時
- 次に進む(StageSelectSceneに遷移)
- 投稿

失敗時
- 戻る(StageSelectSceneに遷移)
- リトライ

失敗時については現状からの変更点なし

**Comment by xiii111** [comment]
### 終了条件
- 成功時は，`次に進む`と，`投稿`というボタンを表示する
- 失敗時は，`戻る`と，`リトライ`というボタンを表示する
- 今後，上記の4つのボタンがどのような挙動をするかなど，調整する可能性があるので，ボタンごとにオブジェクト（Prefab）を作っておく
