### ISSUE TITLE
パネルの判定は色に変える

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#322]
- パネルデータを数字から色
- 画像組み込み

**Comment by takasusuke** [comment]
`https://drive.google.com/drive/folders/12--YMwAFj_N0XLwrkqeXF-AdshqsFBbF`から
`LITO/Treevel/image/GamePlayScene/Panel/bottle/standard/264/`の8つをお願いします。
異なる色合いで`LITO/Treevel/image/GamePlayScene/Panel/bottle/test/264/`にも8ついただいています。
こっちの8つを並べた画面のスクリーンショット等も別にあると嬉しいです。
どの色がどの位置に、というのは適当で良いです。
