### ISSUE TITLE
レベル選択画面の木(桜)画像の案を作る

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#343]
### 終了条件
レベル選択画面の木(桜)についての資料の決定版を作成し、デザイン依頼を行う。

**Comment by takasusuke** [comment]
レベル選択画面の桜の案(#343 )
ステージ選択画面の桜の案(#344 )

[Sakura.pdf](https://github.com/LITO-apps/Treevel-client/files/4469825/Sakura.pdf)

**Comment by xiii111** [comment]
@takasusuke GitHubに乗せるなら，`.png`などの方が，直接表示されて良いかも

**Comment by xiii111** [comment]
> ステージ情報の一覧表示などで、桜の木のステージであることを示すための簡略化された桜の木のアイコン

レベル選択画面の木を使いまわせば良さそう．両方ともある意味アイコン寄りだよね

> 桜の木はユーザがはじめに選択する木と考えてください。レベル選択画面中央周辺に配置する予定です

俺は左下からスタートでもイイと思った

>  季節の色(春ならピンクとか)を変更することで、それぞれの季節に対応させる…わかりやすいけど、ピンクの地面(?)って感じ

ピンクの地面？って感じだけど，こっちの方が分かりやすくてイイ気がする

> 真横から、もしくは少し見上げるアングル 

配置しないと分からないけど，真横かなと思っている

> レベル選択画面と結構絵柄が違くても良いと思う

とてもそう思うけど，隙間はあまりない方が見栄えが良いように思えた（背景があまり見えない）

> クリア数に応じてフィルターの強度を変えるとかどう。 

素晴らしいわ

**Comment by takasusuke** [comment]
![Sakura 001](https://user-images.githubusercontent.com/26213141/79231681-69516d80-7ea1-11ea-8ace-c309cac2a7f8.png)
![Sakura 002](https://user-images.githubusercontent.com/26213141/79231690-6bb3c780-7ea1-11ea-91de-3c8c34176ea7.png)
![Sakura 003](https://user-images.githubusercontent.com/26213141/79231696-6d7d8b00-7ea1-11ea-8635-ec6e248887cc.png)
![Sakura 004](https://user-images.githubusercontent.com/26213141/79231704-6fdfe500-7ea1-11ea-88e9-7976989a9d7f.png)
![Sakura 005](https://user-images.githubusercontent.com/26213141/79231707-71a9a880-7ea1-11ea-8111-0fa8ffbbeb26.png)

**Comment by takesi0627** [comment]
> 季節の色に合うような色にする（緑とか？）....と言うのがすぐに結びつくか微妙ではある。

春と結びつく必要ないかな、同じ色の地面が他に同じ色の地面から生える木と結びつければそれでいいと思った。

> - 未クリアの状態は薄暗い感じ。モノクロはやりすぎ？
> 　- クリア数に応じてフィルターの強度を変えるとかどう？

モノクロはやばいかも。背景と合わせて色調を暗くするとか？（クリアすると背景も木も明るくなる感じ）
フィルターはやって見ないと効果はわからないね、、、でもこれは実装的な話じゃない？デザインに関係あるかな？

**Comment by takasusuke** [comment]
- レベル選択画面の桜の木はアイコンよりにして、ステージ情報などの画面で使い回すのは良さそう
- レベル選択画面の桜の木の位置は未定
- ステージ選択画面の木は真横からの見た目(見上げるって記述したのは見下げるよりも見上げるより。ほぼ真横だけど強いていうならくらいの感じ)
- レベル選択画面の桜の木の根本の領域はいくつかの形とかだけ指定して配色は少しお任せしてみる。
- ステージ選択画面の桜の木の絵柄について
> 隙間はあまりない方が見栄えが良いように思えた（背景があまり見えない）

これはあまり感覚が伝わっていない
資料中の(A), (B)-1, (B)-2, (C)の絵柄についてこの観点からどれが良くてどれがよくないのかのコメント求む

- 未クリア状態にかけるフィルターの話は、クリア済、未クリアの2枚の画像を描いてもらわなくてもクリア済の画像にフィルターをかけることで未クリアの状態を作れば良いんじゃないかな、という話。

**Comment by takasusuke** [comment]
第2版
![Sakura2 001](https://user-images.githubusercontent.com/26213141/79631079-8a5fda00-8191-11ea-981d-50e97fcb1974.png)
![Sakura2 002](https://user-images.githubusercontent.com/26213141/79631082-8d5aca80-8191-11ea-856e-56b6b6ffc804.png)
![Sakura2 003](https://user-images.githubusercontent.com/26213141/79631083-8e8bf780-8191-11ea-924f-ca064debf5de.png)
![Sakura2 004](https://user-images.githubusercontent.com/26213141/79631084-8fbd2480-8191-11ea-9999-51c4a5d79e81.png)
![Sakura2 005](https://user-images.githubusercontent.com/26213141/79631086-9055bb00-8191-11ea-9930-9df1912b6a99.png)

**Comment by takasusuke** [comment]
> 
> 隙間はあまりない方が見栄えが良いように思えた（背景があまり見えない）
> 

これ分かってきた。隙間空いてるとステージボタン配置しにくい気がするわ。

**Comment by takasusuke** [comment]
決定版
![Sakura3 001](https://user-images.githubusercontent.com/26213141/79691299-a64ea300-8299-11ea-8169-aa45251b6312.png)
![Sakura3 002](https://user-images.githubusercontent.com/26213141/79691301-a9e22a00-8299-11ea-9d7d-ce83373f843b.png)
![Sakura3 003](https://user-images.githubusercontent.com/26213141/79691303-ab135700-8299-11ea-91d6-c2bedfbce918.png)
![Sakura3 004](https://user-images.githubusercontent.com/26213141/79691304-ac448400-8299-11ea-8649-34914d25360c.png)
![Sakura3 005](https://user-images.githubusercontent.com/26213141/79691305-ac448400-8299-11ea-8233-517bff5e4261.png)
