### ISSUE TITLE
ゲーム前ポップアップのレイアウトを考え直す

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#346]
- 表示する情報は何なのか
- ポップアップの表示の有無の機能は必要なのか
- 自身の挑戦回数
- 自身が成功しているかどうか
- 他ユーザの成功割合
- 登場するギミックの簡易的なアイコン
- ゲームを行うボタン
- ステージ選択画面を再度表示するボタン

- 季節ごとに異なる
- 中性的なポップアップとは異なる
- 成功/失敗ポップアップとは異なる

**Comment by xiii111** [comment]
要らない
