### ISSUE TITLE
ステージ選択ボタン画像の案を作る

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#347]
<終了条件>
- 資料を作成、レビューに基づき訂正しデザイン依頼を出す

<考慮事項>
- 1本の木に複数の同じステージボタン
- クリア済、未クリア、選択不可の3状態
- ステージボタンの見た目は木の見た目による、季節ごとでも良いかも。テーマカラーを決める。
- 数字あり。
- ステージボタンのモチーフは自由(毒っぽい円とかウイルス)

**Comment by takasusuke** [comment]
https://docs.google.com/presentation/d/1KBr1gdxFI9t4JD24Q3Oq69SZ1vuse715JBVMYB6v8TY/edit#slide=id.g74ddec9183_0_20

2020/04/23の資料
![StageButton-1](https://user-images.githubusercontent.com/26213141/80138910-8d6b2800-85e0-11ea-8311-c211d55fec13.png)
![StageButton-2](https://user-images.githubusercontent.com/26213141/80138919-90feaf00-85e0-11ea-9db1-3d9fb78d3ff4.png)
![StageButton-3](https://user-images.githubusercontent.com/26213141/80138923-91974580-85e0-11ea-8eeb-25f5a2b6aeb4.png)
![StageButton-4](https://user-images.githubusercontent.com/26213141/80138925-922fdc00-85e0-11ea-8108-f05ead82c38c.png)

**Comment by takasusuke** [comment]
- タイル上の傷の表現
- ボタン(正円)の表現
- レベル選択画面の木の表現
- ステージ選択画面の木の表現
など、この素材よりも先に決めるであろう素材の絵柄に準ずる部分が多いと考えているので、想像がしづらいかもしれません。

ステージボタンの[クリア状態], [未クリア状態], [選択不可状態]の3状態について(A), (B), (C)の案を考えたので、ひとまずどれにするかを決めて、その後、その案での表現をさらに考えるようにしたい。

**Comment by xiii111** [comment]
スライドにコメントしました

**Comment by takasusuke** [comment]
決定版(2020/04/27)

![StageButton2-1](https://user-images.githubusercontent.com/26213141/80348992-8e82aa80-88a9-11ea-8f7d-ffd46a44524a.png)
![StageButton2-2](https://user-images.githubusercontent.com/26213141/80349004-92aec800-88a9-11ea-83d1-86b3b4d8bb7a.png)
![StageButton2-3](https://user-images.githubusercontent.com/26213141/80349007-93475e80-88a9-11ea-8fbe-8fbfb210cb57.png)
![StageButton2-4](https://user-images.githubusercontent.com/26213141/80349012-93dff500-88a9-11ea-8a09-aae05a160874.png)
