### ISSUE TITLE
ポップアップ(警告等の表示)の案を作る

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#357]
<終了条件>
資料を作成し、レビューに基づき訂正しデザイン依頼を出す

<考慮事項>
- 拡大縮小するときに、どう拡大縮小するのか
- 比は正方形で良いはず
- 縁
- 画面の縦横比に閾値を設けて、それに対してどう拡大するのかを変更する必要がある(実装)
- 単純な長方形に限らず、上から紐とか
- 立体感(影とか?)が欲しい。手前にある感じ

**Comment by takasusuke** [comment]
https://docs.google.com/presentation/d/1BffhwRJYGJF4zPvpkvrOjnPO6VAbv-tlsCcn9sZ36mk/edit#slide=id.p

2020/04/22 23:53の状態

![popupA-1](https://user-images.githubusercontent.com/26213141/79996946-fe80e180-84f3-11ea-814c-3792a5b2cf67.png)
![popupA-2](https://user-images.githubusercontent.com/26213141/79996960-02146880-84f4-11ea-9cf6-19e3d4391f7d.png)
![popupA-3](https://user-images.githubusercontent.com/26213141/79996962-02acff00-84f4-11ea-997b-c6bc9e3c0cac.png)
![popupA-4](https://user-images.githubusercontent.com/26213141/79996966-03459580-84f4-11ea-9392-7aed99b88af3.png)

**Comment by takasusuke** [comment]
コメントはスライド上でお願いします。
pngを貼りましたがスライドには変更が加わることがあります。
常にスライドの記述が正しいです。
絵柄はボタン(正円)に準拠するので、見るところは縁の太さ、形、色ですね。

**Comment by xiii111** [comment]
スライドにコメントしました

**Comment by takasusuke** [comment]
決定版 (2020/04/27)

![popup_warning2-1](https://user-images.githubusercontent.com/26213141/80349555-621b5e00-88aa-11ea-8dbd-a33afbe65422.png)
![popup_warning2-2](https://user-images.githubusercontent.com/26213141/80349565-65aee500-88aa-11ea-913d-a7b606f9b2c7.png)
![popup_warning2-3](https://user-images.githubusercontent.com/26213141/80349569-66e01200-88aa-11ea-8333-e1f32a92c2d7.png)
![popup_warning2-4](https://user-images.githubusercontent.com/26213141/80349573-68a9d580-88aa-11ea-9527-e3dc9c57102f.png)
