### ISSUE TITLE
iOS（エミュレータ or 実機）でのビルド確認

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#362]
- ビルドはおそらく通らないので重いタスク
- ビルドが完了した場合には，レビュー機能の確認 (https://github.com/LITO-apps/Treevel-client/pull/366) をする

**Comment by takasusuke** [comment]
ビルドが完了した場合には、ステータスバーの確認(#373)をする

**Comment by takesi0627** [comment]
#840 広告のセーフエリア対応

**Comment by xiii111** [comment]
#982
