### ISSUE TITLE
[ERROR] ArgumentException: Invalid path

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#386]
![スクリーンショット 2020-05-10 12 43 41](https://user-images.githubusercontent.com/26104258/81490309-e7940a80-92bb-11ea-95dd-bbb2195644fb.png)

**Comment by takesi0627** [comment]
ちょっと試してみたけど、僕のところはどうしても出ないですね、、、
トレース見たかぎり、 `com.unity.multiplayer-hlapi` というパッケージ（つまりUNet）の初期化で出るエラーらしい。 #381 でも触れたが、 UNetは今後廃止する予定だし、このプロジェクトでは使わないと思うから削除してもいいかと思います。

**Comment by takesi0627** [comment]
https://docs.unity3d.com/Manual/UNetUsingHLAPI.html
