### ISSUE TITLE
オブジェクトの縮小が描画されていてちらつく

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#393]

**Comment by takasusuke** [comment]
#570 (ゲーム画面でCamera縮小しない)や、GameObjectのSpriteRendererを初期値OFFにして、スクリプトでONにしているので、現段階で不具合は確認できない

**Comment by xiii111** [comment]
@takasusuke "オブジェクトの縮小が描画されていてちらつく" というタイトルだけでは現象を的確に思い出せないけど，問題がなかったら Close して良いです！

**Comment by takasusuke** [comment]
Bottleの大きさをコードで変更する時に、変更前の状態で一瞬されて、変更後の状態で描画されていたのでチラついて見えていた。
`SpriteRenderer`をあらかじめ`OFF`にして、大きさを変更した後で`ON`にしているのでこの現象は改善されました。

**Comment by xiii111** [comment]
はーい！
