### ISSUE TITLE
ボタン(通常)のデザイン

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#402]
https://drive.google.com/drive/folders/15-nTUVnzKghqERnYmqlfaCuxYU9IkMPm
Button_final.pdfの草案を参照

**Comment by takasusuke** [comment]
資料
https://docs.google.com/presentation/d/12_3lngUHyMDPduieIA3_8nenHRtF_sFB1zfgDjmI8m0/edit#slide=id.p

**Comment by takesi0627** [comment]
@itochico コメントしました。よろしくお願いします。

**Comment by xiii111** [comment]
@itochico コメントしましたー！

**Comment by takasusuke** [comment]
コメントしました。
こちらもまとめや質問などよろしくお願いします。

**Comment by itochico** [comment]
ラフ第1版コメント返信しました。

現状の論点まとめ
・角はもっと丸くする(2倍くらい?)
・模様はかっちりしたものでなく手描き感を出す
・戻るボタンについて
　・背景の色はどれがいいか
　・木枠をつけるか否か
　についてコメントしていただけると嬉しいです。
　模様は白がいいのでもっと暗い背景がいいです(この中に理想のものがない)、とかこれが一番理想に近いけどもっと明るく/xx色にしてほしい、といった意見でも大丈夫です。
・一時停止ボタンについて
　いまのところ背景色3、木枠無し、手描き白模様がいいという感じでしょうか？

**Comment by takasusuke** [comment]
コメントを追加しました。
- 戻るボタンは、一時停止ボタンと同じ色、同じ模様という体で考えていたのでコメントを省略していました。
- どの色にするか、ということについて意見が分かれている部分があるので、ポップアップ(警告)とボタンは同じ色にする、という前提でポップアップ並びにボタンにも追加コメントを他の人にお願いして意見をまとめます。

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
#406 ポップアップ(警告)とボタンは同じ色、同じ模様、という前提でもう１度コメントをボタン資料にコメントをお願いします。
(迷うも可)

**Comment by xiii111** [comment]
@takasusuke @itochico コメントしました．ちょっとこれ以上は何をコメントすれば良いか分からなくなってしまったので，直感的に良いなと思ったボタンを良い！とコメントしました！

**Comment by takesi0627** [comment]
@takasusuke 木枠についてもボタンとプップアップを統一する想定ですか

僕は
ボタン -> 木枠なし
ポップアップ -> 木枠あり
がいいと思っています。

**Comment by takasusuke** [comment]
> @takasusuke 木枠についてもボタンとプップアップを統一する想定ですか
> 
> 僕は
> ボタン -> 木枠なし
> ポップアップ -> 木枠あり
> がいいと思っています。

みんなの考え次第だけど、とりあえずボタンは木枠無しで考えてる。
ポップアップに木枠をつけるかどうかはまだ迷ってる。

**Comment by takesi0627** [comment]
@itochico コメントしました。僕もいいと思ったボタンをそのまま選びました。

**Comment by takasusuke** [comment]
意見をまとめると、
黄色っぽい色の背景で、黒っぽい手描きでお願いします。
一時停止、戻るボタン共に同じです。

**Comment by xiii111** [comment]
要らないらしい
