### ISSUE TITLE
ステージ選択ボタンのデザイン

### ISSUE THREAD

**Issue by itochico** [LITO-apps/Treevel-client#403]
https://drive.google.com/drive/folders/15-nTUVnzKghqERnYmqlfaCuxYU9IkMPm
StageButtonの草案を参照

**Comment by itochico** [comment]
ラフ案第1版
https://docs.google.com/presentation/d/1SIIRDzBmBtg_he5ql-lcY6FTcu1aFmIE0j2MzSFP4_w/edit#slide=id.p
@takasusuke @takesi0627 @xiii111 お手隙の際にレビューをお願いします。

**Comment by takesi0627** [comment]
@itochico コメントしました！よろしくお願いします！

**Comment by xiii111** [comment]
@itochico コメントしました！

**Comment by takasusuke** [comment]
コメントしました。
これって別に意見をまとめなくて良いですよね？

**Comment by takasusuke** [comment]
意見をまとめました。
A-1でお願いします。
鍵ももうこのままで良いくらい素晴らしいです。
大きさだけ、これくらいの大きさというのをコメントしました。

**Comment by xiii111** [comment]
要らないらしい
