### ISSUE TITLE
桜の木のデザイン

### ISSUE THREAD

**Issue by itochico** [LITO-apps/Treevel-client#404]
https://drive.google.com/drive/folders/1l7LcVngAWR19q8tyi7TyMo6xtnEOVvV1
sakura.pdfの草案を参照

**Comment by itochico** [comment]
ラフ案第1版
https://docs.google.com/presentation/d/1y2NZXL1X_LNwZgOibcS54fVb8Vt8iSnEJpSyiB_sS3U/edit

**Comment by xiii111** [comment]
@itochico コメントしました！

**Comment by takasusuke** [comment]
コメントしました。
コメントに対する質問とか生まれると思うので、コメントしたらgithubの方でも、"コメントした"旨の発言お願いします。

**Comment by takesi0627** [comment]
@itochico コメントしました。よろしくお願いします。

**Comment by itochico** [comment]
ラフ第1版コメント返信しました。結構意見がいただけたのでラフ第2版の作業に入ろうと思います。

現状の論点まとめ
レベル選択画面の木
・幹は細いやつからもう少し細くする
・根っこに関しては意見がわれているのでもう少し考える
・花に関しても意見が割れているので各意見を参考に新しい案を作る(お菓子っぽい、華やか、装飾)
・アイコン感のために輪郭線を書いた案を作って比較
・もう少し上のアングルから見たものにする

ステージ選択画面の木
・画面いっぱいになるように描く(両端は切る)
・地面はフラットに
・グラデーションをもっとはっきりかける
・根っこはあまり生やさないorちょっとだけ生やすの2種類で考える
・花弁をもっと増やしても良い

**Comment by xiii111** [comment]
終わっているらしい
