### ISSUE TITLE
タイル(通常)のデザイン

### ISSUE THREAD

**Issue by itochico** [LITO-apps/Treevel-client#405]
https://drive.google.com/drive/folders/1_zb8RsMH9ATXYK8x1xQE3p4KDjU1QWlu
草案Tile02.pdfを参照

**Comment by itochico** [comment]
ラフ第1版
https://drive.google.com/drive/folders/1_zb8RsMH9ATXYK8x1xQE3p4KDjU1QWlu
樹皮ラフ案.pdfを参照

**Comment by itochico** [comment]
ラフ第2版
https://docs.google.com/presentation/d/1h02KO-ujJiHIhws5RI2zBCCFjOhBtnirXmBls-rLPIY/edit#slide=id.p

**Comment by takesi0627** [comment]
@itochico コメントしました。よろしくお願いします。

**Comment by xiii111** [comment]
@itochico コメントしました．お願いします！

**Comment by takasusuke** [comment]
コメントしました。
コメントまとめられるとことか、コメントを受けてこれにするのが良いと思ったこととかまとめてもらえると助かります。
意見バラバラでまとめきれない、１つに決めて欲しいって部分も。

**Comment by itochico** [comment]
ラフ第2版改訂(6p以降を追加)
https://docs.google.com/presentation/d/1h02KO-ujJiHIhws5RI2zBCCFjOhBtnirXmBls-rLPIY/edit#slide=id.p
@takasusuke レビュー

現状の論点まとめ
・タイル様式 -> 同じタイルを15枚並べるより一枚の絵を15分割した方がよさそう
・タイル隙間 -> ラフ第二版の隙間で良さそう？タイルの縁をどうするか
・タイル模様 -> ラフ第二版でほぼ決定？
・タイル色 -> ２番目か3番目に1票、3番目に1票 -> 3番目？
・傷をどれにするか -> 今のところ3番？色を増やしたのでまた変わるかも
・ボトル見づらい問題
　-> 現状の解決案
　　　・ボトル自体の色を変える(傷に合わせてもっと明るくor暗く？)
　　　・ボトルの下に何らかの色(白~黒？)を置く
　　　・ボトルのデザインを変える(瓶の幅？厚み？を太くするなど)
　　　・その他

**Comment by takasusuke** [comment]
コメントしました。

> ・タイル様式 -> 同じタイルを15枚並べるより一枚の絵を15分割した方がよさそう

○

> ・タイル隙間 -> ラフ第二版の隙間で良さそう？タイルの縁をどうするか

内側に縁をつけます。

> ・タイル模様 -> ラフ第二版でほぼ決定？

○

> ・タイル色 -> ２番目か3番目に1票、3番目に1票 -> 3番目？

3番目でいきましょう。

> ・傷をどれにするか -> 今のところ3番？色を増やしたのでまた変わるかも

３番でいきましょう。

> ・ボトル見づらい問題
> 　-> 現状の解決案
> 　　　・ボトル自体の色を変える(傷に合わせてもっと明るくor暗く？)
> 　　　・ボトルの下に何らかの色(白~黒？)を置く
> 　　　・ボトルのデザインを変える(瓶の幅？厚み？を太くするなど)
> 　　　・その他

コメントしました。
正直、どれも見づらくないんだよな、、、と思っています。
こういう時は変に口出しせず、見づらいと思っている人の意見に100%乗っかるのが良いと思っているで、良さそうなのを選んでもらえるとありがたい。

**Comment by xiii111** [comment]
コメントしました！
判断はお任せします！一意見としてみてもらえたらなって思ってます！

**Comment by takesi0627** [comment]
@itochico  
すみません、9pと10pの色と傷3でもう一枚タイルに違う色のボトルを乗せるバージョンを作っていただけますか

**Comment by itochico** [comment]
ラフ第3版改訂(12p,13pを追加)
https://docs.google.com/presentation/d/1h02KO-ujJiHIhws5RI2zBCCFjOhBtnirXmBls-rLPIY/edit#slide=id.p
@takasusuke @takesi0627 @xiii111  お手隙の際にレビューをお願いします。

補足
・前回のボトルの視認性について
 - 色を強くしないで下に黒を敷いたものが見やすい
 - 色を強くして下に白を敷いたものが見やすい
 - 下に白を置くとボトルが対応するタイルに置いたのエフェクトに対して明るすぎるかもしれない

・今回の変更点
 - なぜAを追加したか:色を強くして下に白を敷いたものが見やすい理由に、ボトルの中の透明度が下がって色がついているからではないかと考えた。エフェクトのことも考えて、ボトルの外側は少し黒くするのが良いのではと考えたため、ボトルの内側を濃くし、外側を暗くしたボトルを新たに作成した
 - p13について:前回のラフ案では対応する傷の上に正解のボトルがのっている案だけだったため、違う色の傷とボトルのときの視認性が確認できるようスライドを追加した。ボトルは自由に動かして見てください

・コメントして欲しいこと
 - ABCのうちどれが一番見やすいか (できればなんとなくでいいので理由も併せて)
 - ABCのうちどれが(ボトルとして)好みか (見やすいやつとこのボトルがいい！っていうのは違うかなと思ったので)

**Comment by itochico** [comment]
p12以降、タイルについてというよりボトルについてだし、タイルの仕様は確定したかなと思うので、
今後さらに議論が伸びそうならボトルの方にissueを移そうとおもいます。

**Comment by takesi0627** [comment]
@itochico コメントしました！よろしくお願いします！

**Comment by xiii111** [comment]
@itochico コメントしました！

**Comment by takasusuke** [comment]
コメントしました。
仰るとおり、タイル、傷の仕様は確定していると思います。

ボトルに議論を移すことを最後に述べて、ボトルissue作ったら
このissueは閉じて良いと思います。

**Comment by xiii111** [comment]
終わったらしい
