### ISSUE TITLE
ポップアップ(警告)のデザイン

### ISSUE THREAD

**Issue by itochico** [LITO-apps/Treevel-client#406]
https://docs.google.com/presentation/d/1BffhwRJYGJF4zPvpkvrOjnPO6VAbv-tlsCcn9sZ36mk/edit
草案を参照

**Comment by itochico** [comment]
資料
https://docs.google.com/presentation/d/19fdB5QUWrt9RpoTikTRGHTpXNSjsfTgHKPPS4DpocXI/edit
@takasusuke レビュー。

縁が明るく中が暗い、の意図があまりわかっておらずこういうことかな…？というものを載せているので、もし想定と違ったら言って欲しいのと、何か例を出していただけると嬉しいです。
また、縁がある場合、真ん中の部分を拡大縮小というお話でしたが、コルクの細かさが変わってくるので拡大縮小よりタイリングの方が良いと思います。

**Comment by takasusuke** [comment]
レビューしました。
- "縁が明るく中が暗い"というのは内部の色が縁の色より暗い色、という意図だったので想定した通りの案を見せていただきました。
- > また、縁がある場合、真ん中の部分を拡大縮小というお話でしたが、コルクの細かさが変わってくるので拡大縮小よりタイリングの方が良いと思います。

おっしゃる通りです、タイリングにします。

**Comment by takasusuke** [comment]
@takesi0627 @xiii111 コメントお願いします。

**Comment by xiii111** [comment]
コメントしました！

**Comment by takesi0627** [comment]
@itochico  
すみません、9pと10pの色と傷3でもう一枚タイルに違う色のボトルを乗せるバージョンを作っていただけますか

**Comment by takesi0627** [comment]
コメントしました。

**Comment by takasusuke** [comment]
#402 と同じコンセプト・見た目を採用するので、そちらに資料等をまとめます
