### ISSUE TITLE
どのタイルを作るかを提案（議論）

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#413]
### やること
- 10個程度提案する
- 10個から議論をして3個にする
- 今までに上がっていたアイデアは #88 にある
- アイデアカラムにもいくつかある

**Comment by xiii111** [comment]
## タイル案①
### 氷タイル
- 角以外の任意の場所に配置可能
- ボトルがこのタイルに移動してきた場合，移動方向に移動可能なら，そのまま移動する

#### イメージ画像
![download](https://user-images.githubusercontent.com/26104258/83410091-ae7d2f00-a450-11ea-9fa9-a838ca1dc856.jpg)

**Comment by xiii111** [comment]
## タイル案②
### 蜘蛛の巣タイル
#### 場所
- 任意の場所

#### 仕様
- ボトルがこのタイルに移動してきた場合，一定時間（要調整）移動ができなくなる

#### イメージ画像
![download-1](https://user-images.githubusercontent.com/26104258/83410289-116ec600-a451-11ea-904f-33370ee7528e.jpg)

**Comment by xiii111** [comment]
## タイル案③
### ひび割れタイル
#### 場所
- 任意の場所

#### 仕様
- 始めはヒビが入っている
- N 回そのタイルの上を通ると，穴になる
- 穴になったタイルは通ることができない（タイル外と同じ扱い）
- 穴になったタイルが一定時間で復活するかは要検討

#### イメージ画像
##### ヒビ
<img src="https://user-images.githubusercontent.com/26104258/83411001-60692b00-a452-11ea-8441-bc42660181ad.jpg" width="200">

##### 穴
<img src="https://user-images.githubusercontent.com/26104258/83411013-64954880-a452-11ea-9d70-b3da56b0e251.jpg" width="200">

**Comment by xiii111** [comment]
## タイル案④
### 毒タイル
#### 場所
- 任意の場所

#### 仕様
- ボトルがこのタイルに移動してきた場合，一定時間（要調整）で 1 ダメージを受ける

#### イメージ画像
<img src="https://user-images.githubusercontent.com/26104258/83411795-e89c0000-a453-11ea-8e00-f3ca1508b943.jpg" width="200">

**Comment by xiii111** [comment]
## タイル案⑤
### 聖域タイル
#### 場所
- 任意の場所

#### 仕様
- ボトルがこのタイルに存在している間，ギミックからのダメージを一切受けない

#### イメージ画像
<img src="https://user-images.githubusercontent.com/26104258/83411991-4fb9b480-a454-11ea-8169-3f680b47d39d.jpg" width="200">

**Comment by xiii111** [comment]
## タイル案⑥
### 矢印タイル
#### 場所
- 画面外に向かうような矢印とならない任意の場所

#### 仕様
- ボトルがこのタイルに移動してきた場合，矢印の方向へ自動的に移動する
- 矢印は 4 方向

#### イメージ画像
![download](https://user-images.githubusercontent.com/26104258/83412409-fbfb9b00-a454-11ea-90c7-c6cd0672e3b2.jpg)

**Comment by xiii111** [comment]
## タイル案⑦
### 雷タイル
#### 場所
- 任意の場所

#### 仕様
- ボトルがこのタイルに移動してきた場合，一定時間（要調整）でボトルが雷を纏う（重複は不可）
- 雷を纏っているボトルは，ギミックから 1 度だけ身を守る（守った後は雷が消える）

#### イメージ画像
![images-1](https://user-images.githubusercontent.com/26104258/83413721-4bdb6180-a457-11ea-879c-14118874df13.jpg)

**Comment by xiii111** [comment]
## タイル案⑧
### ワープタイル改
#### 場所
- 任意の場所

#### 仕様
- ボトルがこのタイルに移動してきた場合，このタイルとすでにボトルが載っているタイルを除く，ランダムなタイルにボトルが移動する

#### イメージ画像
<img src="https://user-images.githubusercontent.com/26104258/83522100-21eb7300-a51b-11ea-93af-56769ec2c6b6.jpg" width="200">

**Comment by xiii111** [comment]
## タイル案⑧
### タイマータイル
#### 場所
- 任意の場所

#### 仕様
- ボトルがこのタイルに移動してきた場合，全ギミックの動作が一定時間（要調整）停止する

#### イメージ画像
<img src="https://user-images.githubusercontent.com/26104258/83522545-c79ee200-a51b-11ea-83a2-f223003fc567.png" width="200">

**Comment by xiii111** [comment]
## タイル案⑩
### マグマタイル
#### 場所
- 任意の場所

#### 仕様
- ボトルがこのタイルに移動してきた場合，ゲームが失敗する
- 雷タイルの保護を受けていても，関係なく失敗する
- ボトルに 2 以上のライフがあっても，関係なく失敗する
- マグマは一定時間（要調整）で発生したり消えたりする

#### イメージ画像
<img src="https://user-images.githubusercontent.com/26104258/83524943-45b0b800-a51f-11ea-82c1-a6ca6a8ac155.jpg" width="200">

**Comment by xiii111** [comment]
@takasusuke @takesi0627 

レビューお願いします．具体的には，以下の 2 つをお願いします

1. 良いと思ったタイル 5 つのみに 👍  リアクションをつけてください

2. 👍  したタイルについて，その理由を書いてください

3. 👍  しなかったタイルについて，その理由を書いてください

**Comment by xiii111** [comment]
### 👍 をしたタイル
個人的には，どのタイルも良いと思って選んでいるが，一応レビューアーと同じことをする

#### 氷タイル
- 見た目で何が起こるかわかりやすい
- 適度な難易度向上をできる

#### 蜘蛛の巣タイル
- 氷タイルと同様，何が起こるかわかりやすく，適度な難易度向上をできる

#### 聖域タイル
- 難易度向上するタイルはあるが，難易度を下げるタイルが少ないので，良いと思った
- 見た目から安全そうな感じが伝わる

#### 雷タイル
- かっこいい
- エフェクトで映えそう

#### マグマタイル
- 絶対にいけない領域みたいな感じが伝わる
- ライフがあるボトルを例外扱いできる

### 👍 をしなかったタイル

#### ひび割れタイル
- うーん，ありきたりすぎるかな？
- 難易度を読むのが難しそう
- 調整する量が多くて，使い勝手が悪そう

#### 毒タイル
- マグマタイルと迷った．どっちかだと思った
- マグマほどのインパクトがないと思った
- 処理が細かく，ライフが 1 のボトルだと，あっ，死んじゃうのか，みたいなことが起こりそう
- 一定時間をユーザに伝えづらい

#### 矢印タイル
- 氷タイルと迷った．どっちかだと思った
- 氷タイルの方が自然を生かしてる感じがあった
- 矢印は無機質すぎて，世界観と合わないと思った

#### ワープタイル改
- 一つワープタイルあるしな
- 既存のワープタイルとの見た目が被りそう
- ランダムに飛んだとして，ギミックのあるところに飛んでいくと，なんか，うーんって気持ちになる

#### 時計タイル
- 聖域タイルと雷タイルが推しなので，助ける系タイルはもういらないかなと
- 演出としては映えそうだとは思ったが，時が止まるのはちょっと強すぎるかも

**Comment by takesi0627** [comment]
👍 をしたタイル

* 氷タイル
配置と移動方向によって影響されない点で言うと面白さは矢印タイルに勝ると思う。

* 蜘蛛の巣タイル
木というコンセプトに合う

* 聖域タイル
息抜きに必要

* 毒タイル
マグマと比較したら毒の方を選んだ。理由はマグナが怖すぎるのと世界観に入りやすい。

* 時計タイル
そのままだと強すぎるかもしれないが、ギミックを遅らせるとかでいいと思う。逆に早くするのもあり。
その場合イラストは時計じゃなくなるかもしれないが。


👍 をしなかったタイル
* 雷タイル
格好いいけど、いいタイルか悪いタイルはちょっと判断し難い。世界観で言うとこう言う自然現象は悪い（敵）印象なので、まさかの味方？って思いました。

* マグマタイル
毒タイルと同じ理由

* ひび割れタイル
実はちょっと押し。6位ぐらい。


* 矢印タイル
氷タイルと同タイプなので氷を選んだ。

* ワープタイル改
今のワープタイルの仕様を変えるか、これを捨てるかの二択ですね

**Comment by takasusuke** [comment]
### 👍をしたタイル
#### 氷タイル
見た目と内容がわかりやすいから。
ステージ設計の幅が広がるから。

#### 聖域タイル
ユーザに優しい要素を考えてなかったけど、とても良いと思った。
簡単にする方へのレベル調整の幅が広がるから。

#### 毒タイル
一定時間が割と長ければ(3秒以上とか)、難ししすぎず、補助的に難易度を調整できそうで良さそう。

#### ひび割れタイル
パズル要素の強いステージを作れそう。

#### 雷タイル
これもユーザに優しいので選んだ。
うまく聖域タイルと使い分けてステージの幅を広げれそう。

### 👍をしなかったタイル
#### 時計タイル
ゲームが上手な人と下手な人で止めてる秒数の価値が大きく異なるから調整が難しそう。
実装が大変そう。

#### マグマタイル
毒タイルとどっちかで考えた。
Life等の要素を無視してしまうのは理不尽な気がした。
一定時間で発生するのは、毒タイルの方にもあると良さそう。

#### 蜘蛛の巣タイル
動きを制限されてギミックに当たって失敗になるのはフラストレーションを与えそうだから。
それを乗り越えてクリアする気持ち良さもあるので迷いどころ。

#### 矢印タイル
パズル要素を強くしたステージを作れそうなので、割と好み。
ただ、カジュアルにならなさそうなのと、地味な気がしたので選ばず。

#### ワープタイル改
運要素が大きくなるから。

**Comment by xiii111** [comment]
#### 👍 が 3 つ
- 氷タイル
- 聖域タイル

この二つは確定で行こうと思います．

#### 👍 が 2 つ
- 蜘蛛の巣タイル
- 毒タイル
- 雷タイル

ですね．この中から 2 つ選びましょう！

**Comment by xiii111** [comment]
僕は蜘蛛の巣タイルで！
理由は，世界観と合っている．適度な難易度感．

**Comment by takasusuke** [comment]
そうか、とりあえずは3つしか実装しないのか。
1位 : 蜘蛛の巣タイル
ギミック考えていると、タイルにまで攻撃判定がある(毒タイル)と、難しいステージしか作れなさそうなので、補助的でいい気がしてきた。

2位 : 毒タイル
同上

3位 : 雷タイル
優しいタイルが3分の2は無くて良いと思うから

**Comment by xiii111** [comment]
@takasusuke 
> 2位 : 毒タイル
> 同上

1位との違いはどんなところですか？

**Comment by xiii111** [comment]
#### メモ
- 本日定例会で確定させる

**Comment by takasusuke** [comment]
> > 2位 : 毒タイル
> > 同上
> 
> 1位との違いはどんなところですか？

ええ。。。攻撃判定があるかどうか、ダメージがあるかどうかで考えて、毒タイルはダメージがあるから、それよりも、補助的に妨害するけどダメージは無い蜘蛛の巣タイルが良いって書いてないすか。。。
(シンプルな疑問なんだけど、文章のどこの部分がわかりにくかったのか気になる。。。)

**Comment by xiii111** [comment]
あーすまん．読み違えた

**Comment by takesi0627** [comment]
三つの中なら蜘蛛かな。理由は特に新しい理由はない、皆さんと同意見。

ただし、そんなに個数にこだわる必要もないかと。三つっていうのもあくまで目安だったから、👍 が 2 つのもうちょっと検討して実装するのもありかも。

**Comment by xiii111** [comment]
個数に拘らないのはそうだけど，一旦これで良いかなと．
増やしたいと思ったらこのイシューに立ち返れば良いし！

**Comment by takesi0627** [comment]
スタンス把握。なら大丈夫。

**Comment by xiii111** [comment]
みなさま

以下の 3 つを実装することにします
- 氷タイル
- 聖域タイル
- 蜘蛛の巣タイル

以下の 2 つは人気はあったので，イシューにだけしておきます
- 毒タイル
- 雷タイル

**Comment by xiii111** [comment]
@takesi0627 こんな感じでどう？

**Comment by takesi0627** [comment]
いい感じ

**Comment by xiii111** [comment]
おけ．
ギミックにも通ずることで，季節に合わせたオブジェクトを使わないといけないという危惧があるので，定例で話しましょう

ex) 氷タイルは冬にしかないんじゃないか？

的な

**Comment by xiii111** [comment]
今回のタイルで言うと，
- 氷タイル → 冬
- 聖域タイル → 通季
- 蜘蛛の巣タイル → 冬以外

- 毒タイル → 通季
- 雷タイル → 通季

**Comment by takesi0627** [comment]
見た目だけ変えれば通ることもあると思う
例えば同機能で：
氷タイル→冬
苔タイル→春、秋

とか

**Comment by xiii111** [comment]
そういう手もある．そういう手が聞かないタイプのタイルもあるから，少し議論は必要かなぁと

**Comment by xiii111** [comment]
イシューにしたら，閉じます

**Comment by xiii111** [comment]
イシューにしました
- 氷タイル → #415 (#451)
- 聖域タイル → #414 
- 蜘蛛の巣タイル → #417 
- 毒タイル → #452 
- 雷タイル → #453
