### ISSUE TITLE
ステージ概要ポップアップの提案

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#416]
* 表示する項目
* レイアウト

**Comment by takesi0627** [comment]
https://docs.google.com/presentation/d/1QiMKKK6LFS0V8qFbEmle2Wn-OuluXm_Dy91dWO1GO2Q/edit#slide=id.g896d804a6a_0_8

提案をこちらにあげました。ご確認してください。コメントはスライドでお願いします。

**Comment by takesi0627** [comment]
@takasusuke @xiii111

**Comment by xiii111** [comment]
レビューは金曜以降（いけたら木曜）

**Comment by takasusuke** [comment]
コメントしました

**Comment by xiii111** [comment]
コメントしました！
残りの議論は明日の打ち合わせの時に話し合いながら固めるで良いかな？

**Comment by takesi0627** [comment]
良き

**Comment by takesi0627** [comment]
#418 のPRで閉じます

**Comment by xiii111** [comment]
提案は終わってるから，閉じていいと思ったよ！（他の提案タスクもそういう感じで閉じたよ）

**Comment by takesi0627** [comment]
では閉じます
