### ISSUE TITLE
どのようなギミックを作るか提案

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#419]
- 10個程度提案 + 既存の`3`個はコンセプトのみ提案 → 議論して合計`8`個にする
- 自然現象に関連付けられると良い

**Comment by takasusuke** [comment]
提案資料
https://drive.google.com/drive/folders/1_zb8RsMH9ATXYK8x1xQE3p4KDjU1QWlu

**Comment by takasusuke** [comment]
@xiii111  @takesi0627 
案の捻出が終わりました。
全てのギミックに対して肯定的な意見 or 否定的な意見のコメントをスライド資料上にお願いします。
上位5個の順位付けの申告をgithubコメントでお願いします(集計しやすい)。

**Comment by xiii111** [comment]
全てにコメントしたつもりです

**Comment by xiii111** [comment]
10個程度 = 8個であってるかな？
- 流れ星
- 直線攻撃
- 波
- 地震
- 引力
- 乾燥
- 霧
- 地割れ

**Comment by xiii111** [comment]
5個選ぶなら
- 直線攻撃
- 引力
- 乾燥
- 霧
- 地割れ

かな！

**Comment by takasusuke** [comment]
> 10個程度 = 8個であってるかな？
> 
> * 流れ星
> * 直線攻撃
> * 波
> * 地震
> * 引力
> * 乾燥
> * 霧
> * 地割れ

判定厳しいなあ。。。
Cartridge1、はまだしもCartridge2とShot1はアイデア出しだと思っていますが！！！

**Comment by xiii111** [comment]
> 判定厳しいなあ。。。
> Cartridge1、はまだしもCartridge2, 3とShot1はアイデア出しだと思っていますが！！！
> あと、これ以上案は出せません。

少し，カテゴリ分けがわかりづらく，判断が揺れて確認した

**Comment by takasusuke** [comment]
コメントしました。
１位 : 霧
2位 : 乾燥
3位 : Cartridge3
4位 : Cartridge1
5位 : 地割れ

**Comment by takasusuke** [comment]
> > 判定厳しいなあ。。。
> > Cartridge1、はまだしもCartridge2, 3とShot1はアイデア出しだと思っていますが！！！
> > あと、これ以上案は出せません。
> 
> 少しカテゴリ分けがわかりづらく，判断が揺れて確認した

これは申し訳ない。

**Comment by takesi0627** [comment]
遅くなってすまん。

1位 : 乾燥
2位 : 霧
3位 : 地震（アイデアはいいけど、仕様をもうちょっと練る必要あるかな）
4位 : 直線攻撃
5位 : 引力（機能はいいが、モチーフはちょっと変えたい）

**Comment by takasusuke** [comment]
決定
- 乾燥
- 霧

**Comment by xiii111** [comment]
- cartridge 3
- shot 1（雷）
- 流れ星
- 直線攻撃
- 波
- 地震
- 引力
- 地割れ

から 3 つ

**Comment by takasusuke** [comment]
Cartridgeは竜巻になりました。
Cartridge1, 2として提案した機能も竜巻に含まれます。

Shotは隕石になりました。

**Comment by takesi0627** [comment]
shot 1（雷）
 直線攻撃
 地震
 引力
 地割れ

**Comment by takasusuke** [comment]
- cartridge 3
- shot1
- 流れ星
- 直線攻撃
- 地割れ

**Comment by xiii111** [comment]
- cartridge 3
- shot 1（雷）
- 直線攻撃
- 地震
- 引力

**Comment by takasusuke** [comment]
3票
- shot1
- 直線

2票
- 地震
- 引力
- 地割れ
- cartridge 3

1票
- 流れ星

**Comment by takesi0627** [comment]
引力

**Comment by xiii111** [comment]
- 地震

**Comment by takasusuke** [comment]
引力

**Comment by takasusuke** [comment]
決定
- 乾燥
- 霧
- 突風(引力)
- shot1(雷?)
- 直線攻撃(太陽光?)

実装は未定ですがissueにしておきます。
- 地震
- 地割れ
- cartridge3(追従する竜巻)

**Comment by takasusuke** [comment]
issueを作成しました。
- 既存のCartirdgeを竜巻に変更し、軌跡を表示する(#463)
- 既存のHoleを隕石に変更する(#458)
- 乾燥ギミック(#454)
- 霧ギミック(#455)
- 突風ギミック(#456)
- 雷ギミック(#457)
- 太陽光ギミック(#459)

---------(実装候補)--------
- 地震ギミック(#460)
- 地割れギミック(#461)
- 追従する竜巻ギミック(#462)
