### ISSUE TITLE
どんな記録画面がどこに必要かを提案（議論）

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#421]
#### 現状の検討画面
- レベル（木）ごと記録の可視化
- レベル（木）すべての記録の可視化

#### 終了条件
- どんな情報を表示する記録画面が必要を決める
- 必要な記録画面はどこから遷移できるかを決める
- 必要な記録画面はどのようなレイアウトかを決める

**Comment by xiii111** [comment]
書き途中（適宜更新）

### 1. 木
#### その木全体の結果
- 木に含まれているステージの何%をクリアしているか？
- 

#### その木に含まれる各ステージの結果を見たい
- 全体（全ての木）の結果を見たい

### 2. ユーザ

### その他
- どのギミックで失敗したか
- 総移動距離
- 総プレイ時間
-

**Comment by xiii111** [comment]
### 2. ステージ結果記録画面
ステージ結果がどういう状態かの情報

### 1. 木
#### その木全体の結果
- 木に含まれているステージの何%をクリアしているか？
- 

#### その木に含まれる各ステージの結果を見たい
- 全体（全ての木）の結果を見たい

**Comment by xiii111** [comment]
@takasusuke @takesi0627 レビューお願いします．レビューして欲しい内容は以下になります．

1. 上記の2画面がそもそも必要か？
2. 上記の2画面に表示する情報は過不足ないか？
3. 上記の2画面のレイアウトは適切か？
4. 上記の2画面への遷移は適切か？

**Comment by xiii111** [comment]
[メモ] 
プルダウンはたくさんになってしまうので，階層的に，季節→各木みたいにすれば遷移が楽になりそう

**Comment by takasusuke** [comment]
1. 上記の2画面がそもそも必要か？
2画面あれば、ゲームしないけど記録画面だけ眺めてニッコリできるので、欲しい。
がしかし、リリースまでにどっちが欲しいと聞かれると総合記録画面です。
(個別記録画面に必要なデータは保存しておく)

2. 上記の2画面に表示する情報は過不足ないか？
総合記録画面
- aveは必要ない派です。
どうしても偏ったデータに影響を受けやすい値なので、ネガティブに捉えています。
あと、他人の記録を参考にやる気を出すゲームでもないのかな、とは思います。

一応、情報の候補を出します(そんなに押してるわけではない)。
- 総起動日数(ログイン日数)
- 初めてプレイした日

個別記録画面
情報の過不足は浮かびません。

3. 上記の2画面のレイアウトは適切か？
総合記録画面
とても見やすい。
円グラフがとても良い。

個別記録画面
- 棒グラフは飛び抜けて多いステージがあると、他のステージが見づらくなる可能性がある
対策として、一定回数以上で区切る、対数表示とか。。。
<img width="127" alt="スクリーンショット 2020-07-17 23 39 03" src="https://user-images.githubusercontent.com/26213141/87798250-b705b980-c886-11ea-8f32-c58df30bfe31.png">
githubのマイページみたいに、回数に応じた色の濃さだと、物理的に見づらくなりはしづらいかと。(それでも飛び抜けて多いのがあると他が透明になったりするので、閾値で区切る必要はある)
(スペース空いた分、同じ季節のStageはまとめて表示するとか)
- クリアしたステージを色の違い以外で表現できないかなあ。色と何か別の要素があるとより伝わりやすいと思う。


4. 上記の2画面への遷移は適切か？
総合記録画面
適切に思う。

個別記録画面
フリックではなく、ボタンで表示を切り替えるか、
総合or個別 のタブ(ボタン)があって、それを押すとフリックの挙動をするとかのUIが必要に思います

**Comment by xiii111** [comment]
@takasusuke レビューありがとうございます．

> がしかし、リリースまでにどっちが欲しいと聞かれると総合記録画面です。
> (個別記録画面に必要なデータは保存しておく)

総合記録画面 > 個別記録画面 の優先順位は同意です．しかし，データをきちんと取るように設計すると思うので，実装しちゃいたいですよね．

> aveは必要ない派です。

うん．同意した．

> 一応、情報の候補を出します(そんなに推してるわけではない)。

一定時間考えたが，今のスペースを狭めてまで必要じゃないと思ったから，採用しない気持ちでいます．

> 棒グラフは飛び抜けて多いステージがあると、他のステージが見づらくなる可能性がある
> 対策として、一定回数以上で区切る、対数表示とか。。。

対策として，棒グラフタップ時に回数が出るようにした．飛び抜けて多いステージによって他のステージの棒グラフの背が低くなることは見づらい要素ではないと思っています．

> クリアしたステージを色の違い以外で表現できないかなあ。色と何か別の要素があるとより伝わりやすいと思う。
> 全部クリアした時に、全部青になるけど、その時初めて記録画面を見た人は、達成感を感じてもらえないのではないか。

うん，気持ちはわかる．けど，このやり方を超えるやり方が出てこなかったら，これで良いとも思う．ステージクリア数のフォント色とクリア状態のステージの棒グラフの色が対応しているので，悪くないと思う．でも赤と青の配色は良くないと思うので，少し修正を加えます！

> フリックではなく、ボタンで表示を切り替えるか、
> 総合or個別 のタブ(ボタン)があって、それを押すとフリックの挙動をするとかのUIが必要に思います

フリックを消すつもりはありません（スマホらしい操作だから）けど，現状だと遷移をユーザが発想できないのは間違いないので，その問題を解決するボタンを検討します（ボタンでもフリックでも遷移可能ということ）

**Comment by xiii111** [comment]
MTG までに修正案を出します

**Comment by xiii111** [comment]
#### 総合記録画面
<img src="https://user-images.githubusercontent.com/26104258/87850249-b70ac580-c929-11ea-98a0-7cb2b90f8309.png" width="300">

##### 変更点
- 平均を消しました
- Twitter への Share ボタンを用意しました
- 右に移動するボタンを用意しました
- フォントカラーを中性的な色にしました（個別記録画面の変更によるもの）

#### 個別記録画面
|春（桜）|夏（ガジュマル）|
|---|---|
|![個別記録画面，春](https://user-images.githubusercontent.com/26104258/87850303-0ea93100-c92a-11ea-923f-bb4700e6c6ca.png)|![個別記録画面，夏](https://user-images.githubusercontent.com/26104258/87850302-0bae4080-c92a-11ea-8f29-266850b2c468.png)|

##### 変更点
- 各木の選択を簡単にしました
- クリアしていないステージの色を灰色にしました
- クリアしているステージの色を季節のモチーフ色にしました（春：ピンク，夏：緑，秋：オレンジ，冬：水色）
- 左に移動するボタンを用意しました
- 上記の事情により，グラフの大きさやフォントの大きさを調整しました

ポップアップの場合も以下に示します
|春（桜）|夏（ガジュマル）|
|---|---|
|![個別記録画面，春，ポップアップ](https://user-images.githubusercontent.com/26104258/87850345-7c555d00-c92a-11ea-8bfd-aefeacdfac75.png)|![個別記録画面，夏，ポップアップ](https://user-images.githubusercontent.com/26104258/87850343-795a6c80-c92a-11ea-9eaa-997c10618f98.png)|

##### 変更点
- そのステージをクリアしていない場合，ポップアップの背景色を灰色にしました
- そのステージをクリアしている場合，ポップアップの背景色を季節のモチーフ色にしました
- 見やすいように，配置 / 大きさ / 表示内容 を調整しました

**Comment by xiii111** [comment]
MTG で議論します！

@takesi0627 は一度もレビューしていないと思うので，時間あればレビューしてください

**Comment by takesi0627** [comment]
総合記録画面を①
個別記録画面を②

として読んでください。

1. 上記の2画面がそもそも必要か？
僕の中に特に優劣はない。しかし、仕様決まったらどちらかがリリース後の実装になっても両方の値を同時にしっかり記録に残りますように。


2. 上記の2画面に表示する情報は過不足ないか？

* ①の総起動時間の必要性はちょっと分からない。起動したままで、プレイしていなくても加算されるから「プレイスタイル」とはあんまり関係ないじゃないかと思いました。ログイン日数とか、連続ログインに数とかにした方がいいかもしれません。今後ログイン日数や連続ログイン日数でボーナスアイテムを与える機能を考えてもいいし。


3. 上記の2画面のレイアウトは適切か？
①についてはすごく見やすくていいと思います！

②も新バージョンですごく良くなってると思いますが、幾つの懸念がありました。

* @takasusuke も言及したように、y軸目印の調整が難しい。
* ステージ選択画面において、ステージの並びは数字とは関係ないため、ここでステージNoだけ表示されても、どのステージかはステージ選択画面に行って確認しないと分からない。
* 回数のところ、旧バージョンでは「プレイ回数」って書いてたけどどうして消しましたか？何の回数かは分からなくなってしまいます。


4. 上記の2画面への遷移は適切か？
フリック＋ボタンはいいと思いますが、なんかボタンが占める面積大きすぎる気もしなくもない・・・



### 質問
1. フリック操作は想定しているようですが、②でフリックすると季節の切り替えになりますか？それとも①に戻りますか？

2. 同季節の違う木は色変わりますか？

3. 木のプルダウンはずっと表示されるものですか

4. このレイアウトはセーフエリアを考慮していないみたいだけど、セーフエリアが加わってもレイアウトは大丈夫でしょうか

**Comment by takasusuke** [comment]
色の変化やShare Buttonはとても良いと思います。

疑問
- グラフタップ時のポップアップは、アプリ内で他に表示するポップアップと同じ形？
- ユーザアイコンを表示？
- ユーザ名を表示？
- 棒グラフのメモリは動的に変化する？最大回数が15回なら、メモリは(10, 20, 30)とかになりますか。
- 棒グラフのメモリは999回以上だったら999+とかが良いと思います。1000000とか表示するとレイアウトが崩れそう
- 季節切り替えるやつ(名前忘れた)ってこの見た目の感じを想定していますか？
Androidで同じ見た目にできるもの？という意味と、他の画面に比べてsystematicな画面に見える、という懸念を含んでいます。

> 
> > 棒グラフは飛び抜けて多いステージがあると、他のステージが見づらくなる可能性がある
> > 対策として、一定回数以上で区切る、対数表示とか。。。
> 
> 対策として，棒グラフタップ時に回数が出るようにした．飛び抜けて多いステージによって他のステージの棒グラフの背が低くなることは見づらい要素ではないと思っています（健全に多いステージが多く見えるだけだから）

👍

> 
> > フリックではなく、ボタンで表示を切り替えるか、
> > 総合or個別 のタブ(ボタン)があって、それを押すとフリックの挙動をするとかのUIが必要に思います
> 
> フリックを消すつもりはありません（スマホらしい操作だから）けど，現状だと遷移をユーザが発想できないのは間違いないので，その問題を解決するボタンを検討します（ボタンでもフリックでも遷移可能ということ）

フリックの他にボタンもある方が良いと思ってコメントした(今見ると日本語終わってるけど)
がしかし、改めて考えると、並列の関係にあるものがフリックで結びつくのかな、とも思う。
各季節の個別記録画面が仮にフリックで遷移できるなら直感的とは思うが、総合記録画面と個別記録画面(その中にプルダウンがある)がフリックは直感的なのか？という意味です。
あんま気にならないっちゃ気にならないけど、一応問題提起として。

**Comment by takesi0627** [comment]
![image](https://user-images.githubusercontent.com/17778395/87854011-8fc3f080-c949-11ea-8c6e-313339739026.png)

**Comment by xiii111** [comment]
### 修正内容
- グラフに挑戦回数を見せる
- 矢印ボタンを上に
- ユーザ名，アイコンを消す
- Share ボタンを中央の上に置く
- Safe Area 考慮
- pull ダウンを中央に寄せて，幅広く
- ステージ選択画面へのボタン

**Comment by takasusuke** [comment]
棒グラフのアイデア(シンプルな芽)
![13026bc185d3772de2e8cd848d73b1f9](https://user-images.githubusercontent.com/26213141/87864591-22de4400-c9a5-11ea-9253-2b065dea69b7.jpg)
例えば、クリアで花が咲く想像図。
![thumb_39182dcce19fe76482731d08b5a56606](https://user-images.githubusercontent.com/26213141/87864594-25409e00-c9a5-11ea-89f1-f54b57e77e35.jpg)


背景色、フォント次第でこんな感じの雰囲気も可能だと思っている。
![thumb_661aeb4af0d0134a90c671afd39c09c7](https://user-images.githubusercontent.com/26213141/87864596-27a2f800-c9a5-11ea-8c7b-047ca593eefe.png)

自分はUI感を現時点での案よりは減らしたいとは思っているけど、見やすさが第一と思っている。
記録画面はある程度体系的でも良いと思っている(自分よりも見やすさに重点を置いている感じ？)、と言っていたよね？と思うので、
表示する内容、画面遷移、表示方法のある程度の方針は決めたとしても、
雰囲気とかのすり合わせは別のissueでも良いんじゃない？というのがミーティングでうまく伝えられなかったところです。

**Comment by xiii111** [comment]
> 例えば、クリアで花が咲く想像図

ふむふむ

> 記録画面はある程度体系的でも良いと思っている(自分よりも見やすさに重点を置いている感じ？)、と言っていたよね？と思うので、表示する内容、画面遷移、表示方法のある程度の方針は決めたとしても、雰囲気とかのすり合わせ(一度レイアウトを実装しても、画像とかで簡単に変えられる部分)は別のissueでも良いんじゃない？というのがミーティングでうまく伝えられなかったところです。

なるほどなるほど．確かに今のはシックすぎるから，ポップにしたい感じはあるよね．とは言え，見やすくないと話にならないとも思っているから，一旦見た目作りの簡単なシックな状態にしておいて，この部分を改良したらポップになるよね！ってところを適宜ポップにしていくのもいい感じだと思いました！

**Comment by xiii111** [comment]
@takasusuke @takesi0627 

https://github.com/LITO-apps/Treevel-client/issues/421#issuecomment-660488436 を満たすように，デザインを修正しました．

### 総合記録画面
<img src="https://user-images.githubusercontent.com/26104258/87941219-bd3da500-cad5-11ea-8a38-7243bf50b0b7.png" width="400">

### 個別記録画面（春）
|通常時|棒グラフ押下時|
|---|---|
|![個別記録画面，春改良](https://user-images.githubusercontent.com/26104258/87941261-d6465600-cad5-11ea-8d26-a50aff9f3981.png)|![個別記録画面，春，ポップアップ改良](https://user-images.githubusercontent.com/26104258/87941258-d5152900-cad5-11ea-90b5-f826d3128691.png)|

### 個別記録画面（夏）
|通常時|棒グラフ押下時|
|---|---|
|![個別記録画面，夏改良](https://user-images.githubusercontent.com/26104258/87941355-fd048c80-cad5-11ea-809e-cb7a137399c0.png)|![個別記録画面，夏，ポップアップ改良](https://user-images.githubusercontent.com/26104258/87941352-fbd35f80-cad5-11ea-96f6-7d0d43f5b516.png)|

**Comment by takesi0627** [comment]
Y軸の目盛りって999+とかにするんだっけ
あと、前気付かなかったけど、ポップアップの位置ってタップした棒の真上になってるそうですが、両端の棒をタップした際、どうなるんでしょうか

**Comment by takasusuke** [comment]
個別記録画面は良いと思います。

総合記録画面は割と最初から良かったからちゃんと見てなかったけど、
"♯5"の文字(ランキング?平均?)が何の数字かわからないです。
無くても良いかもしれません。

あと、内容やレイアウトに関わらないので、細かいけど、
総プレイ回数 → プレイ回数 or 合計プレイ回数
総起動日数 → プレイ日数  or 合計プレイ日数
総フリック回数 → フリック回数 or 合計フリック回数
総失敗回数 → 失敗回数 or 合計失敗回数
とする方が馴染み深い表記だと思います。

**Comment by xiii111** [comment]
@takasusuke @takesi0627 コメントありがとうございます！再レビューお願いします！

以下を修正しました
- 総合記録画面のステージクリア数から，ランキングの削除
- 総合記録画面の文言から，"総" を削除した
    - "合計" だと長く，くどい見た目になった
    - "総" もしくは "合計" を付けないと，総合記録画面であることが伝わりづらい
    - 個別記録，総合記録という文言を 右 / 左 ボタンに追加した
- 個別記録画面から左ボタンを削除したのに，棒グラフの描画範囲を変えてなかったので左の領域を使うようにした
- 上記に伴い，棒グラフの横幅を太くした
- 棒グラフの "プレイ回数" の表示位置を変えた
- 999+ の場合の表記を追加した
- ポップアップの表示高さを固定
- ポップアップと棒グラフの対応を示す線を表示（iOS 純正アプリ，ヘルスケアの歩数棒グラフを参考にした）

### 総合記録画面
<img src="https://user-images.githubusercontent.com/26104258/88120542-1b65a780-cbfe-11ea-93b2-5e663f04ded0.png" width="300">

### 個別記録画面
|春|夏|
|---|---|
|![個別記録画面，春改良3](https://user-images.githubusercontent.com/26104258/88120566-291b2d00-cbfe-11ea-8033-cbb47ec62cff.png)|![個別記録画面，夏改良3](https://user-images.githubusercontent.com/26104258/88120581-36d0b280-cbfe-11ea-89fd-561b55d34014.png)|


### 個別記録画面（ポップアップ）
|春|夏|
|---|---|
|![個別記録画面，春改良3，ポップアップ](https://user-images.githubusercontent.com/26104258/88120571-2ae4f080-cbfe-11ea-99b3-2c2c5b3fda31.png)|![個別記録画面，夏改良3，ポップアップ](https://user-images.githubusercontent.com/26104258/88120584-389a7600-cbfe-11ea-9c5a-4acf8c42d2e0.png)|

**Comment by takasusuke** [comment]
良いと思います。

棒グラフが太くなるだけでやっぱり全然印象違うなあ。
プレイ回数のポップアップの方は999,999回くらい(かなりやり込んだ人でもカンストしない)までは表示したいですね。

**Comment by xiii111** [comment]
> プレイ回数のポップアップの方は999,999回くらい(かなりやり込んだ人でもカンストしない)までは表示したいですね。

実装の時に調整ですね．

**Comment by xiii111** [comment]
@takesi0627 も問題なければ，このイシューは閉じて， #442 に行きます

**Comment by takesi0627** [comment]
問題なし

**Comment by xiii111** [comment]
Thanks!
