### ISSUE TITLE
ギミックのリファクタリング

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#423]
#419 の結果のギミックを考慮した上に設計する

**Comment by takesi0627** [comment]
## Problems
* 繰り返し呼び出すギミック（霧、砂等）の対応
	* 両方対応できるようなAbstractGimmickControllerを考える
* 新規ギミックの実装コストが高い：(Generator、WarningController、ギミック自体のControllerの実装が必要） →　
	* Generatorを統一
	* 警告処理はギミックコントローラーで完結
* `BulletGroup` という概念はまだいる？

## 考案
* 実装クラス：
	* `GimickGenerator` -> 現 `GroupBulletGenerator`。`GimmickData`を受け取り、ギミックの生成の準備、ギミックの生成を全うする。
	* `AbstractGimmickController` -> 全種類のギミックが実装すべき抽象クラス。
* 警告出す・消すタイミングなどは AbstractGimmickControllerに任す。各ギミックコントローラは、警告表示処理を実装（警告要らないギミックは空メソッド）。
* ギミックの生成（Instantiate）は `GimmickGenerator` がパラメータを見てよしなにやる。
* `AbstractGimmickController` はギミックが生成されてから破壊されるまでの流れを記述する（実際の処理は実装するクラスで記述）
* ステートパターン利用するかも（InitialState->WarningState->AttackingState->Destroyみたいな感じ）

**Comment by xiii111** [comment]
以下にコメントをしますが， @takasusuke のコメントの比重は重くしてください！

> 警告処理はギミックコントローラーで完結

- 確かに Warning はギミックコントローラで対応したい

> `BulletGroup` という概念はまだいる？

- `BulletGroup` という概念は，どうでしょうね．繰り返し表示することやランダムに表示することが問題なくできるのであれば，必要ないかもしれません

> `AbstractGimmickController` -> 全種類のギミックが実装すべき抽象クラス。

- `AbstractGimmickController` については，全種類のギミック同様の抽象化を必要とするなら存在価値があるけど，性質がかなり異なるギミックにおいて無理して抽象化をする必要はないと思う．`HogeGimmickController` と `FugaGimmickController`（両方とも抽象クラス）のように抽象すべきグループごとに抽象クラスがあれば良いと思う

> 警告出す・消すタイミングなどは AbstractGimmickControllerに任す。各ギミックコントローラは、警告表示処理を実装（警告要らないギミックは空メソッド）。

- ギミックによって，警告を出す・消すタイミングが異なる可能性があるので，どこまでを AbstractGimmickController に任せるかはシビアだと思う．

> ギミックの生成（Instantiate）は `GimmickGenerator` がパラメータを見てよしなにやる。

- 良い👍

> ステートパターン利用するかも（InitialState->WarningState->AttackingState->Destroyみたいな感じ）

なるほど？単方向にしか流れていかない処理だから，効能がまだ想像できてないけど，確かに段階的な動きはするよね．

**Comment by takesi0627** [comment]
> > `BulletGroup` という概念はまだいる？
> 
> * `BulletGroup` という概念は，どうでしょうね．繰り返し表示することやランダムに表示することが問題なくできるのであれば，必要ないかもしれません

今の `BulletGroup` はただ複数の銃弾の `isLoop` `appearanceTime` `interval` の値をまとめているだけのように見えるが、これらをそれぞれのギミックに設定すればいいじゃないかと思いました。

> > `AbstractGimmickController` -> 全種類のギミックが実装すべき抽象クラス。
> 
> * `AbstractGimmickController` については，全種類のギミックが同様の抽象化を必要とするなら存在価値があるけど，性質がかなり異なるギミックにおいて無理して抽象化をする必要はないと思う．`HogeGimmickController` と `FugaGimmickController`（両方とも抽象クラス）のように抽象すべきグループごとに抽象クラスがあれば良いと思う

`AbstractGimmickController` を「環境変化を起こすギミック」と「実際に攻撃してくるギミック」の両種類の抽象クラスを継承させることも検討しています。

> > 警告出す・消すタイミングなどは AbstractGimmickControllerに任す。各ギミックコントローラは、警告表示処理を実装（警告要らないギミックは空メソッド）。
> 
> * ギミックによって，警告を出す・消すタイミングが異なる可能性があるので，どこまでを AbstractGimmickController に任せるかはシビアだと思う．

もちろん、タイミングはパラメータ化して各ギミッククラスが制御できるように設計する。

**Comment by xiii111** [comment]
3つの返信全て，納得のいく返答です！

**Comment by xiii111** [comment]
一点だけあるとすれば，過度な抽象化は逆に危険な場合があるので，適度に必要な箇所で抽象化をしてもらえたらと思います！（それが難しいって話だが）

**Comment by takasusuke** [comment]
> 新規ギミックの実装コストが高い：(Generator、WarningController、ギミック自体のControllerの実装が必要） →　   
>   * Generatorを統一

現在の`Generator`の処理で、
`Controller`の実体生成をする際に、パラメータが`Random`なら具体的な値を決めてから実体生成する。
これを`Controller`自身が実体生成されたタイミングで決めるようにする、ということですかね。
実装時の記述箇所がまとまるので良いと思います。

>   * 警告処理はギミックコントローラーで完結

これは是非そうしたい。

> * `BulletGroup` という概念はまだいる？

現実装の機能を保存するなら、
`BulletGroup`に含まれる`Bullet`の中から`Random`に`Controller`を作成する時に`Bullet`をまとめる何かは必要だと思う。
今は単体の`BulletData`を作る際にも、`BulletGroupData`を作らないといけないが、`BulletData`だけでもデータを作れるし、`BulletGroupData`でもデータを作れる、というのが理想な気はする。
ただ、
各`Controller`のパラメータが`Random`なのは良いけど、出現する`Controller`も`Random`なステージなんていらないと割と強く思っているので、そもそも`BulletGroup`を使った現実装の機能が不要なら`BulletGroup`は不要です


>   * `AbstractGimmickController` -> 全種類のギミックが実装すべき抽象クラス。

クラスを呼び出す側からすると、全ギミックが実装すべき抽象クラスがあった方が何かと便利だと思うので良いと思います。

> * 警告出す・消すタイミングなどは AbstractGimmickControllerに任す。各ギミックコントローラは、警告表示処理を実装（警告要らないギミックは空メソッド）。
> * ギミックの生成（Instantiate）は `GimmickGenerator` がパラメータを見てよしなにやる。
> * `AbstractGimmickController` はギミックが生成されてから破壊されるまでの流れを記述する（実際の処理は実装するクラスで記述）
> * ステートパターン利用するかも（InitialState->WarningState->AttackingState->Destroyみたいな感じ）

とても分かりやすくて良いと思います。

**Comment by takesi0627** [comment]
> ほとんど同意なんで、"良いと思います"コメントばかりになってしまった。。。

ありがとう。
`BulletGroup` については破棄する方向で進めます。
