### ISSUE TITLE
WarpTileのデザイン草案

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#430]
終了条件
資料を作る

考慮事項
- WarpTileの機能の説明
- WarpTileの画像案
- WarpTIleがWarpしていない時のアニメーションの案
- BottleがWarp中のWarpTileのアニメーションの案
- BottleがWarp中のBottleのアニメーションの案

**Comment by takasusuke** [comment]
資料
https://docs.google.com/presentation/d/1ZRbdBSqMKMu1O0vozkU9AZuTOYitxzoaqiX1DnQbUSs/edit#slide=id.g8a72795a62_0_132

**Comment by takasusuke** [comment]
WarpTileの画像草案を考えました。
なんとなく各案に合いそうなアニメーションも考えました
。
参考画像とか、コンセプトで想像してください。
現時点でアニメーションの技術力がないので、アニメーションの方は目安くらいに考えてください。
アニメーションに慣れたら、その時、別の表現が浮かぶかもしれません。

7つの案があります。
各々の案について、-2・-1・0・1・2の5段階で評価してください。
評価基準は後述します。

また、他のアイデアが浮かんだりすれば、自由に追加して大丈夫です。
画像もコピーペーストできるように、素材ごとに分けてあります。
(と言っても、今回のは組み合わせて別の案が生まれるタイプではないので難しいかも)
(参考画像が3枚以上あれば、なんとなく想像して、他のと同じテイストで作ります)

**Comment by takasusuke** [comment]
### 評価のねらい
- 各案に対する段階評価にすることで、得点が過剰に大きくならない
- 似た案があっても得点が過剰に小さくならない
- 7案に対して、5段階評価なので、重複を許して緩やかに順位付けができる

### 評価基準(目安)
-2 : 面白くない。あまり想像できない。ゲームに合わない。個人的に好みでない。など
-1 : 現時点で課題が浮かぶ。強みがない。など
0 : 特に悪いところはない。他の案と比較するときの基準。
1 : 改善次第でもっと良くできる。強みがある。など
2 : ゲーム画面が想像つく。個人的に好み。他と比べて最も良い。など

### お願い
- 必ず1つ以上は[-2]の評価をつけてください
- 必ず1つ以上は[2]の評価をつけてください

**Comment by takasusuke** [comment]
### 評価テンプレート
1案(同心円状)
[x] : ○○だから

2案(螺旋状)
[x] : 

3案(放射状)
[x] : 

4案(ローテク)
[x] : 

5案(ハイテク)
[x] : 

6案(植物の力)
[x] : 

7案(木の穴)
[x] :

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
次回ミーティングまでお願いします。
追加アイデアは7月17日(金) 23:59まででお願いします。

**Comment by xiii111** [comment]
お疲れ様です．金曜にみようと思っているので，その時に追加アイデアを出せたら出そうと思います！

**Comment by xiii111** [comment]
1案(同心円状)
[-2] : 
- 他に比べて質素
- UI 感がすごいかも
- タイムマシンのイメージは良いなって思う

2案(螺旋状)
[2] : 
- わかりやすい
- 曲がりながら吸い込まれていく感じと渦がフィットしている
- 現状のアニメーションと同じなので，イメージしやすく変じゃないのも経験している
- 粒子が飛ぶ感じも良い

3案(放射状)
[-1] : 
- 少しチカチカする
- 回転せずに吸い込まれていくのは悪くないけど，ちょっとシンプル
- 引力？みたいな世界観なのかな？ちょっと吸い込まれるイメージが湧かない

4案(ローテク)
[1] : 
- 発想がとても好き
- アニメーションが動作とリンクしている
- 少し世界観に合わず浮いているか？
- アニメーション時間が長くなりそうで，心配

5案(ハイテク)
[-1] : 
- ぼやけていく雰囲気は悪くない
- 他のほどなぜ移動するのかに納得感がない
- アニメーション時間が長くなりそうで，心配

6案(植物の力)
[1] : 
- 世界観はとても良い
- 消え方に躍動感が少ないかも
- 通常時の画像が，もう少しグラデーションや葉っぱの移動アニメーションによって良くなりそう
- 抽象的な表現な分，提案段階で優れたものを出すのは難しそうなので，期待も込めてこの点数

7案(木の穴)
[1] : 
- 世界観にとてもフィットしている
- 背景色が通常タイルと同じなので，初めからボトルがある場合に視認しづらそう
- 吸い込まれていく雰囲気も分かる
- A-a，B-b の表現に色を使いづらそう

**Comment by takasusuke** [comment]
### 評価テンプレート
1案(同心円状)
[0] : 見慣れすぎてこれが普通になっている。特に良いところも悪いところもない。背景色を紫から変えればそこそこ良い。

2案(螺旋状)
[1] : 色味を参考画像くらい明るくして、今の渦巻(水)っぽさを減らせば良さそう。螺旋回転のモチーフは、ワープとして一般的に想像つく形状な気がする。

3案(放射状)
[-1] : 主張しすぎな気がする。Bottleとかを見てもらえなくなりそう。消えるエフェクトは良い(タップ時とか別のことに流用できそう)

4案(ローテク)
[2] : 回転とかの他の抽象的なものではなく、具体的なコンセプトなので良い。自然モチーフと反するのが減点ポイントではあるが、ワープとか自然に存在しないので割り切れば良いかと思う。

5案(ハイテク)
[-2] : 特に強みがない。Bottleが透明になっていく様子は悪くはないが、シンプルにまとまりすぎてる。

6案(植物の力)
[-1] : ちょっとごちゃごちゃしすぎてる。

7案(木の穴)
[1] : 世界観は良い。逆に、木の穴に吸い込まれる、というコンセプトがしっかりしている分、吸い込まれてワープする？どういうこと？と思うところもある。

**Comment by takesi0627** [comment]
1案(同心円状)
[1] : 今のままでも結構いいが、他のタイルと合わせるのは難しい
 
2案(螺旋状)
[2] : わかりやすい。見れば吸い込まれるなーと思っちゃう。

3案(放射状)
[-2] : ぱっと見ワープするとは想像しづらいかもしれない。

4案(ローテク)
[0] : ちょっと地味

5案(ハイテク)
[1] : 映える。

6案(植物の力)
[2] : モチーフがいいし、アニメーション映えそう。けど通常時のアニメーションを工夫しないと分かりづかいかもしれない。

7案(木の穴)
[2] : モチーフ的は最高。でも通常時にアニメーションもつけたいですね。渦巻的な

**Comment by takasusuke** [comment]
### 評価まとめ
|案の番号|@xiii111|@takasusuke|@takesi0627|平均点|標準偏差|
|---|---|---|---|---|---|
|1案(同心円状)|-2|0|1|-0.33|1.25|
|2案(螺旋状)|2|1|2|1.67|0.47| 
|3案(放射状)|-1|-1|-2|-1.33|0.46|
|4案(ローテク)|1|2|0|1|0.82|
|5案(ハイテク)|-1|-2|1|-0.67|1.25|
|6案(植物の力)|1|-1|2|0.67|1.25|
|7案(木の穴)|1|1|2|1.33|0.47|

**Comment by takasusuke** [comment]
評価方法改善点
- 総合的な点数をつけるだけでなく、共通して評価できる項目(見やすさ・わかりやすさ・世界観など)を追加する、ただし、人によりどの項目を重視するかが異なるので何かしら対策は必要
- 特に推したい案、特に否定したい案については、pt上限・加減を設けずに、重み付けをできるようにした方が良いのではないか

**Comment by takasusuke** [comment]
https://drive.google.com/drive/folders/1s9Tm9U1bUUob3oFrV0_SxJUDit7_j39M

**Comment by takasusuke** [comment]
2案に決まりました。
この画像を組み込んでイシューを閉じます。
