### ISSUE TITLE
Normal(Life >= 2)Bottleのデザイン

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#431]
資料を作る

今までのBottleをまとめた資料を作る
(既にスライドはある。これがいったん最後のBottleスライドなので明示しておく)

**Comment by takasusuke** [comment]
資料
https://docs.google.com/presentation/d/1bsSJUfJsb6_2F4GxRJfBnM8PsG6wlr2pZGhCTqfd-BI/edit#slide=id.g8b30c1b0f2_0_24

**Comment by takasusuke** [comment]
6つの案があります。
絵柄などでは決めず、コンセプトを意識するようにしてください。

AttackableDynamicBottleにもLife機能をつけるのかによって、見た目の評価が変わると思います。
(AttackableDynamicBottleにも適用すると、表現の幅が少し狭くなる)
基本的に、AttackableDynamicBottleにもLife機能はあると思って考えています。
もし、コンセプトは良いけど、AttackableDynamicBottleには合わないな、ということがあれば、AttackableDynamicBottleのLife機能を撤廃することも考えても良いかな、と思っています。


評価の方法としてコメントの他に、1人10ptを、好むものに重みをつけて割り振ってください。
例)
1番 : 0pt
2番 : 6pt
3番 : 2pt
4番 : 0pt
5番 : 1pt
6番 : 1pt

**Comment by takasusuke** [comment]
次のミーティングまでで構いません。
後、7番以降の案として、コンセプトも募集しています。
(草案担当にならなかったからといって、アイデアを出してはいけないわけではないので)

他の案と比較するためにも、言ってくれれば同じテイストで形にします。

**Comment by takasusuke** [comment]
評価テンプレート
--------------
1番(液体の色で表現する) : Xpt
2番(液体の量で表現する) : Xpt
3番(残りLifeをマークの個数で表す) : Xpt
4番(残りLifeを表すマークをつける) : Xpt
5番(残りLifeを数字で表す) : Xpt
6番(当たっても耐える感じ) : Xpt

**Comment by xiii111** [comment]
> もし、コンセプトは良いけど、AttackableDynamicBottleには合わないな、ということがあれば、AttackableDynamicBottleのLife機能を撤廃することも考えても良いかな、と思っています。

承知

**Comment by xiii111** [comment]
> 現実的に、どのくらいのLifeを設定するのかも考えてみてください。

あえて，スライドを見る前に述べると，多くても3かなーと思っています

**Comment by xiii111** [comment]
僕は7,8番を加えて，12pt入れます

1番(液体の色で表現する) : 0pt → NormalBottle と被る
2番(液体の量で表現する) : 1pt → 量が減るのが悪いこと = 納得．しかし，割れずに減る理由がわかりづらい
3番(残りLifeをマークの個数で表す) : 4pt → ハート好き
4番(残りLifeを表すマークをつける) : 0pt → 単純比較で3番に勝てない
5番(残りLifeを数字で表す) : 0pt → 7番に負ける
6番(当たっても耐える感じ) : 0pt → 7番に負ける
7番(5番+6番)：7pt → 押しを組み合わせたからそりゃ高い．ヒビが入るのは納得の世界観．さらに，数字を書くことでわかりやすさも十分

また，AttackableDummyBottle は life なくても良いかなと思う．3番では表現困難．2番 + 7番に関しては，今のAttackableDummyBottle の見た目でわかりやすく表現するのは簡単ではなさそう．

**Comment by xiii111** [comment]
提出しました！各デザインめっちゃ凝ってて感動したわ．特にハートと数字！よかった

**Comment by takasusuke** [comment]
7番に参考画像を追加しました。
8番の案を追加しました。

@xiii111 案の数 * 2pt、という感じで評価してみようかな、と思ったので可能なら、8番まで含めた16ptで再度振り分けお願いします。

**Comment by xiii111** [comment]
@takasusuke https://github.com/LITO-apps/Treevel-client/issues/431#issuecomment-655003503 のコメントを修正しました．8番を追加し，16ptで振り分けるようにした．

**Comment by takesi0627** [comment]
1番(液体の色で表現する) : 0pt -> わかりづらい
2番(液体の量で表現する) : 0pt -> 6に負ける 
3番(残りLifeをマークの個数で表す) : 8pt -> 個数変更してもデザインは増えない＋かわいい
4番(残りLifeを表すマークをつける) : 0pt -> UI感多め
5番(残りLifeを数字で表す) : 0pt -> UI感多め
6番(当たっても耐える感じ) : 4pt -> ボトルのコンセプトに合う
7番(5番+6番)：2pt -> UIありであればこれ
8番(残りLifeを花(葉)の枚数で表す)：4pt -> 世界観にあう

* ライフは多くて5かな。
* 評価基準：ここはなんかあんまりUIっぽいものを入れたくないので数字もしくはゲージなどUI感あるもので表現するのは避けたい。
* ライフ付きAttackableDummyBottleのデザイン：爆弾というモチーフだからよくあるタイマー爆弾みたいな感じでカウントダウンするのはいかがでしょうか。（テキストですみません。ちょっと探したけど適切なイラスト見つからなかった）

**Comment by takasusuke** [comment]
1番(液体の色で表現する) : 0pt -> 見づらい
2番(液体の量で表現する) : 0pt -> 原理がわからない
3番(残りLifeをマークの個数で表す) : 2pt -> ごちゃごちゃしないか心配はある
4番(残りLifeを表すマークをつける) : 1pt ->数字ほど説明的でなく、かつ、わかりやすい
5番(残りLifeを数字で表す) : 2pt -> わかりやすい
6番(当たっても耐える感じ) : 5pt -> Bottleの性質が反映されている
7番(5番+6番) : 3pt -> 数字だけ、ハートだけの問題点は改善されている
8番(残りLifeを花(葉)の枚数で表す) : 3pt -> 世界観を強められる

**Comment by takasusuke** [comment]
評価方法の問題点メモ
- 似た案が複数ある時、その中で最も良い案が似た他の案のptを全て加算されptが過大になることがある
- 似た案が複数ある時、似た案でptが分散されてしまし、似た案のない案が相対的に高いptになることがある
改善方法メモ
- 各案に対して、5段階などで評価をつける
- 各案のpt上限を設ける

**Comment by takasusuke** [comment]
pt集計結果
1案 : 0 : 0 : 0 : 0pt
2案 : 1 : 0 : 0 : 1pt
3案 : 3 : 8 : 2 : 13pt
4案 : 0 : 0 : 1 : 1pt
5案 : 0 : 0 : 2 : 2pt
6案 : 0 : 4 : 5 : 9pt
7案 : 9 : 2 : 3 : 14pt
8案 : 3 : 4 : 3 : 10pt

**Comment by takasusuke** [comment]
上から1~3位
8案
3案
7案

**Comment by takesi0627** [comment]
1位： 3
2位： 8
3位： 7

**Comment by xiii111** [comment]
1位：7番
2位：8番
3位：3番

**Comment by takasusuke** [comment]
3案, 7案, 8案についてメリット、デメリットを述べてください。
その文章をそのまま資料に載せます。

8案については、他のと同じヒビを入れた画像に変えます。

**Comment by xiii111** [comment]
### 3案
#### メリット
- 可愛い
- ライフである感じがわかる
- UI 感がない

#### デメリット
- なぜライフが減るのかわからない
- 背景色によっては見づらい

### 7案
#### メリット
- ヒビが入ることが割れる兆候だとわかりやすい
- 左上の数字であと何回で割れるのかわかりやすい
- 数字をハートで囲うことでポップさも表現

#### デメリット
- 数字を使うことで UI 感がある

### 8案
#### メリット
- ヒビが入ることが割れる兆候だとわかりやすい
- 左上の花弁であと何回で割れるのかわかりやすい

#### デメリット
- 花びらで即座にあと何回かを視認しづらい

**Comment by takasusuke** [comment]
3案
メリット
- ライフって感じが伝わる
デメリット
- Bottleの色ごとにハートの色を変える手間がかかる

7案
メリット
- ヒビ、というBottleの性質に沿っている
- 一目で残りライフがわかる
デメリット
- 説明的

8案
メリット
- ヒビ、というBottleの性質に沿っている
- モチーフが植物なので、という世界観を強めることができる
- 季節ごとに見た目を変更することができる
デメリット
- 初期ライフが2, 3, 4, 5の時で異なる画像を作成する手間がかかる

**Comment by takasusuke** [comment]
@takesi0627 コメントよろしく〜〜

**Comment by takesi0627** [comment]
### 3案
#### メリット
* シンプルで残りライフ数が伝わる
* 初期ライフが可変でもデザイン工数は増えない
* 可愛い

#### デメリット
* 背景によってみづらくなるので、背景ごとに色を変えないといけない
* ヒビみたいにボトルに合う世界観ではない

### 7案
#### メリット
* 一番わかりやすい
* ヒビはボトルという世界観に合う

#### デメリット
* UI感が強い

### 8案
#### メリット
* 花や葉っぱは世界観に合う
* さらにヒビはボトルのコンセプトに合う


#### デメリット
* 3案と比べると少しシンプルさが失った
* 初期ライフの数ごとに画像の変化パターンを用意しないといけない

**Comment by xiii111** [comment]
@takasusuke `_N` ラベルよろ

**Comment by takasusuke** [comment]
@itochico 
Bottleの資料(以下URLの1p-8p)を作成しました。
https://docs.google.com/presentation/d/1bsSJUfJsb6_2F4GxRJfBnM8PsG6wlr2pZGhCTqfd-BI/edit#slide=id.g8c1e9b31cf_1_41

草案についてのミーティングでどう頑張っても候補が3つから絞れなかったため、
5p・6p・7pに１つずつ、案が記載されています。

それぞれの案についてのメリット、デメリットも記述してあるので、
それらや、描きやすさ、好みなどから1つを決めていただけないでしょうか。

全員どの案になっても納得できるので、是非独断で決めて欲しいです。
よろしくお願いいたします。

(決まったら、別途まとめ資料に記述します)

**Comment by takasusuke** [comment]
通常のBottleの左上に、ハート型のアイコンを付与、さらに残りライフに応じてヒビの装飾を加えることで残りライフが伝わるデザインに決まりました。
資料(以下)は更新してあります。
https://docs.google.com/presentation/d/1bsSJUfJsb6_2F4GxRJfBnM8PsG6wlr2pZGhCTqfd-BI/edit#slide=id.g8c1e9b31cf_1_19
