### ISSUE TITLE
AttackableDynamicBottleのデザイン草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#433]
資料を作る

**Comment by takasusuke** [comment]
資料
https://docs.google.com/presentation/d/1qkyYatH5_bIvkQpRyFLMLc7zUkS9pI5cIKvjEUXBW5Y/edit#slide=id.g893ab52d98_0_6

**Comment by takasusuke** [comment]
@xiii111  @takesi0627 

6つの案があります。
２つ以上に肯定的な意見、２つ以上に否定的な意見くらいの気持ちでコメントお願いします。

**Comment by takasusuke** [comment]
次回ミーティングまでで構いません。

**Comment by xiii111** [comment]
@takasusuke コメントしました！結論としては 6 つの案のうち，5番目が良いです！

**Comment by xiii111** [comment]
@takasusuke これっていつ閉じる？

**Comment by takasusuke** [comment]
閉じ忘れ！
