### ISSUE TITLE
StaticBottleのデザイン草案

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#434]
資料を出す
他Bottleと同様

**Comment by takasusuke** [comment]
資料
https://docs.google.com/presentation/d/1qQub-NuQX0xEY46IS-kLtfmfsy_kN6z2hahx4_l9ORg/edit#slide=id.p

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
コメントよろしくお願いします。
5つの案があります。
可能なら１位から5位のランキングをつけてください。
(4位とか5位は適当でも良い)

**Comment by takasusuke** [comment]
次回ミーティングまで

**Comment by xiii111** [comment]
#### ランキング
1位：岩とか石のモチーフ（4番）
- 世界観にもあってる，動かないのも納得．
2位：記号的、BottleではなくTileとしての機能（5番）
- 工事現場みたいなマークは動かないというか，進入できないことがわかる．ちょっと無機質すぎるけど
3位：瓶が重たそうな見た目をしている、超頑丈そうな素材（1番）
- 動かなそうという意味では納得だけど，岩とかほどの納得感がない．
4位：瓶が自然モチーフなもので固定されている（3番）
- 一時的に動かない感じは表現できてるけど，ずっと動かない感じがない．あとボトル割れちゃいそう
5位：瓶が人工的に固定されている（2番）
- なんか動かない感はあるんだけど，ボトルが割れちゃいそう．あとは，鎖が巻かれてても別に動くよね・・・？

**Comment by takasusuke** [comment]
思いついてしまったので6番の案を追加しました。(3番の案に近いです)

**Comment by takasusuke** [comment]
1位 : 瓶が地面に刺さっている(泥、砂)(6番)
2位 : 岩とか石のモチーフ(4番)
3位 : 瓶が重たそうな見た目をしている、超頑丈そうな素材(1番)
4位 : 記号的、BottleではなくTileとしての機能(5番)
5位 : 瓶が自然モチーフなもので固定されている(3番)
6位 : 瓶が人工的に固定されている(2番)

**Comment by xiii111** [comment]
https://github.com/LITO-apps/Treevel-client/issues/434#issuecomment-652494179 のランキングを修正しました

**Comment by takasusuke** [comment]
スライドにコメントしていますが、ボトルは`DynamicBottle`と同じもの(白い不透明な瓶)を用いることも視野に入れています。

**Comment by xiii111** [comment]
> スライドにコメントしていますが、ボトルはDynamicBottleと同じもの(白い不透明な瓶)を用いることも視野に入れています。

この辺を考慮しても，岩が圧倒的ですね．1位 >>> 2位以下という感情です

**Comment by takesi0627** [comment]
1位：岩とか石のモチーフ（4番）
2位：瓶が地面に刺さっている(泥、砂)（6番）
3位：瓶が重たそうな見た目をしている、超頑丈そうな素材（1番）
4位：瓶が人工的に固定されている（2番）
5位：瓶が自然モチーフなもので固定されている（3番）
6位：記号的、BottleではなくTileとしての機能（5番）

**Comment by takasusuke** [comment]
ptまとめ
瓶が重たそうな見た目をしている、超頑丈そうな素材(1番)
12pt
瓶が人工的に固定されている(2番)
5pt
瓶が自然モチーフなもので固定されている(3番)
6pt
岩とか石のモチーフ(4番)
17pt
記号的、BottleではなくTileとしての機能(5番)
9pt
瓶が地面に刺さっている(泥、砂)(6番)
14pt

**Comment by takasusuke** [comment]
岩とか石のモチーフになりました。
