### ISSUE TITLE
DynamicBottleのデザイン草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#435]
資料を作る

**Comment by takasusuke** [comment]
資料
https://docs.google.com/presentation/d/1N4X_U2YpGb74cvLoL84AzYAWyGBKRL0DcMNyKH1kpRM/edit#slide=id.g8a72795a62_0_106

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 

1\~4の案を出しました。
1\~4の案も液体の有無(資料参照)があるので、細かく分けると8案になります。どれが良いかコメントしてください。

**Comment by xiii111** [comment]
@takasusuke コメントしました！

**Comment by takesi0627** [comment]
@takasusuke コメントしました

**Comment by takasusuke** [comment]
資料を修正しました。
