### ISSUE TITLE
レベル選択画面の背景のデザイン草案

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#436]
### 終了条件
- 資料を作る
- 資料に基づいてデザインを決定する
- LevelSelectSceneに仮画像を組み込む
- 仮画像を組み込んで、道や木の位置を微修正する

### 考慮事項
- 季節ごとに背景が連続的に変更？
- 季節ごとに背景が離散的に変更？
- 道の色合いを季節ごとに変更？
- 主となる色を決定
- 花や草などの装飾品を決定
- 資料作成の段階では、特にクリア状況に応じて変更したりはしない

**Comment by takasusuke** [comment]
考案する背景概要
- 同じ道、同じ木を配置して背景だけ変化させた案を作成する
- 道の色を季節によって変化させるかどうかは道の実装で考えることとする

資料(5/6個作成中)
https://docs.google.com/presentation/d/15gjknD8VwkrRpeEpMUnzI0Ewbz8EWAtzvXifUZlU57k/edit#slide=id.g8d53e76cca_0_80

**Comment by takasusuke** [comment]
|案|点数|
|---|---|
|1案| 0 |
|2案| 0 |
|3案| 0 |
|4案| 0 |
|5案| 0 |
|6案| 0 |

コメント
1案 : 
2案 : 
3案 : 
4案 : 
5案 : 
6案 :

**Comment by takasusuke** [comment]
各案に点数(-3・-2・-1・0・1・2・3)をつけてください。
少なくとも1つに0点をつけてください。0点の案を基準に他の案に評価してください。
点数の理由をコメントで補足してください。

**Comment by takasusuke** [comment]
背景案について、
世界観の提案という形です。
案によって細かな装飾の量が異なっていますが、そこら辺は出来るだけフラットに考えてください。


@xiii111 @takesi0627 
かなり遅くなってしまったので、今日のミーティングで決まればいいけど、
依存するタスクもないので来週でも良いです。

**Comment by xiii111** [comment]
考慮事項の 
> 特にクリア状況に応じて変更したりはしない

ですが，これは確定ってことですかね？？

**Comment by takasusuke** [comment]
> 考慮事項の
> 
> > 特にクリア状況に応じて変更したりはしない
> 
> ですが，これは確定ってことですかね？？

あ、それは資料作成段階ではクリア後の見た目とかは考えてない、という意味です。
（個人的には、木の非解放→解放では背景もグレーから色がつくとか、簡単な変化は工数もかからなさそうだし良いかなと思います。
解放→クリア、は工数かかりそうなので、木のアニメーションで何とかして背景は変わらなくても良いかなと思っています）

**Comment by takasusuke** [comment]
背景案見たらわかると思うんですけど、案によっては道が浮くので、
基本は、前に決めた道のテクスチャを使って、背景に合わせて、色くらいは変えるかなと思います。
（多少、背景側も、もう少し道に寄り添うものにはする）

**Comment by xiii111** [comment]
### 評価
|案|点数(-3 ~ 3)|
|---|---|
|1案| 2 |
|2案| 2 |
|3案| -2 |
|4案| 2 |
|5案| 1 |
|6案| 0 |

### 全体コメント
- 全体的に良すぎます．選べないくらい良いのばっかです
- あくまでも世界観にフィットすることを意識しました
- とは言いつつも，世界観だけに囚われることなく，直感的な思いも含めました

### 個別コメント
1案 : 
- カッケーーーーー．この立体感凄すぎる！！これがいい！！！！！
- 自然観はないけど，他のゲームの標準的な背景 UI と一線を画していて，良いなって思いました！
- 道の繋がりが，地面の有無と連動していてわかりやすい

2案 : 
- 一番オーソドックス
- 世界観と完全にフィット
- あえて言うなら，季節間の違いを作りづらいか？

3案 :
- ドットが懐かしくて好きです
- 世界観を考えると，少し合っていないと思って，基準値以下を付けました
- 各ドットの配色も素晴らしいので，マイナス評価をつけることが心苦しいです

4案 : 
- これもいいですねぇ・・・世界観を崩さないだけじゃなく，島という工夫がある
- 島の外に新しい木を追加したりできそう（しかも島の外ということがワクワクにつながる）
- 季節間の違いを出しやすそう

5案 : 
- 滝があるのが良いですね！4案と似た良さを感じます！
- 4案の方が直感的に良いなと感じたので，1にしています

6案 : 
- 斬新でとても良い！とても好き・・・だが，世界観へのフィット具合を考慮して，基準の 0 とした
- 1と似た独自性がある．こういうゲームも作りたいと思うくらい

**Comment by takesi0627** [comment]
## 採点
|案|点数(-3 ~ 3)|
|---|---|
|1案| 2 |
|2案| 0 |
|3案| -1 |
|4案| 1 |
|5案| 3 |
|6案| 2 |

## コメント
1案 : 
* 独特の世界観を感じる
* 木がリアルだが別の世界観に溶け込んでいて最高

2案 : 
* ポップで可愛い
* 季節に変化ないから木ごとに区切りがつかない感じ。（そもそも区切る必要あるか？）

3案 : 
* 背景がドット絵というコンセプト？あんまりわからない・・・

4案 : 
* 領域繋がってもはっきり季節ごとがわかるのがすごい
* 拡張性は5より劣れているが、その代わりに島がいっぱい積み込んでいてリッチな感じがして最高。

5案 :
* 一覧のページからすごく吸い込まれた。最高
* 拡張性も良さそう、季節ごとに木を生やせるのは最適かも
* 拡張性がある反面に、空いている領域が多く少し寂しさがある 

6案 : 
* 1案と位置付け大体同じ、独特な世界観で最高。





##### 結論
~2と3以外全部最高~

**Comment by takasusuke** [comment]
|案|点数(-3 ~ 3)|
|---|---|
|1案| 1 |
|2案| 0 |
|3案| -2 |
|4案| 1 |
|5案| 2 |
|6案| -1 |

### コメント
1案 : 
- 各木ごとに足場があるので、それぞれの木が際立つ
- 道も表現しやすい
- もう少し世界観に沿う、自然感が強まると良し
2案 : 
- 基準として、無難なアイデアから作ったので、特に強みも弱みもなし
- 道との相性は良い
3案 : 
- ドット絵とか、3Dグラフィックなら映えるけど、今回のコンセプトには合わない
4案 : 
- 木の大きさが相対的に小さいので、旅って感じがする。世界観に合う。
5案 : 
- 画面中央(春夏秋冬の中央)のスペースが活かされている
6案 : 
- 同じく記号的な1案よりも、無機質になりすぎて、世界観に合わなさそう。

**Comment by takasusuke** [comment]
### 評価まとめ
| 案 | @xiii111 | @takesi0627 | @takasusuke | 合計|
| --- | --- | --- | --- | --- |
| 1案 | 2 | 2 | 1 | 5 |
| 2案 | 2 | 0 | 0 | 2 |
| 3案 | -2 | -1 | -2 | -5 |
| 4案 | 2 | 1 | 1 | 4 |
| 5案 | 1 | 3 | 2 | 6 |
| 6案 | 0 | 2 | -1 | 1 |

**Comment by takasusuke** [comment]
4案を主として、季節ごとに島を分ける感じの案を再考。
4つの島の中心が空いていると微妙な感じがするので、そこは一考。

**Comment by takasusuke** [comment]
案を再考しました(資料4~6P)
https://docs.google.com/presentation/d/15gjknD8VwkrRpeEpMUnzI0Ewbz8EWAtzvXifUZlU57k/edit#slide=id.g916f0387ab_0_25

4Pの感じでいかがでしょうか
(右側を先に描いたけど、やりすぎたか？と思って左側も乗せておく)
@xiii111 @takesi0627 御一見ください

**Comment by xiii111** [comment]
@takasusuke みました．すごく良い！！！！

**Comment by takesi0627** [comment]
最高です。右側やりすぎと感じるのも理解できるが、左側だとちょっと寂しくなるので、右側でもう少し控えめな感じがいいかもしれません

**Comment by takesi0627** [comment]
とはいえ、今修正する必要はないです
