### ISSUE TITLE
レベル選択画面の道のデザイン草案

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#437]
### 終了条件
資料を作る

### 考慮事項
- 非解放時、解放時の道の案
- 道にアタッチする画像および、それが道としてレンダリングしたときの想定図を考える
(一旦、Unityで画像をアタッチする、というのを試した方が良いと思う)

**Comment by takasusuke** [comment]
単純な直線のアイデアの他に、こういう点線の道のアイデアを考える前に、
LineRendererでそもそも実装できるのかをこねくり回してみた。
rendering, mesh, polygonわからないからわからない。わからないからできない。

![gght](https://user-images.githubusercontent.com/26213141/88058722-d78f8580-cb9e-11ea-9f62-2f6b087512f3.png)

レベル選択画面の背景を先に考えて、ここら辺の実装はもう少し時間をかけて調べようかと思っています。

**Comment by takasusuke** [comment]
希望見えてきたので、予定通り道のデザインを考えます
<実装メモ>
- Textureをimport
- TextureのWrap ModeをRepeatに変更
これが重要
- Materialを作成し、Textureをアタッチ
- MaterialのShaderをParticles/Standard Unitに変更
公式リファレンスでは、Particles shaderがうまくいくと書かれているが、他のShaderを試したわけではない
https://docs.unity3d.com/ja/2019.4/Manual/class-LineRenderer.html
- スクリプト中で以下のような記述をすることで、線の長さに応じてTileの大きさを変えると、どの線の長さでも同じ回数のTexture(以下では"8"がそれにあたる)を繰り返すことができる
_renderer.material.SetTextureScale("_MainTex", new Vector2(8 / _distance, 1f));

<img width="230" alt="スクリーンショット 2020-07-22 6 07 36" src="https://user-images.githubusercontent.com/26213141/88107236-b7cd8100-cbe1-11ea-9985-4435d234f168.png">

**Comment by takasusuke** [comment]
資料
https://docs.google.com/presentation/d/18Dzg3id2ybkxGOS0T6bUd3ZTjPjgEGOmNhK_Gx2i-3k/edit#slide=id.g8c92d771ba_0_18

**Comment by takasusuke** [comment]
### 評価テンプレート

[name]
|番号|見やすさ|作成コスト|世界観|その他|合計|
|---|---|---|---|---|---|
|1案(単色)| 0 | 0 | 0 | 0 | 0 |
|2案(縁あり)| 0 | 0 | 0 | 0 | 0 |
|3案(自然の道)| 0 | 0 | 0 | 0 | 0 |
|4案(点線, 四角)| 0 | 0 | 0 | 0 | 0 |
|5案(点線, 丸)| 0 | 0 | 0 | 0 | 0 |
|6案(舗装)| 0 | 0 | 0 | 0 | 0 |
|7案(花の道)| 0 | 0 | 0 | 0 | 0 |
|8案(石の道)| 0 | 0 | 0 | 0 | 0 |

**Comment by takasusuke** [comment]
評価基準
- コンセプトや参考画像で判断
- それぞれの評価項目について、自分がどれくらい重要視するかの重みを[0~3]点で評価。
    - 3 : 強い主張がある
    - 2 : 重要視する
    - 1 : 基準値(特に無いならこれ)
    - 0 : 評価に影響しない、他の人に任せる
- 各項目を[-2~2]点で評価(そのほかを除く)
各項目は、評価しやすいように、共通して評価できそうな部分を抽出しただけです。他にあれば自由に評価テンプレートに追加して構いません。
    - 2 : 良い
    - 1 : 少し良い
    - 0 : どちらとも言えない
    - -1 : 少し悪い
    - -2 : 悪い
- その他の項目には[0~10]点で自由に加点
自分なりの評価基準や良い点1つにつき、1or2点で加点。大体5項目くらい加点幅あれば良いかなって感じ。
どういう点を評価したかは個別コメントで補ってください。

**Comment by takasusuke** [comment]
@xiii111 
@takesi0627 
次のミーティングまでよろしくお願いします。
評価方法が複雑になりつつあるので、今回の評価方法についての感想もミーティングで聞くかもしれません。

**Comment by xiii111** [comment]
確かに評価が複雑

**Comment by xiii111** [comment]
### 評価テンプレート

|番号|見やすさ|作成コスト|世界観|その他|合計
|---|---|---|---|---|---|
|評価の重み| 2 | 1 | 2 | 1 | - |
|1案(単色)| 1 | 2 | -1 | 0 | 2 |
|2案(縁あり)| 1 | 2 | -1 | 1 | 3 |
|3案(自然の道)| 1 | -1 | 2 | 0 | 5 |
|4案(点線, 四角)| 0 | 2 | -1 | 0 | 0 |
|5案(点線, 丸)| 0 | 2 | -1 | 1 | 1 |
|6案(舗装)| 0 | 1 | 1 | 0 | 3 |
|7案(花の道)| 2 | 0 | 2 | 2 | 10 |
|8案(石の道)| 0 | 1 | 1 | 1 | 4 |

#### 評価項目の重み基準
- 見やすさ `2`：個人的には重要視．どんなに世界観が良くても見辛かったらストレスが溜まる
- 作成コスト `1`：大切な要素だけど重要視はしたくない．折角時間に縛られず製作できているので
- 世界観 `2`：重要視．ここまで念入りに世界観を構築してきたのだから，遵守したいところ

1案(単色)
- 見やすい
- 少しシンプルすぎる
- 世界観に合わない
- 作成は比較的簡単にできそう

2案(縁あり)
- 1案と同様
- 1案に比べて縁があった方が良さそうだった（その他 +1 ポイント）

3案(自然の道)
- 世界観に合う
- 表現が難しそう
- 自然観を出すには，道だけでなく背景からも出さないといけない？
- マリオの雰囲気は結構良いよね

4案(点線, 四角)
- 1案と同様
- 1案より見づらい（線でなく点々なので）

5案(点線, 丸)
- 4案と同様
- 4案に比べて丸い方が可愛くて良さそうだった（その他 +1 ポイント）

6案(舗装)
- 自然と調和してある道なので，世界観に関しては悪くない
- 少し見づらい．道自体が細いのでごちゃごちゃな感じになってしまっている

7案(花の道)
- スライドにコメントしましたが，花が咲いている案ではなく，緑が豊かな案の方が好きです
- 世界観にあっている
- グレースケールから解放になった時に綺麗
- 個人的に推し（その他 +2 ポイント）

8案(石の道)
- 4案，5案のときの意見と似ているが，点々だと少し見づらい
- 世界観にベストマッチではないが，良い感じ
- 良い画像を作れなかったということで，下方評価している気がする（その他 +1 ポイント）

**Comment by xiii111** [comment]
@takasusuke コメントしました．
評価には苦労しましたが，その分念入りに考えることができた気がします！道でこんだけ良い案が出るのはすごいです！お疲れ様です！！

**Comment by takesi0627** [comment]
作成コストって実装コストか？それともデザインコスト？

**Comment by takesi0627** [comment]
|番号|見やすさ|作成コスト|世界観|その他|合計
|---|---|---|---|---|---|
|評価の重み| 2 | 1 | 2 | 1(固定) | - |
|1案(単色)| 1 | 2 | -1 | 0 | 2 |
|2案(縁あり)| 2 | 2 | 1 | 1 | 7 |
|3案(自然の道)| 2 | 0 | 2 | 3 | 11 |
|4案(点線, 四角)| 2 | 1 | 0 | 2 | 7 |
|5案(点線, 丸)| 2 | 1 | 0 | 3 | 8 |
|6案(舗装)| 0 | -1 | -1 | 0 | -3 |
|7案(花の道)| 1 | 0 | 2 | 1 | 6 |
|8案(石の道)| 1 | 0 | 1 | 2 | 6 |

1案(単色)
- 見やすいけどシンプルすぎる

2案(縁あり)
- 1案よりもっと見やすくなってるが、まだちょっとシンプルすぎ

3案(自然の道)
* 一番好きです
* ちょうど良いシンプルさで見やすいの割に世界観も合う。

4案(点線, 四角)
- 2案と大体同じ位置付け

5案(点線, 丸)
- 4案と似てるけど、個人的に5の方が好き

6案(舗装)
- あんまり世界観に合わないと思ったので世界観は-1にした。
- コストも高そうなので-1

7案(花の道)
- 世界観に合うが、少し複雑でした。

8案(石の道)
- 世界観に合うが、コストが高そうです。見やすさ的にも少し負け気味

全体的見ると自分はなんとなく縁がついている方が好みかもしれません。道だから外側とはっきり分かれるものが欲しいですね。

**Comment by takasusuke** [comment]
> 作成コストって実装コストか？それともデザインコスト？

デザインコストで考えてた。
確かに実装コストもあるか。。

**Comment by takasusuke** [comment]
### 評価
|番号|見やすさ|作成コスト|世界観|その他|合計
|---|---|---|---|---|---|
|評価の重み| 1 | 1 | 1 | 1(固定) | - |
|1案(単色)| 2 | 2 | -1 | 2 | 5 |
|2案(縁あり)| 2 | 2 | 0 | 3 | 7 |
|3案(自然の道)| 2 | 0 | 2 | 4 | 8 |
|4案(点線, 四角)| 1 | 2 | -2 | 0 | 1 |
|5案(点線, 丸)| 2 | 2 | 0 | 0 | 4 |
|6案(舗装)| 0 | -1 | 0 | 3 | 2 |
|7案(花の道)| 0 | -2 | 1 | 0 | -1 |
|8案(石の道)| 1 | -2 | 1 | 4 | 4 |

1案(単色)
- フッターのボタンとか木にこだわるなら道は装飾少ない方が画面がごちゃごちゃしないのではないか。
- ただ、2案くらいには何か装飾あった方が良い気がする

2案(縁あり)
- シンプル
- 1案より少し良い

3案(自然の道)
- シンプル
- 2案より、世界観に沿っている
- そんなに作成コストも多くない

4案(点線, 四角)
- 無機質な感じがする

5案(点線, 丸)
- 無機質な感じがする

6案(舗装)
- 道らしさはあるが、人工感が否めない
- 自然自然な世界観ではなく、これに合わせる背景とか世界観を考える、という意味では良いかも。

7案(花の道)
- 背景と混ざらないか心配、背景をこの感じにする方が良いのではないか。

8案(石の道)
- 参考画像の石の道の感じだとピンとこない
- 6案と混ざる形だけど、石畳のような道なら想像が膨らむ。

**Comment by takasusuke** [comment]
評価方法改善案
- 評価をしやすくするために、いくつかの観点を抽出したが、その合計値と自分のなかの順位が必ずしも一致しないことがある
    - 総合点のみつける形に戻して、抽出した観点はコメントの際に意識する程度で良かった気がする

**Comment by takasusuke** [comment]
各評価の順位表
|名前 | @xiii111 | @takesi0627 | @takasusuke |
|---|---|---|---|
|1案| 0 | 0 | 3 |
|2案| 0 | 0 | 2 |
|3案| 0 | 0 | 1 |
|4案| 0 | 0 | 7 |
|5案| 0 | 0 | 4 |
|6案| 0 | 0 | 6 |
|7案| 0 | 0 | 8 |
|8案| 0 | 0 | 4 |

**Comment by takasusuke** [comment]
３案になりました。
stretchでtextureを貼ります。
