### ISSUE TITLE
クリア状況によってレベル(木)の表示を変える

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#438]
## 終了条件
- レベル選択画面の木に属する全てのステージをクリアしたときに、木をクリア状態にする
- レベル選択画面の木のクリア状態・解放状態に基づいて木の見た目を変更する

**Comment by takasusuke** [comment]
木は
- 非解放
- 解放
- クリア
の3状態だと思っていたけれど、
- 非解放
- 解放
- 仮クリア
- 全クリア
の4状態もありでは？？

Spring1-Summer1の道を解放するために、
[Spring1, Spring2, Spring3]を100%クリアするの大変だけど、
[Spring1, Spring2, Spring3]を80%クリアしたらOKな仕組みにしないかな？

**Comment by takesi0627** [comment]
良さそう
クリアステージ数で解放する感じかな
