### ISSUE TITLE
レベルのデータ構造を提案し、依存関係を実現する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#440]
終了条件
- どの木をクリアしたら、どの木を開放するのか
- 1-1-1とかでステージの情報をplayerprefsに登録する

**Comment by takasusuke** [comment]
## 仕様案
- 木は、その木を解放するための木の情報を持たない。木を結ぶ道が、その道を解放するための木の情報を持つ。道が解放されたとき、道の終点の木を解放する。
(`LevelSelectDirector`が良い感じに道を解放する。解放された道が木を解放する流れ。)
- Stageは、そのStageを開放するためのStageの情報を持たない。Stageを結ぶ道が、その道を開放するためのStageの情報を持つ。Stageが解放されたとき、道の終点のStageを解放する。
- StageはIDを持たない。IDが必要ならUnityが与える`Instance ID`とかを用いる。連番とかで意味のあるIDの必要性が思いつかなかった。
- `LevelSelectScene`から`StageSelectScene`に`Level(Season)`と`TreeName`の情報を送る。
- クリア情報とかは、`TreeName_StageNumber`とかの文字列をkeyにして格納する。`TreeName`から`Level(Season)`は一意に決まるので、`Level_TreeName_StageNumber`である必要はない。

### 擬似実装(読まなくても大丈夫です)
#### 存在するObject(`LevelSelectScene`)
- `LevelTreeController`(木)
```
String treeName; // 木の名前
ELevelName level; // レベル(季節)の名前
bool released; // 解放されているかどうか
void TreeButtonDown(); // 選択されたら木の名前とレベルの名前を`StageSelectScene`に送る
```
- `LevelRoadController`(道)
```
Tree startTree; // 始点の木
Tree endTree; // 終点の木
Tree[] constraintTrees; // 道を解放するためにクリアする必要のある木(int[]とかにはなるかも)
bool released; // 解放されているかどうか
void ReleaseTree(); // 道が解放されたとき、終点の木を解放する
```
- `LevelSelectDirector`(良い感じに道を解放する)

#### 存在するObject(`StageSelectScene`)
- `StageController`
```
int number; // 何番目のStageか
bool released; // 解放されているかどうか
```
- `StageRoadController`(道)
```
Stage startStage; // 始点のStage
Stage endStage; // 終点のStage
Stage[] constraintStages; // 道を解放するためにクリアする必要のあるStage
bool released; // 解放されているかどうか
```
- `StageSelectDirector`(良い感じに道を解放する)

**Comment by takasusuke** [comment]
@takesi0627 @xiii111 
道の存在も考慮したら、木と木、StageとStageの依存関係は道が持つと良いかなと思いました。
こんな感じでどうすかね。
ID周りとか。考えてると他の人が前言ってたこととかよくわからんくなってきたので、考えを文字に残してもらえると助かる。

**Comment by takasusuke** [comment]
別に実装途中で仕様変更あっても特になんとも思わないので、とりあえずこんな感じで進めるんですけど、水曜終わりまでにはコメントあると嬉しいです。

**Comment by xiii111** [comment]
> 水曜終わりまでにはコメントあると嬉しいです。

御意．今日は無理かもしれない🙏

**Comment by xiii111** [comment]
> 木は、その木を解放するための木の情報を持たない。木を結ぶ道が、その道を解放するための木の情報を持つ。道が解放されたとき、道の終点の木を解放する。
(LevelSelectDirectorが良い感じに道を解放する。解放された道が木を解放する流れ。)

前半は OK．道を解放するのは，木でも良いんじゃない？木がクリアされたら，その木に繋がってる道を全て解放する．など．

**Comment by xiii111** [comment]
> Stageは、そのStageを開放するためのStageの情報を持たない。Stageを結ぶ道が、その道を開放するためのStageの情報を持つ。Stageが解放されたとき、道の終点のStageを解放する。

良いと思う．これも Stage を結ぶ道を解放するのは，Stage でも良いかもしれない？

**Comment by xiii111** [comment]
> StageはIDを持たない。IDが必要ならUnityが与えるInstance IDとかを用いる。連番とかで意味のあるIDの必要性が思いつかなかった。

記録画面で使う可能性はあるかも？記録画面において，存在するステージを何かをもとに網羅的に取得できて，不便がないなら要らないと思うけど，どう思う？

**Comment by xiii111** [comment]
> StageはどのTreeか、という情報を持つ。

Tree はどの Level か、という情報はもたなくて良い？

**Comment by xiii111** [comment]
> Stageがその木の中で一意な番号StageNumberを持つ。

うん，これは確定だね

**Comment by xiii111** [comment]
> LevelSelectSceneからStageSelectSceneにLevel(Season)とTreeNameの情報を送る。

ふむふむ，良さそう

**Comment by xiii111** [comment]
> クリア情報とかは、TreeName_StageNumberとかの文字列をkeyにして格納する。TreeNameからLevel(Season)は一意に決まるので、Level_TreeName_StageNumberである必要はない。

なるほど．TreeName はユニークな文字列だと．なのであれば，記録画面で使う場合には，TreeName_StageNumber を使えば良いのかな？

**Comment by xiii111** [comment]
LevelTreeController(木) と LevelRoadController は，それぞれ Level が必要ないと思ったけど，どう？

**Comment by xiii111** [comment]
```
LevelTreeController[] constraintTrees; // 道を解放するためにクリアする必要のある木
```
なるほど．任意の条件で道を解放できるようにするのか．だとすると，

> 道を解放するのは，木でも良いのかな？木がクリアされたら，その木に繋がってる道を全て解放する．など．

というコメントは棄却することになる．正しい？

**Comment by xiii111** [comment]
すごくわかりやすい．全体としては，良いと思います👍 いくつかコメントしました！

**Comment by takasusuke** [comment]
> > StageはどのTreeか、という情報を持つ。
> 
> Tree はどの Level か、という情報はもたなくて良い？

持つ。記述忘れ。追記した。

**Comment by takasusuke** [comment]
> > クリア情報とかは、TreeName_StageNumberとかの文字列をkeyにして格納する。TreeNameからLevel(Season)は一意に決まるので、Level_TreeName_StageNumberである必要はない。
> 
> なるほど．TreeName はユニークな文字列だと．なのであれば，記録画面で使う場合には，TreeName_StageNumber を使えば良いのかな？

そうですねTreeNameは一意で良いかなと思ってます。
記憶画面とかで、TreeNameの他にLevelもあった方が見た目的に良いとかなら、
```
Level GetLevel(Tree tree);
```
とかのメソッドかMapかを用意しておいて、そこから取得する感じで良いかなと思っています。

**Comment by takasusuke** [comment]
> ```
> LevelTreeController[] constraintTrees; // 道を解放するためにクリアする必要のある木
> ```
> 
> なるほど．任意の条件で道を解放できるようにするのか．だとすると，
> 
> > 道を解放するのは，木でも良いのかな？木がクリアされたら，その木に繋がってる道を全て解放する．など．
> 
> というコメントは棄却することになる．正しい？

正しいと思います。
道を解放するのに複数の木のクリアが条件だったりすると、Directorがいた方がわかりやすそうと思いました。

**Comment by takesi0627** [comment]
> * 木は、その木を解放するための木の情報を持たない。木を結ぶ道が、その道を解放するための木の情報を持つ。道が解放されたとき、道の終点の木を解放する。
>   (`LevelSelectDirector`が良い感じに道を解放する。解放された道が木を解放する流れ。)

ごめん、木自身が開放に必要な木の情報を持たないのメリットはあまりわからない。そうすると、特定の木が解放されているかどうかを知りたい時にその木を所有する道を参照しないといけなくなるんじゃないか（しかも道複数ある場合もある）。ステージも同じく。

木とステージは自身の解放条件を持つのが自然だと僕は思います。

**Comment by takesi0627** [comment]
> * StageはIDを持たない。IDが必要ならUnityが与える`Instance ID`とかを用いる。連番とかで意味のあるIDの必要性が思いつかなかった。

サーバに保存する際必要になると思います。Instance IDの仕組みよくわかっていないが、多分デバイス毎に違うだろう。

**Comment by takesi0627** [comment]
> * クリア情報とかは、`TreeName_StageNumber`とかの文字列をkeyにして格納する。`TreeName`から`Level(Season)`は一意に決まるので、`Level_TreeName_StageNumber`である必要はない。

これはStage IDなしの場合で、もし Stage ID が継続に使う場合は Stage IDを keyにすればいいですよね（現状維持）

**Comment by takesi0627** [comment]
とりあえずこの3点かな、他は良さそう

**Comment by xiii111** [comment]
私の意見は終わりです．

**Comment by takesi0627** [comment]
> > > * StageはIDを持たない。IDが必要ならUnityが与える`Instance ID`とかを用いる。連番とかで意味のあるIDの必要性が思いつかなかった。
> > 
> > 
> > サーバに保存する際必要になると思います。Instance IDの仕組みよくわかっていないが、多分デバイス毎に違うだろう。
> 
> `Instance ID`はシーン生成ごとに変わるらしいのでまあ使えないことはわかったんだけど、何かしらUnityが生成するIDはあると思う。
> 調べた感じそれを使うのはめんどいかもなので、わかりやすく自作でuniqueなIDを用意しても良い。
> 
> 連番にするなら、
> 春-1のStageID: 1~100
> 春-2のStageID: 101-200
> 春-3のStageID: 201-300
> 夏-1のStageID: 1001-1100
> みたいに決めないといけないんだけど、
> 
> ```
> select * from stages where id between 201 and 300;
> ```
> 
> みたいな使い方することってある？
> StageはTreeの情報を持っていると思うので、
> 
> ```
> select * from stages where tree = "春-3";
> ```
> 
> みたいに使うならTreeごとに連番じゃなくても良いかなって。

連番じゃなくていいと思います

**Comment by takesi0627** [comment]
StageIDは連番で入れた方がいいですが、レベル順じゃなくてもいいという意味で連番じゃなくていいです

**Comment by takasusuke** [comment]
> StageIDは連番で入れた方がいいですが、レベル順じゃなくてもいいという意味で連番じゃなくていいです

んんん？？
つまり、どういうことだ。。。？

**Comment by takesi0627** [comment]
> > StageIDは連番で入れた方がいいですが、レベル順じゃなくてもいいという意味で連番じゃなくていいです
> 
> んんん？？
> つまり、どういうことだ。。。？

んんん、、なんでもないですww。とにかくTreeごとに連番じゃなくていいです！
