### ISSUE TITLE
記録画面を実装するにあたり，必要なデータの検証をする

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#442]
### 終了条件
- #421 で実装する画面に必要なデータが揃っているかを確認
- 揃っていない場合には，どこでデータを収集し，どこに保持するのかを整理
- 整理した内容をイシュー化

**Comment by xiii111** [comment]
#### 作業中

記録画面（ #421 ）に`必須の情報，ランキング画面など今後に必要そうな情報，DB から取り除く情報を以下に整理する

### 記録画面に必須の情報
- 各ステージのプレイ回数
- 各ステージのクリア有無
- 各ステージの失敗回数
- 各ステージの失敗原因
- 各ステージのフリック回数
- アプリを起動した日付リスト

### ランキング画面など今後に必要そうな情報
- ユーザ名
- 初起動時刻
- 最終起動時刻
- 初クリアまでのプレイ回数

### 要らなくなる情報
- プレイ中のステージ ID（ https://github.com/LITO-apps/Treevel-server/issues/21 ）


### 議論点
-

**Comment by xiii111** [comment]
@takasusuke @takesi0627 `議論点` について，コメントをお願いします．1時間くらいは熟考してくれると助かる．後で改変するのはとても大変．

**Comment by takasusuke** [comment]
記録画面の実装に必要なデータだけ？の議論ですか？
概要ポップアップで`全ユーザの成功率`を表示するのならば、そこも派生して考慮した方が良いと思います。
概要ポップアップはそんとき考えましょう、というニュアンスに感じました。
がしかし、`PlayerPrefs`に置く情報の話もしているので、必ずしも記録画面だけのデータの話では無い感じもして混乱しました。

**Comment by xiii111** [comment]
記録画面の話だけを独立して話すのが難しかったので、混ぜてしまいました。大丈夫ですか？

**Comment by takasusuke** [comment]
じゃあ全部込み込みで議論ということですね。了解しました。

**Comment by takesi0627** [comment]
> * データ構造と処理の流れ は適切か？
> * サーバ (DB) ( ローカル (DB) ) に保持する情報 は適切か？

* PlayDates はアプリ起動日「リスト」としているが、型は time.Time にしているのは正しいでしょうか？
ログイン日数とともにログインした日を正く全て記録したいであればもう一つ `LoginRecord`を用意した方が妥当かと思います。
```
type LoginRecord struct {
    ID        int
    PlayerID  int
    LoginDate time.Time
}
```
日数は該当プレイヤIDのレコード数から取得する。（ローカルDBだとそのテーブルの大きさになる）

もし日数だけ保存したいであれば `Player.PlayDates`を`int` 型にすればいいと思います。

* ⑤について
更新タイミングはローカルが更新される度に行うと多すぎるのは同意です。アプリの起動時と落とす時か、もしくはプレイ中に10分おきに更新するかとかで検討するといいかもしれません。

> 失敗原因 は必要か？記録画面を作っている時から必ず必要なのか？と思っていたが，このタイミングで詰めたい．データ管理が面倒なデータ

結構面白いと思ったから残したいですね。データの保存はJSON形式の文字列でどうでしょう 
```json
{
	"1" : 10,
	"2" : 15,
	"3" : 15,
}
```
こういう感じ、`失敗タイプ : 失敗回数`のペアで保存か、パースするのが面倒であれば新しいテーブル作るしかないと思いますが。

> 記録画面に 全ユーザの成功率 は必要か？

概要ポップアップも表示される予定なので、
取れるであれば見せておくのも良いじゃないかと思いました。


> プレイ中のステージ ID は必要か？

前も一度話しましたが、プレイ中クラッシュしたりするときに戻れるような仕組みあった方がいいと思うから保持したい派です。

**Comment by takasusuke** [comment]
> * `データ構造と処理の流れ` は適切か？

⑤については起動時と終了時、に加えて一定の時間間隔で保存するのは良いと思います。
⑥については現状では起動時だけでも問題ないと思います。(他の画面で表示する内容によっては更新ボタンを作るとか)

> * `サーバ (DB) ( ローカル (DB) ) に保持する情報` は適切か？

- `Player`Tableには最終ログイン日、ログイン日数の2つでどうですかね。
全てのログイン日を活用したい事例が浮かびませんでした。
最終ログイン日は、前回ログイン日からの日数に応じた何かが将来的に考えられると思いました。
- `Record`Tableの`StageId`はString？
- `Recoed`Tableの`MinClearTime`は改めて考えると必要ない気がしてきた
- `Record`Tableに初成功の日時が`FirstSucceededAt(?)`あると、ユーザがどの順番でクリアしていくのか記録できて、動線設計の参考にできるかもしれない。(個別記録画面から、全ユーザの成功率を削除すると画面が寂しい気もするので、これを表示するのもあり)

> * `ローカル (PlayerPrefs) に保持する情報` は適切か？

良さそう。

> * 記録画面に `全ユーザの成功率` は必要か？

確かに同じ情報が複数画面に存在する意味づけが弱い気がするので、記録画面には無い方が良い気がしてきた。
記録画面は個別の情報、という意味付けが出来るのも良い。

> * `プレイ中のステージ ID` は必要か？

主張はないです。保持したい意見があるなら乗ります。

> * `失敗原因` は必要か？記録画面を作っている時から必ず必要なのか？と思っていたが，このタイミングで詰めたい．データ管理が面倒なデータ

見れるとなんか嬉しいという気持ちもあるけれど、
レベル調整や新しいレベル作成の時に、参考になる指標の１つとして欲しいと思いました。
Gimmickの追加、削除に対して変更が容易なので別のTableを作っても良いと思います。
```
type FailureReasons struct {
    ID         int
    PlayerID   int
    Gimmick1   int // Gimmick1の失敗回数
    Gimmick2   int // Gimmick2の失敗回数
}
```

**Comment by xiii111** [comment]
ごめんなさい．一つ一つに返信する形では無く，二人の意見を統合しての変更点や，こうしたいということを以下に書いていこうと思います．

- `PlayDates` に関して

DB で持っていましたが，他ユーザがこの情報を必要としたり，こちらで監視したいということは多分無いので，`ローカル (DB)` に移そうと思いました．型ですが，日数だけ持てば良いので `int` にしようと思います．

- ⑤（個人データの書き込み）について

アプリの起動時，終了時は良い頻度ですね．あとは，ランキング画面を開く時なども行いたいですね．時間で送るのもありだと思います．1日送っていなかったら送るなど．

- 失敗原因について

二人とも残したいという意思を受け取りました！データの持ち方ですが，各ステージごとに収集したいので，僕は @takesi0627 側の意見に寄っています．JSON というのも賛成です．各ギミックや失敗要因に対してきちんと文字列で名前をつけ，

```
{
	"1" : 10,
	"2" : 15,
    "3" : 15,
}
```

**Comment by xiii111** [comment]
@takasusuke @takesi0627 コメントに対する返信や改正案など出してみました！明日の MTG で議論したいと思います！

**Comment by xiii111** [comment]
上記の議論が収束した後，必要なイシューを全部作ったら Close する

**Comment by xiii111** [comment]
追加収集する情報
- フリック回数
- ログイン日数
- 失敗原因
- 初クリアした日付
- 最終起動日

**Comment by xiii111** [comment]
#494 #495 #496 #497 に分離しました．
実装準備は，各種データを取り揃えることと，記録画面を仮で作り，遷移などを実現するタスクです
実装は，各画面にレイアウトを取り込むことです．

まずは， #494 から取り組もうと思います

@takasusuke @takesi0627 異論がなければ閉じようと思います．今後の方針も含めてコメントがあればお願いします．

**Comment by takasusuke** [comment]
☺️👍

**Comment by takesi0627** [comment]
実装準備タスクで仮画面作るのもいいですが、なんか実装タスクのスコープと被りそうで境目が曖昧な気がしますね。実装準備で集計結果を確認したいならログとかで確認できるまででいいんじゃないかと思いましたが、いかがでしょうか。

**Comment by xiii111** [comment]
そうします!!

**Comment by xiii111** [comment]
全てのイシューを上記のように書き換えました！閉じますね！
