### ISSUE TITLE
クリア状況によってレベルの表示を変える

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#443]
### 終了条件設定
- 2020/07/26 改めて仕様を決める。少し実装してみた結果、ステージのクリアタイミングと木の条件変更のタイミングとかをしっかり決めておかないと煩雑になりそう。
- 非解放状態
- 解放状態
- クリア状態
- 全ステージクリア状態
の4状態に応じてステージ選択画面の背景の色などを変更する

### 考慮事項
- 実装する前に仕様を決めて、コメントする
(このタイミングで、作業時間の更新を行います。[4]くらいかと思います。)
- レベル選択画面で木の状態の更新を行なっているが、ステージ選択画面で木の状態の更新が必要？
- #445 とかぶってる部分があるのでまとめるかも

### その他
* 全ステージクリアすればステージ選択画面の背景画像を変える

**Comment by takasusuke** [comment]
レベル選択画面の木の仕様案(特に大きな変更はない)
- 非解放状態
非解放状態の動作を記述するメソッドを用意
木の前面を覆う半透明のオブジェクトを表示し、ステージのButtonにactionを起こさせない(押しても反応しないのではなく押せない、カーソルを合わせても表示が変化しない)。scrollはできる。
- 解放状態
解放状態の動作を記述するメソッドを用意
今まで通り
- クリア状態
クリア時の動作を記述するメソッドを用意
ログ表示
- 全クリア状態
全クリア時の動作を記述するメソッドを用意
ログ表示


- ステージ選択画面、レベル選択画面を開くたびに、それぞれステージのクリア数に応じて木の状態を更新する。共通のライブラリを用いる。
- 状態は保持しない。クリア数を保持し、状態はクリア数から常に求める。
- 木の状態はクリア数以外に制御されない。Spring-1をクリア後、Spring-2の解放アニメーションを表示したいなら、強制的な画面遷移などで実現。Spring-2の解放アニメーションの終了がSpring-2の木の解放条件にはならない。
