### ISSUE TITLE
突風ギミックの実装

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#456]
#419 に基づく

🆕 : 0830追記

## 仕様決め
- クラス名：`GustWind`

### データ（エディタ入力）
- 方向
- 対象行／列

### プレハブパラメータ
* ボトル移動速度の倍率

### 挙動パターン
- ~**警告なし**~ ➡️  **警告あり** 🆕 
- 対象行／列にある~全てのボトル~ -> `DynamicBottle` に対して一番端に強制的に移動させる 🆕 
　・`Collider`は利用せず、`Controller`から`BoardManager`を介して移動させる
　・タイミングはアニメーションと合わせて自然になるよう調整する
- 移動する際は、移動速度の倍率で移動させる

- 移動中のボトルは対象外とする 🆕 
- 移動先のタイルに移動した時の動作は影響しないとする 🆕 

### 演出

メイプルストーリー：トルネードスピン
![unnamed](https://user-images.githubusercontent.com/17778395/90970346-bf64aa80-e53e-11ea-9653-f6672293f5f7.jpg)

これをグルグル回りながら勢いよく前進する印象
![9426B1F4-0D67-43ED-97B1-A1D3293E55DE](https://user-images.githubusercontent.com/17778395/90970348-c8ee1280-e53e-11ea-9c80-6c6211f89f50.png)

**Comment by takasusuke** [comment]
クラス名 : ○
演出 : ○
質問・意見
- 全部のBottle（StaticBottleを除く）と思ってるけど同じ？
- 警告はあった方が良いと思う
- フリック中、ワープ中などの移動中に突風が吹いた時は、そのボトルは移動しない？
- 例えばホールドしてるBottleは突風でも動かないとかは考えてる？

いくつかのユースケースについて質問
（右から左に突風が吹くとする）
（わかりやすいように5列で考える）
（空:空いているタイル、ボ:ボトル）
- ［空　空　空　ボ　ボ］のときは、［ボ　ボ　空　空　空］になるで良い？
- ［空　ボ　空　空　ボ］のときは、［ボ　ボ　空　空　空］になるで良い？

**Comment by takesi0627** [comment]
> * 全部のBottle（StaticBottleを除く）と思ってるけど同じ？

石を移動させても良いかもしれませんね。どう思いますか？

> * 警告はあった方が良いと思う

僕はこのギミックに当たっても即失敗しないから、警告なくても面白いじゃないかと思いましたが、そうとは思わないでしょうか

> * フリック中、ワープ中などの移動中に突風が吹いた時は、そのボトルは移動しない？
> * 例えばホールドしてるBottleは突風でも動かないとかは考えてる？

これについて考えてなかった。移動中のボトルは移動させないとしましょう。
 
> いくつかのユースケースについて質問
> （右から左に突風が吹くとする）
> （わかりやすいように5列で考える）
> （空:空いているタイル、ボ:ボトル）
> 
> * ［空　空　空　ボ　ボ］のときは、［ボ　ボ　空　空　空］になるで良い？

良い

> * ［空　ボ　空　空　ボ］のときは、［ボ　ボ　空　空　空］になるで良い？

良い

**Comment by takasusuke** [comment]
> > * 全部のBottle（StaticBottleを除く）と思ってるけど同じ？
> 
> 石を移動させても良いかもしれませんね。どう思いますか？

石は移動しないほうが、パズルとしては面白いと思った

> 
> > * 警告はあった方が良いと思う
> 
> 僕はこのギミックに当たっても即失敗しないから、警告なくても面白いじゃないかと思いましたが、そうとは思わないでしょうか

突風でバトルが移動した先に他のギミックがあると理不尽な気がしたので、警告はある方が良いと思いました

> 
> > * フリック中、ワープ中などの移動中に突風が吹いた時は、そのボトルは移動しない？
> > * 例えばホールドしてるBottleは突風でも動かないとかは考えてる？
> 
> これについて考えてなかった。移動中のボトルは移動させないとしましょう。

それがいいと思います
突風で動いてほしくないBottleはフリックとかワープさせとくとか出来そう


別の質問だけど、
突風で移動した先にワープタイルや蜘蛛の巣タイルがあるときなど、
突風の移動の後にタイルの効果が働くのかはどうする？
タイルの効果は働かないほうが処理としては楽かなと思った

**Comment by xiii111** [comment]
> > * 全部のBottle（StaticBottleを除く）と思ってるけど同じ？
> 
> 石を移動させても良いかもしれませんね。どう思いますか？

任意の DynamicBottle が対象の方が良い気がしました．つまり石は移動できなくて良いかなと


> > * 警告はあった方が良いと思う
> 
> 僕はこのギミックに当たっても即失敗しないから、警告なくても面白いじゃないかと思いましたが、そうとは思わないでしょうか

僕も警告はあった方が良いと思います．移動した結果，ギミックにあたってしまう可能性もありますし，意図しないことが起きるものには警告が必要な気がします（少し表現は難しいから，いろいろ調べる必要はあるかもしれないが）

> > * フリック中、ワープ中などの移動中に突風が吹いた時は、そのボトルは移動しない？
> > * 例えばホールドしてるBottleは突風でも動かないとかは考えてる？
> 
> これについて考えてなかった。移動中のボトルは移動させないとしましょう。

移動中，何かの影響が作用中は移動しないようにすれば良いと思います．例えば，蜘蛛の巣タイルの上のボトルも動かない方が良い．一方で聖域タイルの上のボトルは仕様次第．迷うところ

> > いくつかのユースケースについて質問
> > （右から左に突風が吹くとする）
> > （わかりやすいように5列で考える）
> > （空:空いているタイル、ボ:ボトル）
> > 
> > * ［空　空　空　ボ　ボ］のときは、［ボ　ボ　空　空　空］になるで良い？
> 
> 良い

ふむふむ．良さそう

> > * ［空　ボ　空　空　ボ］のときは、［ボ　ボ　空　空　空］になるで良い？
> 
> 良い

良さそう

**Comment by xiii111** [comment]
#### コメント
- 複数行，複数列を対象にしても良いと思うので `[Row]` , `[Column]` でも良いかもしれません
- すべてのギミック，ボトル，タイルと相性がよくある必要はないと思いました．同時に出現させなければ良いだけなので．突風の良さを前面に押していきましょう
- 動かない物体（岩など）の裏にあるボトルはどうしますか？
- 突風による移動仕様ですが，一気に端に行くのではなく，一定時間（短め）に一マスずつ移動するのもありだと思いました（参考動画：https://www.youtube.com/watch?v=r-xNbNtsJ1g&t=3s 4:30 あたり）

**Comment by takesi0627** [comment]
> 突風で移動した先にワープタイルや蜘蛛の巣タイルがあるときなど、
> 突風の移動の後にタイルの効果が働くのかはどうする？
> タイルの効果は働かないほうが処理としては楽かなと思った

そこは逆だと思います。 `BoardManager.Move` を利用する想定なので、ボトルがタイルに到達する時点で効果が発生するため、普通に働かせた方が楽だと思いますので、特にタイルの効果はいじらない想定です。

> 動かない物体（岩など）の裏にあるボトルはどうしますか？

処理がすごい面倒そうなので、いったん無視です。

> 突風による移動仕様ですが，一気に端に行くのではなく，一定時間（短め）に一マスずつ移動するのもありだと思いました（参考動画：https://www.youtube.com/watch?v=r-xNbNtsJ1g&t=3s 4:30 あたり）

これはただ瞬間移動だから一マスずつ移動しているように見えるのではないでしょうか。実際一気に端に行く仕様だと思います（風に当たると途中から操作できなくなる）。なめらかの移動で一つずつ移動すると変かなと思います。


> 複数行，複数列を対象にしても良いと思うので [Row] , [Column] でも良いかもしれません

特に強い要望ではなければとりあえず一行・列の仕様で行きたいですが、 @takasusuke はどう思いますか

**Comment by xiii111** [comment]
> これはただ瞬間移動だから一マスずつ移動しているように見えるのではないでしょうか。実際一気に端に行く仕様だと思います（風に当たると途中から操作できなくなる）。なめらかの移動で一つずつ移動すると変かなと思います。

いえ，風が当たって一マス動いた後に，フリックする余地があります

**Comment by takesi0627** [comment]
> > これはただ瞬間移動だから一マスずつ移動しているように見えるのではないでしょうか。実際一気に端に行く仕様だと思います（風に当たると途中から操作できなくなる）。なめらかの移動で一つずつ移動すると変かなと思います。
> 
> いえ，風が当たって一マス動いた後に，フリックする余地があります

なるほど、でもあれは風がずっと吹いているからこれで良いと思いますが、突風とはまた違うものじゃないかな

**Comment by xiii111** [comment]
> なるほど、でもあれは風がずっと吹いているからこれで良いと思いますが、突風とはまた違うものじゃないかな

承知

**Comment by takasusuke** [comment]
一行・一列に対しての突風ギミックで良いと思います

**Comment by takesi0627** [comment]
コメントをまとめて概要を更新しました。
一応これで実装進めたいと思いますが、また何か思いついた事があったらいつでもコメントしてください。宜しくお願いします
