### ISSUE TITLE
Retryするたびに特殊タイルがGamePlaySceneに増える

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#468]
# 終了条件

特殊タイルがあるステージで確認する

**Comment by takesi0627** [comment]
再現が取れましたので、修正します

![CA5FE7D4-8B9E-462E-BEAD-E921DABEF676](https://user-images.githubusercontent.com/17778395/92712810-25ea2500-f395-11ea-82d9-6294c2ad50d0.png)
