### ISSUE TITLE
`LevelSelectScene` にフォーカスされたタイミングで木の状態を更新する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#501]
### 現状の挙動と問題点
- `StartUpScene` で `MenuSelectScene` が `load` されたタイミングに木の更新しているので、アニメーションが見えない時がある

### 完了条件
- [ ] 上記の問題が解消されていること

### 再現手順
1. データをリセットする
2. 春の木をクリアする（夏の木を解放させる）
3. 実行を閉じる
4. 実行する

### 備考
- StartupSceneでMenuSelectSceneをadditiveロードしなければ良さそう

**Comment by xiii111** [comment]
一瞬で終わると意気込んでいたが、単純な修正だとボタンが押せなくなる。その辺を調査中
