### ISSUE TITLE
`OnBoarding` 画面のデザイン草案作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#503]
### 完了条件
- [ ] 草案を決める（こんなイメージだよね、が決まれば良い）

### 備考
- 初めて起動した人にのみ表示する
- iOS でいうと，[こんな感じ](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/onboarding/) のやつ
- ギミックなどのチュートリアルとは別

### 資料
- https://docs.google.com/presentation/d/15e2wcvIBoLabvvKjIMYdpzn_vbQFIBNDrU2XSP7qLP4/edit#slide=id.p

**Comment by xiii111** [comment]
@takasusuke @takesi0627 こちらでも作業を進めますが、気分転換でイメージ画像などを貼ってもらえると捗ります！

**Comment by takasusuke** [comment]
意外に奥が深いOnBoarding...
できるだけ簡潔に、動線を妨げないように、、、
でもその画面で伝えたい１つか２つはちゃんと伝わるように、、、
見せ方次第で、ユーザの継続率等に影響が出る。。。
なるほど。。。

https://developer.apple.com/jp/app-store/onboarding-for-games/

**Comment by xiii111** [comment]
その記事、素晴らしいな。今から読みます！

**Comment by xiii111** [comment]
@takasusuke @takesi0627 方向性を修正してみました。できるだけユーザの作業を妨げないように、一度でも表示したら二度と表示しなくしました。これにより、Spring-1-1 に限定したチュートリアルなどは実装できませんが（ユーザの操作によっては、一番最初にたどり着くステージが Spring-1-1 にならないから）、その必要性も高くないと思っています。詳細は定例会で話したいのですが、予め眺めてもらえると、意見を言いやすいかもしれません。よろしくお願いします。

**Comment by xiii111** [comment]
@takasusuke @takesi0627 

以下のイシューを作成しました！問題あれば言ってください
- #1139
- #1138
- #1140
- #1142 
- #1141 
- #1143

**Comment by xiii111** [comment]
@takesi0627 予め実装するメリットはなんですか？デザイン決めてからまとめてやった方が効率良いかなーって思ってました！

**Comment by takesi0627** [comment]
もちろんデザイン決めてから実装すると思いますが、
 #1140 と #1141 はある程度共通する部分はあるからその共通部分の設計、実装は別としてやっといて、#1140と#1141は画像やデータの入力だけで済むようにした方がいいかなと思いました

**Comment by xiii111** [comment]
@takesi0627 

なるほど！https://github.com/LITO-apps/Treevel-client/issues/1139#issue-994705190 のデザイン草案作成が終わったら、共通部分を実装するイシューを作成することを完了条件に含めておきました！
