### ISSUE TITLE
どのようなボトルを作るかの提案

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#507]
### 終了条件
10個程度提案して、4個選択する

**Comment by takasusuke** [comment]
資料
https://docs.google.com/presentation/d/1bY2kJhoFeTgvKSp5dKCbUdvsjCYfkna56oc1fJV_YZU/edit#slide=id.g905143e56e_0_213

**Comment by takasusuke** [comment]
10個の案を出しました。ここから4個を選びます。
5個の案に肯定的な意見、5個の案に否定的な意見をコメントしてください。

**Comment by takasusuke** [comment]
### (😄 / 😱)BigBottle
- 
### (😄 / 😱)SodaBottle
- 
### (😄 / 😱)AlcholBottle
- 
### (😄 / 😱)CoupledBottle
- 
### (😄 / 😱)StrongBottle
- 
### (😄 / 😱)ErasbaleBottle
- 
### (😄 / 😱)HoneyBottle
- 
### (😄 / 😱)VeiledBottle
- 
### (😄 / 😱)PanaceaBottle
- 
### (😄 / 😱)BabyBottle
-

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
よろしくお願いいたします。

**Comment by xiii111** [comment]
@takasusuke コメントしました！面白いアイデアが多くて楽しかったです！5つずつと書かれていたけど，絶対評価で良いと思ったやつが 6 つだったので，6 つに 😄 を付けさせてもらいました（許して🙏）

### (😱)BigBottle
- クリア判定がある場合には，目標タイルのどこか一部でも，というのが少しわかりづらいかなと思った．あとなんか面白そうと思わなかった！

### (😱)SodaBottle
- ライフが多めに設定されているとわかりづらいし，複雑だから微妙かなと思った

### (😄)AlcholBottle
- 移動方法があべこべになるの地味に面白そう．ポケモンの混乱マークみたいの付けていればちゃんと伝わりそうだし

### (😄)CoupledBottle
- 面白い．連動型ってことだね．問題があるとすれば難しくなりすぎることだけど，遊ぶ姿を想像できて楽しそうだったからアリ

### (😱)StrongBottle
- ちょっと型破りすぎる気がした．トルネードとかなら良いが隕石や雷の時に効力を示さない．影響範囲も難しいため微妙だと思った

### (😄)ErasbaleBottle
- うん，お邪魔ボトルって感じだよね．良いと思う！

### (😄)HoneyBottle
- ちょっと Honey で遅くなるのがよくわからないけど，ベタベタするからって感じであってるかな？速度が遅いボトルは面白いと思う．

### (😄)VeiledBottle
- 面白いね！パズドラとかでいうと動かした時に見え始めるやつだよね．暗闇ボトル的な意味で Darkness とかでも良いと思った！

### (😱)PanaceaBottle
- 面白いと思ったけど懸念点がいくつか挙がったから微妙な方へ．一つは，ゴールタイルを赤5つ，ボトルを赤5つにすれば難易度調整はできてしまう点．二つ目は，どこにでもいけるということをどう伝えようか．虹色とか？RainbowBottle として，どの色にも成れるって世界観ならまだ理解できるけれど．

### (😄)BabyBottle
- うん面白いな．勝手に動いちゃうから閉じ込めておかないとっていうのが良いね．名前は SelfishBottle とか良いかなと思った．Hold とかで移動するのを防ぐのはいらない気がした．クリア判定は誘導する必要が出るから面白い要素でもあるかも？

**Comment by takasusuke** [comment]
### (😄)BigBottle
- パズル感強いステージを作れて面白そうだと思いました。

### (😱)SodaBottle
- ギミックからうまく逃げるゲームなので、それを制限する機能は面白さを損なうと思いました。時間制限をつけることと似ている気がして否定的。

### (😄)AlcholBottle
- このBottleが1,2個含まれているStageは頭を使いそうで楽しそう。

### (😱)CoupledBottle
- 機能としてはパズル的で良いが、ユーザに機能を説明しづらいかな、と思う。

### (😱)StrongBottle
- ギミックを消せる、というのがゲームバランスを壊すというか、コンセプトと合わなそう。

### (😄)ErasbaleBottle
- タップという新しい操作方法が良いと思います。

### (😄)HoneyBottle
- 移動が遅いので、このBottleを優先的にギミックが逃げるように動かす戦略が面白いと思いました。

### (😱)VeiledBottle
- 機能としては面白そうだけど、イライラさせないか不安。やってみないとわからない。。。

### (😄)PanaceaBottle
- ユーザ側に優しい機能のBottleも良い気がする

### (😱)BabyBottle
- ユーザが制御できない要素があるので、イライラさせないか不安。

**Comment by takesi0627** [comment]
クリア判定あるかどうか決めづらかったらパラメータ化すると良いかもしれせん

**Comment by takesi0627** [comment]
時間足りないのですみません。コメント後で足す。あと僕もどうしても5つに絞ることはできません。ごめんなさい

### (😄)BigBottle
- 
### (😱)SodaBottle
- ライフ5つまでという制限がありながらちょっと難しい

### (😄)AlcholBottle
- 

### (😱)CoupledBottle
- ゆっくり解く系のパズルゲームなら面白が、アクション系のパズルゲームとしては適切ではないかと（詰みやすい）

### (😄)StrongBottle
- 
### (😱)ErasableBottle
- 
### (😱)HoneyBottle
- 
### (😄)VeiledBottle
- 
### (😄)PanaceaBottle
- 
### (😄)BabyBottle
-

**Comment by takasusuke** [comment]
BigBottle 2
SodaBottle 0
AlcholBottle 3
CoupledBottle 1
StrongBottle 1
ErasableBottle 2
HoneyBottle 2
VeiledBottle 2
PanaceaBottle 2
BabyBottle 2

**Comment by takasusuke** [comment]
3票
- AlcholBottle
- VeiledBottle
- BabyBottle
2票
- CoupledBottle
- ErasableBottle
1票
- BigBottle
- HoneyBottle
- PanaceaBottle
0票
- SodaBottle
- StrongBottle

**Comment by takasusuke** [comment]
ReverseBottle
- フリック方向と移動方向が逆
- 当たり判定 : あり
- クリア判定 : あり

DarkBottle
- Tap後、一定時間は色がわかる.(実装してみて微妙なら変わるかも)(Tap部分から円状に暗闇が晴れる)
- 正解の場所はそのまま色がわかる
- 当たり判定 : あり
- クリア判定 : あり

SelfishBottle
- 一定時間ごとに勝手に動き出す
- Holdしている間は動き出すまでの時間を止めることができる
- 当たり判定 : あり
- クリア判定 : あり(クリア判定があるかどうかはパラメータで与えた方が良いかも)

ErasableBottle
- 
- 当たり判定 : あり
- クリア判定 : なし

**Comment by takasusuke** [comment]
対応issueは作ってあります
#508 
#509 
#510 
#511
