### ISSUE TITLE
ReverseBottle の実装

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#510]
### 終了条件
- [ ] #507 の仕様通り，機能実装する
- [ ] （簡単な）アニメーション実装

**Comment by takasusuke** [comment]
https://drive.google.com/drive/folders/1feBP_wwzb0jT68kB_sUhA5a4mdL4j7v0
にReverseEffectの元画像を追加しました

**Comment by takasusuke** [comment]
`feature/#510-reverse-bottle`として、画像を分割してアップロードしたものをcommit, pushしました。
