### ISSUE TITLE
【設定画面】機能吟味

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#512]
* 必要・必要のない設定項目あるかの確認
* 生まれたタスクは次のマイルストーンで消化する

- [ ] 設定項目の見直し
- [ ] 必要に応じてイシュー作成

**Comment by takesi0627** [comment]
## 現状の設定項目
![image](https://user-images.githubusercontent.com/17778395/99908059-a331fe80-2d23-11eb-823a-a0d965deda1e.png)

### 問題点
* 「デフォルトへ」は何をデフォルトに戻すのはわからない
→ デフォルトに戻せる項目ごとに設置した方がいい
![1B4D701A-1688-494A-BA77-F20A79274E0A](https://user-images.githubusercontent.com/17778395/99908082-c8bf0800-2d23-11eb-8c0b-41bd56ae091c.png)

* 言語の設定はボタン二つありますけど、どっちかしか機能しないようになっているため画面の無駄かと思いました。
→ プルダウンやポップアップで設定する形がいいかと思います。


## よく見る設定項目：
* 音量設定（BGM/SE/VOICE） -> 実装済み
* 画質設定 -> おそらくスペックが低いスマホにも快適に遊べるための対応ですが、対応予定ある？
* 言語設定 -> 実装済み
* 引き継ぎ関連設定 -> ローカルデータ紛失の場合の対策 -> せっかくサーバ用意するので対応しましょうか？
* 通知設定 -> 通知送るシチュエーションってある？

## ときときある項目：
* BGM設定（曲を変えるとか） → リリース後に機能追加してもいいかも
* スタッフロール → やります
* 利用規約・プライバシーポリシー → やるけど設定画面で設置するかどうか


## 個人的に思う必要項目
* 言語設定（プルダウン）
* BGM音量（スライド＋デフォルトボタン）
* SE音量（スライド＋デフォルトボタン）
* ステージ詳細 on/off （トグル）
* データリセット（ボタン→ポップアップ）
* レビュー（ボタン）
* 引き継ぎ設定（ボタン→ポップアップ）
* スタッフロール（ボタン→ポップアップ）
* 利用規約・プライバシーポリシー（ボタン→ポップアップ）

**Comment by takesi0627** [comment]
@takasusuke @xiii111 

フワッとしているけど、必要項目に過不足があるかコメントいただければと思います。よろしくお願いします

**Comment by xiii111** [comment]
このレビューはレビュー期間まで出来ないかもしれないです（余裕があったらレビューします）

**Comment by takasusuke** [comment]
- デフォルトに戻せる項目ごとに設置 → 賛成です("ステージ詳細"はデフォルト項目に入れなくなるよね？？)

- 多少ずれるけど、"ステージ詳細"だけだと何を設定するのかユーザはわからないかも。ポップアップにして、どんな項目の設定なのか説明するか、今のままテキストを別のにした方がいいと思う。

- 画質設定 → 軽量設定の話自体はあったはずだけど、描画負荷・動作負荷が元々重くないと思うので対応しなくて良いと思います。少なくともリリース当初は無くて良いと思います。

- 言語設定 → プルダウン良いと思います。

- 引き継ぎ関連設定 → 課金がある予定なので対応できるように進めた方が良いけど、リリース当初は無くて良いと思います。

- 通知設定 → N日間ログインしていない時とか、通知するとなったら色々あると思う。リリース当初は無くて良いと思います。

- 利用規約・プライバシーポリシー → 一応、画面に見せる方向で進んでるのかなと思ってる。

- (ライセンス表記) → 個人的にはThirdPartyのライセンス表記は見せなくて良いかな〜と思います。

- レビュー → iPhoneならapp storeへのリンクで、Androidならgoogle playへのリンクに変えてアプリを配布するってことだよね??

- Twitter等へのリンクも載せたいかな、と思うんだけどどうですか？

**Comment by takesi0627** [comment]
> * デフォルトに戻せる項目ごとに設置 → 賛成です("ステージ詳細"はデフォルト項目に入れなくなるよね？？)

そうなります

> * 多少ずれるけど、"ステージ詳細"だけだと何を設定するのかユーザはわからないかも。ポップアップにして、どんな項目の設定なのか説明するか、今のままテキストを別のにした方がいいと思う。("ステージ概要の表示"とか)

「ステージ概要の表示 ◎ON ○OFF」でいいと思います

> * 引き継ぎ関連設定 → 課金がある予定なので対応できるように進めた方が良いけど、リリース当初は無くて良いと思います。

「機種変したら一からやり直さないといけないのはだるいからやめる」という状況があるかもしれないので最初から対応したいですがいかがでしょうか

> * 通知設定 → N日間ログインしていない時とか、通知するとなったら色々あると思う。リリース当初は無くて良いと思います。

同意です

> * 利用規約・プライバシーポリシー → 一応、画面に見せる方向で進んでるのかなと思ってる。

うん？どういう意味？

> * (ライセンス表記) → 個人的にはThirdPartyのライセンス表記は見せなくて良いかな〜と思います。

これについてまた #599 で議論しましょう

> * レビュー → iPhoneならapp storeへのリンクで、Androidならgoogle playへのリンクに変えてアプリを配布するってことだよね??

iPhoneならレビューポップアップ
![image](https://user-images.githubusercontent.com/17778395/99944480-47648580-2db6-11eb-8b7e-eef88be1b591.png)
Androidは対等の機能はあるか分からないが、なければストアへのリンクでいいかな


> * Twitter等へのリンクも載せたいかな、と思うんだけどどうですか？

確かに、載せましょう。（公式Twitterに飛ぶって意味ってあってる？）

**Comment by takesi0627** [comment]
@takasusuke のレビューを受け、https://github.com/LITO-apps/Treevel-client/issues/512#issuecomment-731768422 を更新しました

**Comment by xiii111** [comment]
@takesi0627 お疲れ様です！時間が空いたので，以下レビューしました！

> 「デフォルトへ」は何をデフォルトに戻すのはわからない
> → デフォルトに戻せる項目ごとに設置した方がいい

良いと思います！

> 言語の設定はボタン二つありますけど、どっちかしか機能しないようになっているため画面の無駄かと思いました。
> → プルダウンやポップアップで設定する形がいいかと思います。

プルダウンで十分ですね！

> 画質設定 -> おそらくスペックが低いスマホにも快適に遊べるための対応ですが、対応予定ある？

いらないかなと思います！

> 引き継ぎ関連設定 -> ローカルデータ紛失の場合の対策 -> せっかくサーバ用意するので対応しましょうか？

サーバに記録情報あるので，そいつを引っ張れるようにしますか．そうなると，引き継ぎ用の `Secret Key` 的なのが必要だと思うので，少し工数かかりそうですね

> ステージ概要の表示

良いと思います．ですが，二行にすることを検討した方が良いと思います．

> 通知設定 -> 通知送るシチュエーションってある？

シチュエーションは作れるけど，いらないかな．

> iPhoneならレビューポップアップ

これですが，示されてる画像は，特定の時間が経ったら割り込んで表示する際などに使いますね．なので，設定画面に配置するレビューは，App Store へのリンクで良いと思います！この割り込み型レビューポップアップはまた別のイシューにする必要があります（もしかしたら，すでにあるかも）

**Comment by takasusuke** [comment]
> 
> > * 引き継ぎ関連設定 → 課金がある予定なので対応できるように進めた方が良いけど、リリース当初は無くて良いと思います。
> 
> 「機種変したら一からやり直さないといけないのはだるいからやめる」という状況があるかもしれないので最初から対応したいですがいかがでしょうか

万全の状態でリリースするのと、少し足りない部分があっても出来るだけ早くリリースするのとどっちが大事なんだろうと結構悩んでるから、機能を増やすことには割と消極的なんだよな〜。。。
もちろん引継ぎ設定は大事だけど、リリース時に必須なのかどうかは考えたい

> 
> > * 利用規約・プライバシーポリシー → 一応、画面に見せる方向で進んでるのかなと思ってる。
> 
> うん？どういう意味？
> 
利用規約は設定画面で見せると思っていました

> 
> > * Twitter等へのリンクも載せたいかな、と思うんだけどどうですか？
> 
> 確かに、載せましょう。（公式Twitterに飛ぶって意味ってあってる？）

公式Twitterであってます！

**Comment by takesi0627** [comment]
> > > * 引き継ぎ関連設定 → 課金がある予定なので対応できるように進めた方が良いけど、リリース当初は無くて良いと思います。
> > 
> > 
> > 「機種変したら一からやり直さないといけないのはだるいからやめる」という状況があるかもしれないので最初から対応したいですがいかがでしょうか
> 
> 万全の状態でリリースするのと、少し足りない部分があっても出来るだけ早くリリースするのとどっちが大事なんだろうと結構悩んでるから、機能を増やすことには割と消極的なんだよな〜。。。
> もちろん引継ぎ設定は大事だけど、リリース時に必須なのかどうかは考えたい

データの損失などの時復元の手段がないのはユーザに対して不利益が生じるので結構大事だと思いますので慎重に判断したいです。

> > iPhoneならレビューポップアップ
> 
> これですが，示されてる画像は，特定の時間が経ったら割り込んで表示する際などに使いますね．なので，設定画面に配置するレビューは，App Store へのリンクで良いと思います！この割り込み型レビューポップアップはまた別のイシューにする必要があります（もしかしたら，すでにあるかも）

あーーそうか、誤解したわ。じゃあストアに飛ぶでいいですね

**Comment by takasusuke** [comment]
> > > > * 引き継ぎ関連設定 → 課金がある予定なので対応できるように進めた方が良いけど、リリース当初は無くて良いと思います。
> > > 
> > > 
> > > 「機種変したら一からやり直さないといけないのはだるいからやめる」という状況があるかもしれないので最初から対応したいですがいかがでしょうか
> > 
> > 
> > 万全の状態でリリースするのと、少し足りない部分があっても出来るだけ早くリリースするのとどっちが大事なんだろうと結構悩んでるから、機能を増やすことには割と消極的なんだよな〜。。。
> > もちろん引継ぎ設定は大事だけど、リリース時に必須なのかどうかは考えたい
> 
> データの損失などの時復元の手段がないのはユーザに対して不利益が生じるので結構大事だと思いますので慎重に判断したいです。

課金を実装するなら、確かに一緒に実装するよなーー。。。
そもそも課金がリリース段階で必要なのかという話になるな。。。
現実的に2021/4でそこまで実装できるのか？と思ったり、期限をそこまで大事にするのか？とも思ったり。
別の話になってきてしまうので、一旦、機能吟味という意味では、引継ぎ設定は設定画面に入れましょう！

**Comment by takesi0627** [comment]
設定画面関連イシュー #623 #624 #625 を作成しましたのでクローズします
