### ISSUE TITLE
Util 周りのリファクタリング

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#516]
### 終了条件
- [ ] Util 以下のファイル構成を改善
- [ ] ファイルの中身を適宜移植

**Comment by xiii111** [comment]
ディレクトリ階層案（WIP）

```
Scripts
+-- Modules    // ...Scene など，特定のモジュール群
    +-- StartUpScene
    +-- MenuSelectScene
        +-- LevelSelect
        +-- Record
        +-- Settings
    +-- StageSelectScene
    +-- GamePlayScene
+-- Common    // xxScene に共通したクラス群
    +--GameDatas
    +--Networks
    +--UIComponents
    +--Managers
    +--迷ってる
+-- Editor  // エディタ拡張

**Comment by takesi0627** [comment]
せっかく改装まで替えるなら、この機に `namespace` も変えない？
`Project.Script` を除きたい

**Comment by xiii111** [comment]
`namespace` ってプロジェクトの階層と合わせるのがデファクトじゃないの？？

**Comment by takesi0627** [comment]
そうかもしれませんが、 `Script` 以下で合わせればいいんじゃないかと思うんです。
`Project.Script` はなんか無駄に長い気がする。
もしくは `Project.Script` を `Treevel` に変えるとか少し意味あるやつにしたい

**Comment by xiii111** [comment]
意図は伝わった

**Comment by xiii111** [comment]
@takesi0627 `namespace` に関して色々調べた結果，以下のパターンのどれかが良いと思うんですけど，どうですか？

`Project.Scripts.GamePlayScene.Bottle` を示す場合

1. `Scripts.GamePlayScene.Bottle`
2. `GamePlayScene.Bottle`
3. `${hoge}.GamePlayScene.Bottle`

3 の `${hoge}` の候補としては `TreevelClient` ， `Treevel` ， `LITO` などがあります．他にもこれあるよってコメントも募集

cc: @takasusuke

**Comment by xiii111** [comment]
@takasusuke @takesi0627 

https://github.com/LITO-apps/Treevel-client/issues/516#issuecomment-704277345 この内容についてレビューもらえますか？このような階層にしようと思ってます．このやり方だとこのファイルどうすんだ，みたいな微妙なファイルはありますが，それは明日の定例で話し合いながら分配していきたいなって思ってます．

**Comment by takesi0627** [comment]
> @takesi0627 `namespace` に関して色々調べた結果，以下のパターンのどれかが良いと思うんですけど，どうですか？
> 
> `Project.Scripts.GamePlayScene.Bottle` を示す場合
> 
> 1. `Scripts.GamePlayScene.Bottle`
> 2. `GamePlayScene.Bottle`
> 3. `${hoge}.GamePlayScene.Bottle`
> 
> 3 の `${hoge}` の候補としては `TreevelClient` ， `Treevel` ， `LITO` などがあります（ハイフンは普通使わない様子．`UpperCamelCase` がよい）．他にもこれあるよってコメントも募集
> 
> cc: @takasusuke


3推しかな

レビューはこのあとでやる。

**Comment by takesi0627** [comment]
> #### ディレクトリ階層案
> ```
> Scripts
> +-- Modules    // GamePlayScene など，特定の Scene のモジュール群
>     +-- StartUpScene
>     +-- MenuSelectScene
>         +-- LevelSelect
>         +-- Record
>         +-- Settings
>     +-- StageSelectScene
>     +-- GamePlayScene
> +-- Common    // Scene に共通したモジュール群
>     +--GameDatas
>     +--Networks
>     +--UIComponents
>     +--Managers
>     +--Attributes
>     +--Extensions
>     +--DesignPatterns
>     +--Entities    // GimmickType や RecordData などの Entity
>     +--Utils    // 余り物の集団
>     +--Constants.cs    // AnimationClipName などの定数置き場
> +-- Editor  // エディタ拡張
> ```

・ ボトル、タイル、ギミックは `Modules/GamplayScene/`に置く？
・`Director`系のクラスは `Modules`下の各シーンに置く？
・`DesignPatterns`は`Patterns`でいいと思いますが、どうでしょう
