### ISSUE TITLE
無限警告を消す方針を決める

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#527]
#324 の方法での警告のコメントアウトが永続的に効くようにする

**Comment by takasusuke** [comment]
### 解決策その1
無限警告を出しているPackage`PostProcessing`を`Library`から`Pcakages`ディレクトリにコピーして自作packageとする。
警告をコメントアウトする
メリット : Unityを再起動しても変更が保存される
デメリット : 本来管理しなくていいPackageを管理することになる

### 解決策その2
警告を我慢する or Unity起動のたびに対象部分をそれぞれコメントアウトする
補足
- Unity起動すると、対象部分をコメントアウトするシェルスクリプトが勝手に動く、とか出来るんなら面倒ではなくなる
(一時的にコメントアウトするだけで、`Build`したらコメントアウトしていない元の外部Packageを参照すると思うんだけど、そうなったらスマホで起動時は無限に警告出てるのでは...?)
メリット : 管理しなくていいものを管理しなくて済む
デメリット : 面倒

### 解決策その3
`PostProcessing`を用いない演出にする
メリット : 安全
デメリット : `PostProcessing`を使えなくて悲しい

### 解決策その4
そもそも警告が出ないように`Camera`を縮小させない
メリット : 安全 + `PostProcessing`も使える
デメリット : 大変

**Comment by takasusuke** [comment]
現実的な解決策はこんなところだと思います。
@xiii111 @takesi0627 どうしましょうか。

自分は、
その3 >= その4 >> その1 >>>> その2
って感じです。
(調べて現実的なこと考えた結果、やれって言われたらやりたくないけど、その4やるか、、、って感じ。)

**Comment by takesi0627** [comment]
4 > 1 > 2 >>>>> 3 

かな。
`PostProcessing` はそのために捨てるのはさすがにないと思います。
4はもし現実できな解決方法があればちょっとやって欲しいかも。やらせても全然良いので
もし現実的な解決法がなければ、パッケージ自体あんまり更新していないようだし、1でも良いと思います。

**Comment by takasusuke** [comment]
1は楽で良いよなあ。。！！！(それが良いなあ笑)

`PostProcessing`のエフェクトって仮で付けて、なんか良い感じじゃんってそのままずっと付けてるんだけど、
技術先行になってて見た目を精査してないよな、と引っかかってる部分がある。

見た目を先に決めて`PostProcessing`やっぱり使いたいねってなったら活かす方向で考え直したい気もする。

**Comment by xiii111** [comment]
4 > 2 > 1 > 3

**Comment by takasusuke** [comment]
解決策その4にします
