### ISSUE TITLE
デバッグ環境の検討

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#532]
Unity でビルドする際に環境を選択できるようにする
- Release ビルド（サーバが本番に向く）
- Dev ビルド（サーバが開発に向く）
- Debug ビルド（色々デバッグ向けの機能を付与 ex) 特定のステージの解放）

#### 終了条件
- 上記の対応にどのような手段をとるかを決定する

**Comment by xiii111** [comment]
知見をまとめると

1. `Unity` が用意する `Debug.isDebugBuild`
- `File -> Build Settings -> Development Build` にチェックすると `true` になる
- エディタで起動時には，常に `true` になる

→ 現状やりたいことはできない．基本エディタでビルドするので， `true` のまま

- https://docs.unity3d.com/jp/540/ScriptReference/Debug-isDebugBuild.html
- https://qiita.com/RyotaMurohoshi/items/82bddaca66d04a109a7a

2. シンボル定義 & エディタ拡張
- シンボルを定義し，そのシンボルによって各種設定を行う
- シンボルの変更をエディタ拡張により行う

→ 現状やりたいことはできるが，正攻法かはわからない．ここまでやる必要があるかは疑問だが，api の url の向き先を変えたりはしたいのかな？

- https://smartgames.hatenablog.com/entry/2016/06/30/234028

**Comment by xiii111** [comment]
@takasusuke @takesi0627 方向性について認識をすり合わせたいので，意見もらえますか？

**Comment by takesi0627** [comment]
1. 便利だが、DEVELOPとRELEASEの二つの状態しかない。テストサーバーの運用などもし考えるなら少なくても3状態が欲しいかも。

2. 開発的にはすごく便利し、状態の数は増えても問題ないので個人的に結構気に入りですが、いざビルドする時シンボル変え忘れるとかやっちゃいそうで怖い気もします。

**Comment by xiii111** [comment]
1 はエディタで適用できないのも問題かな．基本的な開発フローとしてはエディタで本番用と開発用のデバッグをして，それらを CI などで iOS 用と Android 用のバイナリを作り，そのバイナリを実機でテストという流れだと思う．そうなったらエディタが主戦場になるから（そもそもこの運用が微妙か？），1 はやはりやりづらいか？

2 に関しては悪いところはないが，非公式なこともあってシンボルの管理が課題．

**Comment by xiii111** [comment]
そもそも Unity の CD や開発フローのデファクトスタンダードを調べてみるわ

**Comment by takasusuke** [comment]
1. は２値しか取れないというのが確かに引っかかる
2. の感じを想像していて使いやすそう

本番用でのビルドは本番用のbranchでやるから大丈夫じゃないかなー。

**Comment by xiii111** [comment]
とりあえずシンボル定義を使う方法を実装することはできるが，今後の CI / CD とかも見据えて考えていきたいね

**Comment by xiii111** [comment]
良い記事を見つけた気がする
- https://qiita.com/yakimeron/items/4d40ce425dfa21e2d69b

**Comment by xiii111** [comment]
実装してます
