### ISSUE TITLE
短時間でのボタンのダブルタップを無視する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#560]
### 完了条件
- [ ] 十分に短い時間でボタンのダブルタップを無視する
- [ ] 以前の PR #629 を閉じる

### 現状起きている弊害
- `GamePlayScene` に行くボタンをダブルタップすると、ボトルなどが 2 セット生成される
- シーンに遷移するボタンをシーンをダブルタップすると、シーンを 2 つ作ってしまう

**Comment by xiii111** [comment]
### 調査進捗（WIP）

ボタンの入力制御はダブルタップだけではないよう．以下のようなものがある
1. ボタンの連続タップ
2. 複数のボタンの同時タップ
3. 複数のボタンの連続タップ

2 に関しては [`Input.multiTouchEnabled`](https://docs.unity3d.com/ja/2020.1/ScriptReference/Input-multiTouchEnabled.html) というのが用意されているっぽい．また連続タップを制御したい状況は，ボタンの処理に非同期処理（シーンの読み込みなど）が含まれているときですね．

対応としては一番シンプルなのは Button を継承した MyButton を作ることですかね．これに関してはあんまり記事とかを見つけれなかったので実装が面倒ですが，この対応をすれば今後別のメリットも出てくるかもです．例えば，ボタン共通の処理を付与したい場合に再利用できます．ボタンタップ時の SE 再生や，ボタンタップ時のエフェクト表示などを想定しています．Button 自体を拡張して利用する方法が以外に，Component で処理するのもあるみたいです（[参考](https://qiita.com/yuichi_katsuoka/items/0291a196d811a9d7be8a)）．完全自前で作る方法も紹介されていたけど，流石に重いな（[参考](https://unity-yuji.xyz/my-button-cant-continuous-hitting-common-process-press-animation/)）

このタスクって調査だったけ，実装までだったけ

**Comment by xiii111** [comment]
実装までやる

**Comment by xiii111** [comment]
📝 GamePlayScene に行くボタンをダブルタップすると、ボトルなどが 2 セット生成される

**Comment by xiii111** [comment]
@takasusuke 

> GamePlayScene に行くボタンをダブルタップすると、ボトルなどが 2 セット生成される

上記ような挙動も起きてしまうからダブルタップはしっかりと制御したい、ということでこのタスクをマイルストーンに置きましたが、Simulator のバグに依るダブルタップ以外で上記の動作は確認できますか？以前の PR を見て当時の状況を思い出した感じ、そこそこタスクは難航すると思います。その結果、実機では起きえないことだった、となりたくないので、Simulator のバグ以外で再現するかを確認しているのですが、自身の全力のダブルタップを試みても、動作は再現できませんでした。何かコツなどがあれば教えていただけませんか？

**Comment by takasusuke** [comment]
> > GamePlayScene に行くボタンをダブルタップすると、ボトルなどが 2 セット生成される
> 
> 上記ような挙動も起きてしまうからダブルタップはしっかりと制御したい、ということでこのタスクをマイルストーンに置きましたが、Simulator のバグに依るダブルタップ以外で上記の動作は確認できますか？以前の PR を見て当時の状況を思い出した感じ、そこそこタスクは難航すると思います。その結果、実機では起きえないことだった、となりたくないので、Simulator のバグ以外で再現するかを確認しているのですが、自身の全力のダブルタップを試みても、動作は再現できませんでした。何かコツなどがあれば教えていただけませんか？

Simulator以外では起きたことないです。
Editorでは起こせないけど、実機だとむしろ起こせるかもしれないから、実機の動き次第かもね〜みたいな記憶がうっすらとないこともない。。。

**Comment by xiii111** [comment]
@takasusuke 返答ありがとうございます。では、`Xcode でビルド可能にし、iOS の実機で動かせるようにする` という issue を作成して、割り込みで取り掛かろうと思います。それで良いでしょうか？

**Comment by xiii111** [comment]
@takesi0627 割り込んでタスクをすることについて、何か反対があれば意見ください

**Comment by xiii111** [comment]
#945 を作成しました。一旦こちらに取り組み、 #945 を閉じた後に帰ってきます

**Comment by xiii111** [comment]
📝 #945 のための PR を出しました。実機で動作確認したところ、実機でもシングルタップがダブルタップになる、という問題が起こりました（ #954 ）そのため、 #954 を閉じた後にこちらに帰ってきます。#954 が解決できなかった場合には、仕方ないですが、本対応を行おうと思います

**Comment by xiii111** [comment]
📝 一度、マイルストーンに戻します

**Comment by xiii111** [comment]
@takasusuke @takesi0627 #954 が解決したことにより、人間（n = 1）の全力ダブルクリックでは問題が起きないことを確認しましたので閉じます。再度同様のことがおきましたら、起票をお願いします🙏
