### ISSUE TITLE
`Unity 2020.1.7f1` にアップグレード

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#571]
### 終了条件
- [ ] アップグレード
- [ ] 動作確認

**Comment by xiii111** [comment]
@takasusuke @takesi0627 Visual Stadio for Mac 🤔

![スクリーンショット 2020-10-04 22 29 40](https://user-images.githubusercontent.com/26104258/95016937-40ac7280-0691-11eb-822f-87538278e2ac.png)

**Comment by xiii111** [comment]
![スクリーンショット 2020-10-04 22 32 38](https://user-images.githubusercontent.com/26104258/95016989-8cf7b280-0691-11eb-9463-fb39eec5ded4.png)

**Comment by takesi0627** [comment]
Visual Studio元々使えたんだけど、何か変わった？

**Comment by xiii111** [comment]
ちゃんと読まないとわからないけど， Visual Studio との連携がめっちゃ押されてるw
