### ISSUE TITLE
【設定画面】レイアウト提案

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#623]
#512 よりの下記機能を含むレイアウトの提案

> 言語設定（プルダウン）
BGM音量（スライド＋デフォルトボタン）
SE音量（スライド＋デフォルトボタン）
ステージ詳細 on/off （トグル）→ 「ステージ概要の表示 ◎ON ○OFF」
データリセット（ボタン→ポップアップ）
レビュー（ボタン→App Store/Google Playへ）
引き継ぎ設定（ボタン→ポップアップ）
スタッフロール（ボタン→ポップアップ）
利用規約・プライバシーポリシー（ボタン→ポップアップ）
Twitter/ホームページへのリンク（アイコン・ボタン）

**Comment by xiii111** [comment]
#624 と被る
