### ISSUE TITLE
【設定画面】デザイン作成

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#624]
### 完了条件
- [ ] `設定画面` のデザイン草案を作成する
- [ ] 上記の草案を元に議論し、`設定画面` のデザインを確定する

※ 実装対象外の内容をついでに対応できそうならやってしまう

※ #512 より、下記機能を含むレイアウトの提案する

- 言語設定（`プルダウン`）
- BGM 音量調整（`スライダー`）、デフォルトに戻せる（`ボタン`）
- SE 音量調整（`スライダー`）、デフォルトに戻せる（`ボタン`）
- ステージ概要の表示（`トグル` or `ラジオボタン`）
- データリセット（`ボタン` + `ポップアップ`）
- アプリレビュー（`ボタン`）※ App Store / Google Play へ移動
- 引き継ぎ設定（`ボタン` + `ポップアップ`）
- ライセンス表記（`ボタン` + `ポップアップ`）
- スタッフロール（`ボタン` + `ポップアップ`）
- 利用規約・プライバシーポリシー（`ボタン` + `ポップアップ`）
- Twitter / ホームページへのリンク（`アイコン画像` + `ボタン`）

### 実装対象外
以下の UI コンポーネントの詳細を決めること
- #1025 
- #811 
- #1024 
- #810 
- #812
- #1026 
- #985

**Comment by xiii111** [comment]
@takasusuke @takesi0627 参考画像をお願いします

**Comment by xiii111** [comment]
https://docs.google.com/presentation/d/1ugcTaLSYVMVWqid6YQqOfPkFFSlGTJMtJU4Uy2JKEow/edit#slide=id.gaaa75cf2d6_0_0

**Comment by xiii111** [comment]
@takasusuke @takesi0627 https://github.com/LITO-apps/Treevel-client/issues/624#issuecomment-864490917 繰り返しになって申し訳ないですが、あったらお願いします！

**Comment by takasusuke** [comment]
@xiii111 
簡単に調べた範囲の画像とコメントしました

**Comment by xiii111** [comment]
@takasusuke あざます！！

**Comment by takesi0627** [comment]
少しコメントしました

**Comment by xiii111** [comment]
@takesi0627 あざます！

**Comment by xiii111** [comment]
@takasusuke @takesi0627 https://github.com/LITO-apps/Treevel-client/issues/624#issuecomment-868987600 を元に通話で議論したいと思っています。通話をする前に、気になる点・直しておいて欲しい点などがあれば、コメントお願いします！

**Comment by xiii111** [comment]
📝 設定の説明 UI のイシューを作る

**Comment by xiii111** [comment]
@takasusuke @takesi0627 実装対象外に書いてある Issue を丁寧に更新しました。こちらは閉じます
