### ISSUE TITLE
Array と List の選定基準を明確にし、修正する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#631]
- [x] Array と List の選定基準を明確にする（提案する）
  - ex) 初期化の段階で配列サイズが決まっている場合は Array
  - ex) 脳死で List を使う
- [x] 上記で決まった内容を、適用する

**Comment by xiii111** [comment]
@takasusuke @takesi0627 以下で 1 ~ 3 の提案をしました。意見とともにどの案が良いかをお願いします

### Array の良いところ
- 2 次元、3 次元配列などを作ることができる
- 先にメモリを確保するので高速（よほど大量なデータでない限り無視できる）

### List の良いところ
- 要素を減らしたり増やしたりすることができる

### どう使い分ける？
※ N 次元の場合には Array を使う以外に術がないので、Array を使うものとする
1. 予め要素数が決まっている場合など Array で困らない時には全て Array を使い、それ以外では List を使う → 高速・最適
2. 使い分けるのが面倒なので全て List を使う → Array と List が入り混じらないので、どっちを使うかに迷わない
3. 使い分けるのが面倒なので基本 List を使い、ライブラリ関数の返り値が Array などの場合にはわざわざ List には変換せずに Array を使う → 楽、何も考えない。グチャグチャにはなる


- [参考リンク1](https://resanaplaza.com/%E3%80%90c%E3%80%91%E9%85%8D%E5%88%97%E3%81%A8%E3%83%AA%E3%82%B9%E3%83%88%E3%81%AE%E9%81%95%E3%81%84%E3%81%AF%EF%BC%9F%E3%81%9D%E3%81%AE%E5%8A%B9%E6%9E%9C%E7%9A%84%E3%81%AA%E4%BD%BF%E3%81%84%E6%96%B9/#:~:text=%E9%85%8D%E5%88%97%E3%81%AF%E5%AE%A3%E8%A8%80%E6%99%82%E3%81%AB%E5%BF%85%E8%A6%81,%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82)
- [参考リンク2](https://ekulabo.com/c-sharp-list-array)

**Comment by xiii111** [comment]
人によって実装が異なっているからか、現状はグチャグチャ。1 ~ 3 のどれにも該当していない。一番近いのをあげるとすると、3

**Comment by takesi0627** [comment]
`List<List<int>>`で二次元配列作れないんだっけ

**Comment by takasusuke** [comment]
推しは1です。
基本、1で考えていました。
型がArrayだから要素数が決まっているんだな、と知れるのも利点だと思っています。

**Comment by xiii111** [comment]
> `List<List<int>>`で二次元配列作れないんだっけ

@takesi0627 分からないけど、作れるんだとしたら、n 次元配列を作れる優位性は array から消える

**Comment by xiii111** [comment]
> 推しは1です。
> 基本、1で考えていました。
> 型がArrayだから要素数が決まっているんだな、とコード読む時に知れるのも利点だと思っています。

@takasusuke ふむふむ。まぁわかる

**Comment by xiii111** [comment]
@takesi0627 どれ推しですか？

**Comment by takesi0627** [comment]
1と2ですごく悩んでるんですが、1の利点はもちろんパフォーマンスがいいところと要素数が知れるところですが、
果たして要素数が決まっていることは必ず変わらないと断言できるでしょうか？
いざ仕様変更となったときのコストが膨大になりそう。

まあ2は正直パフォーマンスが遅いだけだと思うんですけど、参考記事にも書いた通り、実際FPSに影響が出るほど出なければ基本気にしなくてもいいし、このゲームもFPSに影響が出るほどの処理はしてないし2を選んでも差し支えないかもしれない。

推しではないですが、1と2は2よりですね。1.8的な感じ

**Comment by xiii111** [comment]
なるほど。僕もどちらかというと 2 寄りですね。パフォーマンスを考慮する必要はないと思っていて（そこまで大きいプロジェクトでもなく、検索エンジンなどのようにパフォーマンスに全振りする必要もないので）、そうなると List を脳死で使う方が楽だと思いました。

@takasusuke @takesi0627 ライブラリ関数（外部関数）の返り値が Array の場合にはわざわざ List に変換して利用しますか？それとも、このような場合には Array を使いますか？また、二人の意見が割れているので、意見あればもう少し補足お願いします

**Comment by xiii111** [comment]
うーん

```
Enumerable.Range(1, Constants.StageSize.ROW * Constants.StageSize.COLUMN).ToList()
    .Where(tileNum => !tileNumList.Contains((short)tileNum))
    .Select(tileNum => CreateTile(ETileType.Normal, tileNum))
```

のコードはどう考えても `.ToArray()` で十分なんだよなぁ。けど、追加とかしたくなったらできなくなるし、何も気にせず `ToList()` を使うというのもわかる。難しい

**Comment by xiii111** [comment]
http://neue.cc/2011/08/03_336.html

> LINQの結果は遅延評価なので、その場で全部評価して欲しかったりする場合などに使うToArrayとToList。どちらを使っていますか？私はToArrayのほうが好みです。と、いうのも、LINQで書く以上、長さは決まったようなものなので、これ以上AddやRemoveしたいことなんてほとんどない。勿論、必ずないとは言いませんので、その場合だけToListを使いますが、そうでない場合は、長さが固定だという意図を示すためにもToArrayが好ましい。

**Comment by xiii111** [comment]
ソフトウェアエンジニアリングをやっていたものからすると、Array は使った方が... という気持ちが復活してきたので、1.5 の気持ちになって明日を迎えます

**Comment by takesi0627** [comment]
LINQ使うときに `ToArray` を使うと、変数宣言するときに `[]` 使うのと絶対的な関係あるかな

**Comment by takasusuke** [comment]
`TileGenerator`の無駄な`ToArray()`もお願いします。

**Comment by xiii111** [comment]
### 残課題
- [ ] Rider が怒っている箇所（IEnumerable, ToList, ToArray 周り）を直す
- [ ] TileGenerator の無駄な ToArray()
- [ ] その他、時間内でできる貢献
