### ISSUE TITLE
SpiderWebTileのデザイン草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#656]
### 終了条件
- SpiderWebTileのデザイン草案資料を作成する
- 案ごとのスレッドをSlackのdesignチャンネルに作り議論する
- デザインを依頼する

**Comment by takasusuke** [comment]
デザイン草案
https://docs.google.com/presentation/d/1tmQKLnOpy3BgvnCBIKkk3l45hGLKocica2vVzm1JR9w/edit#slide=id.ga801171db5_0_5

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
Slackで議論しましょう。
定例MTGまでにお願いします。

**Comment by takasusuke** [comment]
### 【仕様】
- ゲームの開始時に蜘蛛の巣タイルの場所を知らせる
- ゲームプレイ中は蜘蛛の巣タイルは表示しない
- ボトルが蜘蛛の巣タイルに乗ったとき、蜘蛛の巣が表示される
- 蜘蛛の巣は１度効果を発揮しても無くなったりはしない(ので、拘束時間は短めに設定する予定)

### 【見た目：このタスクで決める】
- 蜘蛛の巣タイル単体の見た目
- ボトルが蜘蛛のスタイルに乗っている時の見た目

(見た目のメモ)
- 蜘蛛の巣の一部だけが見えるタイルと、蜘蛛の巣全体が見えるタイルが混じっている
- シンプルで、わかりやすいこと

### 【演出：このタスクでは決めないが考慮する】
- ボトルが蜘蛛の巣タイルに乗った時
- 蜘蛛の巣からボトルが解放される時

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
スライドを更新しました。
Slackでのコメントお願いいたします。

**Comment by xiii111** [comment]
@takasusuke すみません、蜘蛛の巣の最新スライドって Slack に上がってますか？

**Comment by takasusuke** [comment]
清書して依頼しました。
