### ISSUE TITLE
SEを鳴らす場所を洗い出す

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#661]
- [ ] SE再生する場所をリスト化

**Comment by takesi0627** [comment]
> ボタンと表記しているものはボタンのタップ音を表しています

- [ ] STARTボタン

## MenuSelectScene
- [ ] 川が流れる音（背景に合わせて）
- [ ] フーターボタン
- [ ] 木ボタン

### 記録画面
- [ ] 総合記録画面 <> 個別記録画面 のスライド音
- [ ] 共有ボタン

### 個別記録画面
- [ ] 季節ボタン
- [ ] 木ドロップダウン
- [ ] ステージ一覧へボタン

### 設定画面
- [ ] 各ボタン


## StageSelectScene
- [ ] 木を切り替える時（スワイプ・ボタン）
- [ ]  戻るボタン
- [ ]  ステージボタン
- [ ]  進むボタン
- [ ]  閉じるボタン音・ポップアップが閉じる時の音

## GamePlayScene
### ボトル
- [ ] ボトルの移動音
- [ ] ボトルの破裂音（攻撃された時）
- [ ] DarkEffectが晴れる音

### ギミック
#### Tornado 
- [ ] 警告
- [ ] 登場
- [ ] 曲がる
#### Meteorite
- [ ] 警告
- [ ]  落ちる音
#### GustWind
- [ ] 微風の音
- [ ]  落ち葉の音
- [ ]  竜巻が通る音
#### SolarBeam
- [ ] 太陽が段々怒る音
- [ ] ビームを発射する音
#### Thunder
- [ ] 雷が落ちる音
- [ ] 雲が黒くなる音
#### Powder
なんかある？

#### Fog
なんかある ？

### タイル
- [ ] ワープタイル発動時
- [ ] 蜘蛛の巣に引っ掛かった時
- [ ] アイスタイルに乗った時（通った時）
- [ ] HolyTileに乗った時

**Comment by takesi0627** [comment]
@takasusuke @xiii111 

上記リストについて過不足があればコメントしてください。

**Comment by xiii111** [comment]
気になったのは、以下の二つくらいかな。いざ実装を始めてみて気付くことは多そう

- 川が流れる音（背景に合わせて）は BGM ではない？
- ボトルの破壊音は LifeBottle の部分破壊音と分けた方が良いかも

**Comment by takasusuke** [comment]
全てが必要かはともかく(特にGamePlaySceneで音が多量になるかもしれないので)、鳴らせそうな場所を列挙しました。

### MenuSelectScene
- [ ] 木をクリアしたとき
- [ ] 木を完全にクリアしたとき
- [ ] 道が出現するとき
- [ ] ピンチインしてる時は水の音が大きく、ピンチアウトしてる時は水の音を小さくしたい(SEを鳴らす場所という趣旨とずれるけど)

### GamePlayScene

- [ ] Game成功時
- [ ] Game失敗時
- [ ] Game Tutorialを閉じるボタン
- [ ] 一時停止ボタン
- [ ] 一時停止ポップアップの中のボタン
#### Bottle
- [ ] SelfishBottleが移動しそうなときの音
- [ ] SelfishBottleが移動するときの音
- [ ] ReverseEffectが移動するときの音(は変える？)
- [ ] DarkBottleが加わるときの音
- [ ] ErasableBottleが出現するときの音
- [ ] ErasableBottleが消えるときの音
#### Gimmick

- [ ] Tornadoの移動中
- [ ] Tornadoが衝突したとき
- [ ] 太陽が出現する音
- [ ] 太陽が衝突したとき
- [ ] 雲が出現する音
- [ ] Thunderが衝突したとき
- [ ] Powderが現れるステージ特有の音(砂嵐とか風の音とか)
- [ ] Powderが消える音
- [ ] Fogが出現しているときの音

#### Tile

- [ ] 蜘蛛の巣の効果がなくなったとき
- [ ] HolyTIleの効果でギミックとの衝突を無視したとき

#### その他
- エラーポップアップの閉じる音

**Comment by takesi0627** [comment]
> 気になったのは、以下の二つくらいかな。いざ実装を始めてみて気付くことは多そう
> 
> * 川が流れる音（背景に合わせて）は BGM ではない？

BGMと融合して一つのリソースで再生するのもあり。
が @takasusuke が提案した
> ピンチインしてる時は水の音が大きく、ピンチアウトしてる時は水の音を小さくしたい(SEを鳴らす場所という趣旨とずれるけど)

はできなくなる。

基本的にBGMはメロディ付きのもので、環境音などはSEと認識してリストアップしています。

> * ボトルの破壊音は LifeBottle の部分破壊音と分けた方が良いかも

いいと思います。リストに反映しておきます。

**Comment by takesi0627** [comment]
> 全てが必要かはともかく(特にGamePlaySceneで音が多量になるかもしれないので)、鳴らせそうな場所を列挙しました。
> 
> ### MenuSelectScene

異議なし

> ### GamePlayScene

ステート遷移のこと完全に抜けてた。申し訳ない。

> #### Bottle
> * [ ]  SelfishBottleが移動しそうなときの音
> * [ ]  SelfishBottleが移動するときの音
> * [ ]  ReverseEffectが移動するときの音(は変える？)

ボトルの移動音は統一した方がいいと思ったので列挙してなかったが、selfishが移動しそうな時の音はあった方がいいと思う。


> #### Gimmick
> * [ ]  Tornadoの移動中
> * [ ]  Tornadoが衝突したとき
> * [ ]  太陽が出現する音
> * [ ]  太陽が衝突したとき
> * [ ]  雲が出現する音
> * [ ]  Thunderが衝突したとき
> * [ ]  Powderが現れるステージ特有の音(砂嵐とか風の音とか)
> * [ ]  Powderが消える音
> * [ ]  Fogが出現しているときの音

ギミックがボトルに衝突シリーズですが、ボトルの方でボトルの破裂音だったりが再生されるから、同時に再生するとごちゃごちゃになるのでどっちかだけ再生するようにしたい。
出現時の音は同意です。 

> #### Tile

異議なし。

> #### その他
> * [ ]  エラーポップアップの閉じる音

エラーポップアップはステージ詳細ポップアップと同じでいいと思いますが（というかポップアップ系全部同じがいいと思います）
、いかがでしょうか


同意のものについてチェックを入れてリストに入れておきます。

**Comment by takasusuke** [comment]
- Gimmick衝突の時の音
- 移動する時の音
は自分も無くても良いと思います。

> エラーポップアップはステージ詳細ポップアップと同じでいいと思いますが（というかポップアップ系全部同じがいいと思います）
、いかがでしょうか

これ賛成


一時停止ボタンは、他のボタンと同じ音を鳴らした方が良いんじゃない？

**Comment by takesi0627** [comment]
> 一時停止ボタンは、他のボタンと同じ音を鳴らした方が良いんじゃない？

僕もそう思います。まとめ方悪かったと思いましたので今からもう一度書き直す。

**Comment by takesi0627** [comment]
## UI系
### ポップアップ/ドロップダウン
UIで何かが出てくるときとその何かが消える時の音を統一したいので、
ポップアップとドロップダウン（タップしたら選択肢が出てくる、外側タップすると閉じる）を対象とします。

- [ ] ポップアップ/ドロップダウンが開く音
- [ ] ポップアップ/ドロップダウンが閉じる音

### ボタン
> 対象：木ボタン、ステージボタン、フーター等含む　　　　
- [ ] 普通にタップした音（タップしたら何かが起こることを伝える）
	- ボタン
	- ドロップダウンの選択肢をタップした時
	- 選択されていないトグルを選択した時
- [ ] Disabled・inactive状態でタップした時の音 （タップ操作に反応がないことを伝える）
	- ボタン
	- 選択しているトグルをタップした時


### SnapScrollView
- [ ] ページ切り替えるときの音



## MenuSelectScene
- [ ] 川が流れる音（背景に合わせて）
＊ピンチインピンチアウトに合わせて距離感を感じさせる演出がいいかも


## GamePlayScene
- [x] ゲーム成功時
- [x] ゲーム失敗時
- [ ] 準備中（カウントダウン）

### ボトル
- [ ] ボトルの移動音
- [ ] ボトルの破裂音（攻撃された時）
- [x] ボトルの破壊音（失敗する時）
- [ ] DarkEffectが晴れる音
- [x] DarkBottleが加わるときの音
- [x] ErasableBottleが出現するときの音
- [x] ErasableBottleが消えるときの音
- [x] SelfishBottleが移動しそうなときの音


### ギミック
#### Tornado 
- [ ] 警告
- [ ] 登場
- [ ] 曲がる
- [x] Tornadoの移動中
#### Meteorite
- [ ] 警告
- [ ]  落ちる音
#### GustWind
- [ ] 微風の音
- [ ]  落ち葉の音
- [ ]  竜巻が通る音
#### SolarBeam
- [ ] 太陽が段々怒る音
- [ ] ビームを発射する音
- [x] 太陽が出現する音
#### Thunder
- [ ] 雷が落ちる音
- [ ] 雲が黒くなる音
- [x] 雲が出現する音
#### Powder
- [x] Powderが現れるステージ特有の音(砂嵐とか風の音とか)
- [x] Powderが消える音
#### Fog
- [x] Fogが出現しているときの音


### タイル
- [ ] ワープタイル発動時
- [ ] 蜘蛛の巣に引っ掛かった時
- [ ] アイスタイルに乗った時（通った時）
- [ ] HolyTileに乗った時
- [x] 蜘蛛の巣の効果がなくなったとき
- [x] HolyTIleの効果でギミックとの衝突を無視したとき

**Comment by takesi0627** [comment]
@xiii111 @takasusuke 
UI操作系のものをまとめてリストし直しました。すみませんがもう一度コメントいただければと思います。
チェック付いているものはお二人の意見からのものになります。よろしくお願いします

**Comment by takasusuke** [comment]
良いです！

**Comment by xiii111** [comment]
良いです

**Comment by takesi0627** [comment]
ありがとうございます。
ではリストにあるものは全部実装する方向で次のタスク（ #663 ）に移行したいと思います。
これをもってこのイシューをクローズします。

**Comment by takesi0627** [comment]
https://scrapbox.io/treevel/SE候補

@xiii111 @takasusuke 
一旦こちらに上げている項目で決めたいと思います。
必ず決める必要はなく、微妙だと思ったらなしにして、今後ブラッシュアップ段階でまた適切なものにすればいいと考えております。
決めた項目だけ #662 で実装します。

今回は点数で決めるのはなんか微妙な気がしてきたので、アンケートはやめることにした。
MTGで話し合いながら決めていきたいと思うので各自今週のMTGまでに聞いてコメントなどあればそのまま書いていただければと思います。よろしくお願いします。

ちなみに `.wav` ファイルはサポートしていないらしいので、お手数ですが、 [Googleドライブ](https://drive.google.com/drive/u/1/folders/1vH0drmHwv2zvnaEWkFCfWEwu2ciYUd7c)からアクセスして聞いてください。
