### ISSUE TITLE
SEの選出

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#663]
- [ ] #661 で決めたSEを鳴らす場所に適切な音源を探し、リストアップする。

自分の判断でやれるやつやる

**Comment by takesi0627** [comment]
https://scrapbox.io/treevel/SE候補

@xiii111 @takasusuke 
一旦こちらに上げている項目で決めたいと思います。
必ず決める必要はなく、微妙だと思ったらなしにして、今後ブラッシュアップ段階でまた適切なものにすればいいと考えております。
決めた項目だけ #662 で実装します。

今回は点数で決めるのはなんか微妙な気がしてきたので、アンケートはやめることにした。
MTGで話し合いながら決めていきたいと思うので各自今週のMTGまでに聞いてコメントなどあればそのまま書いていただければと思います。よろしくお願いします。

ちなみに `.wav` ファイルはサポートしていないらしいので、お手数ですが、 [Googleドライブ](https://drive.google.com/drive/u/1/folders/1vH0drmHwv2zvnaEWkFCfWEwu2ciYUd7c)からアクセスして聞いてください。

**Comment by takasusuke** [comment]
コメントしました！いくつか探して追加しました！

**Comment by xiii111** [comment]
コメントしました！

**Comment by takesi0627** [comment]
## UI
* ドロップダウン閉じる: audiostock_4039_sample.mp3

* ボタン押す：二つ使い分ける
    * audiostock_961381_sample
    * audiostock_934243_sample

* 無効な操作：audiostock_872214_sample
* SnapScrollView切り替える：audiostock_140660_sample.mp3


 ## LevelSelectScene
* river01.mp3

## ボトル
* GoalBottle移動：audiostock_90414_sample.mp3
* 破裂音：audiostock_124097_sample.mp3
* 破壊音：audiostock_216434_sample.mp3 

## タイル
* ワープタイル: jump10.mp3


## ギミック
* Powder環境音：audiostock_17795_sample
* Gust衝突音：audiostock_939701_sample
* Thunder：二つランダムで再生
    * audiostock_117097_sample 
    * audiostock_810563_sample
* Meteorite衝突時：audiostock_877259_sample
* Meteorite登場から落下まで：audiostock_824922_sample　の前半

## GamePlayScene 
* 失敗：二つランダム再生
    * audiostock_804694_sample
    * audiostock_963585_sample

* 成功：audiostock_857119_sample

**Comment by takesi0627** [comment]
議論の結果に基づき #662 をやります
