### ISSUE TITLE
タップエフェクトの調査

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#664]
### 参考
全体：シャドウバースのタップエフェクト

- [ ] 全体のUI操作のタップエフェクト
- [ ] ゲーム中のタップエフェクト

**Comment by takesi0627** [comment]
# 市場調査
 
## タップエフェクトなし
※（きのこ以外全部国外の開発会社）
* [Deemo](https://apps.apple.com/jp/app/deemo/id700637744)
* [きのこ](https://apps.apple.com/jp/app/なめこ栽培キットdeluxe-極-放置-育成ゲーム/id1494083019)
* [チャーでん](https://apps.apple.com/jp/app/アーチャー伝説/id1453651052)
* [原神](https://apps.apple.com/jp/app/原神/id1517783697)

## 「ボタンを押した時」「何もない箇所を押した時」のタップエフェクトが違う
* [このファン](https://apps.apple.com/jp/app/この素晴らしい世界に祝福を-ファンタスティックデイズ/id1438616438)

https://user-images.githubusercontent.com/17778395/104341980-b69c6180-553d-11eb-9a7e-a0f2e0439d75.mov



* [ドラガリ](https://apps.apple.com/jp/app/ドラガリアロスト/id1352230941)


https://user-images.githubusercontent.com/17778395/104342275-ff541a80-553d-11eb-8622-a08d1d5ee8ed.mov



* [プリコネ](https://apps.apple.com/jp/app/プリンセスコネクト-re-dive/id1134429300)


https://user-images.githubusercontent.com/17778395/104342324-0d09a000-553e-11eb-8688-baad18c3e131.mov


## 「ボタンを押した時」「何もない箇所を押した時」のタップエフェクトが一緒
* [スクスタ](https://apps.apple.com/jp/app/ラブライブ-スクールアイドルフェスティバルall-stars/id1377018522)


https://user-images.githubusercontent.com/17778395/104343509-5c040500-553f-11eb-965a-e0fbbb762753.mov



* [ガルパ](https://apps.apple.com/jp/app/バンドリ-ガールズバンドパーティ/id1195834442)


https://user-images.githubusercontent.com/17778395/104343584-70480200-553f-11eb-87f8-2cc544c3d983.mov

* [白猫](https://apps.apple.com/jp/app/白猫プロジェクト/id895687962)


https://user-images.githubusercontent.com/17778395/104343658-8c4ba380-553f-11eb-8864-36af354c856b.mov

**Comment by takesi0627** [comment]
調査するまでは「ボタンを押した時」「何もない箇所を押した時」のタップエフェクトが違うゲームがあること知らなかったので、これを含めて検討したいと思います。

ちなみに、ゲームパートとその他のパートでタップエフェクトが違うゲームはありませんでした。

**Comment by takesi0627** [comment]
[タップエフェクトは不要  |  ゲームUI演出](https://gameanimation.info/archives/1110)
[「ドクターマリオワールド」タップエフェクトが無い理由を考えてみました - ゲームアプリのUIデザイン](https://appgameui.hatenablog.com/entry/2019/08/06/000000)

ここら辺の記事を読んだらなんか改めてこの機能の必要性を吟味したくなりました。
タップエフェクトがあった方が個人的にユーザとしては好みですけど、実際にゲームに必要かって言われると確かになくても全然ゲーム性には支障がない。なのでここでもう一度このタスクの優先度と必要性を検討したい。

必要性：
- [ ] あり
- [ ] なし

優先度：
- [ ] 高い（今すぐやるべき）
- [ ] 低い（全体ゲームが完成した後に実装）

**Comment by takasusuke** [comment]
Buttonやフリック、ホールドでアニメーションを入れるならタップエフェクトは必須ではないと思います。
実装するにしても、優先度は低いと思いました。

-----
タップエフェクトの記事面白いね。

ただ華やかにするだけのタップエフェクトは、今回は不要だと思いました。
`GamePlayScene`は`Bottle`のフリックやホールド時にちゃんとアニメーションをつけるならタップエフェクトはなくて良いと思う。

優先度は低いけれど、
`LevelSelect`や`StageSelectScene`でタップした場所に、
春なら花びらのオブジェクトが出て自動で画面下に舞うとか、
冬なら雪のオブジェクトを出すとか、
エフェクトというよりは、ユーザが画面で遊べる１つの機能としてなら実装したいと思った。
季節や木ごとにエフェクトが細かく変わるような凝ったアプリは好きだし、次の木へのワクワク感も与えられるし、
季節を感じさせて世界観を意識してもらえるかなと思いました。

**Comment by takesi0627** [comment]
> `LevelSelect`や`StageSelectScene`でタップした場所に、
> 春なら花びらのオブジェクトが出て自動で画面下に舞うとか、
> 冬なら雪のオブジェクトを出すとか、
> エフェクトというよりは、ユーザが画面で遊べる１つの機能としてなら実装したいと思った。
> 季節や木ごとにエフェクトが細かく変わるような凝ったアプリは好きだし、次の木へのワクワク感も与えられるし、
> 季節を感じさせて世界観を意識してもらえるかなと思いました。

僕もこういうのをイメージしてました。凝らないと実装する意味あんまりないし、凝った実装には工数かかるからやはりブラッシュアップ段階でやることかと思いました。

**Comment by xiii111** [comment]
提示してくれた記事を一通り読んで思ったことを以下に書きます

> パズルゲームだからタップエフェクトがあると画面が見づらい？

というのは納得で、特に本アプリはアクション要素もあるので、ゲーム画面でのタップエフェクトはゲーム性に影響を与えてしまうと思います

> ゲームには遊び心が必要

これは納得。ユーザを飽きさせない要素としても機能すると思います

> タップエフェクトがないアプリ

これが結構多くてなるほど〜って思いました

**Comment by xiii111** [comment]
必要性と優先度について話すと、必要性は高くなく、優先度も高くないと思います。

> 春なら花びらのオブジェクトが出て自動で画面下に舞うとか、
冬なら雪のオブジェクトを出すとか、
エフェクトというよりは、ユーザが画面で遊べる１つの機能としてなら実装したいと思った。
季節や木ごとにエフェクトが細かく変わるような凝ったアプリは好きだし、次の木へのワクワク感も与えられるし、
季節を感じさせて世界観を意識してもらえるかなと思いました。

これは聞いててワクワクしました。`LevelScene`、`StageSelectScene` に関しては季節ごと、木ごとのエフェクトを与えることが、世界観への没入をサポートして、ユーザのゲーム継続率が上がると思います。なので、この機能においてはリリースまでに含める価値があると思いましたが、どうでしょうか？

**Comment by takesi0627** [comment]
> これに関しては聞いててワクワクしました。LevelScene、StageSelectScene に関しては季節ごと、木ごとのエフェクト（雪や花びら）を与えることが、世界観への没入をサポートして、ユーザのゲーム継続率が上がると思います。なので、この機能においてはリリースまでに含める価値があると思いましたが、どうでしょうか？

含める価値はあると思いますし、リリースまでにも実装したいですが、優先度的にはリリース直前のブラッシュアップ段階とかかなって思います。

**Comment by xiii111** [comment]
良いと思います！！

**Comment by takesi0627** [comment]
本タスクは調査までとさせていただきます。
提案作業は #703 にて行います。
調査は完了ということでクローズします。
