### ISSUE TITLE
BGMの選出

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#666]
#80 で決めたBGMを鳴らす場所に適切な音源を探し、リストアップする。

**Comment by takesi0627** [comment]
## StartUpScene 
* 歓迎する雰囲気のBGM

x 1

## MenuSelectScene
* LevelSelect/Record/Settingの画面切り替えで特にBGMは変わらない
* （要検討）地図のスクロール位置の季節に応じてBGMを変える
* （要検討）時間帯による変化

x 1

## StageSelectScene
* 季節毎にBGMを用意
* 木全クリアした状態でアレンジする

x 8
 
## GamePlayScene
* チュートリアル中/Opening中のBGM
* PlayingステートのBGM
* 難しいステージはアレンジする

x 4?

**Comment by takesi0627** [comment]
@xiii111 @takasusuke 
まだまだ終わりが見えないですが、進捗が気になる方は
[こちら](https://scrapbox.io/treevel/BGM) で確認していただければと思います

**Comment by takesi0627** [comment]
新しいマイルストーンに移行するため、見積もりラベルを更新します

**Comment by takesi0627** [comment]
@xiii111 @takasusuke 

最終的にどう選ぶか悩みに悩んだが、やはり議論だけだと決めづらいので数値的な評価にしたいと思いました。
各曲に対して10段階評価してもらいたいと思います。
基準は各自で決めていただいても大丈夫です。ただの好みでも結構です。
記入する順番によって他人の評価に影響される恐れあるかと思うのでアンケートを用意しました。
https://forms.gle/ywuH4mLGYizVf9z59

URLからアクセスして記入してください。期限は今週の2/7のMTGまででお願いします。
記入した点数はMTGまで僕がScrapboxに反映させます。

結構時間かかると思いますので時間の確保にご注意ください。
よろしくお願いいたします。

**Comment by xiii111** [comment]
📝 すごく今更だが、季節ごとに分けることは世界観への愛着が増える一方で、テンポよく画面遷移をして何回もゲームをプレイするというコンテキストには合ってない気がした。BGM が切り替わりすぎる

**Comment by xiii111** [comment]
回答しました！

**Comment by takasusuke** [comment]
回答しました

**Comment by takesi0627** [comment]
使用するBGMは下記と決まりました。

* StartUpScene : [夏の終わりを感じさせる失恋系BGM](https://audiostock.jp/audio/133279)**（27秒まで）**
* MenuSelectScene: [優雅であたたかい神秘的BGM](https://audiostock.jp/audio/199247)
* StageSelectScene-Spring: [桜、春をイメージしたピアノバラード曲](https://audiostock.jp/audio/803875])
* StageSelectScene-Summer: [自然や星空のイメージ　穏やかな生ギター](https://audiostock.jp/audio/862951]) **(＊暫定）**
* StageSelectScene-Autumn: [MusMus-BGM-072](https://drive.google.com/file/d/1ukYnku54F91AdlLmB9k2PSlynTHCcXEm/view?usp=sharing)
* StageSelectScene-Winter: [ピアノソロ個性とプライド](https://audiostock.jp/audio/115117)**（1:03まで）**
* GamePlayScene-Tutorial : [穏やかでノリのいい牧歌的な雰囲気](https://audiostock.jp/audio/174495)
* GamePlayScene-Spring: [桜の舞い散る新生活（ピアノメイン）](https://audiostock.jp/audio/826991)
* GamePlayScene-Summer: [夏の癒し・ノスタルジックなピアノソロ](https://audiostock.jp/audio/841096)
* GamePlayScene-Autumn:  [疾走感・民族調のフルートとギター](https://audiostock.jp/audio/222773)
* GamePlayScene-Winter: [ピアノソロ個性とプライド](https://audiostock.jp/audio/115117)**（1:03から、StageSelectScene-Winterと同じ音源）**
* GamePlayScene-Difficult: [bgm_maoudamashii_piano32](https://drive.google.com/file/d/1gmLcWm2_ZLhj6I8jN2wMwsADgLDPcDaR/view?usp=sharing)


使用するBGMを[Treevel/Sound/BGM/](https://drive.google.com/drive/folders/15JyXV9Hm-oachK2Rh0steV3nzR8OJMBw?usp=sharing)に移しました。


これを持って本イシューを完了とします。
