### ISSUE TITLE
HolyTile上に初期位置を持つBottleがギミックに当たることがある

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#676]
### 現状
ゲーム開始時の`OnEnterTile`が呼ばれる時に、`HolyTile`がインスタンス化されていないことがおそらく原因

### 終了条件
`HolyTile`のインスタンス化を終えてから`OnEnterTile`を呼ぶ

### 実装方針
`Bottle`, `Tile`のインスタンス化を終えてからゲーム開始時のイベントを呼ぶ

**Comment by takasusuke** [comment]
バグ再現手順(3回試行して3回バグを出せた)
[準備]あらかじめステージ詳細をOFFにする
1. 実行する
2. Spring-1-1をクリアする
3. Spring-1-3をプレイする
4. HolyTile上のBottleにTornadoが当たると衝突する

**Comment by xiii111** [comment]
なんだそれw
