### ISSUE TITLE
Rider の Code Style 設定を共有

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#695]
- [ ] `githooks` をやめる
- [ ] `Rider` の `Code Style` 設定を共有して、チームで統一する

**Comment by xiii111** [comment]
📝 

```
$ git config --unset core.hookspath
```

で `githooks` をやめれる

**Comment by xiii111** [comment]
📝 `Rider` のバージョン： `2020.3.2`

**Comment by xiii111** [comment]
- https://pleiades.io/help/rider/Using_EditorConfig.html?keymap=secondary_resharper_osx#what_is
