### ISSUE TITLE
ゲーム画面からステージ選択画面に戻る際に、適切な木に戻れていない

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#699]
再現手順：

https://user-images.githubusercontent.com/17778395/104090263-01f20e00-52b9-11eb-92fd-8ee19c643efc.mov

### 完了条件
- [x] 全ての季節において、ゲーム画面からステージ選択画面に戻る際に、適切な木に戻れるようにする

### 実装メモ
- ステージからゲームに行く時は、木の情報を渡してるけど、ゲームからステージに行く時は、木の情報を渡していない可能性があるので、戻る際に正確な木に移動できていない

**Comment by xiii111** [comment]
📝 StageSelectScene の seasonId と treeId は static メンバーなので、GamePlayScene から StageSelectScene に戻る場合には、これらの情報を渡さずとも正常に動くはず

**Comment by xiii111** [comment]
📝 MenuSelectScene から初めて StageSelectScene に行った場合に、左右の木に移動せず、その木をプレイした場合にのみ、問題が発生する
