### ISSUE TITLE
アプリをバックグラウンドに移動させた時にBGMが小さくならない

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#701]
- [x] #877 による解決したかもしれないので。確認

### 現状
復帰する時に大きくなるので、バックグラウンドから復帰するたびに音量が大きくなる

### 解決策
BGMが流れていない場合でも、音量を変更できるようにする

**Comment by takesi0627** [comment]
develop にて現象が解消されたことを確認したため、本イシューをクローズします
