### ISSUE TITLE
多様なデバイスにUIを対応させることの検討

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#704]
### 終了条件
- CanvasScalerを用いるかどうかを検討する
用いる場合に、対応していない部分を対応させること(対応できるようにするスクリプトなど)を実装するのは別issue

#### 考慮事項
- 既存の UI の内、多様なデバイスだと表示が崩れているものがある（https://github.com/LITO-apps/Treevel-client/pull/689#issuecomment-760185099 など）
- これは CanvasScaler に UI を対応させていないことが原因である
- CanvasScaler 自体の存在価値があるかも、明確ではなくなってきている可能性があるので、CanvasScaler を外すことも検討する
- 他にも `Screen.width` を使っているような場所では、`RuntimeConstants` の定数を使うように変更する必要もあるかもしれない

**Comment by takasusuke** [comment]
### CanvasScalerを使わない場所
#### 1. 画面サイズのx方向、y方向それぞれの比で画像の位置や大きさを指定する場合
画像自体のアスペクト比は崩れる
- 基本的なUI

#### 2. 画面サイズのx(or y)方向の比で大きさを指定し、y(or x)方向はそれに対する比で指定する場合
画像自体のアスペクト比は保証されるが、デバイスに対する画像のアスペクト比は崩れる
- タイトルロゴやマークなど
- 正方形、正円など
- MenuSelectSceneの木？(木と木の間はデバイスによって狭くなったり広くなったりする、画面端に配置するとデバイスによっては見切れる)

### 3. CanvasScalerを使う場所
#### 元々の画像の縦横比もある程度維持しつつ、デバイスのアスペクト比の違いも吸収する場合
- 

https://light11.hatenadiary.com/entry/2019/04/21/222337

**Comment by takasusuke** [comment]
元々なんでCanvasScalerを使ってたのかもわからんくなってきたし、
なんでCancasScalerを使うかどうか検討してるかもわからんくなってきた。
(記録画面のレイアウトは直せた。)

最初は多分、MenuSelectSceneの木のオブジェクトを良い感じに描画したくて使ってたんだけど、整理してたら木のオブジェクトは(2)の方が適切に思える。

逆に、このissueを検討するきっかけになった記録画面は修正できたこともあって、(3)の方がレイアウト的には良い気がしてきた。

**Comment by takasusuke** [comment]
UIやオブジェクトをそれぞれどのように配置するか洗い出して議論したらこのissueは閉じる。
配置方法の修正は別issueにする

**Comment by takesi0627** [comment]
これ今どういうステートですか？

**Comment by takasusuke** [comment]
まだ作業中。

**Comment by takasusuke** [comment]
上：理想的なデバイスのアスペクト比
中央：比率指定で画像を表示している場合にデバイスのアスペクト比を変更した場合
下：サイズ指定で画像を表示している(CanvasScalerあり)場合にデバイスのアスペクト比を変更した場合
<img width="306" alt="スクリーンショット 2021-03-14 8 06 25" src="https://user-images.githubusercontent.com/26213141/111052225-95ec7b80-849c-11eb-8db4-3bf144318e85.png"> 
<img width="504" alt="スクリーンショット 2021-03-14 8 07 02" src="https://user-images.githubusercontent.com/26213141/111052228-984ed580-849c-11eb-8dd8-3fdf6c1ee6e1.png"> 
<img width="558" alt="スクリーンショット 2021-03-14 8 06 39" src="https://user-images.githubusercontent.com/26213141/111052226-971da880-849c-11eb-9b89-26d76d7674f5.png">

**Comment by takasusuke** [comment]
## CanvasScalerを用いる
### メリット
- 異なるアスペクト比のデバイスに対応できる(iPadほどの違いじゃなくても)
### デメリット
- 実装の時に、サイズが変わることを気にして配置する必要がある

## CanvasScalerを用いない
### メリット
- 実装が楽
### デメリット
- 異なるアスペクト比のデバイスで、画像のアスペクト比が変わる

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
各オブジェクトに対してどのように配置すべきかまとめました
(https://github.com/LITO-apps/Treevel-client/issues/704#issuecomment-791977625)

CanvasScalerを使うメリット・デメリットをまとめました( https://github.com/LITO-apps/Treevel-client/issues/704#issuecomment-798800837 )

用いるかどうかコメントお願いします

**Comment by takasusuke** [comment]
CanvasScaler使うぞー！(圧)

**Comment by takasusuke** [comment]
#771 で既存のオブジェクトを修正します
