### ISSUE TITLE
AimingMeteoriteGimmickのデザイン草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#720]
### 終了条件
- 草案資料を作成する

##### Meteoriteと同じ
- モチーフ

#### Meteoriteとの違い
特定のBottleを狙ったことを知らせる必要ある
- 影の部分の登場方法
- 色
- 軌跡(?)
- Game開始時に、狙われているBottleを知らせる

**Comment by takasusuke** [comment]
仕様を先に決める

**Comment by takasusuke** [comment]
Aimingであることを伝える案が視認性などから微妙なら、ユーザには伝えない内部パラメータとするのもありかと思います。
ひとまず、影とかの案を考えます。

**Comment by takasusuke** [comment]
草案資料
https://docs.google.com/presentation/d/1sJTE4G4C7wzXQIcDr9DbdnRKsBpryvShXAaVcBgLRao/edit#slide=id.gaaa75cf2d6_0_0

**Comment by takasusuke** [comment]
@xiii111 @takasusuke 
Slackでのコメントお願いします。
今回の草案はいつもと主旨が違います。
案の中から１つを選ぶのではなく、案の中から採用されたものを全て組み合わせた演出にします。
また、案は絶賛大募集中です。

**Comment by takasusuke** [comment]
結論
- Meteoriteは影がぶれない
- AimingMeteoriteは影がぶれる
- AimingMeteoriteは影が追従する

本体が現れた時の演出(Meteoriteとの違い)は、Metooriteのデザイン適用ののちに、AImingMeteoriteのデザイン適用の際に、以下を実装し比較・決定します！
- 本体の色を変える
- 本体の軌跡を変更する
- 本体の出現位置を右上ではなく、左上にする

**Comment by xiii111** [comment]
@takasusuke Aiming はブレない、じゃなかったっけ？

**Comment by takasusuke** [comment]
AimingMeteoriteはDesign依頼は無いのでいったん終了です。
Meteoriteのデザイン適用のissueが終わったらAImingMeteoriteのデザイン適用issueは作られると思います。

**Comment by takasusuke** [comment]
> @takasusuke Aiming はブレない、じゃなかったっけ？

読まずにコピペしてた。。。修正します！
