### ISSUE TITLE
【PlayFab】基盤実装事前調査

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#724]
[SampleCode](https://github.com/PlayFab/PlayFab-Samples/tree/master/Samples)を読み、適切の実装方法をまとめる

- [ ] Playfabのベストプラクティスについて調査する（公式サンプル、Qiita）
- [ ] 設計を提案する

**Comment by takesi0627** [comment]
# 要件定義
### 目的
* PlayFabClientAPIの仕様の知識がなくても直感的なメソッド呼び出しでPlayFabとの通信を完結させる（このクラス以外はPlayFabClientAPIをアクセスさせない）


* UniTask で通信を await でできるようにする
    * UniTaskに変換する方法：
        * [PlayFabのUnitySDKのコールバック地獄の対応 - Qiita](https://qiita.com/yKimisaki/items/fc8a3deed9b75f752bd3)
        > 古い記事なので検証してみて出来なかったら諦める


### 要件
* クラス名： `PlayFabService`
* ネームスペース： `Common.Networks`
* メソッド例：
`public static UniTask<bool> Login()`
`public static UniTask<StageRecord> GetStageRecord(int stageId)`
`publlic static UniTask<bool> UpdateStageRecord(int stageId, StageRecord newRecord)`
`public static UniTask<List<Achievement>> GetAchievements()`


機能ごとにクラスを細かく分けることが多いですが、（`PlayFabAuthencationService`、`PlayFabPlayerService` などの分け方はよくみられる）
現状考えられる機能は少ないので、とりあえず一つでいきたいと思います。今後ファイルが大きくなったら分ければ良いかと考えています。


### 参考資料

* [UnicornBattle/UnicornBattle at master · PlayFab/UnicornBattle · GitHub](https://github.com/PlayFab/UnicornBattle/tree/master/UnicornBattle)
> 公式が出した完成度が高めのサンプルゲーム。ただPlayFab以外もFirebaseとか別のサービスとの連携もいるので実際に動作確認とかはしてなく、GitHubでコードを眺めただけでした。[ここを見ると雰囲気がわかると思う](https://github.com/PlayFab/UnicornBattle/tree/master/UnicornBattle/Assets/Scripts/PF_StaticsAndHelpers)


* [PlayFab-Samples/Samples/Unity at master · PlayFab/PlayFab-Samples · GitHub](https://github.com/PlayFab/PlayFab-Samples/tree/master/Samples/Unity)
> こちらも公式出しているサンプルですが、どちらかというと機能ごとの紹介なのでコードちょっと適当感があり、あんまり参考にはならなかった。ただし、認証周りのコードは良く書けているので参考にはしています。

* [UNION-OpenSource-MOBA](https://github.com/tammukul/UNION-OpenSource-MOBA)
> 適当に見つけたプロジェクト。[PlayFabManager.cs](https://github.com/tammukul/UNION-OpenSource-MOBA/blob/master/Project/Assets/Scripts/Account%20Management/PlayFabManager.cs) が `PlayFabService` と同じ役割を担当する

* [PlayFabマスターへの道｜PlayFabを学習したいあなたへ](https://playfab-master.com)
> 今回のイシューとはあんまり関係ないが、めちゃくちゃわかりやすいブログなので今後作業するときに参考にできると思います。

**Comment by takesi0627** [comment]
@xiii111 @takasusuke 
要件と言ってもそんな大した設計じゃないですが、
参考したプロジェクトも大体こんな感じでやってるんじゃないかと思います。

気になることあればなんでもコメントしてください。よろしくお願いします
大まかな方向性に異論がなければ実装を進めたいと思います。
（と言ってもクラス作って終わりかもしれません、実装は都度イシュー作成することになると思います）

**Comment by xiii111** [comment]
Singleton にして static ではなくすのはどう（諸説あり）

**Comment by takesi0627** [comment]
`PlayFabClientAPI` 自体が `static` なので、インスタンス化する必要はないかと思います。
実際参考したプロジェクトも `static` にすることが多い

**Comment by takesi0627** [comment]
どちらかというとユーティリティクラスな印象が強い

**Comment by takesi0627** [comment]
あ、 `PlayFabClientAPI` というのは `PlayFab` に実際リクエストを飛ばすメソッドがいっぱい書いているクラスのこと

**Comment by xiii111** [comment]
了解。

> 現状考えられる機能は少ないので、とりあえず一つでいきたいと思います。今後ファイルが大きくなったら分ければ良いかと考えています。

同意。StageRecord の CRUD、Achievement の CRUD ごとに Class は切りたいですが、今回は 1 つで良いと思います。

**Comment by takesi0627** [comment]
🗒️ 要件: 
* リクエスト発行するときにどこに問い合わせているか知る必要はない
* 簡単にサーバーの切り替えができる設計
* 現状の `IServerRequest` の設計を参考に

**Comment by xiii111** [comment]
作業中だったと思うので、カンバン移動しておきます

**Comment by xiii111** [comment]
@takesi0627 これはどうなってます？

**Comment by takesi0627** [comment]
ドキュメント書きたかったけど、要件を揃えた実装になったのでこれでいいや。ww
閉じます。
