### ISSUE TITLE
TornadoGimmick のデザイン草案作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#725]
### 手順
1. TornadoGimmick のデザインに関わる仕様を洗い出す
2. デザインモチーフを調べる
3. 調べた結果からデザインを分類する
4. 伝わる形（草案資料）に書き起こす → ボトルと同じサイズ感にして、実際の状況をイメージできるように
5. デザイン批評会を開く
6. 修正する
7. デザイン依頼をする

### 完了条件
- [x] 草案資料の作成
- [x] デザイン依頼

### 草案
https://docs.google.com/presentation/d/1zcYT-V0iZGVex1-edBUyEhZYvTghHpR8D2mcV5-2wdo/edit#slide=id.gaaa75cf2d6_0_0

**Comment by xiii111** [comment]
@takasusuke @takesi0627 明日の定例会で話したい内容です。認識が違うところ、納得できないところがあれば、すり合わせましょう。

## 仕様
・タイルの行 or 列の延長線上（タイル上を除く画面内）のみから登場する（現状は、画面外から登場する）
・登場する際には、アニメーションが発生し、登場することに対する警告をする（現状は、記号的な警告が出る）
・ThunderGimmick のように斜めには移動せず、十字方向にのみ移動する
・任意のタイルの中心でのみ曲がることができる
・曲がる際には、瞬間的に曲がらず、曲がるタイルの中心で少し停止する（現状は警告がある）
・最終的には必ず退出する
・Bottle との当たり判定は、オブジェクト全体
・Attackable な Bottle に触れたら、Bottle に 1 ダメージを与える
・Attackable な Bottle に触れても、TornadoGimmick は消えない

## 見た目の要件
・移動することが伝わる
・Attackable な Bottle に触れたら、Bottle にダメージを与えることが伝わる
・Attackable な Bottle に触れても、TornadoGimmick が消えないことが伝わる

**Comment by takesi0627** [comment]
> ・最終的には必ず退出する

退出する方法は？
・画面外まで移動する（現状）
・定点フェイドアウト
・デザインに準ずる

**Comment by takasusuke** [comment]
当たり判定
- 常に当たり判定があるのか、当たり判定が無い瞬間があっても良いのではないか(当たり判定がないことを示す演出が必要)
以下に示す案だと、竜巻に近い挙動になると思うが、Tile上の滞在時間が長くなるので難しくなることが予想される。
そこで移動中や曲がる準備中は当たり判定が無くても良いかも、という考えになりました

曲がる方法
- 直角に曲がるのではなく、左方向に進んでいる状態で上方向に曲がる場合、タイル上で回転したら、曲がるまでの猶予時間もあるし、タイル上に警告を出さなくて済むのではないか
![export 214](https://user-images.githubusercontent.com/26213141/107855573-99252500-6e66-11eb-9bc6-195922ab1806.png)

移動方法(デザインには関係ないかも)
- 一方向に進むのではなく、進んで戻って進んで戻っての移動はどうか
![export 213](https://user-images.githubusercontent.com/26213141/107855700-21a3c580-6e67-11eb-8e53-da2a7c4d9842.png)

**Comment by xiii111** [comment]
### 議論で挙がったこと
- 曲がり方をどうするか？一時停止して、予兆なしに曲がる場合には、難し過ぎる。どの方向に移動するのかを伝えたい。その場合にはカーブすることが考えられるが、カーブする時だけ竜巻を小さく表現するなどして、対応する必要もある。
- もう少し竜巻らしさを出すなら、止まったり減速したりなど
- 竜巻の高さはタイルの高さ以内に収めないと、だめ？飛び出てもダイナミックで良いのでは
- 見る角度の違いも提示する

**Comment by xiii111** [comment]
@takasusuke @takesi0627 Slack でコメントお願いします！

**Comment by xiii111** [comment]
@takasusuke https://docs.google.com/presentation/d/1zcYT-V0iZGVex1-edBUyEhZYvTghHpR8D2mcV5-2wdo/edit#slide=id.gaadc17f28d_0_55 この内容でデザイン依頼しようと思っていますが、少しレビューしていただけませんか？

**Comment by takasusuke** [comment]
スライドを追加して、いくつか修正しました。

（これは先に言っとけということだけど）
- 分かりやすぎるくらい分かりやすい方が良い、ということを前聞いたので、それを意識してます。
- 事実、理想を先に書いて、理由とか意図はその後を意識している。端的に、結局欲しいものは何？というのがわかる方が良いらしい。
- これは説明しづらいけど、自分が言われた時にそういう感じで言われたくないな、という表現を直しました。
（こんくらいで良いよ、と言われるよりはこんくらいが良い、と言われた方が楽、みたいな、、、）
（〇〇して欲しい、と言われるよりは、〇〇したい、と言われた方がやる気が出る、というかそんな感じ）

**Comment by xiii111** [comment]
@takasusuke ありがとうございます！明日の定例会で少しすり合わせて、依頼しようと思います！

**Comment by xiii111** [comment]
デザイン依頼（ #764 ）を行いました。
