### ISSUE TITLE
TornadoGimmick のデザイン

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#764]

**Comment by xiii111** [comment]
草案資料（ #725 ) 
- https://docs.google.com/presentation/d/1zcYT-V0iZGVex1-edBUyEhZYvTghHpR8D2mcV5-2wdo/edit#slide=id.gc1253cf8d9_0_0

**Comment by takasusuke** [comment]
https://drive.google.com/drive/u/0/folders/15B-mDQNZSt6RnUJ9tIXlQFTwGoVsCnDG

**Comment by takasusuke** [comment]
@LITO-apps/engineer
確認よろしくです。

何か修正依頼等あればまとめてコメントします。

ない場合、適当にreactionつけといてください。

**Comment by takesi0627** [comment]
最高っす

**Comment by xiii111** [comment]
最高。早く適用したくてしょうがない

**Comment by takasusuke** [comment]
#1194 で適用します
