### ISSUE TITLE
ギミック、ボトル、タイルの関係性をまとめる

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#787]
### 終了条件
ギミックとボトル、ギミックとタイル、ボトルとタイルの関係性を記述する
Decision Tableを書く
状態遷移表を書く

### 考慮事項
OnEnterTileとかのイベントを記述して見やすくする
〇〇されたら××する、とか

**Comment by takasusuke** [comment]
ディシジョンツリーを作成中
成功判定については完了。
https://docs.google.com/spreadsheets/d/1LfxHp_nnuXTH6CqkNJYT9e_vNYCDSmKCyxVwXpereg4/edit#gid=2092108194

**Comment by takasusuke** [comment]
現在のボトル、タイル、ギミックのイベントの実行順序を以下にまとめました
https://app.diagrams.net/#G1HwHyeLbCmKwR8ElG09sZIwbnMaseLXe2

**Comment by xiii111** [comment]
@takasusuke まだレビュー中じゃないです？（メンションくれるみたいな話だったであってる？）

**Comment by takasusuke** [comment]
レビュー中じゃないです(作業中に戻した)

**Comment by takasusuke** [comment]
## 議題
### 1. GoalTileとの組み合わせ
Holy, Spiderweb, Ice, Warpはそれぞれ互いに組み合わせたTileは存在しない、ということになりました。
GoalTile & HolyTile, GoalTile & Spiderweb, GoalTile & IceTileのは存在するのかどうかは決まっていませんので決めます。

### 2. GustWindの仕様について
現状はGustWindの方向に一気にBottleが移動して、その間に通過するTileの効果は発動しない
- このまま
- 一気に移動するけど、通過するTileを順に全て発動する
- 一定時間GustWindを受けていると１Tile移動する
- 一気に移動するけど、途中にSpiderwebがあったら止まるようにする

などなど、どのような仕様にするか。
現状確定しているのは、StaticBottle, ErasableBottleは移動しない、ってことくらい。

### 3. １度に複数のGimmickがBottleに当たった場合の処理について
現状は複数のGimmickがBottleに当たるとその分Lifeが減る。
Lifeが減ってから一定時間無敵扱いするのはどうか。

### 4. その他のレアなユースケースがあればそれについて

## 話し合いで決まったことに加えて以下をissue化してこのissueを閉じます
- Spiderweb中にGhostAttributeの効果が働いてもBottleは移動しない実装になっているのか確認する
- GhostAttribute, PowderGimmickなど内部時間を持っているギミックはIce, GustWindなど他の要因で移動した時にもその時間を0にし直す
- DarkAttributeやGhostAttributeのついたBottleをホールド中にGustWindの効果でBottleが移動した時の挙動を確認する
(ホールドが外れてほしい)

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
議題の1~4についてコメントお願いします

**Comment by xiii111** [comment]
@takasusuke お疲れ様でした。以下コメントしました

> 1. GoalTileとの組み合わせ

GoalTile は全体に背景色を含んでおり、この色情報はユーザに正確に伝わる必要があります。そのため、色を全体に利用している HolyTile と IceTile と組み合わせるのは無しだと思っています。一方で SpiderWeb に関しては、組み合わせることで複雑なステージにはなりますが、色情報を阻害しないので、ステージ制作者の裁量で組み合わされても良いと思います

> 2. GustWindの仕様について

一気に移動する、という仕様にするのであれば、実質瞬間移動と見なされる方が自然だと思いますので、`一気に移動するけど、通過するTileを順に全て発動する` や `一気に移動するけど、途中にSpiderwebがあったら止まるようにする` は無しだと思っています。`このまま` にするか `一定時間GustWindを受けていると１Tile移動する` にするかですが、他のオブジェクトとの不都合が生じづらい方を選ぶ方が、幸せになると思いました。恐らくその観点で選択するのであれば、後者になると思います

> 3. １度に複数のGimmickがBottleに当たった場合の処理について

同時に複数ギミックが当たることは珍しく、エッジケースのために例外を今から実装する必要はないかなと思います。もしテスト段階などで、同時にぶつかり不都合な挙動をしたり、難易度に大きく影響が出ることが判明したら、（少し急ぐことにはなりますが）その時点で実装すれば十分だと思います。

> 4. その他のレアなユースケースがあればそれについて

現時点では特に思いつきません

**Comment by takesi0627** [comment]
>  1. GoalTileとの組み合わせ

前のMTGでも話しましたが、タイルの数が少ないため少しでも組み合わせることができた方がバリエーションが増えていいと思っています。
>>  色を全体に利用している HolyTile と IceTile と組み合わせるのは無しだと思っています

IceTileですが、このように傷と重なっても十分機能するだと思いますが、いかがでしょうか
（もちろん水色とかみづらい場合もあると思うが、そこはステージデザイナー次第なので考慮しなくても良いかと）
![image](https://user-images.githubusercontent.com/17778395/115415356-ceb50880-a231-11eb-9909-b0791d4a9fc5.png)


>  2. GustWindの仕様について
> 現状はGustWindの方向に一気にBottleが移動して、その間に通過するTileの効果は発動しない
> 
> * このまま
> * 一気に移動するけど、通過するTileを順に全て発動する
> * 一定時間GustWindを受けていると１Tile移動する
> * 一気に移動するけど、途中にSpiderwebがあったら止まるようにする

現状だと一番懸念あるのはSpiderwebのモチーフに合わない問題だと思うので、Spiderwebがあったら留まるようにするのはありと思います。というのもSpiderwebのためだけに大幅の改修を避けたいと思った次第です。


> 3. １度に複数のGimmickがBottleに当たった場合の処理について

僕も @xiii111 と同意見で、都度対応すれば良いかと。

**Comment by takasusuke** [comment]
> 1. GoalTileとの組み合わせ
GoalTileとHoly, Spiderweb, Iceのどれも組み合わせたい（実際に組み合わせたステージは終盤のステージじゃないと出さないくらいの感覚）です
GoalTileを仮に8個盤面に置くと、他のTileを置く場所が少なくて尖ったステージを作りにくい、と感じます。
 
> 2. GustWindの仕様について
正直、一気に移動する、かつ、全てのTileを発動する、は考慮するケースが多すぎてあまり望んでいないのと、今のGustWindの強制的にBottleを移動させる演出が気に入っている。
一定時間GustWindを受けていると１Tile移動する、は面白いので別のGimmickとしてあっても良いけど、先に実装するのは一気に移動させる方の気持ち。１Tile分動く演出はGhostAttributeやIceTileでも存在するので、大きく異なる感じのギミックを先に実装したい。
途中にSpiderwebがある場合でも、Gustwindの強さ的にSpiderwebは発動しなくても良いかな〜と思っているけど、強い主張ではない。

> 3. １度に複数のGimmickがBottleに当たった場合の処理について
Lifeが多段Hitするかどうかで作るステージデザインも変わると思います。
自分はLifeが減った場合、一定時間無敵扱いにしたいと考えています。
メリット
- Lifeが減る間のアニメーション時間を確保できる（無敵時間=アニメーションの0.5秒間くらいの認識）
- ユーザにとってゲームが簡単になる（Lifeさえあれば完成の形に無理やり持っていくこともできるから）
薄い話だけど、超将来的に、Lifeをアイテム要素としてゲーム開始前に追加する際にユーザが得られる恩恵が大きい

デメリット
- Lifeさえあれば無理やり完成できるのでゲーム性を失うともいえる
- Lifeが100以上あって、ビームとかが当たっている間は継続的にLifeが減る、といったギミックはできない。
- 無敵時間がある状態で別のTornadoと衝突していて、衝突したままの状態で無敵時間が終わった時の処理をどうするかの問題がある
Lifeが減る、で良いとは思う

その他
- あんまり多段Hitするゲームを知らない。

**Comment by takasusuke** [comment]
1度に複数のGimmickがBottleに当たった場合の処理について

> 
> 同時に複数ギミックが当たることは珍しく、エッジケースのために例外を今から実装する必要はないかなと思います。もしテスト段階などで、同時にぶつかり不都合な挙動をしたり、難易度に大きく影響が出ることが判明したら、（少し急ぐことにはなりますが）その時点で実装すれば十分だと思います。

> 
> 僕も @xiii111 と同意見で、都度対応すれば良いかと。

本来Lifeを導入する段階で仕様として決めておくべき仕話で、起こりうる頻度で判断することではないと思います。
なので、多段Hitを許す他の理由（ゲーム性、実装の都合など）を聞きたいです。
「現状は多段Hitするようになっていて、それを変更するコストを考えると今の仕様でも問題ないからこのまま。プレイしてみて変えたくなったらその時に変えれば良い」というご意見であれば、再度そのようにコメントをお願いします。
変更するコスト、について起こりうる頻度も考慮されている（むしろそれが大きい）と感じたので、起こる頻度は関係ないとしたら、どう感じているのかを知りたい、という理由です。

**Comment by takasusuke** [comment]
# 意見まとめ
### 1. GoalTileとの組み合わせ
SpiderwebはGoalと組み合わせても良さそう
Ice, Holyは組み合わせるor組み合わせないの意見で割れ中。
争点：見え方とステージのバリデーションの天秤。

### 2. GustWindの仕様について
争点：一気に移動する or １Tileずつ移動する
争点：一気に移動するとした場合、Spiderwebが働くかどうか

### 3. 1度に複数のGimmickがBottleに当たった場合の処理について
争点：無敵時間を導入する場合のゲーム性について
争点：導入する場合の実装コスト（とその恩恵）

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
意見をまとめたので、レビュー通話であとは決めましょう。
（他の人の意見を受けた上でコメントしておいてもらえるとレビュー通話の時に楽。）

**Comment by xiii111** [comment]
@takesi0627 

> IceTileですが、このように傷と重なっても十分機能するだと思いますが、いかがでしょうか
（もちろん水色とかみづらい場合もあると思うが、そこはステージデザイナー次第なので考慮しなくても良いかと）

傷との重なりは問題ないですが、紫色の傷には紫色の背景色が含まれるようになったと思います。そことの重なりを危惧しています

**Comment by takasusuke** [comment]
### 1. GoalTileとの組み合わせ

### 2. GustWindの仕様について
このまま

### 3. 1度に複数のGimmickがBottleに当たった場合の処理について

**Comment by takasusuke** [comment]
仕様決定を行いました。

仕様確認、仕様変更のための以下のissue
#894 
#895 
#896 
#897 
を作成しました。
