### ISSUE TITLE
Bottle, Tileが２回生成される問題の確認

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#789]
### 終了条件
- [x] 以下の動画のように、Bottle、Tile(おそらくギミックも)が２回生成される問題が再現できるか確認

### 再現手順
１度ゲームを行い、ポップアップを表示→非表示→表示してゲーム画面に入ると起きる。

https://user-images.githubusercontent.com/26213141/113173814-bbdb9380-9284-11eb-953a-3134cb4ab97a.mov

**Comment by takesi0627** [comment]
再現しないこと確認しましたので閉じます
