### ISSUE TITLE
エラーの詳細を表示せず、エラーコードを表示する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#792]
- [ ] クライアント側のエラーコード習慣調査
- [ ] エラーコードのみ表示する

**Comment by xiii111** [comment]
📝 エラーコードの規則性について、少し調べる

**Comment by takesi0627** [comment]
📝[エラーコードはenumで実装すべきという話](https://qiita.com/nrslib/items/1287b5888f7db6166320)

**Comment by takesi0627** [comment]
https://github.com/orgs/LITO-apps/projects/2#card-64343204

エラーコードの問題をアイデアに挙げました。
割と必要性が低いだと思うのでアイデアにしていますが、MTG時にイシューにするかどうかまた検討する。
このイシューの対応範囲はエラーメッセージを塞ぐことです。
