### ISSUE TITLE
BGMを鳴らすところを洗い出す

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#80]
- [ ] BGMを再生する場所をリスト化

**Comment by xiii111** [comment]
- 待機時のサウンドトラック
- ゲームプレイ時

**Comment by takasusuke** [comment]
細かいissueに分ける

**Comment by takesi0627** [comment]
イシュー名を変えて再開する

**Comment by takesi0627** [comment]
* StageSelectScene
    * 春
    * 夏
    * 秋
    * 冬

* GamePlayScene
    * 春
    * 夏
    * 秋
    * 冬

StageSelectSceneとGamePlaySceneは基本季節に応じてBGMを流す。

StartSceneとMenuSelectSceneについては下記2案を考えています

## 案1
StartScene->MenuSelectSceneで共通1つ（StageSelectSceneとGamePlaySceneとは異なるやつ）

## 案2
* StartScene用BGM１つ
* MenuSelectSceneでは画面中心にいる季節に合わせて、StageSelectScene各季節対応するBGMで切り替える

**Comment by takesi0627** [comment]
@xiii111 @takasusuke 
上記のコメントについてご意見お伺えればと思います。よろしくお願いします

**Comment by xiii111** [comment]
- StageSelectScene や GamePlayScene の BGM が季節ごとだと、季節が変わるまで BGM が変わることがないので、BGM が飽きられてしまいそう。木ごとに BGM を用意するのはどうでしょうか
- StageSelectScene に関しては、木を完全にクリアした場合などには BGM をアレンジしたいです
- GamePlayScene に関しては、一番難しいステージ（木のてっぺん？）などは BGM をアレンジしたいです
- StartupScene と MenuSelectScene に関しては分けたいです、イメージだけで話すと StartupScene は歓迎、MenuSelectScene は日常、という雰囲気の BGM を流したいです。
- MenuSelectScene は現在時刻に合わせて背景を変えたりしたいので、時刻に合わせて BGM が変わっても良いかも。画面中心にいる季節に合わせて切り替えるのは、スクロール領域の狭さ的厳しいと思います（例えば、ガッとスクロールした場合に、いろんな季節を同時に跨いでしまいぐちゃぐちゃになりそう）。季節や木のクリア状況や、プレイ中の木（前回プレイした木とか？）の BGM にするとかも良いかも
- MenuSelectScene の中でも、LevelSelectScene と RecordScene などで BGM は分けたいです

**Comment by takasusuke** [comment]
- MenuSelectScene(LevelSelect, Record, Setting)ではBGMを分け、、、、分け、、分けなくて良い派。Record→LevelSelectに行ったときにBGMが最初から再生されるよりは、通しで聞いてもらいたい気がする。
- StartSceneとMenuSelectSceneは分けたい
- GamePlaySceneチュートリアル中のBGM
- GamePlayScene、Opening中のBGM(チュートリアル中と同じでも可。)Playing中とは別のにしたい。
- GamePlayScene成功時のBGMいる？Play中のBGMそのままでも可。
- GamePlayScene失敗時のBGMいる？Play中のBGMそのままでも可。

**Comment by takesi0627** [comment]
# コメント回答

> 画面中心にいる季節に合わせて切り替えるのは、スクロール領域の狭さ的厳しいと思います（例えば、ガッとスクロールした場合に、いろんな季節を同時に跨いでしまいぐちゃぐちゃになりそう）。

これに関してはスクロール位置が一定時間動かない時に変えたりすれば技術的に解決できると思うので問題にはならないと思います。


> * MenuSelectScene の中でも、LevelSelectScene と RecordScene などで BGM は分けたいです 
> * MenuSelectScene(LevelSelect, Record, Setting)ではBGMを分け、、、、分け、、分けなくて良い派。Record→LevelSelectに行ったときにBGMが最初から再生されるよりは、通しで聞いてもらいたい気がする。

僕もMenuSelectScene 中の LevelSelect/Record/Setting は変えない派です。理由は同 @takasusuke 

> * StageSelectScene や GamePlayScene の BGM が季節ごとだと、季節が変わるまで BGM が変わることがないので、BGM が飽きられてしまいそう。木ごとに BGM を用意するのはどうでしょうか

確かに飽きられそうですが、木ごとにBGM用意するのはさすがにやりすぎだと思います。時間帯によって変えたり、別の方法でバリエションを増やせたら良いかなと思います。


> * GamePlayScene成功時のBGMいる？Play中のBGMそのままでも可。
> * GamePlayScene失敗時のBGMいる？Play中のBGMそのままでも可。

成功時と失敗時流れる音っていうならSEになると思いますが、Play中のBGMを流れながら（もしくは音量を小さくして）成功時・失敗時のSEを再生、再生終了後BGMの音量を戻す。というイメージを考えています。


# 異議なし

@xiii111から：
> * MenuSelectScene は現在時刻に合わせて背景を変えたりしたいので、時刻に合わせて BGM が変わっても良いかも。
> * StageSelectScene に関しては、木を完全にクリアした場合などには BGM をアレンジしたいです
> * GamePlayScene に関しては、一番難しいステージ（木のてっぺん？）などは BGM をアレンジしたいです

上記3点について僕は特に異議なし。@takasusukeも同意であれば仕様にします。


@takasusukeから：
> * GamePlaySceneチュートリアル中のBGM
> * GamePlayScene、Opening中のBGM(チュートリアル中と同じでも可。)Playing中とは別のにしたい。

特に異議なし。@xiii111 も同意であれば仕様にします。


# 決定事項
> * StartupScene と MenuSelectScene に関しては分けたいです、イメージだけで話すと StartupScene は歓迎、MenuSelectScene は日常、という雰囲気の BGM を流したいです。
> * StartSceneとMenuSelectSceneは分けたい

StartSceneとMenuSelectSceneは分けましょう。

**Comment by takasusuke** [comment]
>> StageSelectScene や GamePlayScene の BGM が季節ごとだと、季節が変わるまで BGM が変わることがないので、BGM が飽きられてしまいそう。木ごとに BGM を用意するのはどうでしょうか

> 確かに飽きられそうですが、木ごとにBGM用意するのはさすがにやりすぎだと思います。時間帯によって変えたり、別の方法でバリエションを増やせたら良いかなと思います。

季節の繋がりが同じ島、同じ色合いと視覚的なので、聴覚的にもつながりを感じさせるということで、季節ごとの曲でも良いと思いました。

>> GamePlayScene成功時のBGMいる？Play中のBGMそのままでも可。
GamePlayScene失敗時のBGMいる？Play中のBGMそのままでも可。

> 成功時と失敗時流れる音っていうならSEになると思いますが、Play中のBGMを流れながら（もしくは音量を小さくして）成功時・失敗時のSEを再生、再生終了後BGMの音量を戻す。というイメージを考えています。

良いと思います。

> MenuSelectScene は現在時刻に合わせて背景を変えたりしたいので、時刻に合わせて BGM が変わっても良いかも。
StageSelectScene に関しては、木を完全にクリアした場合などには BGM をアレンジしたいです
GamePlayScene に関しては、一番難しいステージ（木のてっぺん？）などは BGM をアレンジしたいです

良いと思います。

**Comment by xiii111** [comment]
> > 画面中心にいる季節に合わせて切り替えるのは、スクロール領域の狭さ的厳しいと思います（例えば、ガッとスクロールした場合に、いろんな季節を同時に跨いでしまいぐちゃぐちゃになりそう）。
> 
> これに関してはスクロール位置が一定時間動かない時に変えたりすれば技術的に解決できると思うので問題にはならないと思います。

なるほど。いずれにしても、 MenuSelectScene、RecordScene、SettingScene で同じ BGM にすると思うし、中心位置によって BGM を変える実装の優先順位は低めだと思ってます！

> > * MenuSelectScene の中でも、LevelSelectScene と RecordScene などで BGM は分けたいです
> > * MenuSelectScene(LevelSelect, Record, Setting)ではBGMを分け、、、、分け、、分けなくて良い派。Record→LevelSelectに行ったときにBGMが最初から再生されるよりは、通しで聞いてもらいたい気がする。
> 
> 僕もMenuSelectScene 中の LevelSelect/Record/Setting は変えない派です。理由は同 @takasusuke

変えない OK です

> > * StageSelectScene や GamePlayScene の BGM が季節ごとだと、季節が変わるまで BGM が変わることがないので、BGM が飽きられてしまいそう。木ごとに BGM を用意するのはどうでしょうか
> 
> 確かに飽きられそうですが、木ごとにBGM用意するのはさすがにやりすぎだと思います。時間帯によって変えたり、別の方法でバリエションを増やせたら良いかなと思います。

では、基本は季節ごとにしましょう〜

> @takasusukeから：
> 
> > * GamePlaySceneチュートリアル中のBGM
> > * GamePlayScene、Opening中のBGM(チュートリアル中と同じでも可。)Playing中とは別のにしたい。
> 
> 特に異議なし。@xiii111 も同意であれば仕様にします。

同意

**Comment by takesi0627** [comment]
## StartUpScene
* 歓迎する雰囲気のBGM

## MenuSelectScene
* LevelSelect/Record/Settingの画面切り替えで特にBGMは変わらない
* （要検討）地図のスクロール位置の季節に応じてBGMを変える
* （要検討）時間帯による変化

## StageSelectScene
* 季節毎にBGMを用意
* 木全クリアした状態でアレンジする

## GamePlayScene
* チュートリアル中/Opening中のBGM
* PlayingステートのBGM
* 難しいステージはアレンジする

**Comment by takesi0627** [comment]
@xiii111 @takasusuke 
コメントをまとめてみました。
最後に確認して問題なければ閉じたいと思います

**Comment by xiii111** [comment]
👍

**Comment by takasusuke** [comment]
👍

**Comment by takesi0627** [comment]
方針決まりましたのでクローズします
