### ISSUE TITLE
`LevelSelectScene` の背景の草案作成

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#809]
## 終了条件

- [ ] 草案資料を作る

## 考慮事項
- [ ] 道を考える（大陸間の道は別のデザインが良い気がする）
- [ ] 絵柄の詳細を決める
- [ ] 構図を決める
- [ ] ボタンとなる木以外の装飾も考える
- [ ] 海部分の印象も考慮する（今のShaderのままでもまあ良い）

背景資料
https://docs.google.com/presentation/d/15gjknD8VwkrRpeEpMUnzI0Ewbz8EWAtzvXifUZlU57k/edit#slide=id.g824d7aeac6_0_0

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
資料あれば貼っておいてください

**Comment by takasusuke** [comment]
https://docs.google.com/presentation/d/1oMGNRsnw73yHvwSDFmGHFwOhiZcRwMYLEZ1f3FRRQkM/edit#slide=id.p

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
タスク通話で説明します。
それまでにコメントあればお願いします。
特に先に見てなくても大丈夫です

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
草案を修正しました。(主に9~12p, 17~18p)
ざっと確認お願いします。
季節ごとの島のイメージは追加あればご自由にお願いします。

**Comment by takasusuke** [comment]
デザインissue
#1125 を作成しました
