### ISSUE TITLE
[設定画面] ボタン UI のデザイン作成

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#810]
### 完了条件
- [ ] 設定画面で利用する `その他` のためのボタン UI を確定する
- [ ] 設定画面で利用する `外部リンク` のためのボタン UI を確定する

### 備考
- `外部リンク` において、`Twitter へのリンク` では Twitter のアイコンが必要な可能性がある
- `Twitter へのリンク` でアイコンを用意するのであれば、もう一つのリンクである `アプリを評価する` でもアイコンをおきたい
- 上記の問題から、`その他` と `外部リンク` でボタン UI が異なる可能性がある
- ボタンを押した後の UI については対象外

#### シンプルな例
<img width="465" alt="スクリーンショット 2021-07-16 21 37 57" src="https://user-images.githubusercontent.com/26104258/125948983-a692722c-b396-44aa-8446-8583e3583a7b.png">

#### コルク背景を使った例
<img width="372" alt="スクリーンショット 2021-07-16 21 38 39" src="https://user-images.githubusercontent.com/26104258/125948991-127e4188-e385-4eac-a5fe-af995ec6a976.png">

**Comment by takasusuke** [comment]
#1163 の経緯を参照
