### ISSUE TITLE
[設定画面] スライダー UI のデザイン作成

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#811]
[スライド](https://docs.google.com/presentation/d/1iRaB3kg1c35dkxDuv8PbSd8xhXdNiBpfTS4wBonMGxc/edit#slide=id.gf083d22cc3_0_6)

### 完了条件
- [ ] 設定画面と一時停止画面で利用するスライダー UI を確定する

### 備考
- 利用するのは `BGM` と `SE` の項目
- デフォルト音量ボタンを置くかどうか
- 音量ミュートボタンを置くかどうか
- 音量を離散値にするかどうか
- 音量値を置くかどうか

#### デフォルト音量ボタン例
<img width="846" alt="スクリーンショット 2021-07-16 21 24 48" src="https://user-images.githubusercontent.com/26104258/125947152-433e7f98-0b58-4231-9117-b355b8763984.png">

#### 音量ミュートボタン例
<img width="728" alt="スクリーンショット 2021-07-16 21 24 59" src="https://user-images.githubusercontent.com/26104258/125947067-029531e6-943e-4a2d-b735-17d66345f863.png">

#### 離散値例
<img width="684" alt="スクリーンショット 2021-07-16 21 24 51" src="https://user-images.githubusercontent.com/26104258/125947126-3a622849-be2a-4cd0-b5f5-14d5a61f22e3.png">

#### 音量値例
<img width="789" alt="スクリーンショット 2021-07-16 21 24 55" src="https://user-images.githubusercontent.com/26104258/125947086-b287d18d-0215-4a8f-9c7e-9a8abb274650.png">

**Comment by xiii111** [comment]
- デフォルト音量ボタンを置くかどうか  → おかない
- 音量ミュートボタンを置くかどうか → おく
- 音量を離散値にするかどうか → 細かいことを考えたくない人とかを考えて、離散値を使う
- 音量値を置くかどうか → おかない

**Comment by xiii111** [comment]
@takasusuke @takesi0627 [スライド](https://docs.google.com/presentation/d/1iRaB3kg1c35dkxDuv8PbSd8xhXdNiBpfTS4wBonMGxc/edit#slide=id.gf083d22cc3_0_6) の議論を定例会でやりたいと思います。予め目を通していただけたら、スムーズに議論が進むと思います

**Comment by takasusuke** [comment]
- シンプル構成でわかりやすいと思った。
- アフォーダンスとしては、連続的な変更ができる感じがするから、操作した時に違和感があるかもしれない...(?)実際はそんなことないのだろうか...(?)

**Comment by xiii111** [comment]
@takasusuke @takesi0627 [スライド 8ページ目](https://docs.google.com/presentation/d/1iRaB3kg1c35dkxDuv8PbSd8xhXdNiBpfTS4wBonMGxc/edit#slide=id.gf21fbffcd0_0_19) において、以下の 4 つを修正しました。タスク通話で議論しますが、予め目を通していただけたら、スムーズに議論が進むと思います
- [x] フリー画像から取ってくる
- [x] 他の UI とあわせた Radius をかける
- [x] ミュート時の配色を決める
- [x] ミュートボタンを左に置くパターンを出す

**Comment by xiii111** [comment]
@takasusuke @takesi0627 [スライド 9 ページ目](https://docs.google.com/presentation/d/1iRaB3kg1c35dkxDuv8PbSd8xhXdNiBpfTS4wBonMGxc/edit#slide=id.gf553b10e3d_0_0) において、以下を修正しました。マイルストーン MTG で議論しますが、予め目を通していただけたら、スムーズに議論が進むと思います。昨日のタスク通話で、ミュートボタンを左側に置くパターンを提示しましたが、その際に強い主張を感じなかったので、破棄します。ミュートボタンは右側に置くものとします

- [x] ミュートボタンがボタンに見えるようにする

**Comment by xiii111** [comment]
@takasusuke #1163 にスライダー UI を適用する際に必要な全ての情報を転記したつもりです。漏れなどがあったら教えて下さい
