### ISSUE TITLE
[設定画面] 背景画像のデザイン作成

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#812]
### 完了条件
- [ ] 設定画面で利用する背景画像を確定する

### 備考
- 全く決まっていないが、既存の世界観と大きく崩れない方が良い
- 設定画面は UI 色が強いので、過度に世界観を出す必要はなく、無地系でも良いと思われる

### 参考画像

<img width="1639" alt="スクリーンショット 2021-07-16 21 44 06" src="https://user-images.githubusercontent.com/26104258/125949764-a186580b-6cc9-4ffd-a8d9-db46d43dffc3.png">

<img width="937" alt="スクリーンショット 2021-07-16 21 46 57" src="https://user-images.githubusercontent.com/26104258/125950066-a2253f87-b5bf-40e9-a631-89738cfa4718.png">

<img width="577" alt="スクリーンショット 2021-07-16 21 46 47" src="https://user-images.githubusercontent.com/26104258/125950077-92187cfb-fb2b-44a4-ae99-4139046b6ff5.png">

**Comment by takasusuke** [comment]
#1163 のissueで一緒にやります
