### ISSUE TITLE
`SnapScrollView` の `UI` 草案作成

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#825]
以下の画面にある `SnapScrollView` の `UI` 表現を決める
- [x] `StageSelectScene`
- [x] ~~(optional) `RecordScene`~~

### 意識すること
- 過度な UI 表現にして、世界観を崩さないようにする
- できるだけ広いスペースを確保するために、スクロールバーの廃止を検討する
- 離散的なページであることを伝える

**Comment by takasusuke** [comment]
アーチャー伝説
左右のステージが見えているので左右にスクロールできることがわかる。
全ステージは表示されていない。
アップデートで右にステージがどんどん増えていく。

![124A22BA-0803-47B8-A3EA-366924E6DC17](https://user-images.githubusercontent.com/26213141/118383254-2b3ff380-b637-11eb-8729-6f851f534e6e.png)

**Comment by takasusuke** [comment]
ジャンプ+
日から土でループ
矢印でも遷移できる

![CD0ACC1C-AA85-46A1-BECF-34342CD3EA1C](https://user-images.githubusercontent.com/26213141/118383336-c46f0a00-b637-11eb-98b8-8b1e5eb122bc.jpeg)

**Comment by xiii111** [comment]
@LITO-apps/engineer
https://lito-apps.slack.com/archives/CJ30Q29HQ/p1621672609001700
Slack でコメントお願いします！

**Comment by xiii111** [comment]
### 結論
`StageSelectScene` で `SnapScrollView` を利用しないようにする

### 今後の方針
1. `SnapScrollView` の存在がわからないような状態にする
2. 上記に際して、ひどい状況になるのでなんとかする（optional）

**Comment by xiii111** [comment]
↑ で必要なイシューを作成しました。各イシューにはどのようなことをやるのかの詳細まで記述してあります。

@takasusuke @takesi0627 各イシューの内容に問題がないかだけ後追いで確認お願いします。 #941 のみをマイルストーンに入れました

**Comment by xiii111** [comment]
やるべきことを全てやったので閉じます
