### ISSUE TITLE
フッター草案作成

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#827]
### 終了条件
MenuSelectのFooterボタンの草案作成

### 考慮事項
- ボタンが2個~N個になっても対応できるようにする
- LevelSelect, Settings, (Record), (称号)へのボタン

**Comment by takasusuke** [comment]
草案資料
https://docs.google.com/presentation/d/1FWevxAygtMwHSJOZhn_9KLg65Z9EnGqfPThhV_H_q9g/edit#slide=id.gaaa75cf2d6_0_0

**Comment by takasusuke** [comment]
@xiii111 @takesi0627 
https://lito-apps.slack.com/archives/CJ30Q29HQ/p1621099985000400
Slackにてコメントお願いいたします

**Comment by xiii111** [comment]
@takasusuke コメントしました！

**Comment by xiii111** [comment]
@takasusuke 現在作業中であれば、InProgress に戻してもらえますか？？

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
https://docs.google.com/presentation/d/1FWevxAygtMwHSJOZhn_9KLg65Z9EnGqfPThhV_H_q9g/edit#slide=id.gdb6bd35d10_0_4
新案追加しました

**Comment by takasusuke** [comment]
https://drive.google.com/drive/u/1/folders/1SxSWneIXmHHdpHeRTp5mevLy8ZPW_5Nm
に画像を追加しました。

背景、アイコン、文字の配置・大きさ、色は適用した時に微調整します
選択時はアイコンに色がつき、非選択時は茶色。

デザイン依頼は一旦、仮画像で適用してみてから考えても良いかなと思っています。
