### ISSUE TITLE
[#985] 成功ポップアップ

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#831]
- [ ] 草案作成
- [ ] 適用

**Comment by xiii111** [comment]
#915 で議論された話だが、成功ポップアップに成功記録の保存に失敗したことを伝えるテキスト、そして通信をリトライするボタンをおいて、 #915 で実装したポップアップを廃止することを検討する

**Comment by xiii111** [comment]
#985 でやってる
