### ISSUE TITLE
ゲーム成功時のアニメーション

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#836]
- [ ] 演出
- [ ] 実装

**Comment by xiii111** [comment]
@takasusuke #965 を持って閉じますか？

**Comment by takasusuke** [comment]
あーどうしようかなあ。。。
閉じるかーーー。
参照させとくわーーー。

**Comment by xiii111** [comment]
@takasusuke 

> リリースの及第点くらい。。。を目指しています。

とあるので閉じて良いんじゃないすかね
