### ISSUE TITLE
[広告] 実装調査

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#838]
- [ ] 各広告サービスの調査、まとめ、選出。

* UnityAds
* AdMob

必要なアカウント
料金体系
実装方法

**Comment by takesi0627** [comment]
# Unity Ads

### 概要
* Unityが出した広告サービス
* 広告をクリックしてアプリインストールしたら収入発生

* メリット
    * 実装が簡単 (１０分で完結だそうです）
    * Unityとの相性がいい

* デメリット
    * バナー広告は実装できない。動画のみ
    * 広告のアプリをインストールしないと収入発生しないのでハードルが高い。（その分単価も高いと言われているが、ドキュメントまだ確認していないので確信がない）
 

### 参考ページ
* UnityAds使い方：https://freesworder.net/unity-ads/
* UnityAds公式：https://unityads.jp

# AdMob
### 概要
Google のアプリ広告サービス
* メリット
    * 色々な機能がある（広告出す方法）
    * 比較的に収益が上がりやすいと言われている
* デメリット
    * SDKの導入からやるので、UnityAdsよりやや時間かかりそうな印象。（でもみたかぎり、[公式のドキュメント](https://developers.google.com/admob/unity/quick-start)もサンプルもかなり完備しているのでハードルはそこまで高くはなさそう）

**Comment by takesi0627** [comment]
方針としては AdMob で実装したいと思っています。

理由は以下です
* UnityAds はバナー広告に対応していない。
* UnityAds の収益はイマイチといくつの記事で見ました。
* AdMobは前作も使っているのでアカウント周りはおそらく継続で使えるはず


疑問点などあれば、コメントよろしくお願いします。

**Comment by takesi0627** [comment]
@xiii111 @takasusuke

**Comment by takasusuke** [comment]
ビデオ広告 : UnityAds
ビデオ以外の広告 : AdMob
と理解しました。

バナー広告やインタースティシャル広告がメインになると思うので、自分もAdMobが良いと思いました。
UniyAdsと両方実装することもできるみたいなので、動画見る時間に匹敵する価値のあるアイテムとか実装するときはUnityAdsでも良いかもね。（失敗時から再開機能とか）

**Comment by xiii111** [comment]
AdMob が良いと思いました！両方やるとかでも良いけど、管理が面倒なので 1 つのサービスだけで良いかなぁとは思っています

**Comment by takesi0627** [comment]
両方やるのは確かにありですが、UnityAdsの収益あんまり良くないし、動画広告はAdMobでも実装できるので全部AdMobにしたほうがいいかなと思います

**Comment by takesi0627** [comment]
では、AdMobs に決まります。
