### ISSUE TITLE
`StartupScene` の草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#859]
### 完了条件
- [ ] `StartupScene` の草案を複数作成する
- [ ] 上記の草案を元に議論し、`StartupScene` の草案を確定する

### 備考
- `MenuSelectScene` に遷移できる導線を作ること
- `MenuSelectScene` への導線は、リソースロード中は機能しないので、それを考慮すること
- ロード中はロードであることがわかること（背景を動かすなど）
- できるだけ `Treevel` というタイトルに沿った内容を見せること
- `Treevel` というタイトルは置くこと
- 雰囲気は静か、綺麗、しんみり

**Comment by takasusuke** [comment]
検索ワード　[ゲーム　自然　トレイラー]

旅感
![image](https://user-images.githubusercontent.com/26213141/121039566-27ddf900-c7ec-11eb-83f2-f181c5c7cd85.png)

朝焼け（コストも少なそうで良さそう）
![image](https://user-images.githubusercontent.com/26213141/121039665-404e1380-c7ec-11eb-8d88-6dc1fd31c826.png)

日の出
![image](https://user-images.githubusercontent.com/26213141/121039884-6ecbee80-c7ec-11eb-92f7-25f780bd77ba.png)

しんみりした感じに朝焼けのイメージは合うと思う
空が大きく空いているなら、そこに"Treevel"が浮き上がってくる感じとかもできそう
遷移ボタンは、枠のあるボタンボタンしてるものじゃなくて、下図のように"Tap to Start"みたいな文言が
現れると世界観を崩さなそう。
（ボタンの当たり判定自体は画面全体でも可?）

![image](https://user-images.githubusercontent.com/26213141/121040334-c8341d80-c7ec-11eb-8b57-30cc0fd4d479.png)

**Comment by takesi0627** [comment]
![url](https://user-images.githubusercontent.com/17778395/121218923-2aa91e80-c8be-11eb-8013-3b6ad4f9044b.jpg)
![url](https://user-images.githubusercontent.com/17778395/121218942-2ed53c00-c8be-11eb-94af-ac35e752c11d.png)
![url](https://user-images.githubusercontent.com/17778395/121218964-33015980-c8be-11eb-887e-6aa879e3becf.png)

（ゲーム　タイトル画面で検索してイメージにあったものを選んだ）

**Comment by xiii111** [comment]
https://docs.google.com/presentation/d/1Dsl7WDAXFESsOduSDSWbnJAcxO2s60_TsI7GlIyW2FM/edit#slide=id.gaaa75cf2d6_0_0

**Comment by xiii111** [comment]
### 6/20 (日) の定例会での議論まとめ
#### 背景
- 廃れてる、暗い、綺麗なイメージ
- 景色感、旅感、奥行きや広がりを演出する
- リアルなものをやや簡素化するような絵柄
- 静けさも表現したいので、暗さ多めの朝焼けって感じ
- 手前に一本の咲いている木があり、奥に廃れた世界が続いている ... という感じ
- 現在確定している画像などとの調和を検討する

#### タイトル
- 置きたい
- 木や自然、旅を連想させる
- ロゴっぽい感じにする
- 色は背景次第だが、あまりに派手にしない（モノトーンな色）
- 位置は上目で良いが、高すぎない方が良い

#### `Tap to Start`
- なるべく下寄り
- アニメーションや縁をつける程度のことはするが、背景やタイトルを阻害しない程度にする

**Comment by xiii111** [comment]
@takasusuke 以下のスライドの内容で一旦お渡しします。定例会の認識が正しければ、微修正後 `@itochico` とお話ししていただくということだったと思います。何か間違っていれば、補足お願いします🙏

https://docs.google.com/presentation/d/1Dsl7WDAXFESsOduSDSWbnJAcxO2s60_TsI7GlIyW2FM/edit#slide=id.ge143dc45a5_0_17

**Comment by takasusuke** [comment]
@xiii111 
スライドに自分なりに画像集めたりして、補足してみました。
絵柄の部分(④、⑤）は言葉にするの難しかったんでちゃんと説明できていませんが、そこは実際に話してみて補います。
構図(①)は良いのを見つけられたと思う。
畏怖もありつつ、明るい感じ(②)の手前と、畏怖もありつつ、暗い感じ(③)の奥の説明はいかがでしょうか。

作ってくれたまとめスライドと合わせてお話してみようと思っています。

**Comment by xiii111** [comment]
@takasusuke 明日確認します🙏

**Comment by xiii111** [comment]
@takasusuke 

> スライドに自分なりに画像集めたりして、補足してみました。

見ました🙏 自分が一度も見ていない画像がいくつかあったので、まだググリ力が足らないな ... と反省

> 絵柄の部分(④、⑤）は言葉にするの難しかったんでちゃんと説明できていませんが、そこは実際に話してみて補います。

確かに難しいですね ... でも、僕がイメージしていた印象と一緒です。なので、僕が書いたシナリオにある画像も参考にしてもらえたら助かります🙏

> 構図(①)は良いのを見つけられたと思う。

① は素晴らしいですね。まさにこのイメージ。若干の差異を言うとすれば、もう少し手前と奥に隔たりがあると良いと思いました！（あくまでもイメージです）

> 畏怖もありつつ、明るい感じ(②)の手前と、畏怖もありつつ、暗い感じ(③)の奥の説明はいかがでしょうか。

② が希望がある部分のことを説明しているのであれば、`畏怖` がある必要はないのかなと思ってしまいました。暗い感じのイメージは ③ の画像、素晴らしいと思います。こちらに関しても、僕が出したシナリオの画像（枯れているやつとか）も参考画像として出してもらえたら伝わりやすいと思いました！

全体として、同じイメージです！ありがとうございます！

**Comment by takasusuke** [comment]
依頼しました > #1009
