### ISSUE TITLE
称号画面のデータを準備する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#860]
## 完了条件
- [x] イシューを分割する
  - `PlayFab` の称号機能を調査する
  - 今後検討されそうな称号を洗い出す
  - 上記の称号に必要な記録データを洗い出す
  - 必要な記録データを計測する

## 備考
- 現状はローカルが前提なので、ローカルにもデータを持っている必要がある（現状の記録データと同様）

**Comment by xiii111** [comment]
📝 PlayFab にランキング機能のサポートはあるが、称号（実績）機能のサポートはない。なので、ローカルで完結させるのが良さそう。将来的にランキング機能を実装する際に、ローカルのデータをリモートに移行する必要はあるが（現状は、ローカルさえ更新されていれば良いという思想なので）、この時に称号機能の対象として見るデータをリモートにするかローカルにするかは悩ましい 🤔

**Comment by xiii111** [comment]
📝 現状とっているデータ

## UserRecord
- 総起動日数（`StartupDays`）
- 初回起動日（`FirstStartupDate`）
- 最終起動日（`LastStartupDate`）

## StageRecord
- 挑戦回数（`ChallengeNum`）
- 成功回数（`SuccessNum`）
- 失敗回数（`FailureNum`）
- 失敗原因（`FailureReasonNum`）
- フリック回数（`FlickNum`）

**Comment by xiii111** [comment]
@takesi0627 @takasusuke 以下のイシューを作りました！どちらも β 版でやるイシューだと思うので、`β 版++` に入れておきました

**Comment by takesi0627** [comment]
確認しました。特に問題ないと思います

**Comment by takasusuke** [comment]
確認しました○

**Comment by xiii111** [comment]
ありがとうございます！
