### ISSUE TITLE
Addressable Groups 設定が見れない

### ISSUE THREAD

**Issue by takesi0627** [LITO-apps/Treevel-client#870]
![image](https://user-images.githubusercontent.com/17778395/114580190-99e90480-9cb9-11eb-869f-8f9c73233e7c.png)

**Comment by takasusuke** [comment]
自分は見れます。

Close Tabして、
Window > AssetManagement > Addressables > Groups
からも見れない？

**Comment by takesi0627** [comment]
> 自分は見れます。
> 
> Close Tabして、
> Window > AssetManagement > Addressables > Groups
> からも見れない？

本当だ、見れた、ありがとう。
ということでクローズします
