### ISSUE TITLE
様々なタイルを追加する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#88]
- タイルの縦横のサイズがステージによって異なる
- タイルの全体像が単純な長方形ではない

**Comment by takasusuke** [comment]
アイデア
- 滑るタイル(3列の中央に配置して、左から右にパネルを移動させた時、このタイルの上では止まらず勝手に右端まで移動してしまう。ただし、右端に何かがあるのならこのタイルの上で止まる)
- ワープタイル(一方向)
- 燃えるタイル(一定時間毎に、タイルが燃えてその上にパネルが存在していた場合失敗扱い。また燃えている間はそのタイル上に移動させることができない)
- ワープタイル(タイル上に置いただけではワープせず、タイル上のパネルをタップするとワープする)
- 脆いタイル(一定回数パネルの移動を行うと、タイルが壊れてその上にパネルを置けなくなる、一定時間後に復活する)
- 矢印タイル(左から右、上から下など、特定の方向にのみ移動可能なタイル)
- 薬品補充タイル(例えば、特定のボトルが時間経過に応じて薬品量が減少する。そのようなボトルは薬品補充タイル上に移動させて薬品を補充する。薬品が減少した状態のボトルではクリア扱いにならない)

**Comment by xiii111** [comment]
要らない
