### ISSUE TITLE
様々なボトルを追加する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#89]
- 異なる形のパネル
- 数字以外を表示したパネル
- 複数回当たり判定を受けても大丈夫なパネル
- 当たり判定を受けることで、通常のパネルに変化するパネル
- 複数個組み合わせて１つのパネルになるパネル(8の鍵パネルと8の錠前パネルみたいな)
- タップすることで消すことができるパネル(一定の時間間隔で湧く)

**Comment by takasusuke** [comment]
フリックすると、その方向の行けるところまで滑ってしまうパネル

**Comment by xiii111** [comment]
要らない
