### ISSUE TITLE
`Spiderweb`中にどんなことがあっても `Bottle` が動かないことを確認する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#894]
### 完了条件
- [ ] タイトルの現象がどうなるかを確認する
- [ ] https://docs.google.com/spreadsheets/d/1LfxHp_nnuXTH6CqkNJYT9e_vNYCDSmKCyxVwXpereg4/edit#gid=171819460&range=R14 と https://docs.google.com/spreadsheets/d/1LfxHp_nnuXTH6CqkNJYT9e_vNYCDSmKCyxVwXpereg4/edit#gid=171819460&range=R17 を更新する

### 備考
- どんなこと = `フリック`、`GoastAttribute`、`GustWind`

**Comment by xiii111** [comment]
@takasusuke @takesi0627 報告です。閉じます

以下、正常に動作しました
- [x] `Spriderweb` に拘束されている間、フリックで移動できないこと

以下、問題を確認しました（備考に解決方針を書きました）
- `Spriderweb` に拘束されている間、`GoastAttribute` で移動できてしまうこと → #989
- `Spriderweb` に拘束されている間、`GustWind` で移動できてしまうこと → #988 

以下、このイシューとは無関係のバグを発見しました
- #986 
- #987
