### ISSUE TITLE
ホールド中の`Bottle`が移動した時に、ホールドの効果が消えることを確認する

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#896]
### 完了条件
- [ ] タイトルの現象がどうなるかを確認する

### 備考
- 確認は `GustWind` でやると良い
- ホールドの効果 = `GoastAttribute`、`DarkAttribute`

**Comment by xiii111** [comment]
@takasusuke @takesi0627 報告です。閉じます

以下、正常に動作しました
- [x] `GoastAttribute` をホールドした状態で `GustWind` で移動すると、正常にホールド効果が消える

以下正常動作のキャプチャです（バグ #986 も見えてるなぁ）


https://user-images.githubusercontent.com/26104258/122773898-b5891080-d2e3-11eb-820a-3ce0fbb12342.mov



以下、問題を確認しました
- `DarkAttribute` をホールドした状態で `GustWind` で移動すると、明るいままになること → #990
