### ISSUE TITLE
オフライン（通信不良）でのエラーハンドリングをする

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#900]
＊#927 を実施した後にやる

## 完了条件
- [x] オフラインで操作した際に、問題になる箇所を洗い出す
- [x] 問題に対して、どのような対応をするか決める
- [x] 対応を適用する

## 備考
- まずは、通信しているコードを洗い出す。そして、そのコードに対して、失敗した場合にはどうなるかを考慮する
- 失敗原因のうち、通信が悪い場合と普通に失敗した場合に分岐させる
- 通信が悪い場合にはできるだけ穏便に復帰する
- 失敗した場合には失敗した旨を伝える
- 通信が悪い場合の警告は何度も出すとウザいので、考える必要がある
- 根幹となるログイン自体に失敗した場合には、どうするかも考える必要がある。StartupScene で一回しか呼ばれないログイン処理をミスると、以降の全ての PlayFab への通信がミスることになる
- 記録に失敗する場合はローカルに蓄えておいて、通信ができたタイミングで一気に送ることも検討できるが、そこまで大切な記録ではないので、難しい
-

**Comment by xiii111** [comment]
#919 の内容もやる

**Comment by xiii111** [comment]
対応しなきゃいけない箇所
- ログイン（ `NetworkService.Execute(new LoginRequest())` ）
- ステージ記録情報の初期読み込み（ `StageRecordService.PreloadAllStageRecordsAsync()` ）
- ユーザ情報の初期読み込み（ `UserRecordService.PreloadUserRecordAsync()` ）
- ステージリセットボタンにおける、ステージ記録情報のリセット（ `StageRecordService.ResetAsync()` ）
- ステージリセットボタンにおける、ユーザ情報のリセット処理（ `UserRecordService.ResetAsync()` ）
- アプリがフォアグラウンドに移動した際の、起動日数の更新処理（ `UserRecordService.UpdateStartupDaysAsync()` ）
- ステージの成功（ `StageRecordService.SaveAsync()` ）
- ステージの成功に失敗（ `StageRecordService.SaveAsync()` ）
- ステージの失敗（ `StageRecordService.SaveAsync()` ）
- ステージのリタイア（ `StageRecordService.SaveAsync()` ）

**Comment by xiii111** [comment]
## 現状
当初、ランキングなどをリリースに含める予定だったことがあり、リモート中心の設計になっている

リモート中心の設計とは、リモートから取得したデータを取ってきて、ローカルにも反映したり、リモートに書き込んだデータを、ローカルにも反映したりなどがある。この設計にすると、必然的にリモートとのやりとりにおけるエラーのハンドリングが必要になる

例：


## 問題点
リモートとのやりとりにおけるエラーのハンドリングには、ユーザへのポップアップの表示などが含まれる。しかしながら、現段階では、ユーザにリモートを必要とする機能（ランキング、全プレイヤーの統計など）を提供する予定はないので、リモートとのやりとりに失敗した際に、ユーザにポップアップなどを表示するのは適切ではない

## やること
ローカル中心の設計にすること。これは、ローカルが常に最新であるという前提で、アプリ起動時にローカルの内容をリモートへ反映させたり、ローカルを変更時にリモートにも反映させたりする設計である。これにすることで、リモートへの反映が失敗したとしても、ハンドリングする必要はなくなる。スタンスとしては、ローカルで全てが完結するが、今後のためにリモートにもローカルの内容を反映させておく、といった具合である。

**Comment by xiii111** [comment]
@takasusuke @takesi0627 今後の方針を書きました！これに沿って進めようと思います！レビューがあればお願いします！

**Comment by xiii111** [comment]
上記方針で作業を始めます

**Comment by takesi0627** [comment]
目を通しました、現状その方針で良いかと思います
