### ISSUE TITLE
チュートリアルが表示される場合、ゲームが先に進められない

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#908]
### 終了条件
- チュートリアル画面にもmask用のpanelを用意する or GamePlaySceneにあらかじめmaskを用意しておいて、Play直前でmaskを外す
- Opening画面に入ってからOpeningのmaskのenabledをtrueにする

**Comment by takasusuke** [comment]
https://user-images.githubusercontent.com/26213141/116799254-b2b73e00-ab32-11eb-988d-2e95c5424d13.mov

**Comment by takasusuke** [comment]
Game前共通maskをつける
