### ISSUE TITLE
[#600] 利用規約、プライバシーポリシー調査

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#938]
#600 が親タスク

### 完了条件
- [x] 利用規約、プライバシーポリシー、同意文言の表示文言を用意する
- [x] 利用規約の表示タイミング、表示箇所を決める

### 考慮事項
- 他アプリの表記内容
- 他アプリの表記タイミング調査
- 他アプリの利用規約の表示言語は何か、また、その言語はどのタイミングで選択しているか
- 他アプリでユーザの意志で利用規約をどこから見れるか
- 他アプリでユーザの意志で、分析業務への同意/非同意をどこから変更できるか

### メモ
他社利用規約の大項目を比較検討して、必要な大項目を考える。
その後、たたき台を作成する。

**Comment by takasusuke** [comment]
### 利用規約の表示の是非
- 大手はもちろん利用規約を表示している（アプリ内直接やWebサイトへのリンクなど）
- 個人制作などのアプリでは結構、利用規約を表示していないアプリもある
- 利用規約は、保険みたいなものなので、正しく作ることができるなら作成したほうが良い（[参考URL](https://netkiyaku.com/%E5%88%A9%E7%94%A8%E8%A6%8F%E7%B4%84%E6%9B%B8%E3%81%8D%E6%96%B9%E8%AC%9B%E5%BA%A7/%E5%88%A9%E7%94%A8%E8%A6%8F%E7%B4%84%E3%81%AE%E5%BF%85%E8%A6%81%E6%80%A7%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6/)）
↓
表示する

**Comment by takasusuke** [comment]
### Privacy Policyの表示の是非
当アプリでユーザ個人を識別できる情報として該当しそうな情報は端末ID（引き継ぎ時に利用）であるが、こちらは現在の個人情報保護法では個人情報には該当しない。（単体では個人を特定できるとは考えられない、IPアドレスやCookieなども同様）
個人関連情報と呼ばれる。

個人情報をアプリ内で取得していないので、個人情報の取り扱いについて記すPrivacy Policyは不要と判断。

**Comment by takasusuke** [comment]
### 利用規約の表示箇所
多くのアプリでは、設定やメニュー画面と呼ばれるページに利用規約が記載されている。
なめこDXではアプリの開始前にポップアップが表示され、同意しないとアプリを利用できなかった。
しかし、同意を強制しないアプリの利用規約内の文章には、「利用規約に同意しない場合、アプリをアンインストールしてください。サービスの利用がすなわち利用規約の同意。」といった文言を含めることで、
ユーザの心理的障壁を高めるようなポップアップでの同意を行っていないと判断。

結論：当アプリでもその他画面での利用規約の表示で十分と判断。

**Comment by takasusuke** [comment]
### 利用規約の項目名および目的
- 定義
特別な呼び名のつく単語があればここで定義

- 規約への同意、利用規約について、本コンテンツの利用、利用条件について
どのタイミングでユーザが利用規約に同意したことになるか。大体はアプリをインストールした時

- 規約の変更と免責、規約の効力、規約の変更について
規約の変更はどのタイミングで行われるか、事前通知はあるかなど

- 個人情報等の取り扱い
個人情報取らないからなくて良さそう。

- 著作権などの権利の帰属、知的財産権
アプリ内のコンテンツ等の権利は誰にあるか

- サービスの提供、サービスの中断、サービスの終了
どういう状況でサービスが中断されることがあるか、終了することがあるか
サービスの内容の変更が行われるか

- 有償サービス、料金および費用
課金コンテンツがあるならそれについての説明など。未成年に向けた課金額の制限なども記す

- 広告
広告を載せることができるみたいなの。要調査。

- 禁止事項、不正行為の禁止、違反行為
ユーザが行ってはいけないこと

- 利用停止
違反者に対する措置の内容など

- 無保証、本コンテンツの運営
災害などの状況でサービスを提供できない可能性など

- 当社の免責、免責、免責事項
責任を取らなくて良い場合の列挙

- 退会、退会について、本規約の有効性、分離可能性
ユーザに対する利用規約が無効になるタイミングの説明。当社がユーザを退会させる、みたいな内容もあった気がするので要調査。

- 損害賠償
よくわかっていない。要調査。

- 権利義務等の譲渡禁止、権利譲渡の禁止
ユーザデータを譲渡することの禁止（禁止事項とは違うのか？）

- 準拠法および裁判管轄
基本、どこの国の法律に従うか。裁判するときはどこで行うか。日本、東京裁判所にしておけば良さそう。

## そのほか
- 未成年者の場合は、親に見てもらうこと、みたいな文言
- 当社が第三者に情報提供する場合の内容など

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
https://docs.google.com/document/d/1dz5vrZu24DmCDhF59RxkuXxt5aGlVpK9kjOchbkTRYI/edit
利用規約の初版を作成しました。
このissueコメントの上から順に見ていって、その後に、↑のGoogleドキュメントのTreevel利用規約の初版を見ると良いです。

レビュー観点
- 利用規約の誤字・脱字がないか
- 利用規約に表記揺れがないか
- 利用規約のナンバリングおよびその参照は正しいか
- アプリ内での利用規約の表示箇所についての意見
- 利用規約に個人情報、課金まわり、端末引き継ぎ周りの項目を入れないことに関する意見
- 様々なケースが網羅されているか考える（これは、適宜、利用規約を読み合わせしながらで）
- （余力があれば他サービスの利用規約のリンクをGoogleドキュメントに貼っているので比較）

**Comment by xiii111** [comment]
ごめんなさい、レビューは恐らく木曜日になります

**Comment by takesi0627** [comment]
利用規約についてはOKです。
自分が想像できる以上網羅されていると考えています

ただし一点質問ですが、
プライバシーポリシー現段階は要らないとして、
もしいつかApple IDやGoogleアカウントと連携の引き継ぎ機能を実装したら、
プライバシーポリシーは必要になったりしますか？

利用規約で審査落とされることってあるんですかね？
利用規約自体制定されていないアプリもあるって話あったしストア側は多分そこ見てないじゃないでしょうか
そもそも利用規約は自己責任みたいなところあると思います。
要は翻訳まではやらなくても良いんじゃないという意見です。

**Comment by takasusuke** [comment]
> もしいつかApple IDやGoogleアカウントと連携の引き継ぎ機能を実装したら、
> プライバシーポリシーは必要になったりしますか？

やろうと思えばGoogleアカウントに紐づいた個人情報をAPIで取得できると思うので、
「必要以上の個人情報を取得しない」といったプライバシーポリシーが必要になると考えます。

> 利用規約で審査落とされることってあるんですかね？
> 利用規約自体制定されていないアプリもあるって話あったしストア側は多分そこ見てないじゃないでしょうか
> そもそも利用規約は自己責任みたいなところあると思います。
> 要は翻訳まではやらなくても良いんじゃないという意見です。

「英語対応したアプリの審査で、英訳が１箇所できていないだけで審査に落ちた」、みたいな話を聞いたことがあるので、利用規約の有無ではなく、英語版なのに日本語の利用規約しか用意できていないことで審査に落ちたらどうしようか、、、という意味でした！

**Comment by xiii111** [comment]
📝 利用規約の校正を行う

**Comment by xiii111** [comment]
@takasusuke GoogleDocs にコメントをさせていただきました。とてもとても大変さが伝わりました。ありがとうございます。また修正が必要であれば、修正お願いします

**Comment by takasusuke** [comment]
- 個人を特定できる情報は取りません。
- 運営に関してアクセスログ、ユーザIDは取ります。
- これらは原則、開示しません。
みたいなの書いた方が良い気がしてきた。。。（なんか不安になってきた）

**Comment by takasusuke** [comment]
@xiii111 
修正できました！再度ヨロです。
法律で使われる独特な表現が結構あるみたいで面白かった。

**Comment by xiii111** [comment]
@takasusuke ほとんどを納得して解決にしました！2 点だけ残っているので返信などの対応お願いします！

**Comment by takasusuke** [comment]
@xiii111 対応いたしました

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
第９条　運営
の項目を追加しました。見てみてください。
載せるかどうかご意見ください。

**Comment by xiii111** [comment]
> @xiii111 対応いたしました

LGTM です

**Comment by xiii111** [comment]
> @LITO-apps/engineer
> 第９条　運営
> の項目を追加しました。見てみてください。
> 載せるかどうかご意見ください。

読みました。んーーここまで丁寧であるべきなのか、というのはありますが、これがあると私は困る！ということもないので、お任せします

**Comment by takasusuke** [comment]
とりあえず残しておきます。
消すことは後からいくらでも出来るんで、リリース前にもう１回見直すくらいの気持ちでいましょう。
