### ISSUE TITLE
`Xcode` のデバッグログで `Unity` のスタックトレースが見れない

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#952]
<img width="1010" alt="スクリーンショット 2021-06-01 8 06 39" src="https://user-images.githubusercontent.com/26104258/120247968-4f930580-c2b0-11eb-8a7f-f0cc97bfc26a.png">

**Comment by xiii111** [comment]
📝 実機のみで発生。`Simulator` では問題ない

**Comment by xiii111** [comment]
`Simulator` では問題ないし、致命的ではないので `ストック` に移動する

**Comment by takasusuke** [comment]
解決されました
