### ISSUE TITLE
実機で `StartupScene` 遷移時にエラーが出る

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#953]
`StartupScene` 遷移時に以下のようなエラーが出る

`KeyNotFoundException: The given key was not present in the dictionary.`

```
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00000] in <00000000000000000000000000000000>:0 
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelTreeController.UpdateState () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00000] in <00000000000000000000000000000000>:0 
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelSelectDirector.OnEnable () [0x00000] in <00000000000000000000000000000000>:0 
```

### 完了条件
- [ ] 上記バグのログが `Xcode` のログから消える

**Comment by xiii111** [comment]
📝 ログを見る感じ `LevelSelectDirector.OnEnable()` で 1 回、`LevelTreeController.Awake()` で 12 回起きている

**Comment by xiii111** [comment]
両方に共通しているコード片は以下

```
GameDataManager.GetTreeData(treeId).GetClearTreeHandler();
```

**Comment by xiii111** [comment]
📝 `GetTreeData()` が以下のようなコードになっていて、この辞書型でエラーが起きているのがほぼ確定的

```
public static TreeData GetTreeData(ETreeId treeId)
{
    return _treeDataMap[treeId];
}
```

**Comment by xiii111** [comment]
📝 実機でしか起きないため、これも `Addressable` の可能性が高そう

**Comment by xiii111** [comment]
📝 `Addressable` で正常に取れていないせいで `_treeDataMap` が欠損していると思われる

```csharp
public static async UniTask InitializeAsync()
{
    if (_initialized) return;

    // Stageラベルがついてる全てのアセットのアドレスを取得
    var locations = await Addressables.LoadResourceLocationsAsync("Stage").ToUniTask();

    var stageDataList =
        await UniTask.WhenAll(locations.Select(loc => Addressables.LoadAssetAsync<StageData>(loc).ToUniTask()));
    foreach (var stage in stageDataList) {
        _stageDataMap.Add(StageData.EncodeStageIdKey(stage.TreeId, stage.StageNumber), stage);
    }

    // Treeラベルがついてる全てのアセットのアドレスを取得
    locations = await Addressables.LoadResourceLocationsAsync("Tree").ToUniTask();

    var treeDataList =
        await UniTask.WhenAll(locations.Select(loc => Addressables.LoadAssetAsync<TreeData>(loc).ToUniTask()));
    foreach (var tree in treeDataList) {
        tree.stages = _stageDataMap.Values.Where(stage => stage.TreeId == tree.id).ToList();
        _treeDataMap.Add(tree.id, tree);
    }

    _initialized = true;
}
```

**Comment by xiii111** [comment]
📝 `Addressable` のお勉強に移行

**Comment by takesi0627** [comment]
stageDataは取れてる？

**Comment by xiii111** [comment]
@takesi0627 `Addressables.LoadAssetAsync<StageData>(loc)` この部分のことだよね？ちょっとデバッグが `Xcode` 向けにビルドし直す以外の方法がすぐに分からなくてその辺が明らかになっていない

**Comment by takesi0627** [comment]
これチェック入れると確かbreak point張れるようになるので試してみると良いかも（昔Visual Studio使ってった時にやったことあるが、Riderのやり方わからない）
![image](https://user-images.githubusercontent.com/17778395/120895124-8b362280-c656-11eb-9e9c-2be06362f390.png)

**Comment by takesi0627** [comment]
https://pleiades.io/help/rider/Debugging_Unity_Applications.html

**Comment by xiii111** [comment]
@takesi0627 これでは Xcode で実機向けビルドした際の処理を止めることはできないですよね？今回の現象は実機でしか起きないので、Xcode でビルド中の実行についてブレークポイントで止めたいのです

**Comment by xiii111** [comment]
あ、Build And Run ならできるのかもしれない。調べてみます

**Comment by xiii111** [comment]
https://github.com/LITO-apps/Treevel-client/blob/c82fdb6c8f2c55e40a22700d96228cf155c373c6/Assets/Project/Scripts/Common/Managers/GameDataManager.cs#L26-L27

→ 120 取得できている

https://github.com/LITO-apps/Treevel-client/blob/c82fdb6c8f2c55e40a22700d96228cf155c373c6/Assets/Project/Scripts/Common/Managers/GameDataManager.cs#L35-L36

→ 0 なのでここが問題

**Comment by takesi0627** [comment]
> あ、Build And Run ならできるのかもしれない。調べてみます

いけた？
いけたらちょっとやり方伝授してほしいー

**Comment by xiii111** [comment]
いけてない笑

**Comment by xiii111** [comment]
> 📝 ログを見る感じ `LevelTreeController.UpdateState()` で 1 回、`TreeControllerBase.Awake` で 12 回起きている

両方とも消すことに成功。これらを消したら、新たなエラーに遭遇。原因は

https://github.com/LITO-apps/Treevel-client/blob/c82fdb6c8f2c55e40a22700d96228cf155c373c6/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L51

の `clearHandler` が `Null` であることによる `NullReferenceException`
