### ISSUE TITLE
[#846] SolarBeamGimmickの草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#966]
### 終了条件

- [ ] 草案作成

### 考慮事項
- SolarBeamは（半透明、細くする、隙間がある）など、後ろのBottleやTileもそこそこ見える感じ
- 警告の役割の何かはある(、発射方向がわかる)
- N回かBeamを出したのち、警告のオブジェクトが消える
- SolarBeamとその他のギミックとの描画の前後関係は？→出た順
- (ビームの後ろのオブジェクトを黒くするなどshaderでできたらいいな)
 ### メモ
- ポケモンの金銀のソーラービーム

**Comment by xiii111** [comment]
@takasusuke 

### ポケモン金銀のソーラービーム
- https://youtu.be/0Xmw6UQ5xJE?t=268

### その他イメージにあった画像群

![nc175673](https://user-images.githubusercontent.com/26104258/121016354-00306600-c7d7-11eb-9e98-a295b2073971.jpeg)

![23ee24e1decaed2d8ceb8dcba1ed9185](https://user-images.githubusercontent.com/26104258/121016364-03c3ed00-c7d7-11eb-8149-8aca70e5de97.png)

![Eegl8o0VAAwKFjO](https://user-images.githubusercontent.com/26104258/121016377-06bedd80-c7d7-11eb-8aad-125239868bc2.png)

**Comment by takesi0627** [comment]
![image](https://user-images.githubusercontent.com/17778395/121220841-f5053500-c8bf-11eb-9422-4af5d10cbfd2.png)


![image](https://user-images.githubusercontent.com/17778395/121221722-cb98d900-c8c0-11eb-88cd-6c938dacc05c.png)

**Comment by takasusuke** [comment]
https://docs.google.com/presentation/d/1AiZrEcjIDZwXtHOBagcURThWk55nGOa9Qo6A9FiTrvY/edit#slide=id.gdf300cda12_0_0

**Comment by takasusuke** [comment]
草案に結論まとめました。
ソーラービーム、太陽のオブジェクト。
攻撃前にParticleを貯めて放出する感じ。
