### ISSUE TITLE
`Xcode` ビルドの場合 `Awake()` より先に呼ばれる関数が存在し `NullReferenceException` が起こってしまう

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#971]
refs: https://github.com/LITO-apps/Treevel-client/issues/953#issuecomment-856836201

https://github.com/LITO-apps/Treevel-client/blob/c82fdb6c8f2c55e40a22700d96228cf155c373c6/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L51

の `clearHandler` が `Null` であることによる `NullReferenceException` が発生する

```
NullReferenceException: Object reference not set to an instance of an object.
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelTreeController.UpdateState () [0x00027] in /Users/aoi/Treevel-client/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs:51 
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelSelectDirector+<>c.<OnEnable>b__6_0 (Treevel.Modules.MenuSelectScene.LevelSelect.LevelTreeController tree) [0x00001] in /Users/aoi/Treevel-client/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs:67 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00000] in <00000000000000000000000000000000>:0 
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelSelectDirector.OnEnable () [0x0004f] in /Users/aoi/Treevel-client/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs:67 
```

### 完了条件
- [ ] 上記エラーが解消すること

### 詳細
`Unity` ビルドと `Xcode` ビルドで以下のように挙動が異なる。`Xcode` ビルドの際に、`Awake()` より先に呼ばれる関数があることで、想定外の `NullReferenceException` が起きている

### `Unity` ビルド
1. 
https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L37

2.

https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreeControllerBase.cs#L26

3.

https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L45

### `Xcode` ビルド
1.
https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L45

2.

https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreeControllerBase.cs#L26

3.
https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L37

**Comment by xiii111** [comment]
📝 

https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreeControllerBase.cs#L26-L30

よりも先に

https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L45-L54

が呼ばれている

**Comment by xiii111** [comment]
📝 Unity だと ↑ のような順番で処理が呼ばれてしまうことはないため、正常に動作している（なんやそれ）

**Comment by xiii111** [comment]
何回かやっても何故か以下のような実行順序になる。かなり難航しそう

### Unity
1. 
https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L37

2.

https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreeControllerBase.cs#L26

3.

https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L45

### iOS
1.
https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L45

2.

https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/TreeControllerBase.cs#L26

3.
https://github.com/LITO-apps/Treevel-client/blob/aeb011ec4aa77809b0d85e2802b9ba5d9cf3f7a2/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L37

**Comment by takasusuke** [comment]
```
namespace Treevel.Modules.GamePlayScene
{
    [DefaultExecutionOrder(1)]
    public class BoardManager : SingletonObjectBase<BoardManager>
    {
```

**Comment by xiii111** [comment]
@takasusuke @takesi0627 ↑ の方法でやりましたが、iOS ビルドの時のみ上手くいかないですね ... ちょっと試せる人いたら試してみてほしいです🙏

**Comment by takasusuke** [comment]
`LevelSelectDirector`に`[DefaultExecutionOrder(1)]`つけただけだとEditorの時点でエラーでない？？
最終的に
`LevelSelectDirector`に`[DefaultExecutionOrder(10)]`
`ScaleContent`に`[DefaultExecutionOrder(50)]`
`SynchronizeCanvasObject`に`[DefaultExecutionOrder(100)]`
つけてbuild試そうと思ったけど、
`Signing & Capabilities`が出なくて泣いてる
<img width="1399" alt="スクリーンショット 2021-06-14 21 22 51" src="https://user-images.githubusercontent.com/26213141/121891934-126e4f00-cd57-11eb-86a5-a4ed31c6edc6.png">

**Comment by xiii111** [comment]
```
NullReferenceException: Object reference not set to an instance of an object.
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelTreeController.UpdateState () [0x00027] in /Users/aoi/Treevel-client/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs:51 
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelSelectDirector+<>c.<OnEnable>b__6_0 (Treevel.Modules.MenuSelectScene.LevelSelect.LevelTreeController tree) [0x00001] in /Users/aoi/Treevel-client/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs:67 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00000] in <00000000000000000000000000000000>:0 
  at Treevel.Modules.MenuSelectScene.LevelSelect.LevelSelectDirector.OnEnable () [0x0004f] in /Users/aoi/Treevel-client/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs:67 
```

**Comment by xiii111** [comment]
一旦辛いので、#958 と入れ替えます

**Comment by xiii111** [comment]
📝 これは一旦マイルストーンに戻します

**Comment by takesi0627** [comment]
![image](https://user-images.githubusercontent.com/17778395/133105166-c11f1f85-b10e-4e16-92dd-ef6721917fc0.png)

b4df8d0794da5ef3cd7e28e428b5678b3b82c47c （develop最新）にて現象確認しました

**Comment by xiii111** [comment]
@takesi0627 

https://github.com/LITO-apps/Treevel-client/blob/4d31cff1b96e37dd64a89c032390244313435252/Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelTreeController.cs#L49-L54

#1134 をやっていた時に ↑ を ↓ のように直してしまえば、治ることは確認済みだけど、`Awake()` の処理が増えるたびに順番が入れ替わることを考慮しないといけないのは大変だね ... あと `LevelTreeController` 以外にもこのような逆転が起こるとすると、根本原因を見つけないとキリがないね

```csharp
            // 解放条件がない場合、そのまま状態を反映
            if (treeData.constraintTrees.Count == 0) {
                // FIXME: 実機だと Awake() が呼ばれる前にこの処理を通ってしまうので、clearHandler == null の場合には値を入れる
                // https://github.com/LITO-apps/Treevel-client/issues/971#issuecomment-860052623
                clearHandler ??= GameDataManager.GetTreeData(treeId).GetClearTreeHandler();
                state = clearHandler.GetTreeState();
                ReflectTreeState();
                return;
            }
```

**Comment by takesi0627** [comment]
> #1134 をやっていた時に ↑ を ↓ のように直してしまえば、治ることは確認済みだけど、`Awake()` の処理が増えるたびに順番が入れ替わることを考慮しないといけないのは大変だね ... あと `LevelTreeController` 以外にもこのような逆転が起こるとすると、根本原因を見つけないとキリがないね
> 
> ```cs
>             // 解放条件がない場合、そのまま状態を反映
>             if (treeData.constraintTrees.Count == 0) {
>                 // FIXME: 実機だと Awake() が呼ばれる前にこの処理を通ってしまうので、clearHandler == null の場合には値を入れる
>                 // https://github.com/LITO-apps/Treevel-client/issues/971#issuecomment-860052623
>                 clearHandler ??= GameDataManager.GetTreeData(treeId).GetClearTreeHandler();
>                 state = clearHandler.GetTreeState();
>                 ReflectTreeState();
>                 return;
>             }
> ```

この修正僕も試しました、まさにおしゃった通りに、他のところも（ `RoadController`）同じようなことが起きてるので、全体的の依存関係を見直して直す予定。

**Comment by xiii111** [comment]
@takesi0627 

> 他のところも（ `RoadController`）同じようなことが起きてるので、全体的の依存関係を見直して直す予定。

なんて辛いんだ ....

**Comment by xiii111** [comment]
なんか develop の先頭だと本エラーが起きる場所、`LevelSelectScene` に変わってる？って思ったけど、`LevelSelectScene` を `StartupScene` の段階でロードしなくなったから変わったんだね

**Comment by xiii111** [comment]
タイトルを変えておきます

**Comment by takesi0627** [comment]
助かります

**Comment by xiii111** [comment]
いい感じにしました

**Comment by takesi0627** [comment]
今PR書いているのでそこまでしなくてもいいかも・・

**Comment by xiii111** [comment]
自分の頭の整理を兼ねて ...

**Comment by xiii111** [comment]
@takesi0627 https://github.com/LITO-apps/Treevel-client/issues/1134#issuecomment-919611729 の問題も `Awake` の順番に依るものだと思うので、合わせて動作確認お願いできますか？

**Comment by takesi0627** [comment]
ログ見る限り`material`がnullみたいなのでちょっと違うみたいだな・・
後で詳しく見る

**Comment by xiii111** [comment]
@takesi0627 material は Awake() で入れてるの

**Comment by takesi0627** [comment]
あーなるほど、じゃあちょっと僕の修正見れば多分同じことやれば治せる

**Comment by xiii111** [comment]
あ、もしかしてモジュールごとに変更が必要なのか？

**Comment by takesi0627** [comment]
いや、要は `UpdateState` を `StageSelectDirector`からじゃなく `BranchController` で書けばいいです

**Comment by xiii111** [comment]
お、光が見えそうなこと言ってる

**Comment by takesi0627** [comment]
まあ、簡単いいうけど、移動した後色々起こると思うので一個一個潰していくスタイル
