### ISSUE TITLE
[#826] ゲーム外の背景草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#975]
### 終了条件
想定しないデバイス比でゲームをプレイした時に現れるゲーム外の背景
- [ ] 草案作成

### 考慮事項
どんなイメージか
- ロード中にも使える感じ
- 自然の感じ
- 季節ごとに異なるのか、異なるならどこが異なるのか

**Comment by takasusuke** [comment]
Web画面のローディングなので必ずしも沿うわけではないけど。（MyMEMO：https://miurabase.com/ まで見た）
https://sankoudesign.com/category/loading/

↑のうち、使えそうと思ったサイト
海を眺める感じ
https://xico.co.jp/
四季を遷移する感じ 
https://tanakahonke.org/
フルーツが並んでる感じ（木とかにできそう）
https://yamashita-fruit.com/
こういうちょっとしたアニメーションがあるの良い
https://watanabe-meat.com/
単純なグラデーションでも綺麗（昼→夜とかを感じさせる色のアニメーションとかできそう）（あくまでゲーム外背景はBottle, Tile、メイン背景の補佐の役割の感じを意識する）
https://sendai-startups.org/
葉っぱとかのモチーフ、これくらい大きく背景にぼんやり描くのもありだなあ
https://kyotofilmaward.com/

**Comment by takasusuke** [comment]
草案資料
https://docs.google.com/presentation/d/12GS3_BPRSMmaNF78yALfj6ozn4eAr9gwIRgSs6sOcNY/edit#slide=id.ge003c541ce_0_125

**Comment by takasusuke** [comment]
@LITO-apps/engineer 

第一版作りました。
タスク通話で意見伺います。流れ次第では決定まで行います。

別案や、出した案の合成案など、タスク通話までにあげてもらえれば対応します。

全部の案にコメントしなくて良いけど、良い要素などをタスク通話までにこのイシューにコメントしてもらえると、
別案を考える参考になります。

**Comment by xiii111** [comment]
@takasusuke 対応ありがとうございます。そして、結局今のいままで忘れていました。スライドにコメントしていこうと思います

**Comment by xiii111** [comment]
@takasusuke コメントしました。特に、ゲーム外の背景の必要性についてもコメントしてしまいました。このイシュー吟味中にこのコメントはするべきでしたが、レビューしていて思ったので今回のコメントになってしまいました。

**Comment by xiii111** [comment]
コメントの編集や一部削除を行いました。よろしくお願いします🙏

**Comment by takasusuke** [comment]
一時停止画面自体、不要説。

ユーザが一時停止したい場面や、一時停止の利用をそんなに推奨したいわけでもないような。。。
ゲームデザイン（1分くらいで終わる）から考えると一時停止がある理由が見当たらん気がしてきた。

一時停止画面ないなら、ゲーム画面背景もなくても良さそう。

**Comment by xiii111** [comment]
> 一時停止画面自体、不要説。

ユーザへの配慮という意味では、始めても中断して一旦止められるという理由で、ゲームを始めてもらえる敷居が低くなるかもしれない（これはたくさんゲームをプレイしてもらいたい、という観点では良い効果かもしれない）

**Comment by takasusuke** [comment]
ゲーム外背景はなし。
一時停止中は黒透明マスクを実装する。

**Comment by takasusuke** [comment]
#995 で実装します
