### ISSUE TITLE
[親] 各種ポップアップの草案作成

### ISSUE THREAD

**Issue by takasusuke** [LITO-apps/Treevel-client#985]
## 終了条件
成功ポップアップ、失敗ポップアップ、一時停止ポップアップ、警告ポップアップのデザイン草案を１つのスライドで作成する

#830 
#831 
#832 

#345 
#346 

## 考慮事項
- ポップアップ内の文字、ボタン、配置を考える
- ポップアップ本体の色を考える
- 警告ポップアップは確認用とエラー表示用
- 機能面、演出面も多少議論する
- Twitterへのリンク、Twitterの画像使えるかどうか調べる

**Comment by takasusuke** [comment]
草案
https://docs.google.com/presentation/d/10Vh5hkDJVqCuAyPtfU6cAITBtfL6OtS5GUd03uNW-2U/edit#slide=id.ge21fe46126_0_5

**Comment by takasusuke** [comment]
@LITO-apps/engineer 

今までのモチーフの草案と違って、なんでその画面があるのか、というコンセプトの草案なのでちょっと草案の出し方を試験的に変えてみる。

現時点で考えてるゲーム序盤のSpring_1想定で「ゲーム成功時にユーザに与えたい印象」聞かせて。
以下のスライドに点数つけたり、項目が足りなければ追加して。（点数は適当。自分の中で優劣ついてれば良いです）

ユーザに与えたい印象はたくさんあると思うけど、できるだけ厳選する感じでお願いします。
https://docs.google.com/presentation/d/10Vh5hkDJVqCuAyPtfU6cAITBtfL6OtS5GUd03uNW-2U/edit#slide=id.ge15f406ee7_0_36

**Comment by xiii111** [comment]
@takasusuke 成功ポップアップについて、いくつかコメントしたのと、 https://docs.google.com/presentation/d/10Vh5hkDJVqCuAyPtfU6cAITBtfL6OtS5GUd03uNW-2U/edit#slide=id.ge2a8ddc42b_1_0 に、既存の案を組み合わせて良い感じだと思ったやつを貼りました

**Comment by takasusuke** [comment]
成功時の画面を実装します
#1019

**Comment by takasusuke** [comment]
@LITO-apps/engineer 
ゲーム失敗時に与えたい印象について、評価お願いします。
https://docs.google.com/presentation/d/10Vh5hkDJVqCuAyPtfU6cAITBtfL6OtS5GUd03uNW-2U/edit#slide=id.ge15f406ee7_1_5

**Comment by xiii111** [comment]
@xiii111 @takesi0627 一時停止とステージ選択時の重要視する項目のポイントをつける

**Comment by xiii111** [comment]
@takasusuke ポイントをつけました

**Comment by takesi0627** [comment]
@takasusuke 同じく

**Comment by xiii111** [comment]
📝 二人ともポイントつけているので `作業中` に戻します

**Comment by takasusuke** [comment]
- [ ] 成功時
- [ ] 失敗時
- [ ] 一時停止時
- [ ] ステージ選択時
- [ ] エラー時
- [ ] 警告時
- [ ] (利用規約時)
---- このissueでやらないこと ----
- [ ] チュートリアル 
- [ ] 設定画面
- [ ] OnBoarding (#503)

**Comment by takasusuke** [comment]
エラーポップアップの実装issue 
#1089 を作成しました

**Comment by takasusuke** [comment]
警告ポップアップの実装issue
#1094 を作成しました

**Comment by xiii111** [comment]
@takasusuke https://docs.google.com/presentation/d/10Vh5hkDJVqCuAyPtfU6cAITBtfL6OtS5GUd03uNW-2U/edit#slide=id.ge9cf85af01_2_3 で色々考えを書きました！参考にしてもらえると助かります！

**Comment by takesi0627** [comment]
@takasusuke 
p49に提案させていただきました。

**Comment by takasusuke** [comment]
ステージ概要の実装issue
#1097 を作成しました

**Comment by takasusuke** [comment]
以上でこのissueで決める各種画面のレイアウトを全て決定しました。
https://github.com/LITO-apps/Treevel-client/issues/985#issuecomment-894891378
