### ISSUE TITLE
`Attribute` を複数組み合わせた場合の挙動を確認する

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#999]
### 完了条件
- [x] `GhostAttribute` × `DarkAttribute` での挙動を確認する
- [x] `GhostAttribute` × `ReverseAttribute` での挙動を確認する
- [x] `DarkAttribute` × `ReverseAttribute` での挙動を確認する
- [x] `GhostAttribute` × `DarkAttribute` × `ReverseAttribute` での挙動を確認する
- [x] 確認した結果を加味して、今後どうするかを決める

### 備考
- フリックやホールド、ギミックとの衝突、GustWind の影響など幅広く確認する

**Comment by xiii111** [comment]
## 調査結果
### ghost → 当然問題ない
https://user-images.githubusercontent.com/26104258/140747808-381ac2c7-7576-464c-ac01-0a153485fae4.mov

### dark → 当然問題ない
https://user-images.githubusercontent.com/26104258/140747889-22c018a4-debc-4e34-9b21-9e57b3be1963.mov

### reverse → 当然問題ない
https://user-images.githubusercontent.com/26104258/140747991-d80f0f6d-3773-4b09-9f79-3daff404b5c2.mov

### ghost + dark → 意外となんとかなる。敢えて使わないけど
https://user-images.githubusercontent.com/26104258/140748057-7d6ab5ad-1651-433a-bfb1-1212891e24bc.mov

### ghost + reverse → 普通に問題ない。これは利用していける
https://user-images.githubusercontent.com/26104258/140748418-2f02168d-7836-4926-8e44-e73721ec551e.mov

### dark + reverse → 悪くない。これは利用していける
https://user-images.githubusercontent.com/26104258/140750035-37a1a529-45ce-4d0f-b07b-2f355c03c2f5.mov

### ghost + dark + reverse → 意外となんとかなる。ごちゃごちゃはしてる
https://user-images.githubusercontent.com/26104258/140748983-151b48ad-d499-40b0-bac8-9beb4eb68186.mov

## 今後

|type|どうする|
|---|---|
|ghost + dark|あまり使わないでおこう|
|ghost + reverse|ステージ設計次第では使っていこう|
|dark + reverse|ステージ設計次第では使っていこう|
|ghost + dark + reverse|あまり使わないでおこう|

**Comment by xiii111** [comment]
@takasusuke @takesi0627 以上のような結果になりました。今後について、異論があればコメントお願いします

**Comment by takasusuke** [comment]
`ghost + dark` : 思ったより悪くない。というか別に良くない？という感想。

**Comment by xiii111** [comment]
↑ 全体的に、思ったより悪くない、という印象

**Comment by xiii111** [comment]
@takasusuke 

> 視認しづらい等の感想があるのであれば、ちょい具体的に知りたい。

微妙とは書いたが、正直そんなに改善案もない。どちらかというと dark 単体のデザインがもう少しブラッシュアップされると、良いなとは思う（今回のスコープ外）。言葉にするのは難しいが、色合いがもう少し平坦じゃなくなると？良さそう

**Comment by takesi0627** [comment]
### `ask`

`ghost + dark` の動画からわからなかったけど、
放置して `ghost` が動いたら`dark` は晴れますか？

**Comment by xiii111** [comment]
@takesi0627 質問の意図があまり分からなかったけど、以下のような感じ。Dark は 指でホールド or goal にいるときに晴れる

https://user-images.githubusercontent.com/26104258/140911438-7dc81bfa-f58b-4e74-9445-047ceca1ce4a.mov

**Comment by xiii111** [comment]
📝 忘れてたけど、DarkAttribute は GoalBottle にのみ付与できる属性

**Comment by takesi0627** [comment]
`ghost`の機能によって動かされた時に晴れるかっていう質問だけど、
https://github.com/LITO-apps/Treevel-client/issues/999#issuecomment-964036046 新しい動画で分かったらから大丈夫！

個人的に `Dark + Ghost` はDarkを確認したいのに勝手に動くので少し難易度上げ要素としてはありかなと思います。
`Dark + Ghost + Reverse` も同様の理由で使ってもいいかなという気持ち。

見積もりの時気づくべきでしたが、 `LifeAttribute` の組み合わせは確認しなくてもいいですか？
 ライフの演出が見えなかったりするとか何か問題があるかもしれません。

**Comment by xiii111** [comment]
↑ 全部確認するのは大変なので Life + hoge を 3 通り確認しますね

**Comment by xiii111** [comment]
@takesi0627 以下が結果です。life + reverse で若干オブジェクトがかぶってるかな？くらいです

### life + ghost
https://user-images.githubusercontent.com/26104258/140914702-9d337956-03c7-4f3b-8bea-1e0d62a3f4be.mov

### life + dark
https://user-images.githubusercontent.com/26104258/140914622-6934c422-8773-43b1-bc90-055d5300479b.mov

### life + reverse
https://user-images.githubusercontent.com/26104258/140914780-d324d6e4-b602-47d0-a696-728613dd3408.mov

**Comment by xiii111** [comment]
@takasusuke @takesi0627 一通り返答したつもりです。問題なければ閉じますが、何かありますか？

**Comment by takesi0627** [comment]
> @takesi0627 以下が結果です。life + reverse で若干オブジェクトがかぶってるかな？くらいです

確かにちょっと気になるくらい。でもまあ許容できます。


> 一通り返答したつもりです。問題なければ閉じますが、何かありますか？

僕からはもう問題ないですが、
結論は全部の組み合わせ使って問題ないってことで良いですか？

**Comment by xiii111** [comment]
> 結論は全部の組み合わせ使って問題ないってことで良いですか？

機能的には問題ないですが、見やすさが落ちる部分もあるので、慎重に使いましょう、という感じですね！

**Comment by takasusuke** [comment]
- life + reverse は今の時点では使えなさそう。見づらい。
- ghost + dark 見て思うけど、darkをホールドした時に、darkが晴れるまでもう少し早くても良い。(ブラッシュアップ)
- lifeもstart時のアニメーションで透明度上げてくアニメーション入れた方が良い(ブラッシュアップ)

挙動(機能)は問題ないと思います。

**Comment by xiii111** [comment]
おけです！適宜アイデアに乗っけておきます（イシュー作るかどうかは、定例会で）

**Comment by xiii111** [comment]
閉じます！
